### ISSUE TITLE
Add VXLAN encapsulation support

### ISSUE THREAD

**Issue by ggouss** [cloudnativelabs/kube-router#1011]
Problem: In some restricted environments direct IP-IP connectivity between cluster nodes is not available.
Solution: Add VXLAN or other encapsulation support to kube-router
Alternatives considered: Switching CNI plugin to flannel

**Comment by aauren** [comment]
Unfortunately, this would be a large-ish change and none of the project maintainers have time to implement this feature. If you're interested in submitting a PR for the work, we could re-open this and talk about implementation paths.

Closing as stale for now.
