### ISSUE TITLE
Migrate Travis CI to Github Actions

### ISSUE THREAD

**Issue by mrueg** [cloudnativelabs/kube-router#1020]
**Is your feature request related to a problem? Please describe.**
 ```Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information. ```

https://news.ycombinator.com/item?id=25338983

**Describe the solution you'd like**

Look into migration from Travis to Github Actions, which currently seems to be the best available and free system.
It also allows to use https://github.com/nektos/act  (or similar) for local execution of the pipeline.

**Comment by aauren** [comment]
All done. Thanks @mrueg!
