### ISSUE TITLE
Support multiple subnet definitions in CNI conf

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#1023]
**What happened?**

kube-router should support  multiple subnet definitions in CNI conf.  kube-router populated CIDR range from which host-local ipam allocated IP address for the pod. But `10-kube-router.conf` filed with signle entry CIDR which was the only option supported in earlier CNI specification version. Though its still supported as of `0.8.0` cni version, we should fix in kube-router to support ranges to be future proof

**What did you expect to happen?**

{
  "cniVersion": "0.3.0",
  "name": "mynet",
  "plugins": [
    {
      "bridge": "kube-bridge",
      "ipam": {
        "subnet": "10.1.0.0/24",
        "type": "host-local"
      },
      "isDefaultGateway": true,
      "mtu": 1480,
      "name": "kubernetes",
      "type": "bridge"
    }
  ]
}

should be with ranges as in this example 

https://www.cni.dev/plugins/ipam/host-local/#example-configurations

**Comment by aauren** [comment]
This will be fixed when #1386 makes it to a main release
