### ISSUE TITLE
Adding WRR scheduling feature with Kube-router

### ISSUE THREAD

**Issue by kannanvr** [cloudnativelabs/kube-router#1038]
Hi,
At Present, Kube-router doesn't support WRR scheduling for ipvsadm
We would like to add this as a Feature Request.
Following are the advantages over WRR.
1.  Some of the Age old application which completely depends on nodes and does not have the Resource Limit on their deployment and these applications were  deployed with the node who has different Config's -eg. node1=24 cores & node2=72 cores and as Pod size is always same for all Pods, we do not specify the resources for this tight Deployment. And so the instance1.node1's ipvs Weight should be 1 while instance2.node2's ipvs Weight should be 3 in wrr scheduler. Different weights are required in this case

**Solution:**
 1. We can have the node annotation which provide the weight of the node (For example kube-router.io/node.ipvswrrweight=3 on worker node-2)
 2. On service , if we mention the annotation as WRR scheduling (kubectl annotate service my-service "kube-router.io/service.scheduler=wrr")
 3. Our Kube-router should set the weight of the endpoint which deployed at workernode-2 as 3

Request you to provide your valuable suggestion on this problem statement and solution
We are ready to contribute this feature.

Thanks,
Kannan V

**Comment by murali-reddy** [comment]
> Some of the Age old application which completely depends on nodes and does not have the Resource Limit on their deployment 

I am not sure why resource limits can not be set for these deployment

> WRR scheduling for ipvsadm

After thinking about this scehduling I am not very sure we would need this in current cloud-native world. We have granularity at pod level to specify resources it needs independent of the node on which it runs. I agree with tim's comment in https://github.com/kubernetes/kubernetes/issues/96902#issuecomment-740172984

> I think this is a problem.  If we added a concept of weight, it would
PROBABLY be proportional to pod size, not node size.

Please elobrate why current primitives in Kubernetes falls short for your case.

**Comment by kannanvr** [comment]
Hi @murali-reddy 
Thanks for your reply.
   There are  many use case we were trying to solve with this solution.
   
1. Suppose worker node provisioned with same CPU/Memory and the deployment mentioned the CPU/Memory Request and Limit are same.
 But worker node is provisioned with different types of DISK like worker node-1 with SAS, worker node-2 
 with SAT and worker node-3 with SSD disk. Now every worker node can not be treated same with respect to processing. 
 In this case we needed the weight for the node which attached with high capable disk to process the information quickly
  
 2. Suppose Every worker node provoned with different set of processor.
 If we mention the same CPU and memory on the pod resources,
 we needed explicitely mention the weight for the worker node which can process fastly based on High Frequency of Processor.
 
 Also, in the above 2 cases also, kubernetes resource primitives does not help completely and we needed the weight explicitely
 
  Thanks,
 Kannan V

**Comment by kannanvr** [comment]
Hi @murali-reddy 
Thanks for your reply.
   There are  many use case we were trying to solve with this solution.
   
   
1. All the resources on the pod Limit and request is same.  But worker node is provisioned with different types of DISK 
like worker node-1 with SAS, worker node-2 with SATA and worker node-3 with SSD disk.  But the app is depend on hostMount. It is entirely possible. 
 Now every worker node can not be treated same with respect to processing. 
 In this case we needed the weight for the node which attached with high capable disk to process the information quickly
  
2. Suppose Every worker node provisoned with different set of processor.
 If we mention the same CPU and memory on the pod resources, we needed explicit mention of the weight for the worker node 
 which can process fastly based on High Frequency of Processor.
 
3. There can be any difference with respect to HDD/CPU/Application. 
Here Pod will schedule dynamically and we need to match the parity with respect to providing the weights based on nodes and the particular app
 pod which scheduled on the node who has high capability need to given the high weights.
 
4.  2 nodes but it is a tight app that can run only one instance per node.
 The 2 nodes could have different Config's - node1=24 cores & node2=72 cores and as Pod size is always same for all Pods, 
 we do not specify the resources for this tight Deployment. 
 And so the instance1.node1's ipvs Weight should be 1 while instance2.node2's ipvs Weight should be 3 in wrr scheduler. 
 Different weights are required in this case

 
 kubernetes resource primitives does not help completely on all the scenarios and
 we needed the weight explicitely if there is a difference in static Resources Like CPU/HDD/.. etcc 
 
  Thanks,
 Kannan V

**Comment by Shashankft9** [comment]
hey @murali-reddy, any opinions?

**Comment by aauren** [comment]
I think at this point we're going to choose to side with upstream here. Even with the explanation above it still seems to me that this could be resolved with scheduling and that the resulting implementation would add too much complexity to kube-router for us to handle it a way that makes sense at our level.

Additionally, there are other tools that could be added to a cluster to perform this functionality better like an ingress or other load-balancer type deployment.
