### ISSUE TITLE
Replace or remove "--cluster-cidr"

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#107]
Kubernetes conformance tests assume that pods are able to reach the internet by default. I think most Kubernetes users expect this behavior by default as well. We already determine the Pod CIDR at runtime.

So, I think we should:
- Remove `--cluster-cidr`.
- Default to enable SNAT for pod traffic destined outside the cluster.
- Add a new flag to disable the last item, `--disable-pod-egress` or similar.

**Comment by murali-reddy** [comment]
@bzub AFAIR cluster CIDR (subnet used for all the pods across the cluster) information is not available from API's. It is passed as param to kube controller. Knowing just pod CIDR allocted for the node is not sufficient. Kube-proxy continue to have `--cluster-cidr` as well for same reason.

Please see the discussion in https://github.com/kubernetes/kubeadm/issues/102
