### ISSUE TITLE
kube-router fails to execute ipset restore command after sometime

### ISSUE THREAD

**Issue by dhlaluku** [cloudnativelabs/kube-router#1072]
kube-router crashes after sometime when it fails to sync pod network policies and hangs on the `ipset restore` command. This becomes a problem because pod communication becomes unavailable when this happens and we have manually clear the kube-bridges and restart kube-router.

Component Versions:
RHEL: 7.9 with Kernel 3.10.0-1160.15.2.el7.x86_64
Kubernetes: v1.16.13
Docker: 20.10.5 (Both server and client)
ipset v7.1, protocol version: 7
iptables v1.4.21
kube-router: v1.2.0

Running kube-router as an agent on all the nodes with the following flags;
`/usr/bin/kube-router --kubeconfig=/etc/kubernetes/kubeconfigs/kube-router.kubeconfig --hostname-override=xdedflmin2`

Sample kube-router logs:

`Apr 21 04:40:09 xdedflmin2 kube-router[24139]: I0421 04:40:09.850808   24139 network_routes_controller.go:543] Cleaning up old routes if there are any
Apr 21 04:40:09 xdedflmin2 kube-router[24139]: I0421 04:40:09.851604   24139 network_routes_controller.go:557] Cleaning up if there is any existing tunnel interface for the node
Apr 21 04:40:12 xdedflmin2 kube-router[24139]: E0421 04:40:12.164407   24139 network_policy_controller.go:236] Aborting sync. Failed to sync network policy chains: %!v(MISSING)failed to perform ipset restore: ipset v7.1: Error in line 1043: The set with the given name does not exist
Apr 21 04:40:42 xdedflmin2 kube-router[24139]: E0421 04:40:42.795156   24139 network_policy_controller.go:236] Aborting sync. Failed to sync network policy chains: %!v(MISSING)failed to perform ipset restore: ipset v7.1: Error in line 911: The set with the given name does not exist`

**Comment by murali-reddy** [comment]
@dhlaluku thanks for reporting.

Can you please confirm if you are seeing this issue constantly or at random occasions? Does this failure has any functional impact in enforcing network policies?

@aauren @bnu0 @NaPs did you happen to see this error in your environment?

**Comment by dhlaluku** [comment]
@murali-reddy 
It is happening constantly. 

Yes, when it happens, we get network connectivity timeouts from our pods for both egress and pod-to-pod comms.

Also, we don't setup kube-proxy on our nodes and use the kube-router based service proxy.

**Comment by mrueg** [comment]
@dhlaluku can you try with kube-router-1.2.2?

**Comment by dhlaluku** [comment]
@mureg will test on our dev environment and revert back. Thanks

**Comment by aauren** [comment]
@dhlaluku We did change quite a bit in 1.2.2 in how we formulate the ipset restore input.

However, if 1.2.2 doesn't resolve it for you, probably the only way to get to the bottom of what's going on will be to have you insert some logging here https://github.com/cloudnativelabs/kube-router/blob/1943023b40e1c3ac79723b6eedd37c0c34ec3b53/pkg/utils/ipset.go#L479 and run that version in an environment that you can reproduce the error.

Maybe something like:
```go
	stdin := bytes.NewBufferString(buildIPSetRestore(ipset))
        klog.V(2).Infof("Executing the following ipset:\n%s", stdin)
	_, err := ipset.runWithStdin(stdin, "restore", "-exist")
```

If you set your logging verbosity to 2 or greater, it would then show you the ipset restore that it is trying to run, and the line numbers mentioned in the error log will corollate to show us exactly what your cluster is failing on.

**Comment by dhlaluku** [comment]
@aauren @mrueg so far tests in our development environment are looking good, we will promote to higher level environments that have a bit more load and activity and monitor there.

**Comment by aauren** [comment]
@dhlaluku Any update here?

**Comment by dhlaluku** [comment]
@aauren so far so good, upgraded our higher level environments and have not seen issues thus far. I think we can close this ticket

**Comment by mrueg** [comment]
Thanks for the feedback! Closing.
