### ISSUE TITLE
kube-router should prefer node's internal IP over external one

### ISSUE THREAD

**Issue by vladimirtiukhtin** [cloudnativelabs/kube-router#1089]
Currently kube-router adds IPVS rules using node's external IP. Flag "--nodeport-bindon-all-ip" of course solves the problem, but leaves the node vulnerable in case there is no proper firewall applied

**Comment by aauren** [comment]
@vladimirtiukhtin kube-router is pretty purposeful here. It get's the Node object for the node it is running on from the kube-apiserver and then preferrs the `InternalIP`. If the Node object does not have an `InternalIP` attribute, it will then fall back to the `ExternalIP` attribute. If the Node object doesn't have either, then it will throw an error at startup.

You can see this logic here: https://github.com/cloudnativelabs/kube-router/blob/a61059627719a63da1b7304f306d4cfe28afb4ec/pkg/utils/node.go#L50-L63

If you are not seeing it bind on the Internal IP of the Node then I would suspect either InternalIP is not being set on your node object in your Kubernetes API, or it has been set incorrectly.

**Comment by aauren** [comment]
Closing for now, but am willing to re-open if it can be proven that there remains a kube-router bug upon user feedback.

**Comment by vladimirtiukhtin** [comment]
Thanks @aauren. You are quite right. The issue I am experiencing is that cloud provider does not update node object fast enough. Is there a flag to wait for node to be properly provisioned?

**Comment by aauren** [comment]
No, that would be more on the orchestration side, something like kops, kubeadm, etc. should be doing that for you. You may also be able to add your own init container to kube-router if you deploy it via a daemonset that checks the node object before it starts based upon what you expect from your cloud provider, but this would obviously not be a one size fits all solution for all kube-router users.
