### ISSUE TITLE
Routes are not getting created

### ISSUE THREAD

**Issue by vladimirtiukhtin** [cloudnativelabs/kube-router#1091]
After upgrade from 1.1.1 to 1.2.0 routes are no longer getting created. I had to roll back my deployment

My setup:
```
ExecStart=/usr/local/bin/kube-router \
  --kubeconfig=/var/lib/kube-router/kubeconfig \
  --run-firewall \
  --run-router \
  --run-service-proxy \
  --nodeport-bindon-all-ip
```

**Comment by vladimirtiukhtin** [comment]
Something to add. Routes are getting correctly added when I remove flag --enable-overlay=false. But If I remove the flag it attempts to create a tunnel which is not a desired design

**Comment by vladimirtiukhtin** [comment]
In fact, the only workable version of kube-router I found is 0.2.5 which does not attempt to create any tunnels. Starting from 0.3.0 kube-router tries to create tunnels for some reason. How to switch it to the normal behaviour?

**Comment by aauren** [comment]
Please use the issue template provided so that we can be sure that we have all of the information we need to assist you.
