### ISSUE TITLE
Effect of a label on pod networking remains long after label is removed

### ISSUE THREAD

**Issue by carlydf** [cloudnativelabs/kube-router#1099]
**What happened?**
Networking permissions take hours to have an effect after pod labels change.
1. We labelled a pod `network-policy-exempt=""`, which causes network policies to apply to it that allow it to accept ingress from any source and to initiate egress to any destination.
2. The label worked as expected, our processes that required network access were able to run.
3. We removed the `network-policy-exempt` label from that pod.
4. The processes were still able to run! Other pods were able to ping the pod that had _previously_ been labelled exempt. It has now been 18h since removing the label, and that pod is still behaving as if it is exempt. Around hour 16, I restarted the pod by deleting it, hoping that that would trigger an ip table sync, but it continues to behave as if exempt.

**What did you expect to happen?**
I expected that after removing the `network-policy-exempt` label, the iptables would adjust within 30s to 5 minutes, and the pod would become isolated (in it's simplest form, that means unpingable from things that are not labelled `needs-app-b`)

**How can we reproduce the behavior you experienced?**
1. Apply [these network policies](https://github.com/carlydf/docs/blob/master/netpols.yaml)
2. Create deployment `b` with one replica, the deployment spec should label the pod `app=b`
3. Create deployment `a` with one replica, the deployment spec should label the pod `app=a`
3. Test pinging the `b` pod IP from another pod, `c`,  that is not labelled `needs-app-b`. It should fail.
4. Test pinging the `a` pod IP from pod `c`. It should fail.
4. Label pod `b` `network-policy-exempt=""` using `kubectl label pod`
5. Test pinging the `b` pod IP from pod `c`. It should work.
6. Test pinging the `a` pod IP from pod `c`. It should fail.
6. Unlabel `b` `network-policy-exempt=""` using `kubectl label pod <pod name> network-policy-exempt-`
7. Test pinging the `b` pod IP from pod `c`. It should fail, but it doesn't.
8. Test pinging the `a` pod IP from pod `c`. It should fail and it does.

**Screenshots / Architecture Diagrams / Network Topologies **
If applicable, add those here to help explain your problem.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): v0.4.0
 - Kube-Router Parameters: [e.g. --run-router --run-service-proxy --enable-overlay --overlay-type=full etc.] not sure what to put here. running with kops flag `--networking kube-router`
 - Kubernetes Version (`kubectl version`) : [e.g. 1.18.3] `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
 - Cloud Type: AWS, same issue experienced on prem
 - Kubernetes Deployment Type: Kops
 - Kube-Router Deployment Type: [e.g. DaemonSet, System Service]
 - Cluster Size: 1 Node

** Logs, other output, metrics **
Please provide logs, other kind of output or observed metrics here.

[Here](https://github.com/carlydf/docs/tree/master/output) is the output to
> iptables-save
ipset list
route -n
ip addr
get pods -owide

Below is the output from pinging two different pods (both should have failed, the one that is succeeding was labelled `network-policy-exempt=""` almost 20 hours ago.

> % kubectl -n netpols get pods -owide | grep btrdb-0
btrdb-0                                 1/1     Running            0          164m   100.96.2.45   ip-172-20-37-240.ec2.internal   <none>           <none>

> root@ottk-6d48d6bf4c-78dhf:/srv/go# ping 100.96.2.45
PING 100.96.2.45 (100.96.2.45) 56(84) bytes of data.
64 bytes from 100.96.2.45: icmp_seq=1 ttl=64 time=0.141 ms
64 bytes from 100.96.2.45: icmp_seq=2 ttl=64 time=0.055 ms
64 bytes from 100.96.2.45: icmp_seq=3 ttl=64 time=0.061 ms
64 bytes from 100.96.2.45: icmp_seq=4 ttl=64 time=0.052 ms
64 bytes from 100.96.2.45: icmp_seq=5 ttl=64 time=0.057 ms
64 bytes from 100.96.2.45: icmp_seq=6 ttl=64 time=0.058 ms
^C
--- 100.96.2.45 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5119ms
rtt min/avg/max/mdev = 0.052/0.070/0.141/0.033 ms

> % etcd-0-5bfc94576f-6b5nf                 1/1     Running            0          18h    100.96.1.14   ip-172-20-57-139.ec2.internal   <none>           <none>

> root@ottk-6d48d6bf4c-78dhf:/srv/go# ping 100.96.1.14
PING 100.96.1.14 (100.96.1.14) 56(84) bytes of data.
From 172.20.57.139 icmp_seq=1 Destination Port Unreachable
From 172.20.57.139 icmp_seq=2 Destination Port Unreachable
From 172.20.57.139 icmp_seq=3 Destination Port Unreachable
From 172.20.57.139 icmp_seq=4 Destination Port Unreachable
From 172.20.57.139 icmp_seq=5 Destination Port Unreachable
From 172.20.57.139 icmp_seq=6 Destination Port Unreachable
^C
--- 100.96.1.14 ping statistics ---
6 packets transmitted, 0 received, +6 errors, 100% packet loss, time 5097ms

**Additional context**
We've seen other versions of this problem as well, but trying to keep the scope of this issue on one sequence of events.

**Comment by aauren** [comment]
Hi @carlydf 

Thanks for the very thorough bug report.

Unfortunately, this was a bug with older versions of kube-router. This was fixed in https://github.com/cloudnativelabs/kube-router/pull/1046

The first version of kube-router that carried that change was 1.2.0, however, out of the 1.2.X releases, I would very much recommend running 1.2.3 as it is the latest bug fix release in the 1.2 series and fixes a number of problems that users reported having to do with network policies.

In addition to this fix, 1.2 includes a much more streamlined networkpolicy controller which significantly reduces the latency time between syncs.
