### ISSUE TITLE
kube-router pods crash running iptables

### ISSUE THREAD

**Issue by grimurd** [cloudnativelabs/kube-router#1109]
**What happened?**

This is a followup to #1081 

Nodes were loosing network connection after 1.20 upgrade which was fixed by v1.23 but after 1.23 upgrade the kube-router pods keep crashing when getting data from iptables.

If I run a command that previously crashed the pod manually it works fine, e.g.
`kubectl -n kube-system exec kube-router-w9zc9 -- /sbin/iptables -t nat -S KUBE-ROUTER-HAIRPIN --wait
`

Everything is working for the moment aside from the fact that the pods are crashing. The crashing doesn't seem to be causing any issues in the cluster.

**System Information:**

 - Kube-Router Version: v1.2.3
 - Kube-Router Parameters:
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --bgp-graceful-restart=true
        - --hairpin-mode=true
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - -v=2
 - Kubernetes Version: v1.20.6
 - Cloud Type: on premise
 - Kubernetes Deployment Type: kubeadm
 - Kube-Router Deployment Type: daemon set
 - Cluster Size: 3 control and 3 workers
 - OS: CentOS Stream release 8
 - Kernel: Linux kubecp0 4.18.0-310.el8.x86_64  SMP Tue Jun 8 00:24:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Container runtime: CRI-O 1.20.3

**Logs, other output, metrics**
Crash logs from three different pods all different iptables commands
[Logs 1
](https://pastebin.com/V41CEKgU)[Logs 2
](https://pastebin.com/WgH8MAG7)[Logs 3](https://pastebin.com/0196iZ8s)

**Comment by murali-reddy** [comment]
@grimurd does this happen on any particular node or seen on many nodes?

>E0623 10:01:22.645148       1 network_services_controller.go:449] Error syncing hairpin iptables rules: Failed to list iptables chains: running [/sbin/iptables -t nat -S --wait]: exit status -1:

It seem even basic command to list the chains has resulted in errors. Once pod restarts after crash does the problem occurs again?

**Comment by grimurd** [comment]
@murali-reddy Happens on all nodes. The problem occurs again after the pod is restored but it may be several hours or even days until it happens again. It also isn't always the same command but it's always something to do with iptables.

**Comment by rdavyd** [comment]
I can confirm the issue.

![pict](https://user-images.githubusercontent.com/57534322/123744203-1651b380-d8b7-11eb-91f1-06768ce0bd85.png)

Unfortunately I could not grab logs of the possible issue since kube-router container keeps restarting and crashing because it cannot connect to k8s API.

Kubernetes version: 1.20.7 (on prem, deployed via kubespray)
Container engine: containerd 1.4.4
Kube-router version: v1.2.2

**Comment by grimurd** [comment]
@rdavyd looks to me like you're running into the issue from #1081 which was fixed in kube-router v1.2.3

**Comment by rdavyd** [comment]
@grimurd I've just upgraded to v1.2.3 and will monitor situation.

**Comment by aauren** [comment]
Its been a little while, just wanted to check in. We've had a number of users running v1.2.3 for a while now without issue.

@grimurd are you still experiencing this issue? Any additional information you could give if it is happening?

**Comment by grimurd** [comment]
@aauren the pods haven't crashed for a few weeks but the logs still contain iptables related errors

[Log from a running pod](https://pastebin.com/SfHfL2r5)
[Previous log from the same pod](https://pastebin.com/N4P05Gf2)

**Comment by aauren** [comment]
It looks like from your current log, that the only errors in there are still some errors around multiple invocations of ipset logic.

I recently found / merged a fix for adding some additional locking that I had previously missed: https://github.com/cloudnativelabs/kube-router/commit/9bc55dc1fad4e07863e144ff8b474117be543e6e

This fix should be present in the 1.3.1 build that I'm releasing later today. Maybe try that and see if the remainder of your issues go away?

**Comment by grimurd** [comment]
I've updated to the v1.3.1 release. I'll reopen this issue if the pods keep crashing.
