### ISSUE TITLE
iPV6 service IP is not creating the ipvsadm table

### ISSUE THREAD

**Issue by kannanvr** [cloudnativelabs/kube-router#1148]
**What happened?**
Service IP with IPV6 is not created the ipvsadm rules. 
We want to support ipv6 on kubernetes stack. we installed 1.20 version of kubernetes with Dualstack. 
For pod Networking with IPV6 we added the annotation kube-router.io/pod-cidr on all worker nodes..
Now pods were allocated with ipv6 IP. But service when we tried creatig with ipv6 , it is not reachable. 
Its due to ipvsadm is not created.
**What did you expect to happen?**
We wanted to reach ipv6 with service IP

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.3.0
 - Kubernetes Version (`kubectl version`) : 1.20
 -  - Cloud Type: On Premise
 - Cluster Size: 2 nodes

**Comment by aauren** [comment]
This is known. Unfortunately at this time, kube-router does not fully support IPv6. It's something that we've had on the roadmap for a long time, however, recently most of the development time has gone towards bug fixes and performance improvements to help the IPv4 use-cases that are already on-going.

We do still have the IPv6 use-case on our mind, and we'll probably try to make a push for IPv6 in the next couple of minor releases. However, this is hampered a bit by none of the maintainers really having a strong use-case for IPv6.

While it can be difficult to contribute core code like this, as the doc says we do welcome improvements from the community.

At this point, I'm going to close this issue, as I don't think that it will be helpful as IPv6 is a known improvement and is pretty well documented as a deficiency of the project.
