### ISSUE TITLE
ExtrrnalIP advertisement stopped

### ISSUE THREAD

**Issue by rkojedzinszky** [cloudnativelabs/kube-router#1154]
**What happened?**

When two or more services use the same externalIP, and one service is modified by removing that externalIP, the IP is not advertised anymore. If I simply delete one of the services, the advertisement remains in place, as expected.

**What did you expect to happen?**

I expect the advertisement not disappearing.

**How can we reproduce the behavior you experienced?**
1. Setup external bgp connections for a node
2. Enable advertising externalIP
3. Create two services sharing the same externalIP
4. Observe the advertisement on external bgp peer
5. Edit on of the services, removing the externalIP
6. The advertisement will disappear

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`):
```
Running /usr/local/bin/kube-router version v1.3.0, built on 2021-07-05T21:05:58+0000, go1.16.5
```
 - Kube-router flags:
```
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --bgp-graceful-restart=true
        - --bgp-graceful-restart-deferral-time=30s
        - --advertise-pod-cidr=false
        - --advertise-external-ip=true
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --iptables-sync-period=24h
        - --ipvs-sync-period=24h
        - --routes-sync-period=24h
```
 - Kubernetes Version (`kubectl version`) : 1.21.3
 - Cloud Type: Bare metal
 - Kubernetes Deployment Type: kubeadm
 - Kube-Router Deployment Type: daemonset
 - Cluster Size: 10 nodes

**Comment by murali-reddy** [comment]
thanks for reporting the issue @rkojedzinszky I can confirm the issue is occurring on latest release as well. We fixed it recently https://github.com/cloudnativelabs/kube-router/pull/1047 same use-case but seems like there is still a possible bug. Will take a look into it
