### ISSUE TITLE
Panic while starting network policy controller

### ISSUE THREAD

**Issue by rjosephwright** [cloudnativelabs/kube-router#1155]
**What happened?**
Kube router panics intermittently while starting the network policy controller.

**What did you expect to happen?**
The network policy controller should complete initialization and then the network route controller should start.

**How can we reproduce the behavior you experienced?**
Since the problem is intermittent, I usually need to terminate & replace nodes in the cluster until one of them exhibits the behavior.

**System Information (please complete the following information):**
 - Kube-Router Version: This happens with `v1.3.0` and `v1.3.1`
 - Kube-Router Parameters: `--run-router=true --run-firewall=true --run-service-proxy=false --disable-source-dest-check=false --bgp-graceful-restart=true`
 - Kubernetes Version (`kubectl version`) : `v1.19.14`, `v1.20.9`, `v1.20.10`, `v1.21.4`
 - Cloud Type: AWS
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 6-10 nodes

**Logs, other output, metrics**

```
I0814 20:16:00.003755       1 version.go:21] Running /usr/local/bin/kube-router version v1.3.1, built on 2021-08-13T15:31:53+0000, go1.16.7
I0814 20:16:00.116756       1 network_routes_controller.go:1260] Could not find annotation `kube-router.io/bgp-local-addresses` on node object so BGP will listen on node IP: 172.31.93.82 address.
I0814 20:16:00.193518       1 network_policy_controller.go:148] Starting network policy controller
F0814 20:16:00.212008       1 network_policy_controller.go:351] Failed to run iptables command to create KUBE-ROUTER-INPUT chain due to running [/sbin/iptables -t filter -N KUBE-ROUTER-INPUT --wait]: exit status 4: iptables v1.8.7 (nf_tables):  CHAIN_USER_ADD failed (File exists): chain KUBE-ROUTER-INPUT
goroutine 173 [running]:
k8s.io/klog/v2.stacks(0xc000130001, 0xc000980000, 0x132, 0x2b0)
	/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x31e8c60, 0xc000000003, 0x0, 0x0, 0xc000553810, 0x0, 0x28d23da, 0x1c, 0x15f, 0x0)
	/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printf(0x31e8c60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2169122, 0x3b, 0xc0007ab880, 0x2, ...)
	/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:753 +0x19a
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:1514
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).ensureTopLevelChains(0xc00029a8c0)
	/build/pkg/controllers/netpol/network_policy_controller.go:351 +0x62e
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run(0xc00029a8c0, 0xc000133e60, 0xc0001002a0, 0xc000296e30)
	/build/pkg/controllers/netpol/network_policy_controller.go:152 +0x172
created by github.com/cloudnativelabs/kube-router/pkg/cmd.(*KubeRouter).Run
	/build/pkg/cmd/kube-router.go:197 +0xbbd
```

The full output is available at https://gist.github.com/rjosephwright/2d5a3b3a94e6e90aa76d7f0945bfca9b.

**Comment by murali-reddy** [comment]
@rjosephwright thanks for reporting the issue.

Can you please provide me the distro used in the AMI?

`iptables v1.8.7 (nf_tables)` indicates NFTABLES are in use instead of iptables (legacy mode)

You should be able to switch to legacy mode (for e.g. for debian https://wiki.debian.org/iptables).

Having said that, code where fatal error is occurring should have checked if chain already exists and only should add if it does not exist. There is check for error code 1, as seen perhaps only legacy mode, in this case exit status is 4. 

Nevertheless  need code fix which will handle the check gracefully

**Comment by murali-reddy** [comment]
Also, iptables with nf_tables back-end is supposed to be backward compatible, but we have not tested. So please use iptables legacy mode.

**Comment by rjosephwright** [comment]
@murali-reddy this is running on Debian Buster. I will try setting iptables to legacy mode.
