### ISSUE TITLE
kube-router-1.3.1: Hairpin mode enabled does not create rules

### ISSUE THREAD

**Issue by babykart** [cloudnativelabs/kube-router#1158]
**What happened?**
The container's service is no longer reachable from inside the container.

**What did you expect to happen?**
With hairpin mode enabled, I should reach a container's service from inside the container.

**How can we reproduce the behavior you experienced?**
1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Screenshots / Architecture Diagrams / Network Topologies **
If applicable, add those here to help explain your problem.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`):
 
 ```console
Running kube-router version v1.3.1, built on 2021-08-13T15:31:53+0000, go1.16.7
```

 - Kube-Router Parameters:

```console
--run-router=true --run-firewall=true --run-service-proxy=true --bgp-graceful-restart=true --kubeconfig=/var/lib/kube-router/kubeconfig --enable-overlay=true --hairpin-mode=true
```
```console
  cni-conf.json: |
    {
       "cniVersion":"0.3.0",
       "name":"mynet",
       "plugins":[
          {
             "name":"kubernetes",
             "type":"bridge",
             "bridge":"kube-bridge",
             "hairpinMode":true,
             "isDefaultGateway":true,
             "ipam":{
                "type":"host-local"
             }
          },
          {
             "type":"portmap",
             "capabilities":{
                "snat":true,
                "portMappings":true
             }
          }
       ]
    }
```

 - Kubernetes Version (`kubectl version`) : 

```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"archive", BuildDate:"2021-07-27T08:32:34Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

 - Cloud Type: on premise
 - Kubernetes Deployment Type: k3s
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 1 node

** Logs, other output, metrics **
Please provide logs, other kind of output or observed metrics here.

**Additional context**
I tried to add the annotation (kube-router.io/service.hairpin=) on the service but the result is the same.

**Comment by aauren** [comment]
@babykart can you add the steps to reproduce this? 

Make sure to include the ranges that you are using for Cluster IPs and Pod IPs.

Also, we would need to know which IPs you're trying to use to access the service.

Please default to adding as much information as possible, if there is anything else you can think that would be helpful to add (like `kubectl get pods -o wide --all-namespaces` or `kubectl get services -o wide --all-namspaces` or any other output) please include it.

Finally, it would be helpful to have a full dump of iptables for the nat table.

I can tell you that we have been using this feature extensively in our cluster and haven't run into any problems, so while I there maybe a bug here it likely has something to do with a nuance to how you're trying to use it and the only way to flush it out will be with a lot more details.

**Comment by babykart** [comment]
> @babykart can you add the steps to reproduce this?
> 

The step to reproduce is  : 

1. Create a pod with the associate service (in my example TCP 3000)
2. Try to reach the service inside this container: nok

```console
kubectl exec -n git gitea0-5d5795b499-xbgqf -ti -- bash

nslookup gitea0.git.svc.e8e.0.ant0
Server:		10.1.0.10
Address:	10.1.0.10:53

Name:	gitea0.git.svc.e8e.0.ant0
Address: 10.1.208.11
```
```console
curl -I http://gitea0.git.svc.e8e.0.ant0:3000
... timeout ...
curl -I http://10.1.208.11:3000
... timeout ...
```
```console
curl -I http://10.0.0.21:3000
HTTP/1.1 200 OK
Set-Cookie: i_like_gitea=432b2d8597aaef62; Path=/; HttpOnly; SameSite=Lax
Date: Tue, 31 Aug 2021 16:26:25 GMT

curl -I http://127.0.0.1:3000
HTTP/1.1 200 OK
Set-Cookie: i_like_gitea=d1b8a258dc97e135; Path=/; HttpOnly; SameSite=Lax
Date: Tue, 31 Aug 2021 16:26:41 GMT
```

3. Try to reach the service from another pod: ok

```console
kubectl exec -n et0ie wkr0-779d775bd9-2z8gr -ti -- bash

curl -I http://gitea0.git.svc.e8e.0.ant0:3000
HTTP/1.1 200 OK
Set-Cookie: i_like_gitea=cc5226f4d5cfd4c3; Path=/; HttpOnly; SameSite=Lax
Date: Tue, 31 Aug 2021 16:27:22 GMT
```

> Make sure to include the ranges that you are using for Cluster IPs and Pod IPs.

cluster-cidr: 10.0.0.0/16
service-cidr: 10.1.0.0/16

> 
> Also, we would need to know which IPs you're trying to use to access the service.
> 
> Please default to adding as much information as possible, if there is anything else you can think that would be helpful to add (like `kubectl get pods -o wide --all-namespaces` or `kubectl get services -o wide --all-namespaces` or any other output) please include it.

```console
kubectl get pod,svc -n git -o wide
NAME                          READY   STATUS    RESTARTS   AGE   IP          NODE       NOMINATED NODE   READINESS GATES
pod/pgsql0-5f85574678-5nn2j   1/1     Running   0          45h   10.0.0.19   babykart   <none>           <none>
pod/redis0-5f4df4fc54-vtkwd   1/1     Running   0          45h   10.0.0.20   babykart   <none>           <none>
pod/gitea0-5d5795b499-xbgqf   1/1     Running   0          45h   10.0.0.21   babykart   <none>           <none>

NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE   SELECTOR
service/pgsql0   ClusterIP   10.1.58.3      <none>        5432/TCP   45h   app=pgsql0
service/redis0   ClusterIP   10.1.166.224   <none>        6379/TCP   45h   app=redis0
service/gitea0   ClusterIP   10.1.208.11    <none>        3000/TCP   45h   app=gitea0
```

> 
> Finally, it would be helpful to have a full dump of iptables for the nat table.
> 

```console
iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N KUBE-HOSTPORTS
-N KUBE-KUBELET-CANARY
-N KUBE-MARK-DROP
-N KUBE-MARK-MASQ
-N KUBE-POSTROUTING
-N KUBE-ROUTER-HAIRPIN
-A PREROUTING -m comment --comment "kube hostport portals" -m addrtype --dst-type LOCAL -j KUBE-HOSTPORTS
-A OUTPUT -m comment --comment "kube hostport portals" -m addrtype --dst-type LOCAL -j KUBE-HOSTPORTS
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -m set --match-set kube-router-pod-subnets src -m set ! --match-set kube-router-pod-subnets dst -m set ! --match-set kube-router-node-ips dst -j MASQUERADE --random-fully
-A POSTROUTING ! -s 10.0.0.0/24 ! -d 10.0.0.0/24 -m ipvs --vdir ORIGINAL --vmethod MASQ -m comment --comment "" -j SNAT --to-source 1XX.XXX.XXX.XXX --random-fully
-A POSTROUTING -m ipvs --vdir ORIGINAL -j KUBE-ROUTER-HAIRPIN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
-A KUBE-ROUTER-HAIRPIN -s 1XX.XXX.XXX.XXX/32 -d 1XX.XXX.XXX.XXX/32 -m ipvs --vaddr 10.1.0.1 --vport 443 -j SNAT --to-source 10.1.0.1
```

> I can tell you that we have been using this feature extensively in our cluster and haven't run into any problems, so while I there maybe a bug here it likely has something to do with a nuance to how you're trying to use it and the only way to flush it out will be with a lot more details.

I am using kube-router in 12 clusters (from 1 nodes to 13 nodes) with a little difference in the configuration (`--run-router=true --run-firewall=true --run-service-proxy=false --bgp-graceful-restart=true --kubeconfig=/var/lib/kube-router/kubeconfig --overlay-type=full --hairpin-mode=true`) and I have the problem on all.
I will try the downgrade to v1.3.0 to confirm that the problem appears with v1.3.1.

**Comment by aauren** [comment]
@babykart I can see that you're missing hairpin rules for your service address: `10.1.208.11` in your iptables output that you provided, but I can't seem to reproduce that in any cluster that I have access to. In all of mine, when I enable `--hairpin-mode=true` as a parameter then I get many more entries in the `KUBE-ROUTER-HAIRPIN` chain.

Here is some sample output from a kubeadm cluster that I spun up real quick and enabled hairpinning on:
```
% kubectl get services --all-namespaces -o wide
NAMESPACE     NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE    SELECTOR
default       kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP                  100d   <none>
development   toolbox      ClusterIP   10.104.86.194   <none>        443/TCP                  32d    name=toolbox
kube-system   kube-dns     ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   100d   k8s-app=kube-dns

% sudo iptables -nvL KUBE-ROUTER-HAIRPIN -t nat
Chain KUBE-ROUTER-HAIRPIN (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 SNAT       all  --  *      *       172.20.0.14          172.20.0.14          vaddr 10.96.0.10 vport 53 to:10.96.0.10
    0     0 SNAT       all  --  *      *       172.20.0.13          172.20.0.13          vaddr 10.96.0.10 vport 9153 to:10.96.0.10
    0     0 SNAT       all  --  *      *       172.20.0.14          172.20.0.14          vaddr 10.96.0.10 vport 9153 to:10.96.0.10
    0     0 SNAT       all  --  *      *       10.126.100.243       10.126.100.243       vaddr 10.96.0.1 vport 443 to:10.96.0.1
    0     0 SNAT       all  --  *      *       172.20.1.13          172.20.1.13          vaddr 10.104.86.194 vport 443 to:10.104.86.194
    0     0 SNAT       all  --  *      *       172.20.0.12          172.20.0.12          vaddr 10.104.86.194 vport 443 to:10.104.86.194
    0     0 SNAT       all  --  *      *       172.20.0.13          172.20.0.13          vaddr 10.96.0.10 vport 53 to:10.96.0.10
```

You can see for each of the service/pod combinations I have a `vaddr` entry for hairpinning.

Are you seeing any log output from kube-router? Something must be different about your environment.

My kubeadm environment used `iptables-1.8.7-1ubuntu2`

**Comment by babykart** [comment]
@aauren thanks for your reply
My iptables version : `iptables v1.8.7 (legacy)`
Kernel: `5.10.61`

Nothing special in kube-router stdout:

```console
I0829 19:14:11.140143       1 version.go:21] Running /usr/local/bin/kube-router version v1.3.1, built on 2021-08-13T15:31:53+0000, go1.16.7
I0829 19:14:11.310828       1 network_routes_controller.go:1260] Could not find annotation `kube-router.io/bgp-local-addresses` on node object so BGP will listen on node IP: 1XX.XXX.XXX.XXX address.
I0829 19:14:11.513713       1 network_routes_controller.go:222] Setting MTU of kube-bridge interface to: 1480
I0829 19:14:11.514070       1 network_services_controller.go:300] Starting network services controller
I0829 19:14:11.514983       1 network_routes_controller.go:249] Starting network route controller
I0829 19:14:11.522542       1 network_routes_controller.go:991] Could not find BGP peer info for the node in the node annotations so skipping configuring peer.
I0829 19:14:11.669303       1 network_policy_controller.go:148] Starting network policy controller
I0829 19:14:11.700325       1 network_policy_controller.go:159] Starting network policy controller full sync goroutine
```

And nothing in kubelet.log.

Well, if you can not reproduce it's probably relative to the kubernetes distribution that I use because the problem is OS independent on my side.

**Comment by aauren** [comment]
I went through the code in depth and I don't currently see how hairpinning rules wouldn't show up with this option enabled in the absence of any errors. If you want to go over the logic to see if you can see anything that might be causing this on your nodes you're welcome to go over the code as well: https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/proxy/network_services_controller.go#L1392

However, in absence of any way to reproduce this locally, or a smoking gun, I'm going to close the issue for now. I'm more than willing to re-open if something changes.
