### ISSUE TITLE
Missing documentation on https://www.kube-router.io/docs/user-guide/#bgp-configuration

### ISSUE THREAD

**Issue by theonlydoo** [cloudnativelabs/kube-router#1177]
[Linked page](https://www.kube-router.io/docs/user-guide/bgp.md) is a 404
![image](https://user-images.githubusercontent.com/1903124/138280295-f894ee47-2989-4f0b-93b1-3ea52d53d890.png)

**Comment by aauren** [comment]
Yes, unfortunately this is a known issue (https://github.com/cloudnativelabs/kube-router/issues/814), I would recommend using the documentation found on GitHub here: https://github.com/cloudnativelabs/kube-router/tree/master/docs
