### ISSUE TITLE
User should be able to turn off IPIP tunneling

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#119]
For cross subnet pod-to-pod connectivity Kube-router currently uses IPIP tunnelining. While having it default enabled is safe bet. User should be able to disable IPIP tunnelining.

If routing infrastructure can route traffic between the pods across the subnets then we dont need IPIP tunneling.

A node sends packet destined for the pod on node in different subnet, to ite default gateway. If default gateway can route the traffic then there is no need for tunneling.

**Comment by SEJeff** [comment]
Is there any plan to work on this? This also bit us in our kube-router deployment. IPIP is the reason we went with BGP for our network in the first place.

**Comment by murali-reddy** [comment]
@SEJeff i will get this fixed.

**Comment by murali-reddy** [comment]
@SEJeff I have [patch](https://github.com/cloudnativelabs/kube-router/pull/154) ready for this issue. 

When IP-in-IP tunneling is diabled, no routes for the pods in remote node in different subnet will get added. Its assumed that default gateways for the nodes would learn the routes (by BGP peering) for all the pods. I hope this is the behaviour you are expecting as well?

**Comment by jdconti** [comment]
@murali-reddy 👍 that's the behavior we're expecting, thanks for the quick turnaround!

**Comment by SEJeff** [comment]
Yup that looks perfect. My goal was to use kube-router like [Calico with 1 AS per rack](https://docs.projectcalico.org/v2.1/reference/private-cloud/l3-interconnect-fabric#the-as-per-rack-model)

**Comment by murali-reddy** [comment]
thanks @SEJeff @jdconti for comfirming.

Please try `cloudnativelabs/kube-router-git:disable_ipip` image with the fix (image with the fix on top of last release).

You can use use the flag `--enable-overlay` to turn on/off tunneling. When flag is set to false, any existing tunnels (created earlier) will be cleaned up.

**Comment by murali-reddy** [comment]
@SEJeff @jdconti  Latest release https://github.com/cloudnativelabs/kube-router/releases/tag/v0.0.16 has the fix for this issue.
