### ISSUE TITLE
kube-router-hairpin in nat table cannot be updated in real time

### ISSUE THREAD

**Issue by z461948964** [cloudnativelabs/kube-router#1196]
当我删除一个pod然后重新拉起后，nat 表中的 KUBE-ROUTER-HAIRPIN 链会删除原来pod和svc的条目，但不会生成新的 pod和svc 的规则；除非iptables -t nat -F 后，systemctl restart kube-router 重启服务后会生成新的规则，但是我们希望它能实时动态更新Chain KUBE-ROUTER-HAIRPIN   

kubernetes:1.22.4    kube-router:1.3.2      --hairpin-mode=true     hairpinMode:true

**Comment by aauren** [comment]
I'm sorry, but unless you can translate your issue to English we won't be able to help you and will close the issue.

**Comment by z461948964** [comment]
When I delete a pod and pull it up again,KUBE-ROUTER-HAIRPIN CHAIN in NAT table will delete the original entries of pod and SVC,However, new rules for pod and SVC will not be generated；Unless after "iptables - t NAT - F && systemctl restart kube router" will generate new rules after restarting the service, but we hope it can dynamically update Chain KUBE-ROUTER-HAIRPIN

kubernetes:1.22.4 kube-router:1.3.2 --hairpin-mode=true hairpinMode:true

**Comment by aauren** [comment]
Can you post your log files for kube-router?

It would also be helpful to see your exact steps to replicate this issue along with the state of the KUBE-ROUTER-HAIRPIN chain at each of the steps.

**Comment by z461948964** [comment]
![图片1](https://user-images.githubusercontent.com/45219126/144383998-01556a5b-35f3-411e-bbdf-8eac9587ee6c.png)
![图片2](https://user-images.githubusercontent.com/45219126/144384057-34054bf0-1e91-43bd-ad96-a908afd2a7d5.png)

**Comment by z461948964** [comment]
![图片3](https://user-images.githubusercontent.com/45219126/144384223-42506419-3bda-4d9d-af0f-952a7dfa9253.png)
When I delete the pod and restart it, curl clusterip will timeout after entering the new nginx pod; Observe node01. After about 20 to 60 seconds, the original entry will be deleted, but no new rule has been generated

**Comment by z461948964** [comment]
![图片5](https://user-images.githubusercontent.com/45219126/144386238-98b39512-3b0d-42f8-ad24-1c80965b9856.png)
When I execute "iptables - t NAT - F & & systemctl restart kube-router",I can see that a new rule is generated immediately, and then curl clusterip can pass. In fact, I have observed that the "Chain KUBE-ROUTER-HAIRPIN" rule will only be reduced and will not be added unless you clear the NAT rule first and then restart the kube-router service.

**Comment by z461948964** [comment]
[kube-router.log](https://github.com/cloudnativelabs/kube-router/files/7640370/kube-router.log)
This is the log of "kube-router"

**Comment by aauren** [comment]
@z461948964 Thanks for taking the time to translate your issue and for reporting. After spending some time I was able to reproduce the issue you described and found several bugs.

I've created #1200 to help fix these issues, can you please test it out in your environment and see if it resolves the issue you were experiencing?

**Comment by z461948964** [comment]
> @z461948964感谢您花时间翻译您的问题并进行报告。花了一些时间后，我能够重现您描述的问题并发现了几个错误。
> 
> 我创建了#1200来帮助解决这些问题，您能否在您的环境中对其进行测试，看看它是否解决了您遇到的问题？

**Comment by z461948964** [comment]
I have recompiled the "kube-router" file with the "fix_hairpinning" branch, and now a new rule will be generated soon after restarting pod.      
Thank you very much for your help. I like "kube-router" very much. I wish you a happy life.

**Comment by z461948964** [comment]
![微信图片_1](https://user-images.githubusercontent.com/45219126/144715351-907e0277-cb11-4068-9cf3-bc6d176aae93.png)
![微信图片_2](https://user-images.githubusercontent.com/45219126/144715358-1d212a38-3daa-4414-9fd6-c042f9454af0.png)

Sorry, I think there is something wrong with the generation of "kube-router-hairpin" chain.

As shown in the figure, pod is at node01. I think the two rules of kube-router-hairpin chain are necessary at the node where pod is located. For example, in the master01 node, because there are rules in the red box above, it will not match the first one in the red box below; The second item in the red box below will not be matched, because clusterip is DNAT at the node of pod. 

Of course, the addition of these two rules to nodes other than the pod has no impact, but with the increase of services, these rules will become more and more, which is not very friendly.

**Comment by aauren** [comment]
@z461948964 - #1208 should reduce the number of hairpin rules significantly by forcing it to only consider pods with local endpoints. Let me know if that resolves the situation you're seeing.

**Comment by z461948964** [comment]
Yes, I used the branch: "aauren: hairpin_on_node_local" to test, which solved my problem. Thank you!
