### ISSUE TITLE
provide service visualization

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#12]
If we have to track connections for #10 and #5 anyway,  we very well expose http endpoint on Kube-router to visuaize dynamic state of services. Kube-router runs a daemonset so we have pod running on the node, we can expose a service as node port type that can give a light weight service visualization.

**Comment by murali-reddy** [comment]
some thing like http://qubeviz-demo.s3-website-us-east-1.amazonaws.com from [qube-viz](https://github.com/chiradeep/qube-viz) would be nice

**Comment by bzub** [comment]
We could maintain a Grafana dashboard definition and use the Diagram Panel to add some metrics to the visualization (connections to services/endpoints, etc).  Pros/Cons below, but the alternative would be a custom webapp more-or-less.

Pros:
- Easily reuse our own Prometheus metrics
- Widely deployed already on k8s clusters
- Limited scope of kube-router binary

Cons:
- Requires setup of a Grafana server
- May break with Grafana version changes

**Comment by aauren** [comment]
Closing as stale
