### ISSUE TITLE
Can kube-route cni configure 2 interfaces to a pod and there forward iptables rules in node

### ISSUE THREAD

**Issue by rohitashvadialpad** [cloudnativelabs/kube-router#1247]
**Is your feature request related to a problem? Please describe.**
My pod pod1 is getting ingress traffic from below 2 different sources. This pods is schedules on node1.
sources1 : Other internal components.
sources2 : External sources.

pod1 has to listen on 2 different IP's for ingress traffic and based on ingress sources, pod1 has to reply. In reply packet, source ip should be marked to one of the pod1 interface where pod1 got this ingress packets.

Currently on node1, kube-router is doing below jobs: 
1. Allocating only one private ip to pod1.
2. Creating below iptable rules to forward ingress traffic to pod1.

-A FORWARD -d <pod_private_ip> -m physdev --physdev-is-bridged -m comment --comment "rule to jump traffic destined to POD name:pod1 namespace: default to chain <kube-pod-fwd>" -j <kube-pod-fwd>
-A FORWARD -d <pod_private_ip> -m comment --comment "rule to jump traffic destined to POD name:pod1 namespace: default to chain <kube-pod-fwd>" -j <kube-pod-fwd>
-A OUTPUT -d <pod_private_ip> -m comment --comment "rule to jump traffic destined to POD name:pod1 namespace: default to chain <kube-pod-fwd>" -j <kube-pod-fwd>
-A <kube-pod-fwd> -d <pod_private_ip> -m comment --comment "rule to permit the traffic traffic to pods when source is the pod\'s local node" -m addrtype --src-type LOCAL -j ACCEPT
-A <kube-pod-fwd> -m comment --comment "default rule to REJECT traffic destined for POD name:pod1 namespace: default" -j REJECT --reject-with icmp-port-unreachable

For resolving my issue, kube-router needs to allocate 2 private ip to pod1 and create iptable rules to forward ingress traffic to pod1 to both the pod1 private ip's.

I'm not sure whether kube-router is supporting multi-interface functionality currently. Can someone help me here to understand how i can achieve above use case.

This looks like a general ask from many users as many company wants to have separate interfaces for internal and external ingress traffic.

**Describe the solution you'd like**
For resolving my issue, kube-router needs to allocate 2 private ip to pod1 and create iptable rules to forward ingress traffic to pod1 to both the pod1 private ip's.

**Describe alternatives you've considered**
I can see there are few cni who are supporting multiple interfaces.

**Additional context**
NA

**Comment by aauren** [comment]
So there are a couple of things here. First off, kube-router doesn't assign IPs to pods, that is the role of the CNI plugin. However, I don't believe that kube-router would support a CNI which allocated multiple pod IPs in its current state. Or at least I've never heard of a working configuration in which a user has done that. The CNI that we currently recommend using, bridge + ipam, doesn't allow for multiple IPs to be associated with a pod. Supporting such a use-case is not something that is on our roadmap currently.

Additionally, kube-router's support for multi-homed devices is currently very limited. This is a request that we've seen a fair number of times, there is even an issue label out there for it where I've started to compile use-cases. However, supporting mutli-homed use-cases is tricky as Kubernetes doesn't give many semantics for supporting this itself. So each CNI has to forge its own path in this area.

This combined with the fact that none of the maintainers have a multi-homed use case and the fact that of all of the requests that we've had to support it there are very few commonalities across use-cases, means that it hasn't been a large priority for the project.

If there were a user that wanted to comb through the related issues, find the commonalities and then suggest a development path forward, we'd be open to reviewing that, but as it stands now, no one has done that work.
