### ISSUE TITLE
Kube-router network policy controller saves and restores the entire iptables

### ISSUE THREAD

**Issue by nqdao** [cloudnativelabs/kube-router#1248]
**What happened?**
Kube-router network policy controller saves and restores the entire iptables. If there is change applied to iptables by another service between iptables-saves and iptables-restore, the change will get wiped.

**What did you expect to happen?**
The network policy controller should only saves and restores its network policy rules. It should not affect rules by other components.

**How can we reproduce the behavior you experienced?**
1. During kube-router sync, apply an iptables change between iptables-save and iptables-restore of kube-router.
2. Check if the change persists after restore.

**Screenshots / Architecture Diagrams / Network Topologies **
If applicable, add those here to help explain your problem.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): `8e9dfcd6481eb7265e8abbad87d06c44fd0b10e2`
 - Kube-Router Parameters: `--run-router=false --run-firewall=true --run-service-proxy=false`
 - Kubernetes Version (`kubectl version`) : 1.19 and 1.20
 - Cloud Type: on-premise
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: Daemonset
 - Cluster Size: 200

** Logs, other output, metrics **
Please provide logs, other kind of output or observed metrics here.

**Additional context**

**Comment by aauren** [comment]
The decision to use iptables-save and iptables-restore was a very calculated decision as exec'ing out to iptables bears a considerable cost. When we were doing individual execs, we found that the time it took to sync iptables in a small - medium sized cluster was anywhere from 2 - 5 minutes. So rolling back this change, is not something that is acceptable for the project.

In general, kube-router has the ability to play well with other iptables orchestrators that launch and do all of their configuration before kube-router starts. I've seen and maintained multiple sites that have successfully used this methodology for setting up a set of host based policies.

Additionally, if you have a system that uses nftables, you can get away with a system that dynamically generates rules while the host is running as long as it doesn't touch any of the root iptables names or any of the ones that kube-router generates automatically. In this away, the system can run using `nft` and kube-router will happily stay in it's own iptables world. This is made even easier as the iptables legacy stuff for kube-router stays 100% in the `ip` family, and users are free to use the `inet` family how they wish with no impact from kube-router.

All of that being said, kube-router currently is unable to play nice with other engines that are attempting to dynamically control the firewall via `iptables` directly. Given the nature of iptables, its lack of an API, etc. this is something that will not change in kube-router for as long as it uses iptables, which for now is the foreseeable future.
