### ISSUE TITLE
Integrate Envoy as ingress controller

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#130]
Explore feasibility if kube-router can embed/integrate with Envoy. We will have multiple benefits

- can provide L7 ingress
- hook into istio service mesh with out the per-pod side car

I will come up with detailed approach if its feasible.

**Comment by murali-reddy** [comment]
Integration with envoy as sidecar to kube-proxy is farily easy effort to get basic integration.

**Comment by aauren** [comment]
Closing as stale
