### ISSUE TITLE
hook build-image/make.sh into main Makefile

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#135]
as mentioned in #134 kube-router can not be built on Mac. @Thoro submitted patch to build kube-router on Mac. We need to hook that into main Makefile, so that all commands work seamlessly on both Linux and Mac.

**Comment by roffe** [comment]
We can build on Mac fine with BUILD_IN_DOCKER option added in https://github.com/cloudnativelabs/kube-router/pull/377 , Closing the issue, feel free to reopen if needed
