### ISSUE TITLE
CNI config should be corrected when autoConfigureMTU() fails

### ISSUE THREAD

**Issue by tamihiro** [cloudnativelabs/kube-router#1383]
**What happened?**
My on-prem k8s cluster has nodes with multiple L3 interfaces, and each node's nodeIP is on its loopback interface.
After upgrading from pre v1.1.0 to the current version which includes #989, everything seemed fine until a new pod was being created. Newly created pods never progressed from either ContainerCreating or Init:0/1 state.

Found this error log from kube-router pods.

> I1017 21:30:50.456803   29452 network_routes_controller.go:245] Setting MTU of kube-bridge interface to: 65536
> E1017 21:30:50.456910   29452 network_routes_controller.go:248] Failed to set MTU for kube-bridge interface due to: invalid argument

CRI (containerd) kept logging this error mesage.

> Oct 17 21:31:31 tkw-nwop-k8s-wn6 containerd[2648204]: time="2022-10-17T21:31:31.938043966+09:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:rook-ceph-detect-version-8wv4z,Uid:43a729b6-f6e1-4b88-9111-1a8891626cdf,Namespace:rook-ceph,Attempt:0,} failed, error" error="failed to setup network for sandbox \"83e6d5b95244f096662ea33b760693059f1331b2a55c683b48baf3afb07d9283\": failed to make veth pair: invalid argument"

After a while I found that it was invalid because the MTU detected from nodeIP is 65536 while kube-bridge's max MTU is 65535.

```
4: kube-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 66:86:13:04:e9:8c brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535 
    ...
```

Then I found that I could have set `--auto-mtu=false` with specific MTU (`"mtu": 1500`) in the manifest yaml file. I did edit the yaml and applied it. But the worker node's containerd still fails to make a veth pair.
After some head scratching, I figured that the incorrect MTU (65536) for kube-bridge was still there in the node's `/etc/cni/net.d/10-kuberouter.conflist` . 

**What did you expect to happen?**
First I thought /etc/cni/net.d/10-kuberouter.conflist should be always written upon every kube-router restart.
This way, once I disable auto-mtu and restart kube-router, the CNI config file would be updated with a correct MTU.
All it would take to do so is to delete the following condition from the yaml template. 

```
          if [ ! -f /etc/cni/net.d/10-kuberouter.conflist ]; then
              ....
          fi
```

However, it seems to me the real issue is that kube-router writes kube-bridge's MTU value to the CNI config with no validation, then it actually tries and fails to set the MTU with that value, but it leaves the config file uncorrected. 

What I expect to happen is kube-bridge's MTU should be overwritten with a valid size in the CNI config file after actually failing to set the invalid size.

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): v1.5.1
 - Kube-Router Parameters: --run-router=true --run-firewall=true --run-service-proxy=true --bgp-graceful-restart=true --kubeconfig=/var/lib/kube-router/kubeconfig --cluster-asn=4294901760 --advertise-pod-cidr=false --advertise-cluster-ip=false --advertise-external-ip=true --peer-router-asns=4294902008,4294902009 --peer-router-ips=x.x.x.x,y.y.y.y --peer-router-multihop-ttl=4 --metrics-path=/metrics --metrics-port=50052

 - Kubernetes Version (`kubectl version`) : v1.22.15
 - Cloud Type: on premise
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 6 Nodes

**Additional context**
My PR #1382 includes a patch that fixes this by overwriting the config file with the original MTU size if the new MTU is invalid.

**Comment by aauren** [comment]
Fixed via #1382
