### ISSUE TITLE
NodePort type service choose NodeIP

### ISSUE THREAD

**Issue by fisherxu** [cloudnativelabs/kube-router#139]
Something I want to know, in my node has internal IP, but if I want to reach the NodePort through external Ip, the code return the first internal IP default, how can I  get service through external Ip?

**Comment by murali-reddy** [comment]
@fisherxu yes, NodePort service will only provide [service only on NodeIP](https://github.com/cloudnativelabs/kube-router/blob/master/app/controllers/network_services_controller.go#L260). 

AFAIK, kubernetes serviece definition does not presribe how to implement in case node has multiple interfaces and ip's assigned to the nodes. Please see this [proposal](https://github.com/kubernetes/kubernetes/issues/21070) which has some details.

Are you using any public cloud or its baremetal setup. If public cloud you can use `LoadBalancer` service type of use `ingress`.

Also, can i know what you meant by `external Ip`?  Do you have a additional interfaces on the nodes with externally accessible IP's?

**Comment by murali-reddy** [comment]
@fisherxu Yes, kube-proxy does listen on any interface quoting the comment in the [bug](https://github.com/kubernetes/kubernetes/issues/21070)

```
For now, we are listening on any interface for nodePorts.
It can be a problem for machines with a public and private address, where we only want to provide a service in private network.
```
there are pros and cons.

But i do agree to your point. Till Kubernetes `NodePort` semantics explicitly define the expected behaviour, perhaps its better to let user decide how they want to define `NodePort` service behaviour.

I will add a flag to change the current behaviour, so that Kube-router can confirm to the semantics implemented by Kube-proxy.

**Comment by fisherxu** [comment]
> I will add a flag to change the current behaviour, so that Kube-router can confirm to the semantics implemented by Kube-proxy

I agree with you, the IPs of NodePort should set to be configurable in Service. In kube-router now I think it should be said to users in doc clearly, Otherwise in the case of multiple interfaces user maybe can't get reached through NodePort  : )

**Comment by murali-reddy** [comment]
Ok, i tried to fix this issue. It seems there is no simple fix with ipvs. 

I was hoping there is simple way to specify bind on all ip/interfaces (some thing like 0.0.0.0 as VIP). Though we can create service with `0.0.0.0` as VIP for the service it does not seem to work.

Seems like [LVS: Fwmarks](http://www.austintek.com/LVS/LVS-HOWTO/HOWTO/LVS-HOWTO.fwmark.html) is the correct way to approach the problem.

**Comment by murali-reddy** [comment]
Listening on 127.0.0.1 does not work, re-opening the bug

**Comment by m1093782566** [comment]
@murali-reddy 

Why close this issue? I think it has not be resolved yet.

**Comment by murali-reddy** [comment]
@m1093782566 You mean node port not working in general or the node port on IP `127.0.0.1` does not work? Nodeport support was properly enabled by #217 

If your question is specific to `127.0.0.1` then please see #237

**Comment by m1093782566** [comment]
Sorry, I mean `127.0.0.1` as nodeport IP.
