### ISSUE TITLE
[v2.0.0 Issue]: `advertise-cluster-ip=true` does not advertise IPv6 addresses

### ISSUE THREAD

**Issue by rwagoner** [cloudnativelabs/kube-router#1443]
When running with `--advertise-cluster-ip=true` IPv4 cluster IPs are advertised to the BGP neighbors, but IPv6 cluster IPs are not. IPv6 peering is working as I see the pod and load balancer IPv6 addresses advertised.

**System Information:**
 - Kube-Router Version (`kube-router --version`): 2.0.0-rc1
 - Kube-Router Parameters: `        - "--enable-ipv6=true" - "--run-router=true" - "--run-firewall=false" - "--run-service-proxy=false" - "--bgp-graceful-restart=true" - "--enable-cni=false" - "--enable-pod-egress=false" - "--enable-ibgp=true" - "--enable-overlay=true" - "--peer-router-ips=" - "--peer-router-asns=" - "--cluster-asn=" - "--advertise-cluster-ip=true" - "--advertise-external-ip=true" - "--advertise-loadbalancer-ip=true"`
 - Kubernetes Version (`kubectl version`) : 1.26.1
 - Cloud Type: on premise
 - Kubernetes Deployment Type: kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 9 nodes

**Comment by aauren** [comment]
Thanks for submitting this @rwagoner! I'll try to take a look at this next week.

**Comment by aauren** [comment]
@rwagoner the release that I just cut v2.0.0-rc2 should fix this ClusterIP issue. Let me know how it works out for you.

**Comment by rwagoner** [comment]
I can confirm that v2.0.0-rc2 resolves the issue and the IPv6 cluster IPs are now advertised. Thanks!
