### ISSUE TITLE
integrate with kubespray

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#147]
Kube-router alredy has nice integration in to kops, kubeadm. kubespray would be good addition.

**Comment by killcity** [comment]
+1 Has this been implemented?

**Comment by jjo** [comment]
> +1 Has this been implemented?

@killcity https://github.com/kubernetes-incubator/kubespray/pull/3339 PR implements it
in case you want to give it a try, FYI working ok on an openstack deploy.

**Comment by killcity** [comment]
> > +1 Has this been implemented?
> 
> @killcity [kubernetes-incubator/kubespray#3339](https://github.com/kubernetes-incubator/kubespray/pull/3339) PR implements it
> in case you want to give it a try, FYI working ok on an openstack deploy.

Awesome! Thanks! Would love to see this merged (assuming its relatively bug-free). I will update once I've tested.

**Comment by jjo** [comment]
@murali-reddy I think we can resolve this one now ;)

**Comment by murali-reddy** [comment]
thanks @jjo Will resolve now.

Please use kubespray version with https://github.com/kubernetes-incubator/kubespray/pull/3339 to use kube-router integration.
