### ISSUE TITLE
Beta release

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#149]
Its been more than 4 months since the first release of Kube-router. We had some excellent feedback from the users and we did 15 bug fix and feature enhancement releases in the mean time. We also have users running Kube-router in decent sized clusters. Its about time we do a Beta release and move project to Beta status.

This bug is quick checklist of things for Beta release

Checklist
- [ ] per commit CI to run Kubernetes conformance tests (Work is almost done. @bzub is tying up some loose ends)
- [x] Add Kube-router as CNI, network policy provider in kubernetes.io official documentation
- [x] Performance bench mark against other CNI  providers. Work is partly [done](https://github.com/cloudnativelabs/kube-router/issues/102)
- [x] release notes, blog
- [x] minimal functional [website](https://kube-router.io)
- [x] improve documentation
- [x] integration into (atleast popular) cluster installers. we have integrated or has way to use kops, kubeadm, bootkube so far.
- [x] Network policy egress support

**Comment by murali-reddy** [comment]
Label: `beta-blocker` to track beta-blockers.

**Comment by aauren** [comment]
@murali-reddy we're getting close to a full 1.0 release, is it safe to close this?

**Comment by murali-reddy** [comment]
Yes :)
