### ISSUE TITLE
Unexpected behavior when selectively advertising a Service

### ISSUE THREAD

**Issue by vasiliev-a-a** [cloudnativelabs/kube-router#1491]
Hello. I have tried to implement the selective Service advertisement with annotations, as it is described in the [user-guide](https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#advertising-ips), but faced some unexpected behaviors. Not sure are there features or bugs.

## Environment
The three-node Kubernetes cluster deployed with `kubeadm`:
```bash
ansible | v1.27.3 | 172.16.1.23 | Debian GNU/Linux 11 (bullseye) | 5.10.0-23-amd64 | containerd://1.6.21
test-1  | v1.27.3 | 172.16.1.21 | Debian GNU/Linux 11 (bullseye) | 5.10.0-23-amd64 | containerd://1.6.21
test-2  | v1.27.3 | 172.16.1.22 | Debian GNU/Linux 11 (bullseye) | 5.10.0-23-amd64 | containerd://1.6.21
```
```bash
kubectl annotate node --all "kube-router.io/node.asn=64515"
kubectl annotate node --all "kube-router.io/rr.client=100"
kubectl annotate node --all "kube-router.io/peer.ips=172.16.1.201"  # External Cisco router inside the GNS3, which acts as a route-reflector
kubectl annotate node --all "kube-router.io/peer.asns=64515"
```

<details>
<summary>kube-router v1.5.4 deployed as a DaemonSet with the following base arguments:</summary>
  
```bash
--run-router=true
--run-firewall=true
--run-service-proxy=true
--kubeconfig=/var/lib/kube-router/kubeconfig
--bgp-graceful-restart
--bgp-graceful-restart-time=2m
--bgp-graceful-restart-deferral-time=1m
--bgp-holdtime=2m
--enable-overlay=false
--enable-pod-egress=false
--injected-routes-sync-period=1m
--iptables-sync-period=1m
--ipvs-permit-all=false
--ipvs-sync-period=1m
--nodes-full-mesh=false
--routes-sync-period=1m
--service-cluster-ip-range=10.10.10.0/24
--service-external-ip-range=10.10.11.0/24
```
</details>

<details>
<summary>A simple Service for experiments:</summary>

```bash
tee test-service.yaml <<EOF
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: http-echo
spec:
  selector:
    matchLabels:
      application: http-echo
  template:
    metadata:
      labels:
        application: http-echo
    spec:
      containers:
      - image: mendhak/http-https-echo
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: http-echo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
        resources:
          requests:
            memory: 100Mi
...
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  clusterIP: 10.10.10.21
  externalIPs:
  - 10.10.11.21
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    application: http-echo
...
EOF
```
</details>

## Testing an "opt-out" strategy for advertising Services.
Additional arguments are provided to the kube-router DaemonSet:
```bash
--advertise-cluster-ip=true
--advertise-external-ip=true
```
<details>
  
- Inspecting the initial state:
  ```bash
  clear && kubectl get svc -A ; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/912f005e-1231-4d72-959e-c3fd1b2a95b1)

  Only the Pod networks and standard services are advertised. _**Expected**_.

- Deploying the test-service:
  ```bash
  kubectl apply -f test-service.yaml
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service ; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/5e0c0465-913a-4dfd-8c83-24dc1b8b8122)

  Both externalIP and clusterIP are advertised. _**Expected**_.

- Blacklisting the Service:
  ```bash
  kubectl annotate service test-service kube-router.io/service.advertise.clusterip="false"; \
   kubectl annotate service test-service kube-router.io/service.advertise.externalip="false"
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service -o custom-columns=SERVICE:.metadata.name,ANNOTATIONS:.metadata.annotations; echo; kubectl get svc test-service; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```  
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/b16aab37-6cc4-4d9d-b55b-2c7a579845c1)

  "False" annotations present, but both IPs still present in GoBGP table and are advertised to the router. _**Unexpected**_: shouldn't the Service's IPs gone from advertisement?

- Deleting the service:
  ```bash
  kubectl delete -f test-service.yaml
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/6f70a189-9414-4a88-9ced-bc4343f4bfca)

  There is no Service, but both IPs still present in GoBGP table and are advertised to the router. _**Unexpected**_: Service's IPs must not be advertised and should be purged from GoBGP!

- Restarting the kube-router:
  ```bash
  kubectl delete -n kube-system pod -l k8s-app=kube-router
  ```
  Observing:
  ```bash
  clear && kubectl get svc -A ; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/ad99a67d-69fe-4f79-85c3-46af8c223f5b)

  Back to the initial state. _**Expected**_.
</details>

## Testing an "opt-in" strategy for advertising Services.
Additional arguments are provided to the kube-router:
```bash
--advertise-cluster-ip=false
--advertise-external-ip=false
```
<details>
  
- Inspecting the initial state:
  ```bash
  clear && kubectl get svc -A ; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/90457547-e4bf-4359-8b11-41b3040982e5)

  Only the Pod networks are advertised. _**Expected**_.

- Deploying the test-service:
  ```bash
  kubectl apply -f test-service.yaml
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service ; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/5f280898-3cb5-498d-b158-2dfd91381606)

  No additional advertisements. _**Expected**_.

- Whitelisting the Service:
  ```bash
  kubectl annotate service test-service kube-router.io/service.advertise.clusterip="true"; \
   kubectl annotate service test-service kube-router.io/service.advertise.externalip="true"
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service -o custom-columns=SERVICE:.metadata.name,ANNOTATIONS:.metadata.annotations; echo; kubectl get svc test-service; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```  
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/c150329a-4e27-4051-9d6f-b954b666b150)

  "True" annotations present, both IPs appeared in the GoBGP table and are advertised to the router. _**Expected**_.

- Blacklisting the Service:
  ```bash
  kubectl annotate service test-service kube-router.io/service.advertise.clusterip="false" --overwrite; \
   kubectl annotate service test-service kube-router.io/service.advertise.externalip="false" --overwrite
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service -o custom-columns=SERVICE:.metadata.name,ANNOTATIONS:.metadata.annotations; echo; kubectl get svc test-service; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```  
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/3468db6e-46d5-427f-8c5e-52a5b3e8417e)

  "False" annotations present, but both IPs still present in GoBGP table and are advertised to the router. _**Unexpected**_: shouldn't the Service's IPs gone from advertisement?

- Removing annotations:
  ```bash
  kubectl annotate service test-service kube-router.io/service.advertise.clusterip-; \
   kubectl annotate service test-service kube-router.io/service.advertise.externalip-
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service -o custom-columns=SERVICE:.metadata.name,ANNOTATIONS:.metadata.annotations; echo; kubectl get svc test-service; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```  
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/451edda1-3d41-43e5-a002-08e646185a59)

  No annotations, but both IPs still present in GoBGP table and are advertised to the router. _**Unexpected**_: shouldn't the Service's IPs gone from advertisement?

- Deleting the service:
  ```bash
  kubectl delete -f test-service.yaml
  ```
  Observing:
  ```bash
  clear && kubectl get svc test-service; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/bc1ecfb5-3713-4680-a377-55f2d9bfb601)

  There is no Service, but both IPs still present in GoBGP table and are advertised to the router. _**Unexpected**_: Service's IPs must not be advertised and should be purged from GoBGP!

- Restarting the kube-router:
  ```bash
  kubectl delete -n kube-system pod -l k8s-app=kube-router
  ```
  Observing:
  ```bash
  clear && kubectl get svc -A ; echo; for i in $(kubectl get -n kube-system pod -l k8s-app=kube-router -o name) ; do kubectl -n kube-system exec $i --  gobgp global rib ; done
  ```
  ![image](https://github.com/cloudnativelabs/kube-router/assets/115141812/886cf431-ff3f-4a24-921e-94e7d51b3151)

  Back to the initial state. _**Expected**_.
</details>

Looks like a Service goes out of control once being annotated with "false". The only workaround is to restart the kube-router DaemonSet.

**Comment by aauren** [comment]
You're correct. To be honest, in the last couple of years that I've worked on kube-router I've never used the annotations to affect service advertisement, so they kinda slipped off the radar.

Thanks for finding this and reporting it. There is a fix for this in #1498 - part of that build cycle should be generating a container. When it does that, if you would be willing to try it and verify that it fixes this issue for you I'd be much obliged.

**Comment by vasiliev-a-a** [comment]
Awesome, the `image: docker.io/cloudnativelabs/kube-router-git:PR-1498` fixes the issues.

**Comment by vasiliev-a-a** [comment]
Awesome, the image: docker.io/cloudnativelabs/kube-router-git:PR-1498 fixes the issues.

**Comment by aauren** [comment]
Thanks for testing!
