### ISSUE TITLE
hairpin nat issue when source and destination pod selected by IPVS are on same node

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#151]
@Thoro reported this issue over gitter

```
Pod 1: 10.0.0.2
Pod 2: 10.0.0.3
Service 1: 10.1.0.1
```

```
(src) 10.0.0.2 -> (dst) 10.1.0.1
host does nothing with the packet except change dst:
(src) 10.0.0.2 -> (dst) 10.0.0.3
Pod 2 respond to original ip
(src) 10.0.0.3 -> (dst) 10.0.0.2
Pod 1 will say, hey I didn't sent you anything and drop the packet
```

We need to ensure this scenario works, at the same time ensuring network policies works (for which source IP need to be preserved)

**Comment by murali-reddy** [comment]
Exact issue is reported in below bugs.

https://github.com/Azure/acs-engine/issues/539
https://github.com/kubernetes/kubernetes/issues/21613

Fix is to enable `br_netfilter`

We have already enabled `br_netfilter` with release [0.0.14](https://github.com/cloudnativelabs/kube-router/releases/tag/v0.0.14)

Have verified manually by `rmmod br_netfilter` i can repro the problem and once `modprobe br_netfilter` pod-to-pod communication on same node through service ip works fine.

@Thoro please re-open if upgrading to latest release does not address your problem

**Comment by dry4ng** [comment]
I was experiencing the same issue on my CentOS 7.3. As it turned out running `modprobe br_netfilter` doesn't enable `bridge-nf-call-iptables`. I have to first remove the module and then re-add it:

```
[root@kube-node ~]# cat /proc/sys/net/bridge/bridge-nf-call-iptables 
0 
[root@kube-node ~]# modprobe br_netfilter
[root@kube-node ~]# cat /proc/sys/net/bridge/bridge-nf-call-iptables
0
[root@kube-node ~]# rmmod br_netfilter
[root@kube-node ~]# modprobe br_netfilter
[root@kube-node ~]# cat /proc/sys/net/bridge/bridge-nf-call-iptables
1
```
