### ISSUE TITLE
Use AWS VPC routing table for cross-zone pod networking

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#153]
In current kube-router implementation, for pod-to-pod network across the nodes in different zones we use IP-in-IP tunneling. While this works for any cluster sizes, for small deployments with less than 50 nodes we would rather have option to use direct routing through AWS VPC route tables.

But there is limit of [50 entries in the routing table](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html) so it wont work if the cluster size is more than 50 nodes.

But if some one want native VPC performance and has cluster size less than 50 nodes, they can choose this option. If the cluster size goes larger than 50 nodes, there should be option to upgrade to ip-in-ip tunneling.

**Comment by rvadim** [comment]
Hi!
Currently, you can use up to 1000 entries per routing table and 50 by default. So theoretically you can handle ~1000 nodes cluster with AWS VPC routing.
> You can increase this quota up to a maximum of 1000; however, network performance might be impacted. This quota is enforced separately for IPv4 routes and IPv6 routes.

**Comment by murali-reddy** [comment]
@rvadim thanks for sharing this information. 

https://forums.aws.amazon.com/ann.jspa?annID=6554

So its free of cost one can increase the limit to 1000. I guess it make sense not to use IPIP and use direct routing.

**Comment by aauren** [comment]
Closing as stale.
