### ISSUE TITLE
Old service endpoints are not cleaned from IPVS connections

### ISSUE THREAD

**Issue by opipenbe** [cloudnativelabs/kube-router#1533]
**What happened?**
Old service endpoints are not cleaned from IPVS connections. I was able to reproduce this issue ONLY with RHEL8 and its clones (Rocky Linux 8, Oracle Linux 8). For some reason there is no such a bug with newer operating systems such as RHEL 9 / Rocky Linux 9.

Specifically for kube-dns this issue can cause DNS timeouts.

**What did you expect to happen?**
Old service endpoints are removed from IPVS connections table once pod is deleted.

**How can we reproduce the behavior you experienced?**
1. Deploy vanilla kubeadm kubernetes cluster with RHEL/Rocky Linux 8
2. Install kube-router with service proxy
3. Make dns query to kubedns service IP
4. Delete some coredns replicas
5. Observe IPVS connections 

**System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): 1.6.0, but older versions which I tested also have same issue.
 - Operating system: latest patch level for RHEL 8.8;  kernel version: 4.18.0-477.21.1.el8_8.x86_64, iptables version: iptables v1.8.4 (nf_tables)
 - Kube-Router Parameters: --run-router=true, --run-firewall=true, --run-service-proxy=true, --hairpin-mode=true, dsr enabled
 - Kubernetes Version (`kubectl version`) : v1.26.7
 - Cloud Type: on premise
 - Kubernetes Deployment Type: kubeadm
 - Kube-Router Deployment Type: daemonset

**Reproduce**
```
[root@k8snode ~]# kubectl get pods -o wide -n kube-system | grep "NAME\|coredns"
NAME                                 READY   STATUS    RESTARTS   AGE   IP              NODE         NOMINATED NODE   READINESS GATES
coredns-787d4945fb-bslrj             1/1     Running   0          50m   192.168.0.18    k8snode.local   <none>           <none>
coredns-787d4945fb-fddzm             1/1     Running   0          10s   192.168.0.19    k8snode.local   <none>           <none>
coredns-787d4945fb-ncm9x             1/1     Running   0          10s   192.168.0.20    k8snode.local   <none>           <none>

# make dns query
[root@k8snode ~]# nslookup metrics-server.kube-system.svc.cluster.local 10.96.0.10
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	metrics-server.kube-system.svc.cluster.local
Address: 10.103.69.191

# delete 2 out of 3 coredns pods
[root@k8snode ~]# kubectl delete pod -n kube-system coredns-787d4945fb-bslrj coredns-787d4945fb-fddzm
pod "coredns-787d4945fb-bslrj" deleted
pod "coredns-787d4945fb-fddzm" deleted

# after deletion, connection still exists with destination 192.168.0.19 even though it should be removed 
[root@k8snode ~]# ipvsadm -Lcn | grep "IPVS\|expire\|:53$"
IPVS connection entries
pro expire state       source             virtual            destination
UDP 04:04  UDP         172.16.90.226:41529 10.96.0.10:53      192.168.0.20:53
UDP 04:04  UDP         172.16.90.226:50557 10.96.0.10:53      192.168.0.19:53

[root@k8snode ~]# kubectl get pods -o wide -n kube-system | grep "NAME\|coredns"
NAME                                 READY   STATUS    RESTARTS   AGE    IP              NODE         NOMINATED NODE   READINESS GATES
coredns-787d4945fb-55cfd             1/1     Running   0          56s    192.168.0.21    k8snode.local   <none>           <none>
coredns-787d4945fb-fztnt             1/1     Running   0          56s    192.168.0.22    k8snode.local   <none>           <none>
coredns-787d4945fb-ncm9x             1/1     Running   0          88s    192.168.0.20    k8snode.local   <none>           <none>

# ipvs connection with destination 192.168.0.19 exists until connection expiration
[root@k8snode ~]# ipvsadm -Lcn | grep "IPVS\|expire\|:53$"
IPVS connection entries
pro expire state       source             virtual            destination
UDP 03:40  UDP         172.16.90.226:41529 10.96.0.10:53      192.168.0.20:53
UDP 03:40  UDP         172.16.90.226:50557 10.96.0.10:53      192.168.0.19:53
```

**Comment by aauren** [comment]
I'm not really sure that the project will be able to help much here. None of the maintainers have a valid license to any of the RHEL versions that you're talking about. However, it wouldn't be the first time that we've seen problems between the user-space tooling and kernel versions with the various Linux networking code. We had a problem a while back between competing versions of iptables userspace.

It would be interesting to know if you still have this problem if you run kube-router as a binary on the host directly instead of in a container. Then kube-router would be using the same userspace tooling that the OS provides instead of using the userspace tools and libraries from the Alpine container.

This wouldn't explain the OS difference in RHEL versions, but you may want to try playing around with the `--ipvs-graceful-period` and other IPVS related options in kube-router as well.

I know that RHEL is famous for keeping support for crazy long durations, but a 4.18 kernel is pretty old. It wouldn't surprise me if something in the Alpine net library userspace is no longer compatible with a kernel from 2018.

**Comment by opipenbe** [comment]
Hi and thanks for suggestions!

I have also gut feeling that this issue might be related with kernel version. Actually first time I discovered this issue with Rocky Linux 8. Rocky Linux is a free and binary compatible with RHEL 8. In my lab environment I am using RHEL 8 just in case we discover problem from the operating system, then I can create support case to Red Hat as well.

I am sorry from my incompetence, but what exactly is calling a cleanup for IPVS connections? Is it kernel?

I tried to run kube-router as a binary in the host, but I got same issue as with daemonset. I used following options to run-kube router directly from the host:
`./kube-router --run-router=true --run-firewall=true --run-service-proxy=true --kubeconfig=/var/lib/kube-router/kubeconfig --hairpin-mode=true --runtime-endpoint=unix:///run/crio/crio.sock --v=5`

Here I deleted kube-dns endpoint pod with IP address 192.168.0.43. Everything seems to be normal according to the logs:

`
I0831 11:58:43.876285   32949 network_services_controller.go:914] Received update to endpoint: kube-system/kube-dns from watch API
I0831 11:58:43.876320   32949 network_services_controller.go:948] Syncing IPVS services sync for update to endpoint: kube-system/kube-dns
I0831 11:58:43.876335   32949 network_services_controller.go:454] Performing requested sync of ipvs services
I0831 11:58:43.876633   32949 ecmp_vip.go:329] Received update to endpoint: kube-system/kube-dns from watch API
I0831 11:58:43.876642   32949 ecmp_vip.go:188] Updating service kube-system/kube-dns triggered by endpoint update event
I0831 11:58:43.876771   32949 ecmp_vip.go:57] Withdrawing route: '10.96.0.1/32 via 172.16.90.226' to peers
I0831 11:58:43.876824   32949 ecmp_vip.go:57] Withdrawing route: '10.96.0.10/32 via 172.16.90.226' to peers
I0831 11:58:43.876845   32949 ecmp_vip.go:57] Withdrawing route: '10.103.69.191/32 via 172.16.90.226' to peers
I0831 11:58:43.878252   32949 health_controller.go:85] Received heartbeat from NSC
I0831 11:58:43.878343   32949 network_services_controller.go:1706] ipvs service tcp:10.96.0.1:443 (Flags: [hashed entry]) already exists so returning
I0831 11:58:43.878396   32949 network_services_controller.go:1808] ipvs destination 172.16.90.226:6443 (Weight: 1) already exists in the ipvs service tcp:10.96.0.1:443 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.879687   32949 network_services_controller.go:1706] ipvs service udp:10.96.0.10:53 (Flags: [hashed entry]) already exists so returning
I0831 11:58:43.879729   32949 network_services_controller.go:1808] ipvs destination 192.168.0.40:53 (Weight: 1) already exists in the ipvs service udp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.879757   32949 network_services_controller.go:1808] ipvs destination 192.168.0.44:53 (Weight: 1) already exists in the ipvs service udp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.880899   32949 network_services_controller.go:1706] ipvs service tcp:10.96.0.10:53 (Flags: [hashed entry]) already exists so returning
I0831 11:58:43.880937   32949 network_services_controller.go:1808] ipvs destination 192.168.0.44:53 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.880972   32949 network_services_controller.go:1808] ipvs destination 192.168.0.40:53 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.882361   32949 network_services_controller.go:1706] ipvs service tcp:10.96.0.10:9153 (Flags: [hashed entry]) already exists so returning
I0831 11:58:43.882410   32949 network_services_controller.go:1808] ipvs destination 192.168.0.44:9153 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:9153 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.882435   32949 network_services_controller.go:1808] ipvs destination 192.168.0.40:9153 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:9153 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.883737   32949 network_services_controller.go:1706] ipvs service tcp:10.103.69.191:443 (Flags: [hashed entry]) already exists so returning
I0831 11:58:43.883783   32949 network_services_controller.go:1808] ipvs destination 192.168.0.39:4443 (Weight: 1) already exists in the ipvs service tcp:10.103.69.191:443 (Flags: [hashed entry]) so not adding destination
I0831 11:58:43.883838   32949 service_endpoints_sync.go:477] Cleaning up if any, old service IPs on dummy interface
I0831 11:58:43.883932   32949 service_endpoints_sync.go:521] Cleaning up if any, old ipvs service and servers which are no longer needed
I0831 11:58:43.884009   32949 service_endpoints_sync.go:594] Found a destination 192.168.0.43:53 (Weight: 1) in service tcp:10.96.0.10:53 (Flags: [hashed entry]) which is no longer needed so cleaning up
I0831 11:58:43.884052   32949 service_endpoints_sync.go:594] Found a destination 192.168.0.43:53 (Weight: 1) in service udp:10.96.0.10:53 (Flags: [hashed entry]) which is no longer needed so cleaning up
I0831 11:58:43.887655   32949 network_service_graceful.go:167] Deleted conntrack entry for endpoint: 10.96.0.10:53
I0831 11:58:43.887734   32949 service_endpoints_sync.go:594] Found a destination 192.168.0.43:9153 (Weight: 1) in service tcp:10.96.0.10:9153 (Flags: [hashed entry]) which is no longer needed so cleaning up
I0831 11:58:43.888074   32949 network_services_controller.go:751] Attempting to attain ipset mutex lock
I0831 11:58:43.888082   32949 network_services_controller.go:753] Attained ipset mutex lock, continuing...
I0831 11:58:43.907518   32949 pod.go:53] Received update to pod: kube-system/coredns-787d4945fb-gvml8
I0831 11:58:43.907536   32949 network_policy_controller.go:211] Full sync request queue was empty so a full sync request was successfully sent
I0831 11:58:43.907542   32949 network_policy_controller.go:188] Received request for a full sync, processing
I0831 11:58:43.907549   32949 network_policy_controller.go:236] Starting sync of iptables with version: 1693472323907545748
I0831 11:58:43.909214   32949 health_controller.go:85] Received heartbeat from NPC
I0831 11:58:43.953303   32949 network_services_controller.go:756] Returned ipset mutex lock
I0831 11:58:43.953317   32949 service_endpoints_sync.go:454] Setting up policy routing required for Direct Server Return functionality.
I0831 11:58:43.954599   32949 service_endpoints_sync.go:459] Custom routing table kube-router-dsr required for Direct Server Return is setup as expected.
I0831 11:58:43.954615   32949 service_endpoints_sync.go:462] Setting up custom route table required to add routes for external IP's.
I0831 11:58:43.957021   32949 service_endpoints_sync.go:470] Custom routing table required for Direct Server Return (external_ip) is setup as expected.
I0831 11:58:43.957038   32949 service_endpoints_sync.go:86] IPVS servers and services are synced to desired state
I0831 11:58:43.957049   32949 service_endpoints_sync.go:31] sync ipvs services took 80.70863ms
I0831 11:58:43.960276   32949 policy.go:80] Attempting to attain ipset mutex lock
I0831 11:58:43.960288   32949 policy.go:82] Attained ipset mutex lock, continuing...
I0831 11:58:43.977265   32949 network_services_controller.go:1461] Deleted invalid/outdated hairpin rule "-A KUBE-ROUTER-HAIRPIN -s 192.168.0.43/32 -d 192.168.0.43/32 -m ipvs --vaddr 10.96.0.10 --vport 53 -j SNAT --to-source 10.96.0.10" from chain KUBE-ROUTER-HAIRPIN
I0831 11:58:43.979275   32949 network_services_controller.go:1461] Deleted invalid/outdated hairpin rule "-A KUBE-ROUTER-HAIRPIN -s 192.168.0.43/32 -d 192.168.0.43/32 -m ipvs --vaddr 10.96.0.10 --vport 9153 -j SNAT --to-source 10.96.0.10" from chain KUBE-ROUTER-HAIRPIN
I0831 11:58:43.979301   32949 health_controller.go:85] Received heartbeat from NSC
I0831 11:58:43.996579   32949 policy.go:142] Iptables chains in the filter table are synchronized with the network policies.
I0831 11:58:43.996592   32949 policy.go:85] Returned ipset mutex lock
I0831 11:58:43.996597   32949 policy.go:77] Syncing network policy chains took 36.326361ms
I0831 11:58:44.012311   32949 network_policy_controller.go:551] Attempting to attain ipset mutex lock
I0831 11:58:44.012323   32949 network_policy_controller.go:553] Attained ipset mutex lock, continuing...
I0831 11:58:44.013286   32949 network_policy_controller.go:556] Returned ipset mutex lock
I0831 11:58:44.013297   32949 network_policy_controller.go:233] sync iptables took 105.749163ms
I0831 11:58:45.126258   32949 pod.go:53] Received update to pod: kube-system/coredns-787d4945fb-gvml8
I0831 11:58:45.126278   32949 network_policy_controller.go:211] Full sync request queue was empty so a full sync request was successfully sent
I0831 11:58:45.126284   32949 network_policy_controller.go:188] Received request for a full sync, processing
I0831 11:58:45.126291   32949 network_policy_controller.go:236] Starting sync of iptables with version: 1693472325126287476
I0831 11:58:45.128447   32949 health_controller.go:85] Received heartbeat from NPC
I0831 11:58:45.128682   32949 network_services_controller.go:914] Received update to endpoint: kube-system/kube-dns from watch API
I0831 11:58:45.128712   32949 network_services_controller.go:951] Skipping IPVS services sync on endpoint: kube-system/kube-dns update as nothing changed
I0831 11:58:45.128721   32949 ecmp_vip.go:329] Received update to endpoint: kube-system/kube-dns from watch API
I0831 11:58:45.128726   32949 ecmp_vip.go:188] Updating service kube-system/kube-dns triggered by endpoint update event
I0831 11:58:45.128836   32949 ecmp_vip.go:57] Withdrawing route: '10.96.0.1/32 via 172.16.90.226' to peers
I0831 11:58:45.128889   32949 ecmp_vip.go:57] Withdrawing route: '10.96.0.10/32 via 172.16.90.226' to peers
I0831 11:58:45.128910   32949 ecmp_vip.go:57] Withdrawing route: '10.103.69.191/32 via 172.16.90.226' to peers
I0831 11:58:45.139650   32949 network_services_controller.go:914] Received update to endpoint: kube-system/kube-dns from watch API
I0831 11:58:45.139686   32949 network_services_controller.go:948] Syncing IPVS services sync for update to endpoint: kube-system/kube-dns
I0831 11:58:45.139701   32949 network_services_controller.go:454] Performing requested sync of ipvs services
I0831 11:58:45.139923   32949 ecmp_vip.go:329] Received update to endpoint: kube-system/kube-dns from watch API
I0831 11:58:45.139932   32949 ecmp_vip.go:188] Updating service kube-system/kube-dns triggered by endpoint update event
I0831 11:58:45.140052   32949 ecmp_vip.go:57] Withdrawing route: '10.96.0.1/32 via 172.16.90.226' to peers
I0831 11:58:45.140103   32949 ecmp_vip.go:57] Withdrawing route: '10.96.0.10/32 via 172.16.90.226' to peers
I0831 11:58:45.140122   32949 ecmp_vip.go:57] Withdrawing route: '10.103.69.191/32 via 172.16.90.226' to peers
I0831 11:58:45.140216   32949 health_controller.go:85] Received heartbeat from NSC
I0831 11:58:45.141715   32949 network_services_controller.go:1706] ipvs service tcp:10.96.0.10:9153 (Flags: [hashed entry]) already exists so returning
I0831 11:58:45.141773   32949 network_services_controller.go:1808] ipvs destination 192.168.0.40:9153 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:9153 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.141799   32949 network_services_controller.go:1808] ipvs destination 192.168.0.44:9153 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:9153 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.141819   32949 network_services_controller.go:1797] Successfully added destination 192.168.0.45:9153 (Weight: 1) to the service tcp:10.96.0.10:9153 (Flags: [hashed entry])
I0831 11:58:45.143688   32949 network_services_controller.go:1706] ipvs service tcp:10.103.69.191:443 (Flags: [hashed entry]) already exists so returning
I0831 11:58:45.143746   32949 network_services_controller.go:1808] ipvs destination 192.168.0.39:4443 (Weight: 1) already exists in the ipvs service tcp:10.103.69.191:443 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.144862   32949 network_services_controller.go:1706] ipvs service tcp:10.96.0.1:443 (Flags: [hashed entry]) already exists so returning
I0831 11:58:45.144903   32949 network_services_controller.go:1808] ipvs destination 172.16.90.226:6443 (Weight: 1) already exists in the ipvs service tcp:10.96.0.1:443 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.145937   32949 network_services_controller.go:1706] ipvs service udp:10.96.0.10:53 (Flags: [hashed entry]) already exists so returning
I0831 11:58:45.145977   32949 network_services_controller.go:1797] Successfully added destination 192.168.0.45:53 (Weight: 1) to the service udp:10.96.0.10:53 (Flags: [hashed entry])
I0831 11:58:45.146009   32949 network_services_controller.go:1808] ipvs destination 192.168.0.40:53 (Weight: 1) already exists in the ipvs service udp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.146035   32949 network_services_controller.go:1808] ipvs destination 192.168.0.44:53 (Weight: 1) already exists in the ipvs service udp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.148182   32949 network_services_controller.go:1706] ipvs service tcp:10.96.0.10:53 (Flags: [hashed entry]) already exists so returning
I0831 11:58:45.148228   32949 network_services_controller.go:1808] ipvs destination 192.168.0.44:53 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.148266   32949 network_services_controller.go:1808] ipvs destination 192.168.0.40:53 (Weight: 1) already exists in the ipvs service tcp:10.96.0.10:53 (Flags: [hashed entry]) so not adding destination
I0831 11:58:45.148286   32949 network_services_controller.go:1797] Successfully added destination 192.168.0.45:53 (Weight: 1) to the service tcp:10.96.0.10:53 (Flags: [hashed entry])
I0831 11:58:45.148408   32949 service_endpoints_sync.go:477] Cleaning up if any, old service IPs on dummy interface
I0831 11:58:45.148532   32949 service_endpoints_sync.go:521] Cleaning up if any, old ipvs service and servers which are no longer needed
I0831 11:58:45.148654   32949 network_services_controller.go:751] Attempting to attain ipset mutex lock
I0831 11:58:45.148664   32949 network_services_controller.go:753] Attained ipset mutex lock, continuing...
I0831 11:58:45.186014   32949 policy.go:80] Attempting to attain ipset mutex lock
I0831 11:58:45.222995   32949 network_services_controller.go:756] Returned ipset mutex lock
I0831 11:58:45.223011   32949 service_endpoints_sync.go:454] Setting up policy routing required for Direct Server Return functionality.
I0831 11:58:45.224158   32949 policy.go:82] Attained ipset mutex lock, continuing...
I0831 11:58:45.224286   32949 service_endpoints_sync.go:459] Custom routing table kube-router-dsr required for Direct Server Return is setup as expected.
I0831 11:58:45.224293   32949 service_endpoints_sync.go:462] Setting up custom route table required to add routes for external IP's.
I0831 11:58:45.232008   32949 service_endpoints_sync.go:470] Custom routing table required for Direct Server Return (external_ip) is setup as expected.
I0831 11:58:45.232025   32949 service_endpoints_sync.go:86] IPVS servers and services are synced to desired state
I0831 11:58:45.232032   32949 service_endpoints_sync.go:31] sync ipvs services took 92.32514ms
I0831 11:58:45.245494   32949 health_controller.go:85] Received heartbeat from NSC
I0831 11:58:45.258155   32949 policy.go:142] Iptables chains in the filter table are synchronized with the network policies.
I0831 11:58:45.258167   32949 policy.go:85] Returned ipset mutex lock
I0831 11:58:45.258173   32949 policy.go:77] Syncing network policy chains took 72.165628ms
I0831 11:58:45.268173   32949 network_policy_controller.go:551] Attempting to attain ipset mutex lock
I0831 11:58:45.268182   32949 network_policy_controller.go:553] Attained ipset mutex lock, continuing...
I0831 11:58:45.269213   32949 network_policy_controller.go:556] Returned ipset mutex lock
I0831 11:58:45.269222   32949 network_policy_controller.go:233] sync iptables took 142.932057ms
I0831 11:58:46.141557   32949 health_controller.go:198] Health controller tick
I0831 11:58:46.266310   32949 route_sync.go:41] Running local route table synchronization
I0831 11:58:49.448487   32949 pod.go:71] Received pod: kube-system/coredns-787d4945fb-n8wz4 delete event
I0831 11:58:49.448506   32949 network_policy_controller.go:211] Full sync request queue was empty so a full sync request was successfully sent
I0831 11:58:49.448512   32949 network_policy_controller.go:188] Received request for a full sync, processing
I0831 11:58:49.448519   32949 network_policy_controller.go:236] Starting sync of iptables with version: 1693472329448515246
I0831 11:58:49.449475   32949 health_controller.go:85] Received heartbeat from NPC
I0831 11:58:49.504677   32949 policy.go:80] Attempting to attain ipset mutex lock
I0831 11:58:49.504704   32949 policy.go:82] Attained ipset mutex lock, continuing...
I0831 11:58:49.528210   32949 policy.go:142] Iptables chains in the filter table are synchronized with the network policies.
I0831 11:58:49.528224   32949 policy.go:85] Returned ipset mutex lock
I0831 11:58:49.528230   32949 policy.go:77] Syncing network policy chains took 23.559299ms
I0831 11:58:49.546237   32949 network_policy_controller.go:551] Attempting to attain ipset mutex lock
I0831 11:58:49.546251   32949 network_policy_controller.go:553] Attained ipset mutex lock, continuing...
I0831 11:58:49.549220   32949 network_policy_controller.go:556] Returned ipset mutex lock
I0831 11:58:49.549231   32949 network_policy_controller.go:233] sync iptables took 100.714001ms
I0831 11:58:51.142015   32949 health_controller.go:198] Health controller tick
`
I also played with options --ipvs-sync-period and --ipvs-graceful-period, but they also did not make difference and issue remained.

**Comment by opipenbe** [comment]
Update: 

I made few tests more and I can conclude following...

with RHEL 8: If IPVS realserver is deleted, then existing UDP connections stay active until expiration
with RHEL 9: If IPVS realserver is deleted, then existing UDP connections removed instantly

So its rather RHEL than kube-router issue :)

**Comment by aauren** [comment]
Interesting... I wasn't aware that they changed the way IPVS handled existing connections in older kernel versions. But I'm not sure I've ever run kube-router under a 4.18 kernel before. That wasn't even an LTS kernel version, so chances are there was something odd in the implementation in there.

Thanks for raising this, hopefully it will help future people that might be on RHEL 8 variants if they come across it. I'm going to go ahead and close it now since it's not a kube-router issue.
