### ISSUE TITLE
BGP server fails to start if ipv6 is disabled via ipv6.disable Kernel parameter

### ISSUE THREAD

**Issue by jdconti** [cloudnativelabs/kube-router#155]
When IPv6 is disabled using Kernel parameter "ipv6.disable=1" kube-router fails silently. The node gobgp server errors that the "address family not supported by protocol" but on restart attempt finds 0.0.0.0:179 is bound / already in use:
```
E0908 14:36:41.037123       1 network_routes_controller.go:144] Failed to start node BGP server: Failed to start BGP server due to : listen tcp6 [::]:179: socket: address family not supported by protocol
I0908 14:37:40.824288       1 network_routes_controller.go:150] Retrying start of node BGP server
E0908 14:37:40.827157       1 network_routes_controller.go:144] Failed to start node BGP server: Failed to start BGP server due to : listen tcp4 0.0.0.0:179: bind: address already in use
```
It would be ideal if we could customize the listen interface(s) and supported protocol for the BGP server.

**Comment by murali-reddy** [comment]
thanks @jdconti for reporting the issue. Will try to get it fixed.

**Comment by bzub** [comment]
Hey @jdconti, I've tested `cloudnativelabs/kube-router-git:PR156` on a cluster that has ipv6 disabled via kernel parameter. If you need a fix right away that image should do it. Otherwise it will get merged into master and the next release after some more testing.

It doesn't allow specifying BGP server listening addresses yet. We'll keep this open to track adding that as a CLI flag as well. Thanks.

**Comment by murali-reddy** [comment]
@jdconti Latest release https://github.com/cloudnativelabs/kube-router/releases/tag/v0.0.16 has the fix for this issue.

**Comment by jdconti** [comment]
Thanks @murali-reddy!  My apologies for not closing this sooner, thought you closed this with your comment.

**Comment by voidengineer** [comment]
Since 0.2.1 this bug resurfaces.
I disabled IPv6 by setting `net.ipv6.conf.all.disable_ipv6` to 1.

kube-router fails with: Failed to start node BGP server: Failed to start BGP server due to : listen tcp6 [::1]:179: bind: cannot assign requested address

**Comment by uablrek** [comment]
I took a look at the PR for ipv6 peering https://github.com/cloudnativelabs/kube-router/pull/545 and I have altered (corrected)  [here](https://github.com/Nordix/kube-router/blob/8d632a39eb89f14d2d5e0c77ef8766462779157d/pkg/controllers/routing/network_routes_controller.go#L673) from the any-address `[::]` to the local address for ipv6 `[::1]` (which is right I think). But my guess is that the `ipv6IsEnabled()` function returns true even if net.ipv6.conf.all.disable_ipv6=1 and it is ok to bind to ipv6-any, but the loopback address `[::1]` is removed from the lo interface. But to "correct" this problem by returning to use the any-address as local address does not feel right.

**Comment by uablrek** [comment]
Perhaps ithe ipv6IsEnabled() could actually try to use [::1] ?

**Comment by uablrek** [comment]
Yes, net.ipv6.conf.all.disable_ipv6=1 removes `::1/128`;
```
vm-201 ~ # ifconfig lo
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vm-201 ~ # sysctl -w net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6 = 1
vm-201 ~ # ifconfig lo
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by uablrek** [comment]
Re-created on [xcluster](https://github.com/Nordix/xcluster).

**Comment by uablrek** [comment]
I made a PR with a fix in `ipv6IsEnabled()`. I have tested that the problem was fixed with this PR in [xcluster](https://github.com/Nordix/xcluster). To re-create without the PR is simple, just do
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
```
before `kube-router` is started.

**Comment by uablrek** [comment]
This however draws my attention to the ipv6-only case. Guess the reverse problem exists also, e.g. if ipv4IsEnabled() == false, no annotarions are read and probably other things also. Test ipv6-only with ipv4 disabled must be done.
