### ISSUE TITLE
[v2.0.0 Issue]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CoreTechnologyAG** [cloudnativelabs/kube-router#1558]
**What happened?**
Kube-Router does not start after starting with v2.0.0 and afterthat the whole kubernetes cluster aren't working.

If we start the kube-router with the latest v1.6 version, it works fine.

**What did you expect to happen?**
Starting Kube-Router V2.0 as it did in V1.6

**How can we reproduce the behavior you experienced?**
1. Start Kube-router based on https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter-all-features.yaml

**Screenshots / Architecture Diagrams / Network Topologies**
- kubernetes cluster with
  - 3 Base-Server with etcd and coredns
  - 2 Kubernetes Master-Server kubeadm, kubelet, kubectl: GitVersion:"v1.26.6", 
  - 3 Kubernetes Node-Server

**System Information (please complete the following information):**
 - Kube-Router Version: v2.0.0 (Latest)
 - Kube-Router Parameters:
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --bgp-graceful-restart=true
        - --kubeconfig=/var/lib/kube-router/kubeconfig
 - Kubernetes Version: 1.26.6-00 on Ubuntu  20.04.6 LTS 
 - Cloud Type: on premise
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 3 Nodes

**Logs, other output, metrics**
I1012 08:14:55.591795       1 network_policy_controller.go:163] Starting network policy controller
_**panic: runtime error: invalid memory address or nil pointer dereference**_
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x188395e]
goroutine 154 [running]:
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/proxy.(*NetworkServicesController).deleteHairpinIptablesRules(0xc00070b878?, {0x22d179c?, 0x3d?})
/build/pkg/controllers/proxy/network_services_controller.go:1361 +0x5e
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/proxy.(*NetworkServicesController).syncHairpinIptablesRules(0xc000512c40)
/build/pkg/controllers/proxy/network_services_controller.go:1279 +0x33e
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/proxy.(*NetworkServicesController).doSync(0xc000512c40)
/build/pkg/controllers/proxy/network_services_controller.go:374 +0x210
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/proxy.(*NetworkServicesController).Run(0xc000512c40, 0x0?, 0xc0000a0360, 0xc00005ef40)
/build/pkg/controllers/proxy/network_services_controller.go:287 +0x57a
created by github.com/cloudnativelabs/kube-router/v2/pkg/cmd.(*KubeRouter).Run
/build/pkg/cmd/kube-router.go:196 +0x10aa

Thanks for your work at all for the amazing job.
Ritzo

**Comment by aauren** [comment]
Have you read and followed the release instructions for v2.0.0? https://github.com/cloudnativelabs/kube-router/releases/tag/v2.0.0

**Comment by aauren** [comment]
I think that I've found the issue. Working on a fix now.
