### ISSUE TITLE
flush conntrack state for removed/changed UDP Services

### ISSUE THREAD

**Issue by mqliang** [cloudnativelabs/kube-router#157]
@murali-reddy 

should  use `conntrack -D -p udp` to remove conntrack entity if a UDP Service is deleted, see:

https://github.com/kubernetes/kubernetes/issues/19029 
https://github.com/kubernetes/kubernetes/pull/22573

**Comment by murali-reddy** [comment]
thanks @mqliang, will incorporate necessary changes

**Comment by jamestutton** [comment]
Would like to confirm seeing the same sort of issue.  Basically have a fast syslog stream ~10K Messages per minute.  If the pods services are recreated for any reason the old sessions remain in contrack and never connect to the new pods endpoints as expected.  Flushing the connections with conntrack -D causes the connection to be rebuilt and the logs in our case are correctly routed to the pods again. 

It was a little fun to find as devices with slower log rates were working fine and logs were getting into our pods.  But the difference is when the log rate is a few per min the connection is torn down and new one establish by the kernel. When the rate is high the old session is kept alive and never times out and so no new session is created to connect to the current pods.

**Comment by murali-reddy** [comment]
Thanks @jamestutton i will try to accomidate patch for this issue in next release.

**Comment by joemiller** [comment]
Also seeing this. Use case is statsd. Would externalTrafficPolicy: Local avoid the issue? On gce/gke.
