### ISSUE TITLE
Using clusterIP, the container cannot telnet itself locally

### ISSUE THREAD

**Issue by shudingchao** [cloudnativelabs/kube-router#1576]
I use kube-router as a network plug-in and use service to expose the port for the current pod. When I add the clusterIP and port of the telnet service from other containers, I can access it normally, but the container itself cannot respond when I add the clusterIP and port of the telnet service.

**Comment by aauren** [comment]
Can you please fill out the information in the default issue template for this? It gives us a lot of information that helps with requests like these.

Additionally, it would be good to know what the service definition looks like for this service. Along with reproduction instructions (which is also part of the issue template).
