### ISSUE TITLE
Session affinity

### ISSUE THREAD

**Issue by andrenth** [cloudnativelabs/kube-router#159]
Hi

I tried running the `whats-my-ip` example given in (Kube-router: Kubernetes network services proxy with IPVS/LVS)[https://cloudnativelabs.github.io/post/2017-05-10-kube-network-service-proxy/], but I couldn't reproduce the results in the session affinity case. I kept getting responses from different nodes.

I managed to get close by manually editing the LVS virtual service specification to use the source hash scheduler instead of round robin: `ipvsadm -E -t 10.110.235.172:8080 -s sh` and `ipvsadm -E -t $NODE_IP:31321 -s sh`. With this, I always get the same IP back when I connect to the same node, but different nodes will give me different IPs.

This is the service description:

```
$ kubectl get svc myip -o wide
NAME      CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE       SELECTOR
myip      10.110.235.172   <nodes>       8080:31321/TCP   1d        run=myip

$ kubectl describe svc myip
Name:			myip
Namespace:		default
Labels:			run=myip
Annotations:		<none>
Selector:		run=myip
Type:			NodePort
IP:			10.110.235.172
Port:			<unset>	8080/TCP
NodePort:		<unset>	31321/TCP
Endpoints:		10.244.1.17:8080,10.244.2.18:8080,10.244.3.6:8080 + 1 more...
Session Affinity:	ClientIP
Events:			<none>

# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.96.0.1:443 rr
  -> 10.200.12.39:6443            Masq    1      0          0         
TCP  10.96.0.10:53 rr
  -> 10.244.0.3:53                Masq    1      0          0         
TCP  10.110.235.172:8080 sh
  -> 10.244.1.17:8080             Masq    1      0          0         
  -> 10.244.2.18:8080             Masq    1      0          0         
  -> 10.244.3.6:8080              Masq    1      0          0         
  -> 10.244.4.6:8080              Masq    1      0          0         
TCP  10.200.12.116:31321 sh
  -> 10.244.1.17:8080             Masq    1      0          0         
  -> 10.244.2.18:8080             Masq    1      0          0         
  -> 10.244.3.6:8080              Masq    1      0          0         
  -> 10.244.4.6:8080              Masq    1      0          0         
UDP  10.96.0.10:53 rr
  -> 10.244.0.3:53                Masq    1      0          0
```

Have you guys seen this behavior?

**Comment by bzub** [comment]
Hi @andrenth this is fixed in the `cloudnativelabs/kube-router-git:master` image. There will likely be a new release soon that includes this.

Testing results are here: https://github.com/cloudnativelabs/kube-router/pull/160

Please try it out and reopen this issue if any problems remain. Thanks for reporting this!

**Comment by andrenth** [comment]
Hi

Should a `kubectl replace -f ...` pointing to a `kubeadm-kuberouter-all-features.yaml` file with the image name replaced be enough to upgrade? I ran that but I'm still seeing the same behavior.

Thanks

**Comment by murali-reddy** [comment]
@andrenth you need to destroy the kube-router pods as well.

**Comment by andrenth** [comment]
Now `ipvsadm` shows `rr persistent` instead of just `rr`. The behavior I'm seeing is the one I described when I manually changed the scheduler from `rr` to `sh`: when I make a request to a given cluster node, it'll always return the same IP, but a request to another node will possibly return a different IP.

Is this the expected behavior?

**Comment by murali-reddy** [comment]
Yes this is expected behaviour of session affinity based on client IP. From same client to same node port will select same endpoint.

**Comment by andrenth** [comment]
Cool, thanks!
