### ISSUE TITLE
Configuration via env variables and configmap

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#162]
All CLI flags to configure kube-router should have equivalent environment variables. With this enhancement users can keep configuration in a file or configmap/secret which is sourced to load the variables.

Variable names should be namespaced with a `KUBE_ROUTER_` prefix, and match CLI flags with hyphens replaces by underscores, and all uppercase letters.

**Comment by roffe** [comment]
Should env variables have precedence over command args or vice versa in the case where both exists?

**Comment by roffe** [comment]
My vote is for command args have precedence over ENV variables.

**Comment by SEJeff** [comment]
It should follow the principal of least surprise. On 'nix this is generally:

1. Hardcoded defaults
2. Configuration file
3. Environment variables
4. Command line flags

Where each subsequent one overwrites the previous one. FYI much to all of k8s upstream follows this model, so I definitely agree with you here @roffe.

**Comment by roffe** [comment]
Alrighty then. I'll take a shot at this :)

**Comment by aauren** [comment]
I think this is still a good idea, but it seems to have lost steam. Closing for now, if someone is interested in contributing this, we could slot it in for a future release.
