### ISSUE TITLE
DSR mode: "rpc error: code = NotFound desc = could not find container "": container ID should not be empty"

### ISSUE THREAD

**Issue by opipenbe** [cloudnativelabs/kube-router#1640]
**What happened?**
Unable to enable DSR mode with kube-router v2.1.0 (atleast with cri-o runtime):

```
W0404 06:42:26.785234  345351 linux_networking.go:102] got an IfaceHasNoAddr error while trying to delete address from netlink: cannot assign requested address (this is not normally bad enough to stop processing)
W0404 06:42:26.785901  345351 linux_networking.go:117] got a No such process error while trying to remove route: exit status 2 (this is not normally bad enough to stop processing)
I0404 06:42:26.788147  345351 linux_networking.go:758] Successfully assigned VIP: 172.16.69.69 in endpoint 192.168.3.68.
I0404 06:42:26.788255  345351 linux_networking.go:780] Successfully disabled rp_filter in endpoint 192.168.3.68.
I0404 06:42:26.788276  345351 linux_networking.go:790] Current network namespace after revert namespace to host network namespace: NS(15: 4, 4026531840)
E0404 06:42:26.789164  345351 service_endpoints_sync.go:60] Error setting up IPVS services for service external IP's and load balancer IP's: failed to setup DSR endpoint 172.16.69.69: unable to setup DSR receiver inside pod: failed to prepare endpoint 192.168.5.75 to do DSR due to: rpc error: code = NotFound desc = could not find container "": container ID should not be empty
```

**What did you expect to happen?**
DSR mode enabled without errors.

**How can we reproduce the behavior you experienced?**
1. Install kubeadm k8s cluster without kube-proxy and with cri-o runtime.
2. Deploy kube-router v2.1.0 using kubeadm-kuberouter-all-features-dsr.yaml (https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/kubeadm-kuberouter-all-features-dsr.yaml).
3. Make sure to make following changes in kubeadm-kuberouter-all-features-dsr.yaml:  
- set `--runtime-endpoint=unix:///run/crio/crio.sock` 
-  replace `/var/run/docker.sock` with `/run/crio/crio.sock` in volumeMounts and volumes configuration
- instead of:
```
      - name: kubeconfig
        configMap:
          name: kube-proxy
          items:
          - key: kubeconfig.conf
            path: kubeconfig
```
replace with:
```
      - name: kubeconfig
        hostPath:
          path: /var/lib/kube-router
```

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`): v2.1.0
 - Kube-Router Parameters:         - --run-router=true - --run-firewall=true  - --run-service-proxy=true- --bgp-graceful-restart=true - --kubeconfig=/var/lib/kube-router/kubeconfig - --runtime-endpoint=unix:///run/crio/crio.sock
 - Kubernetes Version (`kubectl version`) : 1.29.2 (container runtime CRI-O v1.29.2)
 - Cloud Type: on premise
 - Kubernetes Deployment Type: Kubeadm
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 6 nodes

**Additional context**
It seems to be a problem with kube-router v2.x release. I also tested same configuration with kube-router v1.6.0 and DSR works like a charm.

**Comment by aauren** [comment]
Thanks for taking the time to report this!

This is definitely a bit odd... As far as I can think not much changed in the DSR code between v1.X and v2.X of kube-router. But this definitely seems like some sort of bug.

For the pod that is represented by `192.168.3.68` are you able to get the output of the following command?

```
kubectl get pod -n <pod namespace> <pod> -o "jsonpath={.status.containerStatuses[0].containerID}"
```

That's essentially what kube-router is doing to get the container ID. After that it parses it and removes the part of the URL before `://` and then uses the rest of the string as the Container ID.

If that looks normal, then I may have to provide you with a kube-router build that has more debug information so that we can figure out what's going on here.

**Comment by opipenbe** [comment]
Yes, this command works:
```
kubectl get pod -n traefik traefik-6679df4cb6-qv5rb -o "jsonpath={.status.containerStatuses[0].containerID}"
cri-o://4c8e984b9e8b9f252751be8cd75732c6141ceaff34f835ddb36316a7a823b649
```
I tried to reproduce this error again, and then I found in the logs that kube-router pod is attempting to reach a container that is not located on the same node. Maybe this helps to explain why this bug occurs?

So in the original case which I posted - 192.168.5.75 is not on the same node.

**Comment by aauren** [comment]
Yeah, that would definitely explain it. If the container is not running on the node, then it would not be able to enter the container to setup DSR and you'd get this type of issue.

I'll try to dig into the code and see if I can figure out what's going on here.
