### ISSUE TITLE
IPVS director with hashing (preferably consistent hashing)

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#166]
Its common practice to use below setup in a pure software load-balanced on-prem clusters

```
       ECMP/L3 LB                    consistent hash
Router -------------> L4 director-------------------> L7 proxy--------------> server
```
L4 director does not proxy the connection but directs the traffic to the L7 proxy. L4 director advertises the VIP to the first-hop routers. Routers load balance traffic to the L4 directors (or can use hashing to send to same L4 director to avoid out-of-order packets). It is required that a traffic corresponding to a flow should always be directed by L4 director to same L7 proxy for which some sort of consistent hashing is used.

Kube-router already advertises `cluster ip` and will advertise `external ip` of service to the peer routers. 
To achive similar setup with Kube-router, we need to implement source hashing/consistent hashing in IPVS. IPVS does not do any NAT but will just direct the traffic. We can use tunneling to send original packet as is to service endpoint. Service endpoint in the kubernetes context can be L7 ingress controller pod or actual service endpoint it self.

Service endpoint will use DSR (#40) to return the traffic directly to the client by-passing the L4 director. 

http://www.linuxvirtualserver.org/docs/scheduling.html

**Comment by voidengineer** [comment]
Is there anything missing for this?
Can this be closed?

**Comment by murali-reddy** [comment]
DSR itself is implemented. You can use direct  server return functionality of kube-router now. But it _only_ works with combination of L3 fabric routers doing L4/flow level load balancing. I.e) traffic for a flow ends up at same kubernetes node.

But there is still a missing piece, which is to have a consistent hashing. Newer kernels has the support for Maglev hashing. Please see https://github.com/cloudnativelabs/kube-router/issues/554 as well.

Once we have IPVS consistent hashing, routers of L3 fabric can just perform L3 load balancing, and traffic can spread across Kubernetes nodes. As each node due to IPVS consistent hashing sends traffic to same endpoint.

**Comment by murali-reddy** [comment]
Maglev hashing support https://github.com/cloudnativelabs/kube-router/pull/564

**Comment by aauren** [comment]
@murali-reddy Is there any work remaining on this now that #564 is merged?

**Comment by kfox1111** [comment]
There anything missing for this functionality?

**Comment by murali-reddy** [comment]
> There anything missing for this functionality?

@kfox1111  What specifically you are looking for? If its direct server retrun then its implemented and usable with kube-router. consistent hashing in the form of Maglev hashing which is supported by ipvs can be configured in kube-router. But no one tested end-to-end use-case i.e.) uninterrupted session inpsite of failover of a proxy node.

**Comment by kfox1111** [comment]
Thats kind of what I was wondering. Is it known to fully work? It sounds like in theory it should work but not tested.

I did spend a bit of time last night reading through the Maglev paper. In there, they describe other consistent hashing like rendezvous not failing connections during backend changes (section 5.3). Then they gave some metrics using 1000 backends that using maglev, it only only causing ~.5-2.5% disruption to connections. But that assumes your trying to do HA on a very large pool of backends. I'd expect if you were trying a small number (3-5) of backends, the failure rate would be substantial, potentially making maglev not worth using as the failure rate is almost as high as not using it?

https://github.blog/2018-08-08-glb-director-open-source-load-balancer/ implements rendezvous and looks like it might work well for small numbers of backends. If the number of backends gets too large, then switching to something like maglev makes sense

**Comment by aauren** [comment]
Closing this issue as to our knowledge this functionality works, but it is missing time from the team to test an end-to-end use-case. If some one has time to test and finds missing functionality in kube-router, please re-open and we'll revisit.
