### ISSUE TITLE
Feature: L3 ECMP + L4 director + DSR

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#167]
Consolidatng one blanket bug to track serveral sub-features to achieve highly available, scalable ingress model for bare-metal deployments.

```
       ECMP/L3 LB                    consistent hash
Router -------------> L4 director-------------------> L7 proxy--------------> pod
```
or 

```
       ECMP/L3 LB                    consistent hash
Router -------------> L4 director-------------------> pod
```

- [x] define a custom service annotation to indicate service needs DSR
- [x] ability to advertise external ip's #161 if service is marked with annotation
- [x] support consistent hashing for IPVS service #166 is marked with annotation
- [x] Ability to create IPVS service with FWMARK's if service is marked with annotation
- [x] Ability to create IPVS service with IPIP tunnel mode
- [x] add additional tunnel interface inside the service endpoint pod, and configure the external ip

**Comment by murali-reddy** [comment]
I am working on a prototype. Will share once i have something in testable state, for feedabck.

**Comment by murali-reddy** [comment]
Support for DSR: cloudnativelabs/kube-router@6d43268 
Support for external IP’s: cloudnativelabs/kube-router@ba7697b 
Support for advertising external IP’s: to BGP peers cloudnativelabs/kube-router@4ca0afa

**Comment by SEJeff** [comment]
You gentlemen are on 🔥 please do keep it up!

**Comment by murali-reddy** [comment]
We have all pieces of puzzle for this feature. I will use #88 to document how to use these individual features.

Only thing that could have been better is use proper consistent hashing, which is not available in stock LVS. We will need patched version.

For now SH (Source Hashing) support has been added in https://github.com/cloudnativelabs/kube-router/commit/77f45e356ba58c81f45f54d98fe8293ad586f38b
