### ISSUE TITLE
Use RollingUpdate strategy, health probes in DaemonSet manifests

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#171]
When changing versions of kube-router, the current method of deleting pods manually could be automated with a RollingUpdate strategy. Combined with liveness/readiness probes it would ensure that a failed upgrade has minimal impact (one node) and easily revertible.

**Comment by murali-reddy** [comment]
Moving the feedback from #218

thanks to @pilsy some inputs to improve upon the reference manifests

set imagePullPolicy: IfNotPresent
alternative to init container
      - name: install-cni
          command:
            - /bin/sh
            - '-c'
            - >-
              set -e -x; if [ ! -f /etc/cni/net.d/10-kuberouter.conf ]; then
                TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
                cp /etc/kube-router/cni-conf.json ${TMP};
                mv ${TMP} /etc/cni/net.d/10-kuberouter.conf;
              fi;
              while true; do sleep 3600; done;
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cni-conf-dir
              mountPath: /etc/cni/net.d
            - name: kube-router-cfg
              mountPath: /etc/kube-router
          image: busybox
checkpointer.alpha.coreos.com/checkpoint: 'true'

**Comment by aauren** [comment]
This is now the default update strategy for daemonsets (https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/) and is currently in use in all of our current YAML manifests. Feel free to re-open if I missed anything.
