### ISSUE TITLE
documentation/DSR examples: mount directory containing the socket instead the socket directly

### ISSUE THREAD

**Issue by rkojedzinszky** [cloudnativelabs/kube-router#1719]
## Is your feature request related to a problem? Please describe

I've setup DSR following the guide, mounting crio.sock directly. Howewer, with this setup, if crio is restarted in the background, the socket will get stale, and kube-router won't be able to communicate with the runtime anymore, kube-router must also  be restarted.

## Describe the solution you'd like

Simply mount the directory holding the control socket.

**Comment by aauren** [comment]
Seems reasonable. Care to submit a PR to update the documentation and the example deployment files?

**Comment by jnummelin** [comment]
I'm working on enhanced docs and manifests for this
