### ISSUE TITLE
NetworkServiceController - RoCEv2 and --random-fully ipvs

### ISSUE THREAD

**Issue by thoro** [cloudnativelabs/kube-router#1746]
## What happened?

The default SNAT rule when using ipvs utilizes --random-fully which uses the ports 1024 - 65536 as source ports for outgoing connections. RoCEv2 uses udp port 4791 which is caught by Mellanox Connect X-5 network adapters, these shallow malformed RoCEv2 packets.

When a DNS query uses the port 4791 as outgoing port the response from the dns query will never reach the host. If you are using nginx, then the source port will never be changed, and the connection in ipvs stays active leading to DNS timeout errors.

## What did you expect to happen?

Use a different method to map to the source ports, for example as mentioned in the following ticket: https://github.com/aws/amazon-vpc-cni-k8s/issues/509

Current rule:
```
-A POSTROUTING -m ipvs --vdir ORIGINAL --vmethod MASQ -m comment --comment "" -j SNAT --to-source 10.21.13.40 --random-fully
```

Proposed rules:
```
 -A POSTROUTING -m ipvs --vdir ORIGINAL --vmethod MASQ -m comment --comment "" -p udp -j SNAT --to-source 10.21.13.40:32768-60999
 -A POSTROUTING -m ipvs --vdir ORIGINAL --vmethod MASQ -m comment --comment "" -p tcp -j SNAT --to-source 10.21.13.40:32768-60999
```

Best to use the ports from: net.ipv4.ip_local_port_range = 32768	60999

## How can we reproduce the behavior you experienced?

Have a Mellanox network adapter and send traffic to port 4791, you'll see that the traffic never reaches the host. (https://forums.developer.nvidia.com/t/rocev2-is-disabled-on-connectx-5-but-the-nic-still-captures-rocev2-packets/206023/3)

**Comment by aauren** [comment]
I would say that there is very little interest from the kube-router project to solve this particular use-case.

It feels like it would impose a fairly large burden on the project to maintain a work around for functionality that ought to be fixed elsewhere.

As mentioned in the linked article, the only way to get the solution proposed there to work would be to be protocol specific. Right now the current rules are written L4 agnostic. Adopting the proposed solution would mean that kube-router might not work where it worked before.

I would suggest that a protocol that steals packets destined to/from specific ports before it gets to the OS is the one at fault here. Maybe the should add logic into the RoCEv2 protocol that allows it to pass through packets that aren't part of their protocol?

Additionally, if this were solved at the Kernel layer, then it would be solved for all use-cases and no longer be an application specific concern, so it would be better to solve it there, if the protocol can't be changed.
