### ISSUE TITLE
utils: ipset issues

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#176]
@ryarnyah Could you take a look at these items and tell me if there's a bug or if I'm doing something wrong:

https://github.com/cloudnativelabs/kube-router/blob/2ac68610995668c43c99ccf78b1d0122a9406393/utils/ipset.go#L169
IPSet.Create() adds a Set with a nil pointer, should point to the IPSet object.

https://github.com/cloudnativelabs/kube-router/blob/2ac68610995668c43c99ccf78b1d0122a9406393/utils/ipset.go#L289
The other issue I saw was trying to use Set.Refresh(), the command line would usually be malformed under the call to Restore() linked above. It would end up with Go symbols in the command line like `'[hash:net` as the type argument. I believe the issue is with the `%v` printing Go representations of slices in this function: https://github.com/cloudnativelabs/kube-router/blob/2ac68610995668c43c99ccf78b1d0122a9406393/utils/ipset.go#L268

Could you also help me understand the workflow for using Save() and Restore() methods? The comments seem more for CLI usage than Go. Thanks for your help!

**Comment by ryarnyah** [comment]
I will look at this tonight, it seem that there are some flaws in my code. Your analyze seem correct about Create function and about %v. I will push a PR to clean up my mess and add some more Go comment to save and restore.

About save and restore functions, save get current ipsets and build a new ipset struct in memory and restore do the oposite.
