### ISSUE TITLE
Unexpected IP Masquerade

### ISSUE THREAD

**Issue by jimmypw** [cloudnativelabs/kube-router#1780]
## What happened?

I'm trying to set up a dual stack k8s cluster using kube-router to integrate the pod networks in to my routing infrastructure. The route advertisements work and I can access LoadBalancer IP's and pod ip's from outside the cluster. 

When I attempt to communicate outside of the cluster the traffic is masqueraded to the IP of the node.

I am using k3s with most of the built in stuff disabled

`--disable=traefik --disable=local-storage --disable=servicelb --tls-san=api.k3s.example.com --datastore-endpoint=snip --flannel-backend=none --disable-network-policy --disable-kube-proxy --cluster-cidr 192.168.192.0/18,2a02:snip::/56 --service-cidr 192.168.184.0/20,2a02:snip::/112 --kube-controller-manager-arg='node-cidr-mask-size-ipv4=22' --kube-controller-manager-arg='node-cidr-mask-size-ipv6=60' --kube-controller-manager-arg='allocate-node-cidrs=true'`

I have ensured that between attempts the lvs and iptables config has been cleaned down after running the cleanup command on `https://www.kube-router.io/docs/user-guide/#containerd` using `ipvsadm`, `iptables-save` and `ip6tables-save`. I've also been checking `nft list ruleset` but i don't think this is relevant.

## What did you expect to happen?

I expected the pod to communicate outside the cluster directly without any SNAT. Both ipv4 and ipv6 addresses attached to the pod are being SNAT'd. I need this because I want to firewall the two parts of the cluster independently at a higher level to networkpolicy.

## How can we reproduce the behavior you experienced?

See deployment switches.

## Screenshots / Architecture Diagrams / Network Topologies

NA

## System Information (please complete the following information)

- Kube-Router Version: `kube-router version v2.4.1`
- Kube-Router Parameters: 
```
        - "--masquerade-all=false"
        - "--enable-overlay=false"
        - "--enable-ipv6=true"
        - "--enable-ipv4=true"
        - "--run-router=true"
        - "--run-firewall=true"
        - "--run-service-proxy=true"
        - "--run-loadbalancer=true"
        - "--advertise-loadbalancer-ip=true"
        - "--loadbalancer-ip-range=192.168.188.0/22"
        - "--loadbalancer-ip-range=2a02:snip::/56"
        - "--bgp-graceful-restart=true"
        - "--kubeconfig=/var/lib/kube-router/kubeconfig"
        - "--peer-router-ips=192.168.14.1"
        - "--peer-router-asns=65000"
        - "--cluster-asn=65001"
```
- Kubernetes Version: `1.31.3-k3s1`
- Cloud Type: `bare metal`
- Kubernetes Deployment Type: `k3s-ansible lightly modified`
- Kube-Router Deployment Type: `daemonset`
- Cluster Size:  `8 nodes (2 master inc, mariadb backed kine backend`

**Comment by jimmypw** [comment]
I've done some debugging the rule causing the masquerade is:-

`-A POSTROUTING -m set --match-set kube-router-pod-subnets src -m set ! --match-set kube-router-pod-subnets dst -m set ! --match-set kube-router-node-ips dst -j MASQUERADE --random-fully`

Tracing the code it get to this block of code https://github.com/cloudnativelabs/kube-router/blob/6ce2c6dbf26fdad9154eb0b4a28c36d659015b66/pkg/controllers/routing/network_routes_controller.go#L217 
that relates to the `--enable-pod-egress` option. Sure enough setting to `false` disables the creation of the rule, however it doesn't work quite right. I'll try and fine more time to debug this afternoon.

**Comment by jimmypw** [comment]
It's looking a lot better now I have added that option. I'm seeing the correct ip addresses in my logs.

IPv6 just works, no surprises there. 

IPv4 needed some manual tweaking of SNAT on my gateway. pfsense only masq's directly attached networks by default.

The last issue I have is coredns responses failing with `FORMERR`. Since that's not related to this issue I'll close this one off.

**Comment by aauren** [comment]
Thanks for all of the details. I'm sure that your issue will help someone else down the road!

Good luck!
