### ISSUE TITLE
add opentracing support

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#181]
Opening a bug for feedback from #30 I think its worth supporting opentracing overall not just for ingress

---
Additionally, one feature critical to any serious ingress controller would be integrated [opentracing support](http://opentracing.io/). Several of the more commonly used ingress controllers support this. The nginx ingress just added support for it in the [most recent beta release](https://github.com/kubernetes/ingress/releases/tag/nginx-0.9.0-beta.14)

[zipkin go client libs](https://github.com/openzipkin/zipkin-go-opentracing)
[jaeger go client libs](https://github.com/uber/jaeger-client-go)

Having an instrumented distributed application really helps application owners troubleshoot things. Having this as part of kube-router natively (in addition to the prometheus stats) would be incredible.
***

**Comment by SEJeff** [comment]
FWIW this was released today as an open source version's of google's internal tracing tool and natively supports a ton of stuff:

[opencensus](http://opencensus.io/)

It supports opentracing via zipkin amongst several other things and gives builtin pprof support. Perhaps the existing pprof code could be dropped if this was used? Might be nice.

**Comment by aauren** [comment]
Closing as stale
