### ISSUE TITLE
Test switching between various kube-router settings

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#190]
We need to test what happens when kube-router is restarted and the configuration has changed, then compile a list of issues (bugs, leftover routes, rules, ipsets, etc) to be corrected.

Priority settings to consider:
- [ ] `--run-firewall`, `--run-router`, `--run-service-proxy`
- [ ] `--enable-overlay`
- [ ] `--enable-pod-egress`
- [ ] `--masquerade-all`

**Comment by aauren** [comment]
Closing as stale.
