### ISSUE TITLE
Support for 32 bit ASN numbers

### ISSUE THREAD

**Issue by xnaveira** [cloudnativelabs/kube-router#194]
When trying to configure kube-router to peer with our TOR switches we get the following error:

```Failed to run kube-router: Failed to create network routing controller: Error processing Global Peer Router configs: Invalid ASN number "4242000042" for global BGP peer.```

The following code fragment from ```network_routes_controller.go``` suggests that kube-router doesn't support 32 bit ASN numbers:

```go
if asns[i] > 65534 {
  return nil, fmt.Errorf("Invalid ASN number \"%d\" for global BGP peer.",asns[i])
}
```

It would be nice to have support for 32 bit ASN numbers that are frequently used in "private" setups, specifically the range ```4200000000 - 4294967294``` as specified by [RFC 6996](https://tools.ietf.org/html/rfc6996)

**Comment by murali-reddy** [comment]
Fix will be part of next release, but if you wish to use/try below image has the fix.

cloudnativelabs/kube-router-git:PR196

**Comment by xnaveira** [comment]
Awesome, thanks!
