### ISSUE TITLE
Guidance for cluster size?

### ISSUE THREAD

**Issue by zapman449** [cloudnativelabs/kube-router#198]
In `Documentation/bgp.md` it is stated: "This mode is suitable in public cloud environments or small cluster deployments."

What does "Small" mean in this case?  

In a Public Cloud, how large (# nodes) does the cluster need to be before "full mesh" does not work?  Is there any guidance?  (i'm looking for something like "between 150-200 nodes, you need to start thinking about segmenting" or similar)

**Comment by murali-reddy** [comment]
@zapman449 sorry about open ended statement `This mode is suitable in public cloud environments or small cluster deployments.`. We have not done large scale cluster testing to see at what point the full-mesh of cluster nodes forming iBGP peers becomes bottleneck. So don't have empirical data. But cluster size 100-200 nodes should be perfectly fine IMO, as really there is little work (processing advertised routes) each kube-router pod would be doing. We will have to do bit of testing and prescribe a guideline.

If your use-case is public cloud or does not require advertising pod CIDR's or service IP's (basically the need for BGP) etc then really there is no need to run BGP at all. Please see #199. This would be something similar to Flannels [HostGW](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#host-gw). Kube-router also does the IPIP tunnelling so you can use HostGW like functionality across different subnets (or availability zones on public clouds).

Alternativley you can use Flannel/Weave etc for pod networking and still use Kube-router for service proxy and network policy.

**Comment by zapman449** [comment]
Basically, I have two distinct problems:

1) Using kops with kubenet, I'm limited to ~20ish nodes due to the 50 route table entry limit.  I can bump that to 100, which will give me ~40-45 useable nodes (I currently replace nodes by double and half the ASG.  As the cluster grows, I can get away form double/half to "replace 10 at a time" or similar, but still.)  So I'm keeping my eyes open for alternatives to kubenet.  Kube-router seems really promising.  But if I solve this, I'd like the solution to take me to 500 nodes before I have to seriously consider it again.

2) I'm giving a talk in a few days about the various alternatives for kubernetes networking.  I'll include kube-router (because it seems really promising), but I'd love to be able to give some generic advice like "if your cluster size is between X and Y use Z" and give some rough stair steps in that growth curve.

**Comment by murali-reddy** [comment]
>Using kops with kubenet, I'm limited to ~20ish nodes due to the 50 route table entry limit. I can bump that to 100, which will give me ~40-45 useable nodes (I currently replace nodes by double and half the ASG. As the cluster grows, I can get away form double/half to "replace 10 at a time" or similar, but still.) So I'm keeping my eyes open for alternatives to kubenet. Kube-router seems really promising. But if I solve this, I'd like the solution to take me to 500 nodes before I have to seriously consider it again.

I tested provisioning a cluster with KOPS with hundred nodes across zones. There are some issue with time taken to bootstrap cluster #202 But pod networking worked with no issues after cluster is boot strapped. But like mentioned there is work cut out to test kube-router at scale ensure smooth functioning irrespective of cluster size.

Perhaps you can also look at Flannels VXLAN backend, which suits your needs

>I'm giving a talk in a few days about the various alternatives for kubernetes networking. I'll include kube-router (because it seems really promising)

Great!!

>I'd love to be able to give some generic advice like "if your cluster size is between X and Y use Z" and give some rough stair steps in that growth curve.

There is no inherenet limitation in Kube-router regarding cluster size ((like 50 routes of VPC for Flannels AWS VPC backend ) Technically you can scale to any extent. Its just matter of how well Kube-router is tested to work for large clusters.

**Comment by murali-reddy** [comment]
Closing this issue as other issue like #192 etc can effectivley mean there are no constraints on cluster size.
