### ISSUE TITLE
support to turn-off iBGP peering

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#199]
Currently each kube-router instance on the node advertises to the rest of the nodes (or iBGP peers) about the pod CIDR allocated to the node. Each kube-router instance advertise and learn routes and setsup the kernel forwarding table accordingly.

In use-cases where there is no need to make pods and service VIP's routable really there is no need to be running GoBGP. Kube-routers depends on Kubernetes controller manager to do the subnet allocation to the nodes. Kube-router can read from the Kubernetes API server, subnets allocated for each node and can setup the local forwarding table accordinlgy.

This would be something similar to Flannels [HostGW](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#host-gw). Kube-router also does the IPIP tunnelling so you can use HostGW like functionality across different subnets (or availability zones on public clouds).

This should ease out the deployment where there is no need for BGP. Particulary requirments to have full mesh of iBGP peers or use route-reflector etc.

**Comment by andrewsykim** [comment]
Missed this issue, seems like we're good to close it after https://github.com/cloudnativelabs/kube-router/pull/227

**Comment by murali-reddy** [comment]
Will keep it open. Yes #227 solves disabling the peering. But also wanted to see if there is a way to get simple (like Flannel HostGW) way to populate routing than using iBGP. Basically each node reads the pod CIDR allocated to all the nodes and then configure the routing table locally with out using BGP.  Particularly useful in AWS scenario.

**Comment by murali-reddy** [comment]
On digital ocean due to security rules for anti-spoofing prevents using direct routing.

https://github.com/cloudnativelabs/kube-router/issues/252
https://kubernetes.slack.com/archives/C09NXKJKA/p1514608373000008

Since ip-ip tunneling is in place, its one option to use as overlay network when iBGP peering is turned off. But have to verify if ip-ip tunneling works on DigitalOcean

cc @andrewsykim

**Comment by andrewsykim** [comment]
I'm going to test this out, will report back soon!

**Comment by aauren** [comment]
Closing as stale
