### ISSUE TITLE
panic with advertise cluster IP and headless service

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#20]
I'm not at my computer so I can get logs of the panic later. I believe there's an issue when kube-router tries to advertise the IP of a headless service, which has no service IP but instead sets up DNS records going directly to the POD IPs for the service.  The log mentioned advertising service IP [] (empty slice I believe), and then the panic was a memory access error, probably accessing a nonexistent element of the empty slice.

Reference: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

**Comment by murali-reddy** [comment]
Oh, i see. There is a check in place to advertise only ClusterIP and NodePort service types, but i guess there might be still some flaw logic. Will wait for your logs. thanks.

**Comment by bzub** [comment]
The service type is still `ClusterIP` but with service IP set to `None` in the yaml/json at least. So it will get past the check you linked.

Here's an example I found that checks if the service is headless or not. Hopefully it's relevant. https://github.com/kubernetes/dns/blob/master/pkg/dns/dns.go#L719

**Comment by murali-reddy** [comment]
Ok, got it, i will get that fixed.
