### ISSUE TITLE
kube-router the hard way

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#205]
Kube-router [documentaion](https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/README.md#user-guide) covers how to set up Kubernetes clusters with kube-router using cluster installers.

But the docuemntation on how to use Kube-router when setting up Kubernetes cluster with out using cluster installers is not in great detail. Lately some of the users had trouble as well.

Need to document steps on how to setup kube-router on clusters setup manually.

**Comment by roffe** [comment]
I'd say that with https://github.com/cloudnativelabs/kube-router/pull/284 , https://github.com/cloudnativelabs/kube-router/pull/283 & https://github.com/cloudnativelabs/kube-router/pull/281 we should be able to close this issue

**Comment by murali-reddy** [comment]
Yes indeed. Thanks @roffe

**Comment by murali-reddy** [comment]
https://github.com/cloudnativelabs/kube-router/tree/master/Documentation#generic
