### ISSUE TITLE
kops + kube-router master inaccessible

### ISSUE THREAD

**Issue by iterion** [cloudnativelabs/kube-router#208]
I've been trying to setup a k8s 1.7 cluster with kops and kube-router but I'm having issues where pods can't access the master.

I see errors like the following:
```
E1026 21:21:00.195745       1 autoscaler_server.go:86] Error while getting cluster status: Get https://100.64.0.1:443/api/v1/nodes: dial tcp 100.64.0.1:443: i/o timeout
```

If I exec onto a kube-router pod I can curl that ip fine, but if I exec onto a pod it just times out.

I'm not sure where else to look to troubleshoot this. One pod (kube-dns), was actually able to start connecting to master after a few restarts, but nothing has worked for other pods that are experiencing these issues.

Also, I should add we're using a multi-az private network topology, not sure if that matters.

**Comment by iterion** [comment]
I believe I've narrowed down the problem to when a pod is trying to access a master in a different az than what it's on. Since connections between masters to masters are balanced it seems that sometimes you'll get lucky and make a connection to the master in the same AZ and everything works fine. Otherwise, the traffic will just fail to route.

**Comment by murali-reddy** [comment]
@iterion thanks for reporting.

It turns out you need to add a security group rule in `masters.mycluster.aws.cloudnativelabs.net` security group to allow IPIP packets. Please try adding a rule with type of `Custom Protocol`and protocol 4 (IPIP traffic) to master nodes. 

I will add this required step in KOPS documentation for Kube-router.

**Comment by iterion** [comment]
:+1: I'll try and report back. Would it be possible to automate this step through kops? I'm happy to give that a shot if there aren't any blockers (or even if there are :grin:)

**Comment by iterion** [comment]
Security rule was all that was needed, everything seems happy now!

**Comment by murali-reddy** [comment]
Thanks for confirming @iterion. I suspect no one (other CNI integrations in KOPS) is using IPIP, so perhaps that rule was not needed in general. But we could add that in KOPS, should be easy. Please give it a shot else will try to add in the documentation at the least.

**Comment by iterion** [comment]
@murali-reddy will do, thanks!

**Comment by iterion** [comment]
It turns out this was pretty easy to automate as Calico and Romana already need IPIP allowed. PR here: https://github.com/kubernetes/kops/pull/3730

**Comment by murali-reddy** [comment]
Awesome. Thanks. Closing this bug for now.
