### ISSUE TITLE
pod networking between the nodes in different subnets

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#21]
Current model host gateway based routing of Kube-router assumes nodes are L2 adjacent or in same subnet. this should work fine for most cases. But if we have a cluster with nodes in different subnets, i.e nodes are not in L2 adjacent., then host routing based approach for cross node pod-to-pod connectivity does not work.

Perhaps easy way to address is to use VXLAN encapsulation. So routes are set such that if destination node is in not in same subnet then use the interface to VXLAN  encap.

**Comment by ChenLingPeng** [comment]
I think we should point this limit(L2 adjacent) out in README.md/requirements section

**Comment by murali-reddy** [comment]
@ChenLingPeng thanks, yes you are right it should be in the requirements section. Will add neccessary details.

**Comment by m1093782566** [comment]
I think introducing VXLAN encapsulation for ipvs while preserving source pod IP is the biggest challenge.

**Comment by m1093782566** [comment]
refer to https://github.com/kubernetes/community/pull/692

**Comment by murali-reddy** [comment]
Fixed as part of #92
