### ISSUE TITLE
kube2iam compatibility

### ISSUE THREAD

**Issue by iterion** [cloudnativelabs/kube-router#211]
I'm trying to set up https://github.com/jtblin/kube2iam with kube-router which recommends setting up an iptables rule as defined here: https://github.com/jtblin/kube2iam#iptables

They give information for a lot of other CNI but not kube-router. I've tried both the docker0 and kube-bridge interfaces but neither seems to be working. docker0 in my case shows no traffic. kube-bridge has traffic, and seems to work on first glance, but adding an iptables rule seems to mess up all other traffic.

My repro case:
On a cluster created with kops I added kube2iam which creates an iptables rule:
```
iptables \
  --append PREROUTING \
  --protocol tcp \
  --destination 169.254.169.254 \
  --dport 80 \
  --in-interface kube-bridge \
  --jump DNAT \
  --table nat \
  --to-destination `curl 169.254.169.254/latest/meta-data/local-ipv4`:8181
```

This setup gets kube2iam working, but unfortunately, it breaks all other traffic.

**Comment by murali-reddy** [comment]
I am not very familiar with kube2iam. But if its just boils down to adding a iptables rule as above in effect, i wonder why that would block rest of the traffic.

Any way will try to repro the problem, and see if there is anything from Kube-router that is interfering.

**Comment by murali-reddy** [comment]
@iterion sorry i did not get chance to try this out. I dont see any issue after running the required iptables rule for kube2iam. Both pod-to-pod networking and external connectivity is working fine for me.

**Comment by iterion** [comment]
Bummer, I wish I had a better repro case. Unfortunately, we don't have the environment that was experiencing the issue running anymore. Feel free to close this issue, I'm sure it will come up again if it's still a problem.

**Comment by murali-reddy** [comment]
Thanks.
