### ISSUE TITLE
Support BGP Graceful Restart Mechanisms

### ISSUE THREAD

**Issue by andrewsykim** [cloudnativelabs/kube-router#219]
kube-router should support BGP restarts so that the routes on host are not removed whenever kube-router (the pod) restarts. Removing BGP provided routes can be problematic when performing rolling updates on kube-router since BGP may have replaced a route that was originally required to start kube-router (reaching docker registry, etc). Seems like gobgp already supports graceful restarts :). 

cc @murali-reddy

**Comment by murali-reddy** [comment]
@andrewsykim Incidentally we just happened to discuss on this very issue yesterday in the project chat room. This is something that hit other users as well during rolling updates. We will get this issue addressed.

**Comment by andrewsykim** [comment]
@murali-reddy great! Any idea on when this would be addressed? I can try to submit a PR if you are busy with other issues for the upcoming week.

**Comment by murali-reddy** [comment]
I was planning to look at https://github.com/cloudnativelabs/kube-router/issues/202 as well. Basically to fix rough edges with GoBGP integration. Not sure effort and timeline at the moment.

So a PR would be awesome @andrewsykim if you can submit.

**Comment by murali-reddy** [comment]
Already fixed in#220
