### ISSUE TITLE
Support more than a single AS per cluster to allow AS per rack design

### ISSUE THREAD

**Issue by SEJeff** [cloudnativelabs/kube-router#22]
In specific, this [project calico document](http://docs.projectcalico.org/v2.1/reference/private-cloud/l3-interconnect-fabric#the-as-per-rack-model) shows a really common design that network engineers really like for these sorts of things. I'd like to use kube-router, but can't due to it not supporting this.

This involves each rack using a different AS

**Comment by murali-reddy** [comment]
Thanks @SEJeff i will see how best we can incorporate that support.

**Comment by jdconti** [comment]
@murali-reddy I think this falls under the same design goals but I just want to explicitly state it; we would also like to peer with different external BGP routers either via metadata or statically defined.

**Comment by murali-reddy** [comment]
thanks @jdconti for the inputs i will work towards flexible model to support multiple AS.

**Comment by murali-reddy** [comment]
sorry did not get enough time to look in this issue, will try to get this sorted out and implement early next week

**Comment by murali-reddy** [comment]
@SEJeff @jdconti please see the documentation, please open a bug if you run into any issue.

https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/bgp.md

**Comment by SEJeff** [comment]
Fantastic stuff and that looks like a very clean implementation. Thanks @murali-reddy !

This looks a lot lighterweight than Calico.
