### ISSUE TITLE
Failed setup custom routing table required to add routes for external IP's due to: Failed to add route for xx.xxx.xx.174 in custom route table for external IP's due to: exit status 1

### ISSUE THREAD

**Issue by fanhaozzu** [cloudnativelabs/kube-router#223]
version: v0.0.18

Failed setup custom routing table required to add routes for external IP's due to: Failed to add route for xx.xxx.xx.174 in custom route table for external IP's due to: exit status 1

ipvsadm
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn

**Comment by murali-reddy** [comment]
@fanhaozzu please try https://github.com/cloudnativelabs/kube-router/releases/tag/v0.0.19 which has the fix for the regression introduced in v0.0.18

**Comment by fanhaozzu** [comment]
i tried, still have the error:
E1120 02:42:24.052691       1 network_services_controller.go:261] Failed setup custom routing table required to add routes for external IP's due to: Failed to add route for x.18.xx.174 in custom route table for external IP's due to: exit status 1

**Comment by fanhaozzu** [comment]
this error occur when node have no kube-bridge dev， service needs  kube-bridge dev?

**Comment by murali-reddy** [comment]
@fanhaozzu I see, usually bridge gets automatically get created when a pod is launched on the node. But if there is no bridge (yet on the nodes) on that particual node this scenario can occur. 

Marked issue as a bug.

**Comment by murali-reddy** [comment]
@fanhaozzu can you try image `cloudnativelabs/kube-router-git-PR225` which has the fix.
