### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by andrewsykim** [cloudnativelabs/kube-router#229]
I think kube-router can benefit from having a unit test suite. Not sure how easy it may be to add some now, but seems like reasonable task to group the code in a way that's more testable. 

Related: https://github.com/cloudnativelabs/kube-router/issues/28

cc @murali-reddy

**Comment by murali-reddy** [comment]
Indeed it will benefit. We tried to run k8s networking integration tests as part of CI #140 (using packet, dind etc) but it still pending. Atleast unit test can be added.

**Comment by aauren** [comment]
While there are still areas lacking coverage, I think that in the broad spirit of this issue that kube-router has a good amount of unit testing now.
