### ISSUE TITLE
how to monitor kube-router

### ISSUE THREAD

**Issue by huyipow** [cloudnativelabs/kube-router#234]
I'm going to use prometheus-operator to monitor kube-router. if kube-router has a metrics port to be monitored for monitoring 

 Kuber-router startup parameters 
```/usr/local/bin/kube-router --run-router=true --run-firewall=true --run-service-proxy=true --master=10.18.19.143:8080```

I found that kube-router did not start the 8080 port

```
[root@app558 ~]# netstat -tlunp | grep router
tcp        0      0 0.0.0.0:50051           0.0.0.0:*               LISTEN      68037/kube-router
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      68037/kube-router
```

**Comment by murali-reddy** [comment]
Kube-router at the momet is not publishing any Prometheus metrics (please see #232).

**Comment by murali-reddy** [comment]
Support for service proxy metrics are now enabled as part of #232.
