### ISSUE TITLE
External IPs are not removed from the pod tunnel if the annotation is removed

### ISSUE THREAD

**Issue by Thoro** [cloudnativelabs/kube-router#235]
When creating a service with the DSR tunnel annotation the POD is setup correctly, if the annotation is removed via

kubectl annotate service xxxx kube-router.io/service.dsr-

The ipvsadm and iptables configuration is teared down successfully, but the IP remains on the pods tunnel interface.

**Comment by murali-reddy** [comment]
@Thoro Yes, external IP is not getting removed from the tunnel interface inside the pod when annotation is removed on the service. 

While this should be fixed, its does not have any side affect, as the tunnel interface in the pod is noarp interface will not respond back to ARP's. for the external IP's.

**Comment by KJSui** [comment]
@murali-reddy @Thoro If I use DSR, do I need to config IPIP in kube nodes or by default it will have ipip if enabling DSR service?

**Comment by aauren** [comment]
Closing this issue as stale.
