### ISSUE TITLE
Stop bgp routes from overriding local interface routes

### ISSUE THREAD

**Issue by Thoro** [cloudnativelabs/kube-router#236]
It's possible to override local interface routes with routes from bgp, if that happens they have to be manually readded.

Assume you have a local route:

10.21.12.0/22 dev eth0

If you pass the same route via the external bgp peer, the route of the interface will be replaced with

10.21.12.0/22 via 10.21.15.254

This will lead to no route to the gateway + no route to the interface

**Comment by aauren** [comment]
I believe that this has been fixed now that we added import/export BGP policies to kube-router. Please re-test with a new version of kube-router and feel free to re-open with new information if the issue persists.
