### ISSUE TITLE
Nodes are missing some peer route entries

### ISSUE THREAD

**Issue by h3po** [cloudnativelabs/kube-router#238]
I have kube-router running on a bare-metal cluster, advertising peer routes to an external router box running quagga. I was having connectivity issues with certain pods, depending on which node they were placed on. When diagnosing the issue, I discovered that the routing tables on the problematic nodes were missing some (not all) entries, while kube-router logs look normal to me.
Before I collected the snippets below, node 2 and 6 were missing entries. I deleted the kube-router pod from node6, after respawn the entries were correct.

My nodes are in 10.128.8.0/24, pod_cidr is 172.18.0.0/16 and service_cidr is 172.19.0.0/16.

Initially, node 2 and 6 both only had 7 routes:
> for node in {1,2,3,4,5,6}; do ssh core@node${node}.k8s.local.mydomain.com 'echo -n "$(hostname): "; ip route list | wc -l'; done
> node1.k8s.local.mydomain.com: 10
> node2.k8s.local.mydomain.com: 7
> node3.k8s.local.mydomain.com: 10
> node4.k8s.local.mydomain.com: 10
> node5.k8s.local.mydomain.com: 10
> node6.k8s.local.mydomain.com: 10

correct routing table:
> ssh core@node1.k8s.local.mydomain.com ip route list
> default via 10.128.8.1 dev eno1 proto dhcp src 10.128.8.93 metric 1024 
> 10.128.8.0/24 dev eno1 proto kernel scope link src 10.128.8.93 
> 10.128.8.1 dev eno1 proto dhcp scope link src 10.128.8.93 metric 1024 
> 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
> 172.18.0.0/24 via 10.128.8.97 dev eno1 proto 17 
> 172.18.2.0/24 via 10.128.8.95 dev eno1 proto 17 
> 172.18.3.0/24 via 10.128.8.54 dev eno1 proto 17 
> 172.18.4.0/24 via 10.128.8.53 dev eno1 proto 17 
> 172.18.5.0/24 via 10.128.8.50 dev eno1 proto 17 
> 172.18.6.0/24 dev kube-bridge proto kernel scope link src 172.18.6.1
> 

routing table on node2 missing entries:

> ssh core@node2.k8s.local.mydomain.com ip route list
> default via 10.128.8.1 dev eno1 proto dhcp src 10.128.8.50 metric 1024 
> 10.128.8.0/24 dev eno1 proto kernel scope link src 10.128.8.50 
> 10.128.8.1 dev eno1 proto dhcp scope link src 10.128.8.50 metric 1024 
> 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
> 172.18.2.0/24 via 10.128.8.95 dev eno1 proto 17 
> 172.18.4.0/24 via 10.128.8.53 dev eno1 proto 17 
> 172.18.5.0/24 dev kube-bridge proto kernel scope link src 172.18.5.1 

ipvs list: (note there is a mapping for 172.18.6.4, for which there is no route)
> ssh core@node2.k8s.local.mydomain.com sudo ipvsadm -l --numeric 
> IP Virtual Server version 1.2.1 (size=4096)
> Prot LocalAddress:Port Scheduler Flags
>   -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
> TCP  172.19.0.1:443 rr persistent 10800
>   -> 10.128.8.50:443              Masq    1      0          0         
> TCP  172.19.0.10:53 rr
>   -> 172.18.4.6:53                Masq    1      0          0         
> TCP  172.19.12.93:6790 rr
>   -> 172.18.0.15:6790             Masq    1      10         0         
> TCP  172.19.32.247:3306 rr
>   -> 172.18.0.14:3306             Masq    1      0          0         
> TCP  172.19.42.231:443 rr
>   -> 172.18.0.18:8443             Masq    1      0          0         
> TCP  172.19.53.92:44134 rr
>   -> 172.18.3.3:44134             Masq    1      0          0         
> TCP  172.19.55.155:3306 rr
> TCP  172.19.55.155:9104 rr
> TCP  172.19.59.33:6790 rr
> TCP  172.19.62.147:6790 rr
>   -> 172.18.5.8:6790              Masq    1      0          39        
> TCP  172.19.68.9:8082 rr
>   -> 172.18.3.7:8082              Masq    1      0          0         
> TCP  172.19.116.35:3306 rr
>   -> 172.18.3.5:3306              Masq    1      0          0         
> TCP  172.19.116.35:9104 rr
>   -> 172.18.3.5:9104              Masq    1      0          0         
> TCP  172.19.122.160:6790 rr
>   -> 172.18.6.4:6790              Masq    1      9          0         
> TCP  172.19.175.1:8124 rr
>   -> 172.18.0.12:8124             Masq    1      0          0         
> TCP  172.19.208.126:3306 rr
>   -> 172.18.5.11:3306             Masq    1      0          0         
> UDP  172.19.0.10:53 rr
>   -> 172.18.4.6:53                Masq    1      0          0

one chunk of logs from kube-router container on node2:

> I1207 16:22:43.512939       1 network_routes_controller.go:336] Processing bgp route advertisement from peer                                
> I1207 16:22:47.556961       1 network_services_controller.go:194] Received endpoints update from watch API                                                    
> I1207 16:22:47.557110       1 network_services_controller.go:251] Setting up policy routing required for Direct Server Return functionality.                  
> I1207 16:22:47.559440       1 network_services_controller.go:256] Custom routing table kube-router-dsr required for Direct Server Return is setup as expected.
> I1207 16:22:47.559452       1 network_services_controller.go:258] Setting up custom route table required to add routes for external IP's.                                                               
> I1207 16:22:47.565741       1 network_services_controller.go:264] Custom routing table external_ip required for Direct Server Return is setup as expected.                                              
> I1207 16:22:47.566322       1 network_services_controller.go:1189] Successfully added destination 10.128.8.53:443 (Weight: 1) to the service TCP:172.19.0.1:443 (Flags: [persistent port][hashed entry])        I1207 16:22:47.567828       1 network_services_controller.go:458] Cleaning up if any, old ipvs service and servers which are no longer needed                                                                   
> I1207 16:22:47.568095       1 network_services_controller.go:504] Found a destination 10.128.8.50:443 (Weight: 1) in service TCP:172.19.0.1:443 (Flags: [persistent port][hashed entry]) which is no longer need
> ed so cleaning up                                                                                                        
> I1207 16:22:47.568338       1 network_services_controller.go:514] IPVS servers and services are synced to desired state!!     
> I1207 16:22:47.568348       1 network_services_controller.go:243] sync ipvs servers took 11.324736ms                                        
> I1207 16:22:49.734937       1 network_policy_controller.go:118] Performing periodic syn of the iptables to reflect network policies                           
> I1207 16:22:49.748204       1 network_services_controller.go:159] Performing periodic syn of the ipvs services and server to reflect desired state of kubernetes services and endpoints
> I1207 16:22:49.749045       1 network_services_controller.go:822] No hairpin-mode enabled services found -- no hairpin rules created                      
> I1207 16:22:49.760560       1 network_services_controller.go:251] Setting up policy routing required for Direct Server Return functionality.                                                            
> I1207 16:22:49.765832       1 network_services_controller.go:256] Custom routing table kube-router-dsr required for Direct Server Return is setup as expected.                                          
> I1207 16:22:49.765856       1 network_services_controller.go:258] Setting up custom route table required to add routes for external IP's.                                                                       I1207 16:22:49.784152       1 network_services_controller.go:264] Custom routing table external_ip required for Direct Server Return is setup as expected.                                                      
> I1207 16:22:49.793023       1 network_services_controller.go:458] Cleaning up if any, old ipvs service and servers which are no longer needed
> I1207 16:22:49.794651       1 network_services_controller.go:514] IPVS servers and services are synced to desired state!!
> I1207 16:22:49.794668       1 network_services_controller.go:243] sync ipvs servers took 34.209824ms        
> I1207 16:22:49.856353       1 network_policy_controller.go:298] Iptables chains in the filter table are synchronized with the network policies.
> I1207 16:22:49.857677       1 network_policy_controller.go:957] Found pod name: mariadb-single-rookfs-686b77864-s64gb namespace: default for which network policies need to be applied.
> I1207 16:22:49.857691       1 network_policy_controller.go:957] Found pod name: pod-checkpointer-wm6bb namespace: kube-system for which network policies need to be applied.
> I1207 16:22:49.857704       1 network_policy_controller.go:957] Found pod name: kube-router-jxzd5 namespace: kube-system for which network policies need to be applied.
> I1207 16:22:49.857709       1 network_policy_controller.go:957] Found pod name: kube-controller-manager-6dbb74fcdb-l9kqp namespace: kube-system for which network policies need to be applied.
> I1207 16:22:49.857716       1 network_policy_controller.go:957] Found pod name: pod-checkpointer-wm6bb-node2.k8s.local.mydomain.com namespace: kube-system for which network policies need to be applied.
> I1207 16:22:49.857725       1 network_policy_controller.go:957] Found pod name: kube-apiserver-shvvf namespace: kube-system for which network policies need to be applied.
> I1207 16:22:49.857733       1 network_policy_controller.go:957] Found pod name: kube-scheduler-784bbf758c-tbjhf namespace: kube-system for which network policies need to be applied.                           E1207 16:22:49.921252       1 network_policy_controller.go:890] Found pod fw chain to cleanup: KUBE-POD-FW-XSGK4MWJGKEIMJBO                  
> I1207 16:22:49.924686       1 network_policy_controller.go:899] Deleted pod specific firewall chain: KUBE-POD-FW-XSGK4MWJGKEIMJBO from the filter table                                                         
> I1207 16:22:49.924704       1 network_policy_controller.go:189] sync iptables took 189.747328ms
> I1207 16:22:50.826144       1 network_routes_controller.go:199] Syncing ipsets.                                          
> I1207 16:22:50.889281       1 network_routes_controller.go:888] Syncing BGP peers for the node.                                             
> I1207 16:22:50.893472       1 network_routes_controller.go:211] Advertising cluster ips of services to the external BGP peers                                 
> I1207 16:22:50.893487       1 network_routes_controller.go:220] found a service of cluster ip type                                          
> I1207 16:22:50.893498       1 network_routes_controller.go:517] Advertising route: '172.19.0.1/32 via 10.128.8.50' to peers                                   
> I1207 16:22:50.893579       1 network_routes_controller.go:336] Processing bgp route advertisement from peer                                                                                            
> I1207 16:22:50.893629       1 network_routes_controller.go:220] found a service of cluster ip type                                                        
> I1207 16:22:50.893640       1 network_routes_controller.go:517] Advertising route: '172.19.53.92/32 via 10.128.8.50' to peers                                                                                   I1207 16:22:50.893726       1 network_routes_controller.go:220] found a service of cluster ip type                                           
> I1207 16:22:50.893734       1 network_routes_controller.go:517] Advertising route: '172.19.59.33/32 via 10.128.8.50' to peers                                                                                   
> I1207 16:22:50.893741       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.893824       1 network_routes_controller.go:220] found a service of cluster ip type                       
> I1207 16:22:50.893833       1 network_routes_controller.go:517] Advertising route: '172.19.116.35/32 via 10.128.8.50' to peers              
> I1207 16:22:50.893833       1 network_routes_controller.go:336] Processing bgp route advertisement from peer                                                  
> I1207 16:22:50.893883       1 network_routes_controller.go:336] Processing bgp route advertisement from peer                                
> I1207 16:22:50.893921       1 network_routes_controller.go:220] found a service of cluster ip type                                                            
> I1207 16:22:50.893929       1 network_routes_controller.go:517] Advertising route: '172.19.42.231/32 via 10.128.8.50' to peers                                                                          
> I1207 16:22:50.894013       1 network_routes_controller.go:220] found a service of cluster ip type                                                        
> I1207 16:22:50.894020       1 network_routes_controller.go:517] Advertising route: '172.19.175.1/32 via 10.128.8.50' to peers                                                                                   I1207 16:22:50.894051       1 network_routes_controller.go:336] Processing bgp route advertisement from peer                                 
> I1207 16:22:50.894096       1 network_routes_controller.go:336] Processing bgp route advertisement from peer                                                                                                    
> I1207 16:22:50.894123       1 network_routes_controller.go:220] found a service of cluster ip type  
> I1207 16:22:50.894132       1 network_routes_controller.go:517] Advertising route: '172.19.12.93/32 via 10.128.8.50' to peers
> I1207 16:22:50.894186       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.894221       1 network_routes_controller.go:220] found a service of cluster ip type
> I1207 16:22:50.894229       1 network_routes_controller.go:517] Advertising route: '172.19.122.160/32 via 10.128.8.50' to peers
> I1207 16:22:50.894319       1 network_routes_controller.go:220] found a service of cluster ip type
> I1207 16:22:50.894325       1 network_routes_controller.go:517] Advertising route: '172.19.208.126/32 via 10.128.8.50' to peers
> I1207 16:22:50.894330       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.894404       1 network_routes_controller.go:220] found a service of cluster ip type
> I1207 16:22:50.894408       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.894411       1 network_routes_controller.go:517] Advertising route: '172.19.62.147/32 via 10.128.8.50' to peers
> I1207 16:22:50.894464       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.894496       1 network_routes_controller.go:220] found a service of cluster ip type
> I1207 16:22:50.894504       1 network_routes_controller.go:517] Advertising route: '172.19.32.247/32 via 10.128.8.50' to peers
> I1207 16:22:50.894579       1 network_routes_controller.go:220] found a service of cluster ip type
> I1207 16:22:50.894584       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.894587       1 network_routes_controller.go:517] Advertising route: '172.19.55.155/32 via 10.128.8.50' to peers
> I1207 16:22:50.894656       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.894663       1 network_routes_controller.go:220] found a service of cluster ip type
> I1207 16:22:50.894670       1 network_routes_controller.go:517] Advertising route: '172.19.68.9/32 via 10.128.8.50' to peers
> I1207 16:22:50.894750       1 network_routes_controller.go:220] found a service of cluster ip type
> I1207 16:22:50.894758       1 network_routes_controller.go:517] Advertising route: '172.19.0.10/32 via 10.128.8.50' to peers
> I1207 16:22:50.894764       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.894839       1 network_routes_controller.go:242] Performing periodic syn of the routes
> I1207 16:22:50.894851       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:50.897139       1 network_routes_controller.go:365] Advertising route: '172.18.5.0/24 via 10.128.8.50' to peers
> I1207 16:22:50.897277       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
> I1207 16:22:51.644629       1 network_services_controller.go:194] Received endpoints update from watch API
> I1207 16:22:51.644781       1 network_services_controller.go:251] Setting up policy routing required for Direct Server Return functionality.
> I1207 16:22:51.647593       1 network_services_controller.go:256] Custom routing table kube-router-dsr required for Direct Server Return is setup as expected.
> I1207 16:22:51.647605       1 network_services_controller.go:258] Setting up custom route table required to add routes for external IP's.
> I1207 16:22:51.654056       1 network_services_controller.go:264] Custom routing table external_ip required for Direct Server Return is setup as expected.
> I1207 16:22:51.656396       1 network_services_controller.go:1189] Successfully added destination 10.128.8.50:443 (Weight: 1) to the service TCP:172.19.0.1:443 (Flags: [persistent port][hashed entry])
> I1207 16:22:51.656611       1 network_services_controller.go:458] Cleaning up if any, old ipvs service and servers which are no longer needed
> I1207 16:22:51.656843       1 network_services_controller.go:504] Found a destination 10.128.8.53:443 (Weight: 1) in service TCP:172.19.0.1:443 (Flags: [persistent port][hashed entry]) which is no longer need
> ed so cleaning up
> I1207 16:22:51.657015       1 network_services_controller.go:514] IPVS servers and services are synced to desired state!!
> I1207 16:22:51.657022       1 network_services_controller.go:243] sync ipvs servers took 12.327147ms
> I1207 16:22:57.611508       1 network_services_controller.go:194] Received endpoints update from watch API
> I1207 16:22:57.611654       1 network_services_controller.go:251] Setting up policy routing required for Direct Server Return functionality.
> I1207 16:22:57.614112       1 network_services_controller.go:256] Custom routing table kube-router-dsr required for Direct Server Return is setup as expected.
> I1207 16:22:57.614128       1 network_services_controller.go:258] Setting up custom route table required to add routes for external IP's.
> I1207 16:22:57.620509       1 network_services_controller.go:264] Custom routing table external_ip required for Direct Server Return is setup as expected.
> I1207 16:22:57.620865       1 network_services_controller.go:1189] Successfully added destination 10.128.8.53:443 (Weight: 1) to the service TCP:172.19.0.1:443 (Flags: [persistent port][hashed entry])
> I1207 16:22:57.622533       1 network_services_controller.go:458] Cleaning up if any, old ipvs service and servers which are no longer needed
> I1207 16:22:57.622713       1 network_services_controller.go:504] Found a destination 10.128.8.50:443 (Weight: 1) in service TCP:172.19.0.1:443 (Flags: [persistent port][hashed entry]) which is no longer need
> ed so cleaning up
> I1207 16:22:57.622872       1 network_services_controller.go:514] IPVS servers and services are synced to desired state!!
> I1207 16:22:57.622877       1 network_services_controller.go:243] sync ipvs servers took 11.293884ms

**Comment by murali-reddy** [comment]
@h3po if you run into issue again can you use [pod toolbox](https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/pod-toolbox.md) and see how the BGP neighbours and routes in the RIB looks like.

If you still have node2 with missing entries, please share the above info.

**Comment by h3po** [comment]
Thanks, I did not know tools are included with the pod. Will do if it appears again, currently everything is working since i killed the pod on node2 as well.

**Comment by murali-reddy** [comment]
@h3po i am closing this bug as nothing can be done to diagnose. But i have opened #241 to proactivley figure any issues and throw errors in the logs.
