### ISSUE TITLE
Compare to other components?

### ISSUE THREAD

**Issue by thockin** [cloudnativelabs/kube-router#239]
Hi! I have not been able to keep up with all the cool community efforts, so I apologize.  Do you have anything that compares this project, at a technical level, to the IPVS kube-proxy and to Calico for net policy and BGP?

**Comment by murali-reddy** [comment]
@thockin glad you noticed the project.

Vision of Kube-router is to offer a holistic soltuon for both north-south and east-west traffic. For pod-networking functionally it will be same as calico, and same goes with network policy. Kube-proxy IPVS implementation and Kube-router's IPVS implementation functionally will be same.

But where it gets interesting (other than offering operational simplicity) in combination of routing and service proxy. Kube-router has ability to advertise `ClusterIP` and `ExternaIP` to BGP peers. Kube-router currently can do DSR becuase its control over data-path.

Perhaps https://cloudnativelabs.github.io/post/2017-11-01-kube-high-available-ingress/ will be good unique use-case of kube-router.

**Comment by murali-reddy** [comment]
@thockin closing this ticket. Happy to answer any further questions.
