### ISSUE TITLE
improve diagnosis

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#241]
While things do work most part, there will be always cases where for bugs or bizzare reasons actual configuration does not really reflect the desired state. For instance Kube-router may add the intended nodes as BGP peers, and try to install advertised routes from the peers into the routing table.

But for various reasons things may not be expected, and even worse there may not be any errors from Kube-router side (for instance #238).

[Pod toolbox](https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/pod-toolbox.md) should help in detecting the problem as after effect, we need more ways to proactivley figure everything is as expected.

Couple of thoughts and suggestion welcome.

As part of the controller sync loop, Kube-router can also verify actual configuration is in desired state. For instance retrieve all the IPVS services and endpoints and match againest the current set of services and endpoints in the Kubernetes. Get the list of the nodes in the cluster and allocated pod CIDR, and cross-verify in kernel routing table there is a route exists for each pod CIDR etc.

Also, an out-of-cluster tool or script to run through the kube-router pods in the cluster and give diagnostic information to troubleshoot would be useful.

**Comment by SEJeff** [comment]
If you make said control loop toggle a "healthy" vs "unhealthy" flag, you could get #80 virtually for free. Just add a http endpoint that checks the state via the control loop (along with a few other things obviously) and returns :+1: or :-1:

**Comment by roffe** [comment]
I will try to make some time next week to see if I can solve this

**Comment by aauren** [comment]
Closing as stale
