### ISSUE TITLE
kube-dummy-if is created in Pod (possibly DSR?!)

### ISSUE THREAD

**Issue by Thoro** [cloudnativelabs/kube-router#248]
I'm currently testing DSR as a passive option (e.g. not activly utilizing it)

Today the pod that has the DSR Tunnel (kube-tunnel-if) suddenly also had the kube-dummy-if.

I believe there may be some timing issue in creating / updating the dummy-if and the tunnel-if.

**Comment by murali-reddy** [comment]
It definitely is a namespace issue. So kube-router running in host namespace enters into pod’s network namespace to create tunnels, dummy interfaces etc. I have run into issue multiple times during development of DSR, where kube-router should gracefully should return back to the host network namespace. Failing which results are catastrohpic like this one. I tested various corner cases and added necessary defence. 

https://github.com/cloudnativelabs/kube-router/blob/master/app/controllers/network_services_controller.go#L562-L672

But looks like there is still a case where switch does not happen.

just FYI, if DSR is not used, namespace are never touched by Kube-router

**Comment by murali-reddy** [comment]
Possibly there is bigger issue with switching namespaces with GoLang

https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix
docker/libnetwork#1113
https://groups.google.com/forum/#!topic/golang-dev/6G4rq0DCKfo/discussion

For now i added more logging, and pin the gorouting to the same thread.

If the problem still reproduces then only possible solution is to fork the process to achive network configuration in the pod

**Comment by murali-reddy** [comment]
Re-open if issue is still seen.
