### ISSUE TITLE
Support DSR for clusterIP

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#249]
It's just matter of enabling it for clusterIP. Current implementation for external IP just need to adopted.

**Comment by aauren** [comment]
@murali-reddy I would argue that there isn't a great need for DSR on cluster IPs given that cluster IPs are largely for in-cluster communication and as such should be direct path communication anyway. e.g. `pod -> cluster IP -> IPVS -> pod` doesn't seem like there would be a lot of benefit for DSR. There could be use-cases I'm not thinking of though.

Do you still think this is needed?

**Comment by aauren** [comment]
Closing as stale.
