### ISSUE TITLE
Support externalTrafficPolicy

### ISSUE THREAD

**Issue by andrewsykim** [cloudnativelabs/kube-router#254]
It would be great if kube-router can advertise BGP routes based on `externalTrafficPolicy`. It would depend on https://github.com/cloudnativelabs/kube-router/issues/242 since `externalTrafficPolicy` only works with service of type `NodePort` or `LoadBalancer`. 

Happy to take this on if you are busy @murali-reddy :)

**Comment by murali-reddy** [comment]
@andrewsykim sure I could always use a PR :) 

So we have `--advertise-cluster-ip ` and `--advertise-external-ip` already (`--advertise-loadbalancer-ip` will be added with #242), based on `externalTrafficPolicy` and if there are local service endpoints, service VIP will be advertised or not. This should be easy part.

Unfortunaley IPVS integration still need iptables. Currently there is masqurade rule if source ip is not from podCIDR range. This rule needs to be overridden as well.

```
iptables -m  ipvs --ipvs --vdir ORIGINAL --vmethod MASQ  ! -s podCidr -j MASQUERADE
```

**Comment by murali-reddy** [comment]
https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typenodeport

```
 Kubernetes has a feature to preserve the client source IP (check here for feature availability). Setting service.spec.externalTrafficPolicy to the value Local will only proxy requests to local endpoints, never forwarding traffic to other nodes and thereby preserving the original source IP address. If there are no local endpoints, packets sent to the node are dropped, so you can rely on the correct source-ip in any packet processing rules you might apply a packet that make it through to the endpoint.
```

**Comment by Tatsu-Kishi** [comment]
@murali-reddy Looking at #262, is this implemented as well?
Currently looking at migrating to a new k8s cluster and re-evaluating the components and this is a must have feature for us.

**Comment by murali-reddy** [comment]
@Tatsu-Kishi Yes this functionality is implemented.

**Comment by aauren** [comment]
Closing as implemented.
