### ISSUE TITLE
SCTP support

### ISSUE THREAD

**Issue by GuoyouZhang** [cloudnativelabs/kube-router#266]
Some telecom VNF need SCTP support even in 5G. But k8s does't mention SCTP at all in its plan.  if kube-router could support this (e.g. by annotation, since k8s API model cannot be changed from kube-router point of view), that will be a good reason for telecom vendor to use kube-router.

**Comment by murali-reddy** [comment]
@GuoyouZhang thanks for the issue.

From IPVS point of view which Kube-router uses for service proxy, SCTP is supported

```
ipvsadm -A|E virtual-service [-s scheduler] [-p [timeout]] [-M netmask] [--pe persistence_engine] [-b sched-flags]

virtual-service:
  --tcp-service|-t  service-address   service-address is host[:port]
  --udp-service|-u  service-address   service-address is host[:port]
  --sctp-service    service-address   service-address is host[:port]
```
Like you mentioned k8s API does permit only TCP/UDP. So there is no clean way to configure service with SCTP as protocol. But use of annotation is one option.

Since IPVS already supprts SCTP it's not that hard to support. I will see how to add support with larger picture of NFV.

**Comment by GuoyouZhang** [comment]
@murali-reddy thanks a lot for considering this

**Comment by hwinkel** [comment]
@murali-reddy I tink thats two fold, Adding it should not so complicated as said. The Annotation is a pain but could also wake up the k8s folks to think about Non UDP or TCP protocols. As SCTP is just another L4 which needs to be "proxied" to reach the right SCTP Socket it fit's still in the typical socket termination use cases, reagrdless SCTP is used often in Telco Environments for SIGTRAN or DIAMETER protocols, it is still just Socker termination and not "packet forwarding" in a NVF/VNF Service Function Chain (SFC) for payload data. Therefore I would consider separating them to move forward with this issue.

Some references where this work could be linked too:

https://github.com/kubernetes/kubernetes/issues/44485#issuecomment-299536246

**Comment by lehongwen** [comment]
@hwinkel @murali-reddy  

Kube-router supports configuration of sctp used by ipvsadm，such as：
SCTP 10.161.50.120:32000 rr
  -> 172.20.3.38:32000            Masq    1      0          0         
SCTP 10.254.145.42:32000 rr
  -> 172.20.3.38:32000            Masq    1      0          0         
SCTP 127.0.0.1:32000 rr
  -> 172.20.3.38:32000            Masq    1      0          0

kube-router logs as follows：
I1111 10:10:04.921023       1 network_services_controller.go:1782] s.Protocol=132 
I1111 10:10:04.921039       1 network_services_controller.go:2042] Successfully added destination 172.20.3.35:32000 (Weight: 1) to the service SCTP:127.0.0.1:32000 (Flags: [hashed entry])
I1111 10:10:04.921082       1 network_services_controller.go:1782] s.Protocol=132 
I1111 10:10:04.921100       1 network_services_controller.go:2042] Successfully added destination 172.20.3.35:32000 (Weight: 1) to the service SCTP:10.161.50.120:32000 (Flags: [hashed entry])
I1111 10:10:04.921142       1 network_services_controller.go:1782] s.Protocol=132 
I1111 10:10:04.921159       1 network_services_controller.go:2042] Successfully added destination 172.20.3.35:32000 (Weight: 1) to the service SCTP:192.168.122.1:32000 (Flags: [hashed entry])

but sctp error as follows：
sctp client： in k8s
sctp_recvmsg error(-1), error:Unknown error -1

sctp server：out of k8s
sctp_sendmsg error(-1), error:Unknown error -1

**Comment by aauren** [comment]
Closing this issue as stale. However, Kubernetes now has some support for SCTP (https://kubernetes.io/docs/concepts/services-networking/service/#sctp) and I think support in general has grown.

If someone has interest in testing this against a modern k8s cluster, with a CNI plugin that supports SCTP and kube-router, and a recent version of kube-router, please feel free to re-open with the specifics from your test.
