### ISSUE TITLE
Support to change port for Promethues Metrics

### ISSUE THREAD

**Issue by rockwyc992** [cloudnativelabs/kube-router#271]
`kube-router` will use 8080 port for Promethues Metrics, but it use [hard code](https://github.com/cloudnativelabs/kube-router/blob/master/app/controllers/network_services_controller.go#L136) to define that.

``` go
// register metrics
prometheus.MustRegister(serviceActiveConn)
prometheus.MustRegister(servicePpsIn)
prometheus.MustRegister(servicePpsOut)
http.Handle("/metrics", promhttp.Handler())
go http.ListenAndServe(":8080", nil)
```

It should move this design to somewhere configurable.

**Comment by xanonid** [comment]
If possible, there should be also annotations added to the pods such that prometheus can auto-discover the metrics (cf. https://github.com/prometheus/prometheus/blob/ec94df49d45baa8e680d81e732294eb04fff00de/documentation/examples/prometheus-kubernetes.yml#L244 )

**Comment by murali-reddy** [comment]
Thanks @xanonid for your comments. requirement make sense. we will try to address it in the coming releases.

**Comment by roffe** [comment]
Submitted a PR for this that also adds the option to change the path

https://github.com/cloudnativelabs/kube-router/pull/288

**Comment by roffe** [comment]
PR #288 has been merged and we should be able to close this issue.

@xanonid  I have added docs for what you are asking in https://github.com/cloudnativelabs/kube-router/pull/289 comments welcome!

**Comment by roffe** [comment]
This issue can be closed
