### ISSUE TITLE
Have test framework in place for CI

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#28]
Quality Assurance: Have a basic test framework in place that can find some issues/regressions without manual testing. Using and passing kubernetes conformance tests would also help alleviate fears of new software.

**Comment by murali-reddy** [comment]
@bzub please share your thoughts how to go about testing. i will give a try this week to have test infra in place.

**Comment by aauren** [comment]
I believe this is in place with the unit tests we have and travis-ci integration.
