### ISSUE TITLE
Wrong node ASN number used

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#280]
When full mesh is disabled. A node peers up with only nodes with same ASN. But the ASN number used is default ASN number and not the one configured on the node object annotation.

https://github.com/cloudnativelabs/kube-router/blob/v0.0.20/app/controllers/network_routes_controller.go#L997

**Comment by cjbrigato** [comment]
May it be the same but I was mentioning off-topic on the route-reflector Issue there https://github.com/cloudnativelabs/kube-router/issues/192#comment-348304914 ?

**Comment by murali-reddy** [comment]
Fixed as part of #362
