### ISSUE TITLE
kube-router and docker

### ISSUE THREAD

**Issue by tiukhtinvladimir** [cloudnativelabs/kube-router#297]
Hello

I am trying to find a way to integrate kube-route with docker. For example flannel provides couple of variables which help configure docker to use proper bridge and ip range. How this is done in kube-route? Thanks

**Comment by roffe** [comment]
Hello @tiukhtinvladimir and thanks for your question.

kube-router is designed to fetch all information from the kubernetes api via [client-go](https://github.com/kubernetes/client-go).

We use [kubenet](https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/#kubenet) as CNI and then listen on the event stream from the api to configure services & BGP peering for the nodes.

Ip asignement is done by [controller-manager](https://kubernetes.io/docs/reference/generated/kube-controller-manager/) and the kubelet on the node sets the ip of the pod in docker after we bootstrap the kubelet cni conifg at kube-router start.

Unfortunately, as far as i know there is no usage case for kube-router outside a Kubernetes cluster.

**Comment by tiukhtinvladimir** [comment]
Hi @roffe 
Thanks for your explanation. One thing I don't understand, how can I use kube-router as daemon-set, if after kube-router is deployed and kube-bridge is created, somehow I should reconfigure docker to use kube-bridge, which requires doker daemon shutdown and kube-route in turn...

**Comment by roffe** [comment]
Hi tiukhtinvladimir we do not reconfigure docker to use that bridge interface, its for the IPVS services.

Docker stil uses Docker0 bridge where the kubelet takes care of setting pod ip's etc
