### ISSUE TITLE
kube-controller pod keeps shutting down

### ISSUE THREAD

**Issue by sigxcpu76** [cloudnativelabs/kube-router#302]
I've installed kube-router few hours ago, following the kubeadm instructions. It is installed in "full features" mode, replacing kube-proxy too.
After some time I've noticed it entered in a crash loop, always looking like it shuts down cleanly.

Here is the last part of the log:
```
I0210 20:59:03.718120       1 network_routes_controller.go:359] Processing bgp route advertisement from peer
I0210 20:59:03.917800       1 network_routes_controller.go:948] Syncing BGP peers for the node.
I0210 20:59:15.571134       1 server.go:163] Shutting down the controllers
I0210 20:59:15.571206       1 network_routes_controller.go:278] Shutting down network routes controller
I0210 20:59:15.571234       1 network_services_controller.go:167] Shutting down network services controller
I0210 20:59:15.571243       1 network_policy_controller.go:129] Shutting down network policies controller
```

Checking the code, it should behave like this on SIGTERM or SIGINT. None is sent by me or any other service (this is an empty cluster).

Digging further it seems that it doesn't start listening on the default port for health checks (20244).

**Comment by murali-reddy** [comment]
@sigxcpu76 health checks are only added recently still not in any release version.

As you noted there is SIGTERM or SIGINT resulting in graceful shutdown of kube-router.

Do you see any information in the pod events? Do you see this issue on any particular node or across the nodes?

**Comment by sigxcpu76** [comment]
events: livenessProbe fails.
They are enabled, following the installation guide here:

https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/kubeadm.md

This yaml https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml creates the liveness probe:

```
livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 10
          periodSeconds: 3
```

**Comment by murali-reddy** [comment]
Oops. @sigxcpu76 we updated manifests recently. Current HEAD has the liveliness [enabled](https://github.com/cloudnativelabs/kube-router/commit/a480a518320b726853686e88b71f178a1531417b). We need to make a release to get the functionality. However manifest have been update. 

To fix this , please disable liveliness checks. 

In any case, we will be making new release in a day or two.

**Comment by sigxcpu76** [comment]
Thanks. Of course I've disabled livenessProbe to be able to play with kube-router.
Just made sure you are notified.

**Comment by murali-reddy** [comment]
New release is out. Please reopen if you still run into any issue.

https://github.com/cloudnativelabs/kube-router/releases/tag/v0.1.0-rc2
