### ISSUE TITLE
Multicast support

### ISSUE THREAD

**Issue by Daviey** [cloudnativelabs/kube-router#309]
It doesn't seem that multicast is currently functional, is this something that could be supported?

**Comment by murali-reddy** [comment]
@Daviey sorry for dumb question. How multicast is expected to be supported? Can you give details what a CNI plugin is expected do to achive it.

**Comment by murali-reddy** [comment]
Thanks for the pointers. Will take a look.

**Comment by basvandenbrink** [comment]
I am also interested in multicast support for kube-router. Are there any plans to implement this?

@Daviey : I know that Weave support multicast, but AFAIK, they use an overlay network. This would mean that they have to broadcast multicast datagrams to all nodes. Do you know more about this? Does it perform well?

I also know that [Contiv](https://github.com/contiv/netplugin) supports multicast in L2 (Ethernet bridging) mode. We have experimented with this and it seemed to work pretty well. However, the project seems to be abandoned and the integration of kube-router with Kubernetes is a lot better compared to Contiv.

**Comment by aauren** [comment]
@murali-reddy Is this still something that you're interested in supporting in the near-term? If not, we should probably just wrap up the thread.

**Comment by aauren** [comment]
Closing from lack of interest.
