### ISSUE TITLE
Add release and commit tags to container images

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#31]
- [ ] `cloudnativelabs/kube-router:latest` tag should point to the latest release version.
- [ ] `cloudnativelabs/kube-router:master` tag should point to the latest commit version.

All previous releases and commits should be available in the registry separately.

I will have to investigate how to do this automatically with every release/commit.  I've done it before with quay.io registry but I haven't used Docker Hub yet.

**Comment by murali-reddy** [comment]
@bzub please check .travis yaml file i addes some support for master branch, may need to tweek it for this bug though
