### ISSUE TITLE
Mis-leading error msg if br_netfilter is not provided as a kernel module

### ISSUE THREAD

**Issue by TjWallas** [cloudnativelabs/kube-router#311]
In older versions of the linux kernel, br_netfilter was built-in and not provided as a separate kernel module. See: http://ebtables.netfilter.org/documentation/bridge-nf.html (flashing text on top).

As a result, this error msg is **mistakenly** logged when trying to `modprobe br_netfilter` on these systems:
```
Failed to enable netfilter for bridge. Network policies and service proxy may not work
```
See: https://github.com/cloudnativelabs/kube-router/blob/617c7736557ce5254516685d8a8703050b6ec35d/app/controllers/network_routes_controller.go#L181

I suggest to check for the presence of the br_netfilter in a different way.

### OS:
Debian jessie
```
vagrant@k8s-source:~$ uname -a 
Linux k8s-source 3.16.0-4-amd64 #1 SMP Debian 3.16.51-2 (2017-12-03) x86_64 GNU/Linux
```

**Comment by aauren** [comment]
Closing as stale. Even though 3.16 is still technically supported as LTS you'll probably run into many other issues attempting to run cloud native workloads that require modern kernel features. It now receives very few patches and will be EOL in June.
