### ISSUE TITLE
Use golang 1.10 to fix potential issues in DSR due to Golang limitations

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#314]
As noted in #258 

https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix
https://github.com/docker/libnetwork/issues/1113
https://groups.google.com/forum/#!topic/golang-dev/6G4rq0DCKfo/discussion

Go lang 1.10 is relased with the fix for https://github.com/golang/go/issues/20676

**Comment by murali-reddy** [comment]
https://www.weave.works/blog/linux-namespaces-golang-followup

**Comment by aauren** [comment]
I believe we're using Go 1.10 for our builds now. Feel free to open again if I got something wrong here.
