### ISSUE TITLE
Is hairpin-mode required for kube-dns?

### ISSUE THREAD

**Issue by t3hmrman** [cloudnativelabs/kube-router#316]
Hey all, thanks for the work on `kube-router`!

I apologize if this is a simple mistake, but am I right in assumign that `kube-router` does *not* replace `kube-dns`? I'm trying to get `kube-dns` to work on top of `kube-router` (ClusterIP <-> ClusterIP connections work just fine), but I'm having a problem getting names to actually resolve.

As far as why this might be happening, I'm thinking that this log line from `sidecar` inside the `kube-dns` pod might be helpful?

```
W0220 20:24:30.247394       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:58863->127.0.0.1:53: read: connection refused
```

I also thought maybe it might be related to the [alpine bug regarding resolv.conf](https://github.com/gliderlabs/docker-alpine/issues/8), but people are at least getting IPs returned there, I get:

```
/ #  nslookup kubernetes.default
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kubernetes.default': Try again
```
If I force the ServiceIP of the DNS service:

```
/ #  nslookup kubernetes.default 10.32.0.2
Server:    10.32.0.2
Address 1: 10.32.0.2

nslookup: can't resolve 'kubernetes.default': Try again
```
The Direct IP of the pod doesn't fare any better. I know the service has endpoints, and I know the Service is reachable (I'm also running the kubernetes dashboard and I can curl to it by service IP).

What I thought I might be missing was `--hairpin-mode=true`, since the error message from the `sidecar` container says that it's trying to access `127.0.0.1:53`, but that hasn't worked either... Does anyone know what I might be missing?

If I try to `dig` the ClusterIP of the dns pod from inside an `alpine` container:
```
/ # dig +add +trace  @10.244.1.53 kubernetes-dashboard

; <<>> DiG 9.10.2 <<>> +add +trace @10.244.1.53 kubernetes-dashboard
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
/ # dig  @10.244.1.53 kubernetes-dashboard

; <<>> DiG 9.10.2 <<>> @10.244.1.53 kubernetes-dashboard
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39233
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kubernetes-dashboard.          IN      A

;; Query time: 0 msec
;; SERVER: 10.244.1.53#53(10.244.1.53)
;; WHEN: Tue Feb 20 20:45:59 UTC 2018
;; MSG SIZE  rcvd: 49
```
 
**NOTE** After a machine restart I no longer get the probe error from `sidecar`, so that is no longer an issue I think, but DNS still doesn't work so maybe this question is more general now

**Comment by murali-reddy** [comment]
@t3hmrman So you are not able to get functioning kube-dns service? There is no need for hairpin mode. Any pod should be able to access cluster ip of DNS service.

even if you delete the pod you still have issue with DNS resolution?

**Comment by t3hmrman** [comment]
Hey @murali-reddy yeah that's exactly what's happening. Good to know hairpin mode is not required -- it must be something wrong with the resource definition I'm using for kube-dns.

I will try deleting the pod again -- it's especially weird that I can acess the other kube-dashboard resource by it's service IP but not the dns...

**Comment by t3hmrman** [comment]
An update -- this very likely is not the fault of `kube-router`, after lots more investigation, pod internal traffic is working just fine, it's `kubedns` that is actually broken. I think my specific setup (arch + systemd-orchestrated api/controller-manager/scheduler) is what's causing this interop issue.

Here's a snippet of the logs (`kubedns` container inside the `kube-dns` service's pod) that I'm currently investigating:
```
     I0222 08:12:55.749225       1 dns.go:584] Query for "kubernetes.default.svc.cluster.local.", exact: false <--- every once in a while
     I0222 08:12:55.749262       1 dns.go:704] Found 1 records for [local cluster svc default kubernetes] in the cache <---- every once in a while
     I0222 08:12:57.616885       1 dns.go:436] No service for endpoint "kube-scheduler" in namespace "kube-system" <--- constantly
     I0222 08:12:57.616919       1 dns.go:436] No service for endpoint "kube-scheduler" in namespace "kube-system" 
     I0222 08:12:57.632853       1 dns.go:436] No service for endpoint "kube-controller-manager" in namespace "kube-system" <--- constantly
     I0222 08:12:57.632865       1 dns.go:436] No service for endpoint "kube-controller-manager" in namespace "kube-system"
```
It may very well be the case that `kube-dns` just expects to access the `kube-scheduler` and `kube-controller-manager` from services?

**Comment by murali-reddy** [comment]
@t3hmrman did you get a chance to try CoreDNS instead of kube-dns?

**Comment by t3hmrman** [comment]
Hey @murali-reddy, thanks for taking the time to help -- my next step is to try CoreDNS next, absolutely.

I didn't want to give up, since the solution seems so close :) I'm taking notes as I go so I can make a blog post about my floundering, and at least file a ticket with `kube-dns` so they know about it.

What I've done lately is use a headless service to expose the services:

```
kind: Service
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  type: ExternalName
  externalName: <node ip>

kind: Service
apiVersion: v1
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  type: ExternalName
  externalName: <node ip>
```

**Comment by t3hmrman** [comment]
Hey @murali-reddy I managed to narrow it down some more --  it looks like actually the `Service` IPs are not being routed properly for my nodes:

```
/ # dig @10.32.0.2 -p53 kubernetes-dashboard
<hangs>
^C
/ # dig @10.244.1.65 -p53 kubernetes-dashboard

; <<>> DiG 9.11.2-P1 <<>> @10.244.1.65 -p53 kubernetes-dashboard
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 54312
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kubernetes-dashboard.          IN      A

;; AUTHORITY SECTION:
.                       67846   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2018022200 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 10.244.1.65#53(10.244.1.65)
;; WHEN: Thu Feb 22 10:39:38 UTC 2018
;; MSG SIZE  rcvd: 124

/ #

```

I doubt the external name service stuff I did was necessary, but I'll file an issue with `kube-dns` to find out anyway. 

This issue does seem to be related to *kube-router*, because it's a pod <-> service endpoint issue -- going to start re-reading the docs on `kube-router` service configuration, I must have set something up wrong

**Comment by t3hmrman** [comment]
Found it! the issue was [`ufw`](https://wiki.archlinux.org/index.php/Ufw). I use UFW internally and it was stopping DNS traffic from moving around internally on the node!

I apologize for the wasted cycles, I just need to update my rules to allow traffic between the locally created networks!

**Comment by murali-reddy** [comment]
@t3hmrman great you could figure out.

**Comment by t3hmrman** [comment]
For posterity the fix was:

$ sudo ufw allow to 10.32.0.0/16 from 10.244.0.0/16
$ sudo ufw allow from 10.32.0.0/16 to 10.244.0.0/16

To connect my service cluster to the regular pods to interact
