### ISSUE TITLE
Pod Toolbox documentation issue

### ISSUE THREAD

**Issue by Matty9191** [cloudnativelabs/kube-router#317]
I think the "Logging In" info needs to be updated on the following page:

https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/pod-toolbox.md

The documentation contains the following shell snippet:

KR_POD="basename $(kubectl -n kube-system get pods -l k8s-app=kube-router --output name|head -n1)"

Which assigns the string "basename pod/XXX" to the variable. 

I think you want a second command substitution to get just the pod name:

KR_POD=$(basename $(kubectl -n kube-system get pods -l k8s-app=kube-router --output name|head -n1))

- Ryan

**Comment by murali-reddy** [comment]
@Matty9191 thanks for reporting. Yes you are right. Documentation needs correction.
