### ISSUE TITLE
Create a kube-router Helm Chart

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#32]
To increase testing/adoption and further automate and standardize configuration/deployment.  It should probably live in the official [Chart](https://github.com/kubernetes/charts) repository for maximum exposure and help with issues, so it won't be added to this repository in that case.  I will work on this and close this ticket once it's added to the official Chart repo.

### References
[Helm](https://github.com/kubernetes/helm)

**Comment by pilsy** [comment]
Helm chart is coming along, currently in https://github.com/pilsy/kube-router/tree/helm-chart/chart

**Comment by rdegez** [comment]
Hi, we maintain the following kube-router helm chart : [https://hub.helm.sh/charts/enix/kube-router](https://hub.helm.sh/charts/enix/kube-router) built from [https://github.com/enix/helm-charts/tree/master/charts/kube-router](https://github.com/enix/helm-charts/tree/master/charts/kube-router).

Give it a try!

Cheers

**Comment by murali-reddy** [comment]
@rdegez Thanks for trhe helm chart. Would you be able refer helm installation next to here https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#try-kube-router-with-cluster-installers?

**Comment by aauren** [comment]
Closing as stale
