### ISSUE TITLE
Kube-router fails to start when to small cluster-cidr is given to controller-manager

### ISSUE THREAD

**Issue by roffe** [cloudnativelabs/kube-router#320]
When a cluster has been initialized with a to small cluster CIDR controller-manager does not allocate a PodCIDR for the node.

e.g
     --allocate-node-cidrs=true
     --cluster-cidr=10.10.0.1/24
     --node-cidr-mask-size=24

Error in controller-manager with 1 node would look like:

    ormal' reason: 'CIDRNotAvailable' Node cf12 status is now: CIDRNotAvailable
    E0223 09:50:35.810656       1 controller_utils.go:267] Error while processing Node Add/Delete: failed to allocate cidr: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
    I0223 09:50:35.810722       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"cf12", UID:"5782a6ae-187d-11e8-95f8-ac1f6b17f23e", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'CIDRNotAvailable' Node cf12 status is now: CIDRNotAvailable

The error from kube-router would look like

    Error from server (NotFound): pods "kube-router-pmrmt" not found
    root@cf14:/home/ansible# kubectl logs -n kube-system kube-router-pmrmt
    I0223 09:21:17.242039       1 health_controller.go:127] Starting health controller
    I0223 09:21:17.266625       1 network_policy_controller.go:108] Starting network policy controller
    E0223 09:21:17.270063       1 network_routes_controller.go:88] Failed to get pod CIDR from CNI conf file: Failed to get IPAM details from the CNI conf file: invalid CIDR address: 
    E0223 09:21:17.271419       1 network_routes_controller.go:95] Failed to get pod CIDR from node spec: node.Spec.PodCIDR not set for node: cf12
    Failed to run kube-router: Failed to create network services controller: Failed to get pod CIDR details from Node.spec: node.Spec.PodCIDR not set for node: cf12
    root@cf14:/home/ansible#

We should add some more text to the error telling the user to review their controller-manager setup as it hasn't allocated a PodCIDR required for kube-router to run

**Comment by aauren** [comment]
Closing this as stale. I agree that the message isn't super informative, however, I think it gives the users enough information and while we could be more generous in the message here, it would require a lot more intelligence in the logic for something that is essentially a failing of the kubernetes configuration. (i.e. it would be inappropriate to guess why the node was not receiving a pod CIDR from Kubernetes, so we would need to find a way to lookup what the configured subnet was to judge if it was large enough to support a pod CIDR before outputting the message)

**Comment by Aniket61** [comment]
when initializing kubeadm  we are asked to used --pod-network-cidr=<ip range> , and after the complete setup we get to see that the range which we have given is taken by the --cluster-cidr=<ip range>, and also we cant make changes to it and also --node-cidr-mask-size=24 ,it is by default 24 ...i found this all under the kube-controller-manger-<nodename> pod running in namespace kube-system..
can anyone please update me on this that what i am missing

**Comment by SinHouse** [comment]
Hi @Aniket61, you can show a possible solution in this [comnet](https://github.com/rancher/k3s/issues/697#issuecomment-576463182) :)
