### ISSUE TITLE
ClientIP+SrcPort based session persistence in IPVS

### ISSUE THREAD

**Issue by PadmabushanReddy** [cloudnativelabs/kube-router#322]
Is it possible to have a clientIP+clientPort based persistence as opposed to Just clientIP where all requests from a particular IP (but different port) goes to same node ?. IPVS (or atleast keepalived) supports this granularity in persistence. Kube-router doesn't seem to support this.
To check this, i issued curl commands from a host with different --local-port option when affinity is ClientIP

**Comment by murali-reddy** [comment]
@PadmabushanReddy at this point `clientIP+clientPort` based persistence is not there. I will check and revert back if its possible to implement it.

**Comment by PadmabushanReddy** [comment]
similar issues in kubernetes:
https://github.com/kubernetes/kubernetes/issues/60688
