### ISSUE TITLE
Is there support for ppc64le?

### ISSUE THREAD

**Issue by ivankennethwang** [cloudnativelabs/kube-router#328]
I can't seem to run it on ppc64le.

**Comment by murali-reddy** [comment]
@ivankennethwang No it's no supported yet. Recently support for arm was added in this commit 

https://github.com/cloudnativelabs/kube-router/commit/c7ce39836788d66b634b3c7c4f4c935468394bad

Perhaps something can be added in similar lines.

**Comment by paulbsch** [comment]
kube-router builds seem to work just fine for ppc64le.  We are running an environment mixed with amd64 and ppc64le machines.  Including ppc64le builds in the official multi-arch builds would be helpful.   Here is a pull request to enable that:

https://github.com/cloudnativelabs/kube-router/pull/847

**Comment by paulbsch** [comment]
I was able to build and push multiarch amd64 and ppc64le images here:
https://hub.docker.com/r/nimbix/kube-router/tags

**Comment by murali-reddy** [comment]
Fixed by https://github.com/cloudnativelabs/kube-router/pull/847
