### ISSUE TITLE
Installing as Daemonet - Pods in CrashLoopBackOff state after installing kube-router

### ISSUE THREAD

**Issue by andygoremat** [cloudnativelabs/kube-router#329]
After installing Kube-Router as a Daemonset, the pods that is has deployed to are in a CrashLoopBackOff state.  The logs of the pods all share the same error message:

**Failed to parse kube-router config: Failed to build configuration from CLI: Error loading config file "/var/lib/kube-router/kubeconfig": read /var/lib/kube-router/kubeconfig: is a directory**

Kube-Router installed with : **kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kube-router-all-service-daemonset.yaml**

Running on Kubernetes 1.8.2 on Azure AKS

**Comment by murali-reddy** [comment]
@andygoremat error indicates there is no proper kube configuration file in the location. How did you provision the cluster? Are you using any cluster installers like kubeadm?

**Comment by murali-reddy** [comment]
Also please try https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/generic-kuberouter-all-features.yaml if it helps.

**Comment by andygoremat** [comment]
Hi, it was provisioned using the Azure AKS installer.

**Comment by murali-reddy** [comment]
Ok, I will try to add a manifest that works with AKS installer.

But basically kube-router needs kubeconfig with proper master details and certificate to access the API server.

**Comment by mjhoffman65** [comment]
@murali-reddy did you get a chance to look into this at all?  I'm running into the same issue on an AKS cluster

**Comment by mjhoffman65** [comment]
Got an example working.   I can open up a PR if there's interest and it works for others

In the meantime, this is what I did to get it working:

- Used https://github.com/Azure/AKS/blob/master/examples/vnet/00-README.md as an example to setup my AKS cluster using azure networking

- Ran `kubectl get nodes -o name | xargs -I {} kubectl patch {} -p '{"spec":{"podCIDR":"10.53.8.0/22"}}'` (Replace podCIDR value with whatever you used from previous step)

- Created the kube-route daemonset using https://github.com/mjhoffman65/kube-router/blob/AKS/daemonset/aks-kube-router-firewall-daemonset.yaml

**Comment by murali-reddy** [comment]
@mjhoffman65 sorry i did not a chance to look into AKS. But glad you figured out. A PR would be awesome. Thanks.

**Comment by aauren** [comment]
Closing as stale with workaround.
