### ISSUE TITLE
kube-router is incompatible to cni v0.6.0 multi subnets

### ISSUE THREAD

**Issue by Thoro** [cloudnativelabs/kube-router#330]
In cni 0.6.0 you can have multiple subnets for the cni config:

```
{"bridge":"kube-bridge","ipam":{"ranges":[[{"gateway":"10.253.12.1","subnet":"10.253.12.0/24"}],[{"gateway":"2a0b:37c0:1:100c::1","subnet":"2a0b:37c0:1:100c::/64"}]],"type":"host-local"},"isDefaultGateway":true,"name":"mynet","type":"bridge"}
```

Instead of editing the sub range, kube-router adds a new subnet field.

```

{"bridge":"kube-bridge","ipam":{"ranges":[[{"gateway":"10.253.12.1","subnet":"10.253.12.0/24"}],[{"gateway":"2a0b:37c0:1:100c::1","subnet":"2a0b:37c0:1:100c::/64"}]],"subnet":"10.253.12.0/24","type":"host-local"},"isDefaultGateway":true,"name":"mynet","type":"bridge"}
```

Which means that pods can't be started anymore, because that config file is invalid.

**Comment by murali-reddy** [comment]
@Thoro thanks for reporting this issue. This is a concerning. `v0.6.0` is around for a quite a while, wonder why this issue did not surface so far.

**Comment by Thoro** [comment]
probably because nobody was so stupid and configure ipv6 directly in the ipam module :D

**Comment by Thoro** [comment]
suggestion from my side:

upgrade the cni module and remove the writing of the subnet into the file - or make it optional via flag

**Comment by aauren** [comment]
Closing as duplicate of #1023
