### ISSUE TITLE
Nodes are accessible from Pods or outside if clusterIp or external Ip is routed to any of kubelet nodes.

### ISSUE THREAD

**Issue by lavajnv** [cloudnativelabs/kube-router#331]
We can able to access ports like ssh etc. of kubelet nodes using kube-dummy-if interface IPs. 
All the ports of the Node can be accessed from pods or other newtorks if ClusterIP subnet or External Ips used in services.  are routed any kubelet node.

Can the IPs attached to  kube-dummy-if allow only the ports which are part of kubernetes services. Access to other ports from these clusterIP or external Ip can be potential secuirty risk. 

Or  do we have to write explicit network policies on kubernetes to restrict access via kube-interface-if

**Comment by murali-reddy** [comment]
> Can the IPs attached to kube-dummy-if allow only the ports which are part of kubernetes services. Access to other ports from these clusterIP or external Ip can be potential secuirty risk.

Yes this needs be fixed by default, dont need to write network policies.

**Comment by murali-reddy** [comment]
@lavajnv I am working on the fix for this issue as part of #282. Closing this bug.
