### ISSUE TITLE
Blocked access from pods in the host network namespace

### ISSUE THREAD

**Issue by stevenewey** [cloudnativelabs/kube-router#332]
We're using kube-router as our NPC along with flannel VXLAN for our basic networking.

We have an issue where one of our teams makes use of `kube proxy` as part of their deployment process.

They can add a policy the allows traffic from the kube-system namespace, and I can see kube-router does what makes sense on the node. There are ipset entries for each pod in kube-system, including for the kube-apiservers, which run in the host network namespace, and are therefore included with the host IP from the primary NIC.

Unfortunately, traffic from pods in the host network namespace instead enters via the `flannel.1` interface, and so appears instead to come from the IP address on this interface (always 10.1.x.0 in our case).

I can add cidrBlock rules for every possible 10.1.x.0/32 address, but this feels like quite a kludge.

Is this something that could be addressed by kube-router?

**Comment by murali-reddy** [comment]
@stevenewey any reason you closed this issue?

**Comment by stevenewey** [comment]
@murali-reddy sorry about that, we implemented a workaround in our tooling, and I mentioned this issue in the process, so Github seems to have decided it must have been fixed! Re-opening.

**Comment by murali-reddy** [comment]
Note from slack discussion.

> kube-router’s network policy controller did what it is supposed to do i.e) allow traffic from the pod IP of the pod in the `kube-system` namespace in this case. But Linux network stack would pick the ip on the bridge interface as it make more sense to use to reach the destination pod IP (in case of same node). Unfortunately this does break the semantics of network policy. however this does need to be fixed from kube-router side.
