### ISSUE TITLE
Use Cached Informer for network routes controller

### ISSUE THREAD

**Issue by andrewsykim** [cloudnativelabs/kube-router#349]
As discussed in https://github.com/cloudnativelabs/kube-router/pull/347, we should use informers so we can get update events for services/endpoints immediately as opposed to waiting for the next sync period. This should significantly decrease convergence time when we withdraw routes.

**Comment by andrewsykim** [comment]
cc @murali-reddy @TvL2386

**Comment by murali-reddy** [comment]
Closing as its already done in #373
