### ISSUE TITLE
kube-bridge has not assigned a ip

### ISSUE THREAD

**Issue by zhaofengcumt** [cloudnativelabs/kube-router#356]
kube-bridge has not assigned a ip,and it logs show 

E0328 04:41:20.151591    8770 network_routes_controller.go:190] Failed to enable netfilter for bridge. Network policies and service proxy may not work: exit status 1
I0328 04:41:20.151691    8770 network_routes_controller.go:200] Starting network route controller
I0328 04:41:20.325834    8770 network_routes_controller.go:1429] Could not find BGP peer info for the node in the node annotations so skipping configuring peer.

**Comment by murali-reddy** [comment]
@zhaofengcumt There are two different problems here.

IP gets assigned to `kube-bridge` interface lazily by `Bridge` CNI plug-in. Only when a pod is created on the node, bridge CNI will assing gateway IP to the interface. Please deploy some pods and see.

Regarding `Failed to enable netfilter for bridge`, what OS and Kernel version are you using.

Please see https://github.com/cloudnativelabs/kube-router/issues/311 this could be benign error.

**Comment by zhaofengcumt** [comment]
does 'Failed to enable netfilter for bridge'  influence the function of kube-router？

**Comment by murali-reddy** [comment]
Please see #311 . It depends on Kernel version. In older version `br_netfilter` is built-in. So this error can be ignored.

But if your Kernel does not have `br_netfilter` and enabling it is failing then this error has impact on functionality.

Enabling `br_netfilter` is must for all CNI's.

**Comment by zhaofengcumt** [comment]
8: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether d6:b8:3d:28:9a:1a brd ff:ff:ff:ff:ff:ff
9: kube-dummy-if: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 76:21:12:ba:ff:33 brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.1/32 brd 172.21.0.1 scope link kube-dummy-if
       valid_lft forever preferred_lft forever
    inet 172.21.153.131/32 brd 172.21.153.131 scope link kube-dummy-if
       valid_lft forever preferred_lft forever
    inet 172.21.213.175/32 brd 172.21.213.175 scope link kube-dummy-if
       valid_lft forever preferred_lft forever
    inet6 fe80::7421:12ff:feba:ff33/64 scope link 
       valid_lft forever preferred_lft forever
10: kube-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether 12:6a:62:16:70:3d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::106a:62ff:fe16:703d/64 scope link 
       valid_lft forever preferred_lft forever
[root@k8s home]# kubectl get pods --all-namespaces 
NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE
default       k8s-webapp-demo-55b55858d4-6npxx   1/1       Running   0          15s
kube-system   kube-router-4bwwb                  1/1       Running   0          2m
kube-system   kube-router-m9c72                  1/1       Running   0          2m

**Comment by zhaofengcumt** [comment]
when i start a pod  kube-bridge still has no ip

**Comment by zhaofengcumt** [comment]
my kernel is Linux bigdata5 4.4.104-1.el7.elrepo.x86_64 #

**Comment by zhaofengcumt** [comment]
and i still find that when I create a service with the type nodeport,the port did not up

**Comment by murali-reddy** [comment]
kernel 4.4.104 should have br_netfilter disabled by defualt. So kube-router attemepting to enable should have worked. I am not sure why it is failing.

Can you try manually and see if you can run

`modprobe br_netfilter`

**Comment by zhaofengcumt** [comment]
i got it thanks

**Comment by g0194776** [comment]
@zhaofengcumt 
Did you finally solve it?

**Comment by leonlau** [comment]
I have the same problem
manually run :
```
[root@deploy112v8 ~]# uname -r
4.4.186-1.el7.elrepo.x86_64
[root@deploy112v8 ~]# modprobe br_netfilter
[root@deploy112v8 ~]# lsmod |grep br_netfilter 
[root@deploy112v8 ~]# lsmod |grep filter
iptable_filter         16384  1
ip_tables              28672  3 iptable_filter,iptable_nat
```
kube-router  logs
```
[root@deploy111v8 ~]# kubectl -n kube-system   logs kube-router-68znc |grep E
E1101 05:42:09.028805       1 network_routes_controller.go:207] Failed to enable netfilter for bridge. Network policies and service proxy may not work: exit status 1
```
I did not encounter this problem in the  kernel 3.10 .

**Comment by g0194776** [comment]
@leonlau 

Normally, the IP will be assigned at the first time to allocate.

The error message you mentioned doesn't matter with IP assignment.
