### ISSUE TITLE
does flannel needed when using kube-router

### ISSUE THREAD

**Issue by zhaofengcumt** [cloudnativelabs/kube-router#358]

**Comment by zhaofengcumt** [comment]
does flannel needed when using kube-router?

**Comment by zhaofengcumt** [comment]
does flannel needed when using kube-router?

**Comment by murali-reddy** [comment]
@zhaofengcumt kube-router provides multiple functionalities typically needed for Kubernetes networking. 

* kube-router can be used to enforce network policies
* kube-router can be used to network service proxy
* kube-router can be used for pod-to-pod networking.

Depending on what you choose to use it for, Flannel can be used, but not a must. For e.g you can use Flannel for pod-to-pod networking, and use in combination with kube-router to provide service proxy and network policy.

Please take a look at https://cloudnativelabs.github.io/post/2017-04-18-kubernetes-networking/ for various network components used in Kubernetes.
