### ISSUE TITLE
Create a debugging toolbox container

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#36]
For people like me that use CoreOS or other minimal/immutable operating systems, there are very few tools easily available for troubleshooting and advanced configuration.  A common practice for Kubernetes applications is to make available a toolbox container that comes with software and configuration ready to perform these tasks.

For kube-router the toolbox should include:
- gobgp client
- ipvsadm
- iproute2 suite
- other? **open for input**

Configuration:
- gobgp config automatically populated to talk to kube-router nodes
- gobgp CLI completion configured
- other? **open for input**

**Comment by bzub** [comment]
Alternatively we add this functionality to the kube-router container image, the downside being an increased image size.  That might not be so bad with the current software list.  I added ipvsadm, iproute2, and bash, and it came out to ~3.5MB larger.  gobgp client is an additional 16MB at this time.

**Comment by murali-reddy** [comment]
This would be pretty useful. I think its better we include in base image itself, like you mentioned its marginal increase.
