### ISSUE TITLE
kubeadm init start when join node then kube-router error

### ISSUE THREAD

**Issue by shibd** [cloudnativelabs/kube-router#360]
kubeadm init start when join node then kube-router error

`Failed to create network services controller: Failed to get pod CIDR details from Node.spec: node.Spec.PodCIDR not set for node: master-etcd3`

kubeadm init command：
`
kubeadm init \
--pod-network-cidr=192.168.0.0/24
`
How set node CIDR?

**Comment by murali-reddy** [comment]
kube-router relies on `kube-controller-manager` to allocate the pod CIDR's for the node. I believe `/24` is too low for allocation. By default kube-controller-manager allocates /24 CIDR. Either you change the below [flag](https://kubernetes.io/docs/reference/generated/kube-controller-manager/) or give higher cidr for `--pod-network-cid` for kubeadm init.

`--node-cidr-mask-size int32                                         Mask size for node cidr in cluster. (default 24)`

**Comment by shibd** [comment]
I try change kube-controller-manager config

**Comment by murali-reddy** [comment]
Either of `kubeadm init --pod-network-cidr=192.168.0.0/16` or `kube-controller-manager` with `--node-cidr-mask-size 28` should work.

**Comment by shibd** [comment]
Thanks for your answer,  I solved it.
