### ISSUE TITLE
Failed setup custom routing table required to add routes for external IPs

### ISSUE THREAD

**Issue by farcaller** [cloudnativelabs/kube-router#361]
kube-router-v2fsl kube-router E0402 15:15:54.388599       1 network_services_controller.go:328] Failed setup custom routing table required to add routes for external IP's due to: Failed to add route for 10.202.0.1 in custom route table for external IP's due to: exit status 2

this is cloudnativelabs/kube-router:latest on a brand new kubeadm-based cluster.

**Comment by murali-reddy** [comment]
@farcaller thanks for reporting. What Linux flavour are you using and kernel version.

**Comment by farcaller** [comment]
Ubuntu 16.04.4 LTS running 4.13.0-17-generic.

**Comment by murali-reddy** [comment]
Basically `ip route add $externalIP dev kube-bridge table 79` comand is being run. Exit status code `2` means misuse of shell builtins. So not sure whats going wron here.

Could you please try manually and see if it works?

Are you trying to use DSR functionality.

**Comment by farcaller** [comment]
```
root@kube-master-1:~# ip route add 1.1.1.1 dev kube-bridge table 79
root@kube-master-1:~# echo $?
0
```
(and I just disabled cloudflare dns, heh)

no, not DSR. I'm trying to make kube-router talk to quagga bgpd on my bare metal machine. I think it actually works fine – I'm only confused by this message in the logs as I don't know what failed and if I should expect anything to be broken

**Comment by murali-reddy** [comment]
Please re-open if you run into any issue again.
