### ISSUE TITLE
Run kube-router only with --run-service-proxy

### ISSUE THREAD

**Issue by xiaoxubeii** [cloudnativelabs/kube-router#366]
Can kube-router be used for service proxy without pod networking (--run-router)? I use cni macvlan for pod networking, and just want to use service proxy of kube-router. Is that possible?

**Comment by murali-reddy** [comment]
@xiaoxubeii yes, its possible. I never tried with MacVlan though.

**Comment by murali-reddy** [comment]
@xiaoxubeii please reopen if you face any issue.

**Comment by xiaoxubeii** [comment]
OK, i will have some tests. Thanks.

**Comment by maximih** [comment]
I am also interested in this but I want to use [multus.](https://github.com/Intel-Corp/multus-cni) as CNI plugin. @xiaoxubeii please let us know if it worked for you with `macvlan`
