### ISSUE TITLE
network policy issue: optimize NetworkPolicyIngressRule.Ports

### ISSUE THREAD

**Issue by chenchun** [cloudnativelabs/kube-router#375]
1. It seems currently `NetworkPolicyIngressRule.Ports` is implemented by multiple iptable rules and `hash:ip` ipset instead of a single iptable rule and ipset type `hash:ip,port` or `hash:net,port`. I think the latter one is more efficient if there are many ports. 

![image](https://user-images.githubusercontent.com/985861/38464324-52aa2610-3b3e-11e8-876d-5f61e2ff3415.png)

2. `NetworkPolicyPeer.IPBlock.Except` is ignored ?

![image](https://user-images.githubusercontent.com/985861/38464385-98829db0-3b3f-11e8-846d-e9e6eeee9947.png)

3. Named ports is not supported yet ?

https://github.com/cloudnativelabs/kube-router/issues/338

**Comment by murali-reddy** [comment]
Yes, both Except (https://github.com/cloudnativelabs/kube-router/issues/326) and named ports(https://github.com/cloudnativelabs/kube-router/issues/338) not supported yet.

**Comment by chenchun** [comment]
Sorry, my mistake. I think `hash:ip` ipset is suitable for `NetworkPolicyPeer.NamespaceSelector` and `NetworkPolicyPeer.PodSelector`, `hash:net` ipset is suitable for `NetworkPolicyPeer.IPBlock`. ipset `nomatch` option is capable for implementing `IPBlock.expect`.

For multiple ports, using iptables `multiport` extension is efficient than multiple single dport rules.

**Comment by aauren** [comment]
Fixed through #679
