### ISSUE TITLE
Test and document kubeadm integration

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#38]
Kubeadm is one of the most popular and officially supported methods of deploying Kubernetes.  Need to test and document it for those users.

User @rmb938 has provided initial [RBAC related definitions](https://gist.github.com/rmb938/d2f8a0d6c3bb9bccd30bd11e9c3fb867) for this environment.

**Comment by murali-reddy** [comment]
yes, RBAC related definitions are good to go into manifests that we refer. I did incorporate them for kops [integration](https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template)

**Comment by bzub** [comment]
There are several folks using kubeadm so I'm putting a higher priority on this.

**Comment by murali-reddy** [comment]
Closing the bug. All aspects of using kubeadm to deploy kubernetes cluster with kube-rotuer are done.
