### ISSUE TITLE
Fine tuning informers resync period 

### ISSUE THREAD

**Issue by andrewsykim** [cloudnativelabs/kube-router#380]
As per discussion here https://github.com/cloudnativelabs/kube-router/pull/373#discussion_r179933074 we should investigate what resync period we should be using for informers. A resync period of 0 might be okay given we run a seperate sync loop in each controller.

**Comment by murali-reddy** [comment]
Part of #399 resync period of shared index informer is set to 0. As per the [discussions](https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/PbSCXdLDno0) is sig-api machinery and on my own verfication, it is observed all the objects from cache's are replayed which can get really expensive operation (processin updated). There is no real benefit to set to any value greater than 0, instead periodic full list of objects and ensure if any reconciliation are required is better.
