### ISSUE TITLE
Failed to start API watchers

### ISSUE THREAD

**Issue by andrenth** [cloudnativelabs/kube-router#381]
Hi

I'm trying to bring up a 3-node Kubernetes cluster using Kube-Router. I'm following the current [HA docs](https://kubernetes.io/docs/setup/independent/high-availability/), but when the kube-router pod is getting into a CrashLoopBackOff status. The output from the pod's log is

```
I0410 19:17:05.481290       1 server.go:210] Running /usr/local/bin/kube-router version v0.1.0, built on 2018-03-19, go1.8.7
Failed to run kube-router: Failed to start API watchers: Failed to launch network policy api watcher: Failed to get API server version due to the server has asked for the client to provide credentials
```

My setup is perhaps somewhat nonstandard in that my servers have two NICs (eth0 and eth1) and I'm trying to get all Kubernetes components listening on eth1. It seems that, for example, in flannel, an extra argument is needed to make it use a non-default interface. Is something like that needed with kube-router?

The `podCIDR` given to `kubeadm init` was `192.168.0.0/16`, although I'm not sure if this matters.

I can provide more cluster info if needed.

**Comment by murali-reddy** [comment]
@andrenth Have you performed the step mentioned in the docs.

Kube-router uses the same configmap that is generated for kube-proxy. So please update the configmap and give it a try.

```
kubectl get configmap -n kube-system kube-proxy -o yaml > kube-proxy-cm.yaml
sed -i 's#server:.*#server: https://<masterLoadBalancerFQDN>:6443#g' kube-proxy-cm.yaml
kubectl apply -f kube-proxy-cm.yaml --force
```

**Comment by andrenth** [comment]
So I decided to rebuild the node from scratch, because I had done a number of previous experiments with flannel, weave, etc before. Doing that, I can't reproduce the problem above, so I guess there were leftovers from previous configuration attempts preventing kube-router from working correctly.

Sorry for the noise.

**Comment by roffe** [comment]
@andrenth I've had similar problems. key has been to clear out /etc/cni/net.d on the host as flannel, weave, kube-router etc does not cleanup and remove the cni config from there if you delete their daemonsets

**Comment by andrenth** [comment]
@roffe I was doing that, but somehow it was not enough in my case... but I conjured up a "wipe all the things" kubectl command, rebooted and then it worked. Here's the command:

```
kubectl -n kube-system get 2>&1 \
  | grep '\*'                   \
  | awk '{print $2}'            \
  | xargs -I__X__ kubectl -n kube-system delete __X__ --all
```
