### ISSUE TITLE
make kube-router service VIP advertisement functionality independently usable.

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#392]
Network routes controller in kube-router does two crticial jobs now.

- advertise pod CIDR's allocated to the nodes to the peer nodes, extenal peers etc
- Advertise the service VIP's to the external peers.

I think its useful to have the functionality of #2, independent of #1.

Which mean, i should be use Flannel/Weave as CNI, yet deploy kube-router's and can use its service proxy and VIP advertisement capability.

Its not a big change at all, but need clear documetnation on presecribing what  flags to use when.

**Comment by aauren** [comment]
While documentation is always nice, I think there is a good amount in other projects on how to integrate with kube-router's BGP functionality such as: https://docs.cilium.io/en/v1.2/kubernetes/install/kube-router/
