### ISSUE TITLE
create policies  with kube-router with higher priority than kubernetes network policies      

### ISSUE THREAD

**Issue by anihak** [cloudnativelabs/kube-router#398]
I am using calico as CNI for my  kubernetes cluster.  **As an admin**,  I want to isolate namespaces at cluster scope in such a way that users in namespaces can't access to other namespaces even if they create nework policies to performe this.   Calico allow me to do that  with **global network policies**  which insert rules into iptables with  higher priority than network policies. 

I didn't find in your doc something equivalent to calico global network policies,  can we create policies rules which have higher priority than kubernetes network policies   ???

**Comment by murali-reddy** [comment]
There is no equivalent of calico global network policies. It's only Kubernetes network policies that kube-router conforms with.

**Comment by aauren** [comment]
Closing as stale. Additionally, kube-router tries to follow the lead of the kubernetes project in these cases for which there is no similar metaphor.
