### ISSUE TITLE
broken link to docs on www.kube-router.io GET STARTED section

### ISSUE THREAD

**Issue by sylecn** [cloudnativelabs/kube-router#402]
All links in homepage GET STARTED section is broken.

e.g.
```diff
-https://github.com/cloudnativelabs/kube-router/blob/master/Documentation/how-it-works.md
+https://github.com/cloudnativelabs/kube-router/blob/master/docs/how-it-works.md
```
I didn't find the repo for the homepage, so reporting it here.

**Comment by murali-reddy** [comment]
Thanks for reporting. Will fix the links.

**Comment by murali-reddy** [comment]
Fixed https://github.com/cloudnativelabs/kube-router.io/pull/15

thanks
