### ISSUE TITLE
Where appropriate kube-router should install multi-path routes

### ISSUE THREAD

**Issue by uablrek** [cloudnativelabs/kube-router#410]
When multiple peer routers are configured, for example `--peer-router-ips="192.168.0.201,192.168.0.202"` then router should be configured to all peer routers. This enables load sharing for outgoing traffic.

This is supported when gobgp uses the [zebra backend](https://github.com/osrg/gobgp/blob/master/docs/sources/zebra-multipath.md).

All routers are in the RIB (narrowed);

```
# gobgp global rib
   Network              Next Hop             AS_PATH              Age        Attrs
*> 192.168.2.0/24       192.168.0.201        65000                00:52:55   [{Origin: i} {Med: 0}]
*  192.168.2.0/24       192.168.0.202        65000                00:52:49   [{Origin: i} {Med: 0}]
```

But only one is actually used;

```
# ip ro
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.2 
192.168.2.0/24 via 192.168.0.201 dev eth0 proto 17 
```

I use gobgp/zebra for test as GWs and multi-path routes are configured;

```
# ip ro
12.0.0.1 proto zebra metric 20 
        nexthop via 192.168.0.2  dev eth0 weight 1
        nexthop via 192.168.0.3  dev eth0 weight 1
        nexthop via 192.168.0.4  dev eth0 weight 1
        nexthop via 192.168.0.1  dev eth0 weight 1
```

(`12.0.0.1` is my kubernetes-ClusterIP, others are node addresses)

**Comment by wzrdtales** [comment]
Adding to this it would be also good to mark any peer-router as fallback by a lower weigth. I.e. when the first route uses the private network and the second wents over the internet instead, you would not want it to route there unless the other routes are dead or saturated.

**Comment by Thoro** [comment]
Actually, it's not required to use Zebra for that, just enable the MultiPath config option and then it will do.

**Comment by varuzam** [comment]
any updates on this? this is really cool to have multi path beetween nodes in a cluster
