### ISSUE TITLE
Garbage collect KUBE_DUMMY_IF ip assignments

### ISSUE THREAD

**Issue by johanot** [cloudnativelabs/kube-router#411]
Deleted or changed service IP's are not removed from the **KUBE_DUMMY_IF** on nodes.

We currently have about 70 active ClusterIP services in our cluster, but kube-dummy-if has *1059* ip-addresses assigned. This actually turned out to be a real problem, because we had another host service that was configured to listen on all interfaces and breached ulimits when trying to open its 1024+ listening socket.

Since no auto-cleanup is running and we don't want to restart kube-router with `--cleanup` every night or so, I believe it should be a reconciliation step to delete unused serviceIP's from the dummy interface, just like unused ipvs rules are purged today.

**Comment by killcity** [comment]
Is this the same as https://github.com/cloudnativelabs/kube-router/issues/383?

**Comment by johanot** [comment]
@murali-reddy Works like a charm! Just tested - during today's keynote in Copenhagen :-) - on our cluster and stale IP's are removed as expected.

**Comment by murali-reddy** [comment]
@johanot thanks for confirming.

@dlamotte Keep the PR's coming in :)

**Comment by murali-reddy** [comment]
> Just tested - during today's keynote in Copenhagen :-)

@johanot do plan to attend https://kccnceu18.sched.com/event/Dqv8/global-container-networks-on-kubernetes-at-digitalocean-andrew-sy-kim-digitalocean-intermediate-skill-level :)
