### ISSUE TITLE
Upgrade kubernetes dependencies to support v1.10 

### ISSUE THREAD

**Issue by andrewsykim** [cloudnativelabs/kube-router#419]
Specifically client-go, api, and apimachinery.

**Comment by ieugen** [comment]
Hi, 
Does this mean kube-router does not work with k8s 1.10? I wish to try it out with hobby-kube setup [1]. 

[1] https://github.com/hobby-kube/guide

**Comment by andrewsykim** [comment]
Hey @ieugen, kube-router should still work with 1.10. If it doesn't please let us know :)

**Comment by aauren** [comment]
This was completed via #976 and merged into master via #982
