### ISSUE TITLE
include diagnostic tool in the pod toolbox

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#423]
[Pod toolbox](https://www.kube-router.io/docs/pod-toolbox/) comes pretty handy in showing the configuration done by the kube-router on node. To complement include a diagnostic tool in the pod toolbox which can do below:

- run through IPVS service and server and match against the k8s service and endpoint objects and verify necessary configuration are there
- verify `kube-dummy-if` is present and service VIP's are assigned
- verify `kube-bridge` interface exists and local route to send the traffic to local pod's over `kube-bridge`
- verify there is a route to reach to all the pod CIDR corresponding to each node in the cluster
- verify necessary PBR entries are present
- verify rp_filter is enabled
- verify netfliter bridge module is installed
- verify necessary PBR is present for the external IP's.

On failure of any above conditions, report the problem.

*What could be even more nice is an external script, that can run this diagnostic tool on each kube-router pod get the result and prescribe corrective actions.*

**If this is not enough run above script as cronjob on Kubernetes cluster to periodically check if network is okay :)**

**Comment by aauren** [comment]
Closing as stale
