### ISSUE TITLE
Linux host routing to external networks?

### ISSUE THREAD

**Issue by eriklindahl** [cloudnativelabs/kube-router#444]
Hi,

This is likely not any issue with Kube-router, but a limitation of my understanding (well, PEKBAC, to be honest).

We have a cluster with a default internal network (on, say, eth0) in the 172.17.xxx.yyy range, and then we use the same network cables/switches with a VLAN to be able to expose selected hosts externally too (although this particular host we use does not have any public IPv4, the VLAN interface is merely enabled).

We have set up k8s with kube-router, metallb and nginx-ingress and have basic stuff working fine, and as long as we stay on the internal (172.17.x.y) net, all services work fine both internally and externally - MetalLB appears to bind to kube-dummy-if, and accessess all hardware interfaces that way.

However, exposing thing externally is more problematic:

If I allocate an external IP in MetalLB, this binds to kube-dummy-if, but it is (obviously) not routed correctly externally automatically. If I add policy-based routing rules to send all packages with an origin/destination of our public IP range or the VLAN interface, the incoming connections work fine - but if I then have a pod running cert-manager trying to access an internal interface on the same node it can't find it (likely because the policy rules throw the packages to the external interface and its gateway).

Am I trying to accomplish something impossible here, or am I misunderstanding something fundamental about how kube-router and kube-dummy-if works?

I would prefer not to assign public IPv4s to the host nodes themselves, since that creates an unnecessary security-hazard exposure...

**Comment by murali-reddy** [comment]
> If I allocate an external IP in MetalLB, this binds to kube-dummy-if, but it is (obviously) not routed correctly externally automatically. 

Sorry i am not able to comprehend what the problem is. Can you please elobrate above comment?

**Comment by aauren** [comment]
Closing as stale.
