### ISSUE TITLE
Service Router does not cleanup old ports in ipvs

### ISSUE THREAD

**Issue by alebsack** [cloudnativelabs/kube-router#448]
I have an app that uses a [service without selectors](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors).  I've noticed that when pods use a `PATCH` on the endpoints object to update the port but not the IP address (in the case of a container restart and using ephemeral ports in the pod), old `ip:port` entries are not cleaned up from ipvs:

```
TCP  100.70.101.121:7800 rr
  -> 100.97.212.65:33550          Masq    1      0          0         
  -> 100.97.212.65:34276          Masq    1      0          0         
  -> 100.97.212.65:34484          Masq    1      0          0         
  -> 100.97.212.65:34499          Masq    1      0          0         
  -> 100.97.212.65:34715          Masq    1      0          0
```

Here is an example of the endpoints, with only one port defined:
```
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2018-05-09T16:29:27Z
  name: example-service
subsets:
- addresses:
  - ip: 100.97.212.65
    nodeName: ip-10-71-12-49.us-west-2.compute.internal
    targetRef:
      kind: Pod
      name: example-app-0
      namespace: example-namespace
      resourceVersion: "279017418"
      uid: 65b251dd-5de7-11e8-b798-06ee3cf7dcf6
  ports:
  - name: web
    port: 33550
    protocol: TCP
```

If you patch the endpoints and change the port manually, you will see a new entry in the ipvs table as shown above, where I would expect only one.

**Comment by aauren** [comment]
This has been fixed as part of the 1.0 effort. Please re-open if you still see any issues after upgrading.
