### ISSUE TITLE
kube-router initContainer pod gets stuck under rktnetes

### ISSUE THREAD

**Issue by t3hmrman** [cloudnativelabs/kube-router#449]
kubernetes: `v1.10.2`
kube-router: `v0.2.0-beta.6`
rkt:
```
rkt Version: 1.29.0
appc Version: 0.8.11
Go Version: go1.9.4
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```

While getting a new cluster up and running with `rkt` and Kubernetes `1.10.2`, I found that the `kube-router` pod would get stuck initializing, with the following errors showing up in the `kubelet` systemd logs:

```
May 24 18:24:10 localhost kubelet[8153]: W0524 18:24:10.386751    8153 rkt.go:2513] networkNamespace: failed to parse pod from file /run/systemd/system/k8s_f647491b-a532-4023-9161-c9030759f459.service
May 24 18:24:10 localhost kubelet[8153]: W0524 18:24:10.387796    8153 rkt.go:2517] rkt: NetworkPlugin cni failed on the status hook for pod "kube-router-z9j6n_kube-system": Unexpected command output nsenter: reassociate to namespace 'ns/net' failed: Invalid argument
May 24 18:24:10 localhost kubelet[8153]:  with error: exit status 1
```
I was using [`kubeadm-kuberouter-all-features.yaml`](https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter-all-features.yaml) resource definition(s).

**Workaround**

- Insert the expected `kube-router` configuration yourself in `/etc/cni/net.d/10-kuberouter.conf` (you can look at the `ConfigMap` contents)
- Remove the `initContainer` (and associated `ConfigMap`, volume mounts, etc)

I think the issue *might* be related to the `initContainer` not having enough privileges when handled by `rkt` (as opposed to `containerd` which I was using before). it might be the case that `rkt`users must always do this step (assuming privileged `initContainer`s aren't a thing)

**Comment by aauren** [comment]
Closing as stale.
