### ISSUE TITLE
help: not sure if kube-router support multi-cidrs in ipam?

### ISSUE THREAD

**Issue by jmzwcn** [cloudnativelabs/kube-router#454]
question: not sure if kube-router support multi-cidrs in ipam?

e.g: 
"subnets": ["10.0.0.0/24", "20.0.0.0/16"]

similar to calico:
```json
{
    "name": "any_name",
    "cniVersion": "0.1.0",
    "type": "calico",
    "ipam": {
        "type": "calico-ipam",
        "ipv4_pools": ["10.0.0.0/24", "20.0.0.0/16"]
    }
}
```
Thanks for your any reply or advice in advance.

**Comment by murali-reddy** [comment]
@jmzwcn sorry about the delayed response. 

Kube-router does not actually do any IPAM. So it relies on kube-controller-managet to allocate CIDR's for the nodes from the subnet specified through `--pod-network-cidr`. With in the node uses `host-local` CNI IPAM plugin for IP allocation to the pods.

**Comment by shufanhao** [comment]
> @jmzwcn sorry about the delayed response.
> 
> Kube-router does not actually do any IPAM. So it relies on kube-controller-managet to allocate CIDR's for the nodes from the subnet specified through `--pod-network-cidr`. With in the node uses `host-local` CNI IPAM plugin for IP allocation to the pods.

As we know, host-local ipam plugin support specific subnet not podCIDR,  but I try it for kube-router, find it doesn't support. Could you help me to confirm it ?  
```
               "type": "host-local",
		"ranges": [
			[
				{
					"subnet": "10.10.0.0/16",
					"rangeStart": "10.10.1.20",
					"rangeEnd": "10.10.3.50",
					"gateway": "10.10.0.254"
				}
			]
		],
```

**Comment by aauren** [comment]
Closing as stale.
