### ISSUE TITLE
Improve Kops integration

### ISSUE THREAD

**Issue by aleerizw** [cloudnativelabs/kube-router#456]
At the moment, kube-router is not configurable at all in kops. Several feature like health check, hostport support, cli options are not configurable. It would be nice if support can be added for these features.

**Comment by roffe** [comment]
Hi @aleerizw all of these options are configurable in a Kops cluster. However it requires you to create a local manifest and replace the Daemonset Kops deploys after the cluster is started.

I see the benefits of being able to customize this at the deploy, However this is on Kops end and currently there is not much ways to interact with the addon manifests it deploys

https://github.com/kubernetes/kops/blob/master/docs/addon_manager.md

**Comment by aleerizw** [comment]
I the health check and the metrics port to the existing manifest:https://github.com/kubernetes/kops/pull/5426

**Comment by aauren** [comment]
Closing as stale
