### ISSUE TITLE
not cleaning up iptables -t nat rules

### ISSUE THREAD

**Issue by MarkDeckert** [cloudnativelabs/kube-router#464]
I have Kube-Router running with all features enabled (no kube-proxy).  If I drain and delete a node, ipvsadm and iptables shows a bunch of leftover rules.  When I rejoin the node to the cluster, Kube-Router doesn't seem to be cleaning up all those leftover rules and it's causing weird issues.

I had to manually clean up the nat rules (ie iptables -t nat -F)

This specifically was causing weird issues with Network Policies and blocked pod to pod networking across nodes for one deployment.  Some other deployments were fine.  Running kube-router in cleanup mode prior to rejoin didn't fix it.  Incrementally trying iptables -F and -X and ipvsadm -C also prior to rejoin didn't help.  Finally after running iptables -t nat -F, the network policy is functioning correctly again.

I was able duplicate the issue again by creating new node or even same node and drain/delete/rejoin/redeploy.  This leads me to believe Kube-Router is creating nat table rules and then not cleaning them up at start or via cleanup mode.  I've searched the repository and all the cleanup code appears to only run against the filter table.  Not sure if this is something that needs to be added?  I can make an attempt at a PR, or am I missing something?

**Comment by murali-reddy** [comment]
> Running kube-router in cleanup mode prior to rejoin didn't fix it. 

there is a [clean up performed](https://github.com/cloudnativelabs/kube-router/blob/master/pkg/cmd/kube-router.go#L64-L73) by all controllers but as an explicit step. Please see if there is a missing iptable configuration to NAT table that is not getting cleaned up.

```go
// CleanupConfigAndExit performs Cleanup on all three controllers
func CleanupConfigAndExit() {
	npc := netpol.NetworkPolicyController{}
	npc.Cleanup()

	nsc := proxy.NetworkServicesController{}
	nsc.Cleanup()

	nrc := routing.NetworkRoutingController{}
	nrc.Cleanup()
}
```

> Not sure if this is something that needs to be added? I can make an attempt at a PR, or am I missing something?

I wonder even if its really kube-router should do clean-up on first start. It might be possible many users may be adding their deployment specific configuration in iptables etc. I would imagine if a node is getting decommissioned with intent to be reused then should not that node be wiped out properly. 

Anyway to me clean approach would be fix missing cleanup in `CleanupConfigAndExit` and use it as part of your node decommissioning scripts.

**Comment by MarkDeckert** [comment]
Perhaps it shouldn't cleanup on start for the reasons you mentioned.  But it seems like it should be able to correct the discrepancy later during one of its normal syncs.  This would fall in line with the "self healing" kubernetes ideal.

I can think of a number of situations why one might drain and delete a node and then re-join it, without completely wiping it.  It could be a step in investigating or troubleshooting another problem, or some kind of maintenance.  It could be a bare metal server that's being temporarily removed from the cluster for some physical reason.  There wouldn't necessarily always be a desire to completely rebuild.

It appears the explicit cleanup functions for the "filter" table only match chains with names related to kube-router.  eg: https://github.com/cloudnativelabs/kube-router/blob/7c21815b43eed0b9270b5ee85c722f453fd26722/pkg/controllers/netpol/network_policy_controller.go#L1361

It should be possible to add similar logic to only cleanup "nat" table chains identified by name.  Not sure yet which ones that would be.  I'll continue to investigate.

**Comment by MarkDeckert** [comment]
After quite a bit of testing I believe the initial problem was caused by left-overs from a previous kube-proxy daemonset.  It appears that kube-proxy can leave "time-bombs" if it's able to start up and create iptables rules.  These leftover rules often don't have any effect until much later, depending on how dynamic the cluster is.  At that point it's so late after the initial cause that it can be hard to identify which rules are causing issues.  I'm closing this for now.
