### ISSUE TITLE
IPv6: Unable to get subnet of node IP

### ISSUE THREAD

**Issue by pmichali** [cloudnativelabs/kube-router#470]
Trying to bring up three node cluster with IPv6 using bridge plugin, and then switch over to using kube-router, instead of kube-proxy.

When applying the kuberouter-all-features.yaml, I see kube-router in a crash loop, with this error message:

I0619 16:14:29.935769       1 kube-router.go:186] Running /usr/local/bin/kube-router version v0.2.0-beta.7, built on 2018-06-08T09:34:34+0000, go1.8.7
I0619 16:14:30.549949       1 network_policy_controller.go:125] Starting network policy controller
Failed to run kube-router: Failed to create network routing controller: Failed find the subnet of the node IP and interface onwhich its configured: Failed to find interface with specified node ip

Looking at the code, the error occurs in pkg/controllers/routing/utils.go getNodeSubnet(), where it looks like it is filtering on IPV4 only addresses, and the nodeIP is IPv6:

```
      addresses, err := netlink.AddrList(link, netlink.FAMILY_V4)

```

**Comment by roffe** [comment]
We do currently not support IPv6, any PR's assisting in that work is greatly appreciated.

https://github.com/cloudnativelabs/kube-router/issues/307

**Comment by pmichali** [comment]
Is there already an issue for IPv6 support? How does one report problems seen, when trying IPv6?

**Comment by pmichali** [comment]
OK, so should problems seen with IPv6 use, be reported under issue #307? I'm just trying to capture a specific problem seen.
