### ISSUE TITLE
NetworkPolicy: Support including both podSelector and namespaceSelector in a NetworkPolicyPeer

### ISSUE THREAD

**Issue by voidengineer** [cloudnativelabs/kube-router#475]
Hi,

Kubernetes 1.11 allows including both podSelector and namespaceSelector in a NetworkPolicyPeer (see PR https://github.com/kubernetes/kubernetes/pull/60452 and issue https://github.com/kubernetes/kubernetes/issues/58637).

Are there any changes required in kube-router to support this?

**Comment by johanot** [comment]
Yes, changes are required.

The network_policy_controller currently assumes that the policy peers have _either_ namespaceSelector or podSelector. I'm working on a PR.

**Comment by johanot** [comment]
@murali-reddy @voidengineer When you have time, let me know what you think of: https://github.com/cloudnativelabs/kube-router/pull/479

**Comment by voidengineer** [comment]
LGTM

**Comment by murali-reddy** [comment]
Fixed in https://github.com/cloudnativelabs/kube-router/pull/479
