### ISSUE TITLE
New chains are not generated, irrespective of the added syncVersion 

### ISSUE THREAD

**Issue by johanot** [cloudnativelabs/kube-router#477]
The fix for #461 introduced a syncVersion which is appended to the components that make up the unique firewall and policy chain names. Unfortunately, a int64 to string conversion has been implemented incorrectly such that chain names are always the same.

Since the ClearChain step has been removed, this mistake causes old chain rules never to get cleaned up, and thus changes to existing network policies never get reconciled correctly.

**Comment by aauren** [comment]
This appears to have been fixed in #477 please re-open if this is not the case.
