### ISSUE TITLE
Allow setting next-hop when multiple peer routers are defined

### ISSUE THREAD

**Issue by jdconti** [cloudnativelabs/kube-router#480]
As discussed on [#kube-router slack.](https://kubernetes.slack.com/archives/C8DCQGTSB/p1530560213000411)  We should be able to define the next-hop for a given peer router in the `--peer-router-ips` list or `kube-router.io/peer.ips` annotation.  

One possible use-case for this would be for resiliency:
```
NodeA → Interface1 (10.0.1.1) → Router (10.1.0.1)
    ↓                            ↑                   
     →  Interface2 (10.0.2.1) →  ↑
```
\* The above assumes the same ASN per interface with all other attributes the same except next-hop

**Comment by murali-reddy** [comment]
thanks to @Thoro actually, i just hijacked his old PR #295
