### ISSUE TITLE
Documentation clarification regarding --allow-privileged=true ?

### ISSUE THREAD

**Issue by ieugen** [cloudnativelabs/kube-router#482]
Hi, 

From the docs at [2] it mentions that:

> If you choose to run kube-router as daemonset, then both kube-apiserver and kubelet must be run with --allow-privileged=true option 

Is this still valid? If yes, it would be great to have some instructions on how to do/check that. 
If this is not valid in recent Kubernetes versions, then a link to docs + mention is great. 

I can make a PR for the docs i this is  

> From Kubernetes v1.1, any container in a pod can enable privileged mode, using the privileged flag on the SecurityContext of the container spec. 

[1] https://kubernetes.io/docs/concepts/workloads/pods/pod/#privileged-mode-for-pod-containers
[2] https://github.com/cloudnativelabs/kube-router/blob/master/docs/generic.md#configuring-the-kubelet

Thanks,

**Comment by xanonid** [comment]
IMHO, instead of using  privileged:true, only the required capabilities (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#capabilities-v1-core  ) like NET_ADMIN and probably some few others should be used and documented.

**Comment by voidengineer** [comment]
Can anyone tell which capabilities would be needed?

**Comment by aauren** [comment]
Closing as stale.
