### ISSUE TITLE
Performace regression due to #433

### ISSUE THREAD

**Issue by aleerizw** [cloudnativelabs/kube-router#486]
I tired to upgrade kube-router from version  v0.1.0  to v0.2.0-beta.6 and I noticed that the kube-router pod is using a lot more CPU, from ~10 % peak to more than 125% continuously.

One big difference that I saw was services sync takes longer than before:

For v0.2.0:
```
kube-router-7jrnv kube-router I0705 10:52:25.564539       1 bgp_peers.go:33] Syncing BGP peers for the node took 16.273637ms
kube-router-7jrnv kube-router I0705 10:52:32.059363       1 network_services_controller.go:505] sync ipvs services took 7.80255427s
kube-router-7jrnv kube-router I0705 10:52:39.673070       1 network_services_controller.go:505] sync ipvs services took 7.575286219s
kube-router-7jrnv kube-router I0705 10:52:47.297617       1 network_services_controller.go:505] sync ipvs services took 7.599028427s
```

And for v0.1.0
```
kube-router-d99mm kube-router I0705 10:49:37.598236       1 network_services_controller.go:310] sync ipvs services took 702.138909ms
kube-router-d99mm kube-router I0705 10:49:37.613382       1 network_routes_controller.go:1059] Syncing BGP peers for the node took 11.84567ms
kube-router-d99mm kube-router I0705 10:49:38.238651       1 network_services_controller.go:310] sync ipvs services took 635.746068ms
kube-router-d99mm kube-router I0705 10:49:38.869822       1 network_services_controller.go:310] sync ipvs services took 627.011078ms
kube-router-d99mm kube-router I0705 10:49:39.505315       1 network_services_controller.go:310] sync ipvs services took 631.339836ms

```

We do have a lot of services ~3k, but both of these pods were running on the same cluster and with the same configuration. The only thing different was the version.

I did some digging, the source of the delay seems to be the `ip route replace` command: https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/proxy/network_services_controller.go#L130

Which was added as part of https://github.com/cloudnativelabs/kube-router/pull/433

The command gets called for each service by the syncIpvsServices func and since we have a lot of services it take a pretty long time. I am not sure if its because of the exec.Command or something else.

I made a custom build with the route replace disabled in syncIpvsservices  on master i.e.
`err := nsc.ln.ipAddrAdd(dummyVipInterface, svc.clusterIP.String(), false)` instead of https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/proxy/network_services_controller.go#L549
and this solved the performance regression.

**Comment by roffe** [comment]
@aleerizw that route replace command is also the command that sets up up the initial route, if you deploy this code to existing nodes not much will break since the routes are already there, if you run it on a new fresh node the services will not be routed correctly

I created  a PR and added a function to check if the ip already is on the interface, and if not, don't run the command at all. This call should be much cheaper than shelling out to run the route replace command

**Comment by roffe** [comment]
I got a image built for the PR @ `roffe/kube-router-git:issue-486-1`

**Comment by roffe** [comment]
Made new build after some code cleanup `roffe/kube-router-git:issue-486-2`

**Comment by roffe** [comment]
@murali-reddy i also implemented a debounce function so sync() can't be called more than every 100ms by the event handler. The normal sync is still executed according to syncPeriode

**Comment by aauren** [comment]
Closing as stale, also it looks like this has been resolved via some of the comments above.
