### ISSUE TITLE
Dashboard not working out of the box 10.96.0.1:443: getsockopt: no route to host

### ISSUE THREAD

**Issue by mgcrea** [cloudnativelabs/kube-router#487]
Not sure if I have missed something but after having tried flannel with a very basic `nginx-ingress` based setup, I wanted to give kube-router a go:

after un full cluster reset:

```
kubeadm init --pod-network-cidr=10.244.0.0/16
kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
```

went with the `kube-router providing pod networking and network policy` only to try, (if I understood correctly you have the choice between a light install and full-fledged install.

```
KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
```

If I try to spin up the dashboard:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```

I get a crash loop:

```
$ kubectl logs kubernetes-dashboard-6948bdb78-vr62c -n kube-system
2018/07/09 23:17:34 Starting overwatch
2018/07/09 23:17:34 Using in-cluster config to connect to apiserver
2018/07/09 23:17:34 Using service account token for csrf signing
2018/07/09 23:17:34 No request provided. Skipping authorization
2018/07/09 23:17:37 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: getsockopt: no route to host
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ
```

Same thing with `ingress-nginx`.

- Was the `pod-network-cidr` parameter wrong? In [your docs](https://github.com/cloudnativelabs/kube-router/blob/master/docs/kubeadm.md) you don't specify it.

- Should I go for the full install (with service proxy)?

Thanks!

**Comment by anhcq151** [comment]
I'm having same issue. In my case, I give kube-router the first try in spinning up my first k8s cluster.

**Comment by aauren** [comment]
Closing as stale, more information about the cluster state would need to be known to triage this.

I was able to execute the exact same instructions on an AWS EC2 instance from scratch with kube-router using the existing state of kube-router. It's been a while, so it's possible this was an issue at the point in time in the project when this issue was filed.
