### ISSUE TITLE
WaitForCacheSync method is too slow to lead to unhealthy judgment

### ISSUE THREAD

**Issue by jimmy-zh** [cloudnativelabs/kube-router#489]
In some cases, when the WaitForCacheSync method is too slow and the --iptables-sync-period value is too small,the CheckHealth method will return false, which will eventually cause k8s to restart kube-router circularly. 
In fact,the CheckHealth method should take into account the initialization process including WaitForCacheSync.

**Comment by murali-reddy** [comment]
@jimmy-zh thanks for your analysis
default value for `-iptables-sync-period` is 5min, at what time values you are seeing this behaviour?

cc @roffe

**Comment by roffe** [comment]
@jimmy-zh Which version of kube router are you running there was some big changes in the healthcheck system not to long ago, also as @murali-reddy mentioned, What sync period are you running, the default 5 min?

**Comment by andrewsykim** [comment]
Slow `WaitForCacheSync` can also mean you're API server has too much load.

**Comment by jimmy-zh** [comment]
@murali-reddy @roffe @andrewsykim thanks for your reply

kube-router version: 57f4eea2f45cd574da785c5ad2ab1806f43063de
`-iptables-sync-period`=1s

Explanation:
1. The `WaitForCacheSync` method may last for a few seconds like 2s to 20s when the k8s cluster has many resource objects. This situation should be foreseen.

2. In order to make the synchronization process more real-time, `-iptables-sync-period` may be set to a small value like 1s.

3. The main logic of health check is:
```
//RunCheck starts the HealthController's check
func (hc *HealthController) RunCheck(healthChan <-chan *ControllerHeartbeat, stopCh <-chan struct{}, wg *sync.WaitGroup) error {
	t := time.NewTicker(5000 * time.Millisecond)
	defer wg.Done()
	for {
		select {
		case <-stopCh:
			glog.Infof("Shutting down HealthController RunCheck")
			return nil
		case heartbeat := <-healthChan:
			hc.HandleHeartbeat(heartbeat)
		case <-t.C:
			glog.V(4).Info("Health controller tick")
		}
		hc.Status.Healthy = hc.CheckHealth()
	}
}
```
```
graceTime := time.Duration(1500 * time.Millisecond)
	if hc.Config.RunFirewall {
		if time.Since(hc.Status.NetworkPolicyControllerAlive) > hc.Config.IPTablesSyncPeriod+hc.Status.NetworkPolicyControllerAliveTTL+graceTime {
			glog.Error("Network Policy Controller heartbeat missed")
			health = false
		}
	}
```
If the `WaitForCacheSync` time is 8s, the first time the health check is triggered, `time.Since(hc.Status.NetworkPolicyControllerAlive)` will be approximately equal to 5s,  `hc.Config.IPTablesSyncPeriod` is 1s and `hc.Status.NetworkPolicyControllerAliveTTL` is 0, this will lead to unhealthy judgement.

So my suggestions are:
1. Split health check into web server startup and actual health check logic. The former is before `WaitForCacheSync` and the latter is after `WaitForCacheSync`.

2. The `NetworkPolicyControllerAliveTTL` is intended to measure the first iptable's synchronization, this should not include the time of `WaitForCacheSync`. So the `NetworkPolicyControllerAlive` should be initialized after `WaitForCacheSync`.

3. The `WaitForCacheSync` method should have its own timeout control. The timeout value can be provided by a command line option.

I submitted a PR to fix this problem.

**Comment by jimmy-zh** [comment]
@murali-reddy @roffe 
A new PR #498. Please check it.

**Comment by murali-reddy** [comment]
thanks @jimmy-zh we will check out.

**Comment by roffe** [comment]
Thank you @jimmy-zh !
