### ISSUE TITLE
/var/lib/kube-router/kubeconfig: is a directory

### ISSUE THREAD

**Issue by mancosun** [cloudnativelabs/kube-router#491]
Hi  ：
     when deploy kube-router use"kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kube-router-all-service-daemonset.yaml"
got this logs:"Failed to parse kube-router config: Failed to build configuration from CLI: Error loading config file "/var/lib/kube-router/kubeconfig": read /var/lib/kube-router/kubeconfig: is a directory"

pls

**Comment by murali-reddy** [comment]
@mancosun Were you able to resolve the issue?
