### ISSUE TITLE
Allow for use of non-standard BGP-port internally and externally

### ISSUE THREAD

**Issue by johanot** [cloudnativelabs/kube-router#492]
### Usage Scenario

I have a router box that runs bird for peering with other parties outside the cluster. I want the same server to peer with my k8s cluster using kube-router. Thus, I get a socket ip:port clash. 

Bird and other BGP clients/servers support specifying a custom remote and listening port for BGP. 

### Request

It should be possible to select a custom listening port for the BGP-server as well as a custom remote port for external BGP peers.

### Implementation

I will soon have a PR ready for discussion.

**Comment by aauren** [comment]
Closed through #493
