### ISSUE TITLE
kube-bridge's IP didn't change after kubectl delete node and then restart kubelet

### ISSUE THREAD

**Issue by polym** [cloudnativelabs/kube-router#496]
Kube-router was running in DaemonSet pod on the node. 

After `kubectl delete node NODE_NAME`, all pods on the node was deleted by kubelet, and all data related with this node was deleted by api-server (or other component). At this moment, 

```
$ ip addr
9: kube-dummy-if: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether d2:c5:38:08:6c:e8 brd ff:ff:ff:ff:ff:ff
    inet 10.96.0.1/32 brd 10.96.0.1 scope link kube-dummy-if
       valid_lft forever preferred_lft forever
15349: kube-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 0a:58:0a:f4:08:01 brd ff:ff:ff:ff:ff:ff
    inet 10.244.7.1/24 scope global kube-bridge
       valid_lft forever preferred_lft forever
    inet6 fe80::30ba:8ff:fe8f:93fc/64 scope link
       valid_lft forever preferred_lft forever
```

Then, restarted kubelet to join kubernetes cluster again, and kube-router pod started up. I found CIDR in 10-kuberouter.conf was changed, but kube-bridge was using old CIDR (10.244.7.1/24)

```
{"bridge":"kube-bridge","ipam":{"subnet":"10.244.8.0/24","type":"host-local"},"isDefaultGateway":true,"name":"kubernetes","type":"bridge"}
```

In this scenario, pod can't be deployed to the node any more, and raise some informations.

![image](https://user-images.githubusercontent.com/2860926/43298357-3592d7fc-9188-11e8-9627-cb2332f1f0d0.png)

```
$ kube-router -V
Running kube-router version v0.2.0-beta.9, built on 2018-07-12T20:56:27+0000, go1.8.7
```

**Comment by murali-reddy** [comment]
@polym thanks for reporting this issue. Kube-router underneath uses `bridge` CNI plug-in, i guess bridge CNI must be failing as it has conflicting situation here.

I will try to add at least a check and throw error if bridge interface has IP different from what is expected.

**Comment by danbeaulieu** [comment]
I just ran in to this as well. I removed a node from the cluster by kubeadm reset and kubectl delete node. Confirmed everything was cleaned up including /etc/cni/net.d. Then reran my kubeadm join to rejoin the cluster and pods are stuck with the same error as @polym.

Is there a workaround?

**Comment by roffe** [comment]
Hi @danbeaulieu delete the bridge interface on the node as a part of your cleaning up so it's gone before kube-router starts

**Comment by acloudiator** [comment]
I ran into the same issue. 
But in my case, I deleted the offending IP from `kube-bridge` and checked again, the correct (new) IP was assigned to it. Things are working now.

**Comment by RaveNoX** [comment]
Please see by comment in other issue https://github.com/cloudnativelabs/kube-router/issues/689#issuecomment-475174187

It can help you to fix this

**Comment by aauren** [comment]
Closing as stale. This has more to do with CNI plugins not cleaning up previously created bridges.
