### ISSUE TITLE
Remove hardcoded pre-run checks

### ISSUE THREAD

**Issue by vladimirtiukhtin** [cloudnativelabs/kube-router#500]
Hello

Currently in kube-router.go
```
	if os.Geteuid() != 0 {
		return fmt.Errorf("kube-router needs to be run with privileges to execute iptables, ipset and configure ipvs")
	}
```

I prefer to grant kube-router more capabilities than running it under root unconditionally. Thanks

**Comment by murali-reddy** [comment]
Sure, make sense. This check expects kube-router to be too permissive.

**Comment by aauren** [comment]
Closing as stale. If someone has an interest in getting this going, a PR would still definitely be welcome.
