### ISSUE TITLE
Service ClusterIP Accessible Outside Cluster

### ISSUE THREAD

**Issue by Queuecumber** [cloudnativelabs/kube-router#501]
I am currently working with kubernetes on a single node cluster for evaluation. My LAN uses the Class A network, (10.0.0.0/8) and since the cluster should support a large number of pods/services, it also uses the Class A network. I noticed today that I can access services by their cluster IP from any machine in my LAN (pods, however, can only be accessed from inside the cluster).

Is this expected if the cluster and LAN share the same IP ranges and is there any way to restrict it? 

Additionally, if I set an explicit externalIP on my services, it seems like it needs to be from the service cidr or it won't get assigned. For me this isn't an issue since my LAN and my cluster both use Class A (and apparently I don't even need externalIP), but for a different setup, for example LAN on Class C, would the Class A addresses be routable from the LAN?

How is externalIP supposed to work in that case? Or is it simply not up to kube-router and some other software needs to make sure that externalIP is routed to the clusterIP of the service?

**Comment by murali-reddy** [comment]
>  I noticed today that I can access services by their cluster IP from any machine in my LAN (pods, however, can only be accessed from inside the cluster).

No this is not expected. Cluster IP's are assigned to a dummy interface on each of the cluster nodes, but they don't respond to ARP requests. They can only be accessed from with in the node. Can you verify when you access cluster IP who is responding?

> Is this expected if the cluster and LAN share the same IP ranges and is there any way to restrict it?

You are free to choose any CIDR for cluster IP range.

> Additionally, if I set an explicit externalIP on my services, it seems like it needs to be from the service cidr or it won't get assigned.

No, it does not have to from service CIDR range. What do yo mean by it wont get assigned. 

> How is externalIP supposed to work in that case? 

You specify intended IP as external IP in the Kubernetes service object. But traffic for the external IP need to be attracted towards the nodes. This is where kube-router comes into play. Kube-router advertised configured external IP's to the upstream routers. Routers are expected to ECMP load-balance traffic to external IP.

Here is a quick demo of how external IP works with kube-router 

https://asciinema.org/a/145163

**Comment by Queuecumber** [comment]
I'm fairly certain that the single-node cluster is who is responding, but I can double check it next week when I have the cluster in front of me again. I can see a veth device that has the service cluster IPs assigned to it, when my externalIP is from the service CIDR range, I can see it gets assigned to this interface just as the clusterIPs are. When my externalIP is from another range, I don't see the IP getting assigned to that interface, and I can't access the service using that address. I just use `ip addr` on the node to check.
