### ISSUE TITLE
Why initContainers in the daemonset manifest?

### ISSUE THREAD

**Issue by cjbottaro** [cloudnativelabs/kube-router#523]
I'm following the instructions for being able to use hostPort, and I'm wondering why the initContainer that copies the configmap entry into some dir.

Why not just directly mount the configmap entry to the location that kube-router expects? It would make the manifest a lot more simple.

**Comment by murali-reddy** [comment]
Init containers create the cni conf file only if it does not exist. If there is a file already (because it was created already by kube-router) it is not overwritten because, kube-router modifies the CNI conf file to includer pod CIDR's allocated to the node by `kube-controller-manager`. Once the kube-router pods are running you can see in the cni conf file for pod CIDR details.

so basically its not static content.

**Comment by cjbottaro** [comment]
Ahh, I see, thank you for the explanation.

For posterity, kops doesn't setup kube-router to work with hostPort; here are the patches I used:

`kube-router-cfg-patch.yaml`:
```
data:
  cni-conf.json: |-
    {
      "cniVersion":"0.3.0",
      "name":"kube-router-net",
      "plugins":[
        {
          "name":"kubernetes",
          "type":"bridge",
          "bridge":"kube-bridge",
          "isDefaultGateway":true,
          "ipam":{
            "type":"host-local"
          }
        },
        {
          "type":"portmap",
          "capabilities":{
            "snat":true,
            "portMappings":true
          }
        }
      ]
    }
```

`kube-router-patch.yaml`:
```
spec:
  template:
    spec:
      containers:
      - name: kube-router
        env:
        - name: KUBE_ROUTER_CNI_CONF_FILE
          value: /etc/cni/net.d/10-kuberouter.conflist
        image: cloudnativelabs/kube-router:v0.1.0
      initContainers:
      - name: install-cni
        command:
        - /bin/sh
        - -c
        - set -e -x; if [ ! -f /etc/cni/net.d/10-kuberouter.conflist ]; then TMP=/etc/cni/net.d/.tmp-kuberouter-cfg;
          cp /etc/kube-router/cni-conf.json ${TMP}; mv ${TMP} /etc/cni/net.d/10-kuberouter.conflist;
          fi
```

Then simply...
```
kubectl patch configmap kube-router-cfg -n kube-system -p "$(cat kube-router-cfg-patch.yaml)"
kubectl patch daemonset kube-router -n kube-system -p "$(cat kube-router-patch.yaml)"
```
