### ISSUE TITLE
Possible for ALB to address pods directly?

### ISSUE THREAD

**Issue by cjbottaro** [cloudnativelabs/kube-router#525]
Sorry, networking is not my strong point, but going to try to describe this as best I can...

I recently switched from amazon-vpc-cni to kube-router and it doesn't work with the alb-ingress-controller in "ip" mode. I think what it boils down to is that in "ip" mode, the ALB needs to be able to address the pods directly by their Koob ip address.

Is it possible to do this with kube-router?

Thanks for the help!

**Comment by murali-reddy** [comment]
@cjbottaro I don't think its possible to use direct POD ip's.  `amazon-vpc-cni` might put pod's in the VPC subnet so it may be possible.

You should be able to use ALB ingress with NodePort's?

**Comment by roffe** [comment]
NodePorts work fine with ALB and the build in support from Kubernetes when using Kube-router

**Comment by cjbottaro** [comment]
Yes, alb-ingress-controller works fine with NodePort and kube-router, but my issue is that we have hundreds of nodes, but only a few of them (properly labeled) will have the pods that are running the NodePort service. It just seem massively inefficient.

I've opened up an issue with alb-ingress-controller to only target nodes with a specific label, specified by an annotation, but no one has answered. I guess it's time for at PR.

Thank you for your answers.
