### ISSUE TITLE
Support ipv4/ipv6 dual stack for external traffic with ipv6 prefix

### ISSUE THREAD

**Issue by uablrek** [cloudnativelabs/kube-router#534]
## Support ipv4/ipv6 dual stack for external traffic

There is currently a Kubernetes Enhancement Proposal ([KEP](https://github.com/leblancd/community/blob/dual-stack-kep/keps/sig-network/0013-20180612-ipv4-ipv6-dual-stack.md)) for dual stack in Kubernetes. The intention is to make Kubernetes dual stack aware while still keeping compatibility. This is of course very hard considering internal structures, APIs, CLIs, upgrade and possibly migration to dual stack and I think GA for dual stack in Kubernetes will take a long time.

For many Kubernetes deployments the important issue is not the protocol used internally but the addresses accesible from the outside world. I propose an interim solution to support dual stack for external traffic using a ipv6 `prefix` ([rfc6052](https://tools.ietf.org/html/rfc6052)). For instance;

```
2000::1:192.168.1.4
```

A big problem with dual stack in k8s is to make the ipv6 addresses known, structures must extend etc. But with an ipv6 prefix it becomes trivial to derive the ipv6 address from ipv4 addresses.

I propose a new option to `kube-router`;
```
kube-router --ipv6-prefix=2000::1:0:0/96 ...
```
When specified the prefix is used to configure for both ipv4 and ipv6 access and support dual stack.

### CNI/ipam

First the CNI/ipam must support dual stack. The first 2 goals in the KEP above are;

 * Pod Connectivity: IPv4-to-IPv4 and IPv6-to-IPv6 access between pods

 * External Server Access: IPv4-to-IPv4 and IPv6-to-IPv6 access from pods to external servers

For traffic these affect the CNI/ipam only if an ipv6 prefix is used. They are be implemented without affecting k8s in any way.

I have made a ([feature-request](https://github.com/containernetworking/plugins/issues/179)) to ipam host-local for support for ipv6 prefix. To add support is quite simple (I have done is locally) but it may be hard to find a way that fit good enough to the existing program structure to be accepted.

The function needed in the `kube-router` CNI is to setup BGP for the ipv6 addresses as well as for ipv4. GoBGP supports ipv6 and applying the prefix and handle ipv6 addresses in the same way as ipv4 should not be too hard.

There is a **Non-Goal** in the KEP above;

* External load balancers that rely on Kubernetes services for load balancing functionality will only work with the IP family that matches the IP family of the cluster's service CIDR.

This implies that some load balancers bypasses the k8s load-balancing (kube-proxy/kube-router) entirely. With the CNI/ipam for ipv6 prefix in place those load balancers can support dual stack immediately.

### Kubernetes proxy support

I want to support dual stack (with ipv6 prefix) also for external services. This includes services with;

 * externalIPs
 * loadBalancerIP
 * NodePort

The externalIPs and loadBalancerIP should also be announced to external routers so the "router" function in `kube-router` should also be extended.

#### Use case; externalIPs

In this example the service specifies `externalIPs`;

```
apiVersion: v1
kind: Service
metadata:
  name: someapp
spec:
  selector:
    app: someapp
  ports:
  - port: 80
  externalIPs:
  - 22.22.22.22
```

The ipv4 address `22.22.22.22` is exposed externally and with an ipv6 prefix of `2000::1:0:0/96` the corresponding ipv6 address becomes; `2000::1:22.22.22.22`. The ipv6 prefix should be a segment of an ipv6 prefix owned by the operator which makes the derived ipv6 externalIPs valid Global Unicast Addresses (GUA). As a side note; all POD addresses formed with the ipv6 prefix will also be GUA's which makes outgoing ipv6 connects very simple (only routing).

This is what `kube-router` does today for ipv4 (simplified!);

 * Watch service objects for `externalIPs`
 * Find the endpoint addresses for the service
 * Setup rules in `ipvs` to loadbalance traffic to the `externalIPs` between the endpoint addresses
 * Some other things like; `iptables` rules e.g. for NAT, assign the address to a dummy interface, etc. (glossed over in this example)
 * Insert the externalIPs in the goBGP RIB
 
To implement the dual stack function the `kube-router` only needs to pre-pend the ipv6 prefix to the externalIPs and endpoint addresses and repeat the three last items for ipv6. The ipv6 operations are
essentially the same as for ipv4 but with different addresses so the implementation should not be too hard.

### To consider

[Dns64](https://coredns.io/explugins/dns64/) plugin for `CoreDNS` and `NAT64` with [tayga](http://www.litech.org/tayga/) can be explored to provide transparent ipv4 access to the internet.

**Comment by uablrek** [comment]
### About future compatibility

The dual stack in k8s will preserve backward compatibility with the current ipv4-only configuration. Since this proposal does not assume anything else it can (in theory) live along side the "real" k8s dual stack forever.

It is of course desirable that `kube-router` supports the k8s dual stack and I see no contradicion.The k8s dual stack may get ipv6 addresses for pod's from independent ranges and the external addresses will be explicitly specified in service manuscripts. But the basic functions for dual stack support in `kube-router` will be the same as for this proposal, e.g. entries for both ipv4 and ipv6 must be hadled in iptables, ipset and ipvs.

The night mare story is that this proposal in some way prevents support for the k8s dual stack in the future, but I think it will actually make support for k8s dual stack easier.

And the important thing; this proposal makes it possible to support dual stack fast since k8s is not altered.

**Comment by uablrek** [comment]
I have a fast-test `host-local` that supports ipv6 prefix in https://github.com/Nordix/plugins branch "ipv6-prefix-test"

**Comment by Ulexus** [comment]
Issue bump:  dual stack support is now alpha as of k8s 1.16  (with significant fixes in 1.17)

**Comment by uablrek** [comment]
This issue has been made obsolete by the support for dual-stack in K8s. Closing...

**Comment by MihailKo** [comment]
@uablrek 

> This issue has been made obsolete by the support for dual-stack in K8s. Closing...

So, it means that is works now?
I would like to know how to configure kube-router to actually use dual stack.

**Comment by uablrek** [comment]
No, `kube-router` does not support dual-stack or ipv6. But the proposal in this issue was intended as a "gap-filler" until K8s had dual-stack support.

Now when K8s *has* dual-stack support `kube-router` should be updated to be conformant with K8s, and not as proposed in this issue.

Unfortunately I have no time to work with this even though I would like to because it has been decided that we will not use `kube-router`.

**Comment by MihailKo** [comment]
@uablrek Thanks for the reply.

**Comment by sfxworks** [comment]
https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#ipv4-ipv6-dual-stack-support

 In Kubernetes 1.21 dual-stack networking has graduated from alpha to beta, and is now enabled by default.
