### ISSUE TITLE
Pods Ips diferent from PodCIDR

### ISSUE THREAD

**Issue by brunovlucena** [cloudnativelabs/kube-router#537]
Hi all,

Does anyone have an idea why my pods are scheduled in wrong subnets? The kube-router seems to be working correctly but, the problem is that the kube-controller-manager assigns the pod-ips independent of the kube-router. However, i did not find where the controller is misconfigured. 

Extracted from Kubelet logs:

k8s4:
Sep 14 12:43:19 k8s4 kubelet[2887]: I0914 12:43:19.200164    2887 kubelet_network.go:73] Setting Pod CIDR:  -> 10.200.1.0/24

k8s1:
Sep 14 12:43:19 k8s1 kubelet[7497]: I0914 12:43:19.109519    7497 kubelet_network.go:73] Setting Pod CIDR:  -> 10.200.0.0/24

k8s:5
Sep 14 12:43:19 k8s5 kubelet[3190]: I0914 12:43:19.199141    3190 kuberuntime_manager.go:917] updating runtime config through cri with podcidr 10.200.2.0/24                                                       
Sep 14 12:43:19 k8s5 kubelet[3190]: I0914 12:43:19.199760    3190 kubelet_network.go:73] Setting Pod CIDR:  -> 10.200.2.0/24
Sep 14 12:44:51 k8s5 kubelet[3190]: I0914 12:44:51.268810    3190 kubelet.go:1837] SyncLoop (ADD, "api"): "kube-router-qgjz8_kube-system(353df51b-b80b-11e8-8a12-0cc47ae2583a)"

The seems to be normal and i don't get any other kind of update from the logs after a testing pod is scheduled.

Moreover, I am using TLS Bootstraping to connect the kubelets to the api.

I am using the following parameters:
K8S_CONTROLLER_MANAGER=--address=127.0.0.1 \
--cluster-cidr=10.200.0.0/16 \
--allocate-node-cidrs=true \
--cluster-name=test \
--kubeconfig=/etc/k8s/kube-controller-manager.kubeconfig \
--leader-elect=True \
--leader-elect-lease-duration=30s \
--leader-elect-renew-deadline=15s \
--feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true,SupportIPVSProxyMode=true,AdvancedAuditing=true \
--service-cluster-ip-range=10.0.0.0/16 \

K8S_CONTROLLER_MANAGER_TLS_BOOTSTRAP=--controllers=*,bootstrapsigner,tokencleaner \

K8S_CONTROLLER_MANAGER_SECURITY=--root-ca-file=/var/lib/k8s/ca.pem \
--use-service-account-credentials=True \
--service-account-private-key-file=/var/lib/k8s/service-accounts-key.pem \
--cluster-signing-cert-file=/var/lib/k8s/ca.pem \
--cluster-signing-key-file=/var/lib/k8s/ca-key.pem \

![screenshot from 2018-09-14 13-04-24](https://user-images.githubusercontent.com/20466126/45546817-c0531480-b81e-11e8-83a2-0f15caca656f.png)

**Comment by murali-reddy** [comment]
@brunovlucena how did you provision the cluster? Did you any provisioners like kubeadm?

Likely kubelet is not using CNI (in the case of kube-router kubelet should be using `bridge`, and `host-local` plugins)

Typically you need to pass the `--network-plugin=cni` for kubelet with additional information of `--cni-bin-dir=/opt/cni/bin` and `--cni-conf-dir=/etc/cni/net.d` 

Please try  `--network-plugin=cni` parameter to kubelet.

**Comment by brunovlucena** [comment]
I did not use kubeadm. I am configuring it from scratch. That said:

- the kube-router is modifying the file 10-kuberouter.conf correctly
![screenshot from 2018-09-14 13-59-53](https://user-images.githubusercontent.com/20466126/45549011-88e86600-b826-11e8-987d-54c20ac28fb7.png)

the cni plugins are there:
![screenshot from 2018-09-14 14-01-43](https://user-images.githubusercontent.com/20466126/45549082-c9e07a80-b826-11e8-929a-fdb5dee31954.png)

i did selected cni as network plugin:
![screenshot from 2018-09-14 14-02-50](https://user-images.githubusercontent.com/20466126/45549122-f2687480-b826-11e8-859d-665d5f2a030c.png)

**Comment by brunovlucena** [comment]
1) cluster is created from scratch (etcd's data deleted).
![screenshot from 2018-09-14 14-14-19](https://user-images.githubusercontent.com/20466126/45549612-adddd880-b828-11e8-887d-3fe4e98b23be.png)

2) after seconds the kube-bridge is set (according to the IP)
![screenshot from 2018-09-14 14-15-07](https://user-images.githubusercontent.com/20466126/45549682-e54c8500-b828-11e8-9509-866d1677342e.png)

**Comment by brunovlucena** [comment]
continuing...

![screenshot from 2018-09-14 14-28-13](https://user-images.githubusercontent.com/20466126/45550211-838d1a80-b82a-11e8-9280-faa5c25cfbd2.png)
![screenshot from 2018-09-14 14-28-36](https://user-images.githubusercontent.com/20466126/45550221-8982fb80-b82a-11e8-9f72-1dc5d9df3cf2.png)

**Comment by brunovlucena** [comment]
Update: So, I was using the following cni plugin version:
https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
which I downgraded to 0.6.0 and still does not work.

![screenshot from 2018-09-14 14-52-41](https://user-images.githubusercontent.com/20466126/45551340-dc11e700-b82d-11e8-907c-6def1042882c.png)

**Comment by murali-reddy** [comment]
Sorry, which pod's you are suspecting to have wrong IP addresses? I see all busy boxes got proper IP address from expected CIDR's?

**Comment by brunovlucena** [comment]
sorry, it seems to me quite clear.

in this example:

busybox-7fd544df89-k66tv   1/1       Running   0         5s        10.200.0.2   k8s4

{"bridge":"kube-bridge","ipam":{"subnet":"10.200.2.0/24","type":"host-local"},"isDefaultGateway":true,"name":"kubernetes","type":"bridge"}

default   busybox-7fd544df89-cddz6   1/1       Running   0         5s        10.200.1.2   k8s1
{"bridge":"kube-bridge","ipam":{"subnet":"10.200.0.0/24","type":"host-local"},"isDefaultGateway":true,"name":"kubernetes","type":"bridge"}

just look the routes. the kube-bridge's ip match the assigned ip, but the routes configured by kube-router are different

**Comment by brunovlucena** [comment]
update: if i don't pass the parameter it does not read the path. Is it a bug from k8s 1.11 ?

--cni-conf-dir string
  | The full path of the directory in which to search for CNI config files. Default: /etc/cni/net.d

**Comment by brunovlucena** [comment]
I was too fast... it is not the problem. I deleted the cluster and created again so the problem still persists... it was just a coincidence that matched. the assigments seem to be at random

**Comment by brunovlucena** [comment]
If i setup manualy networking as i supose it should be i receive an error from k8s

![screenshot from 2018-09-14 16-39-33](https://user-images.githubusercontent.com/20466126/45557044-061ed580-b83d-11e8-9ea2-f07b85a8c447.png)

![screenshot from 2018-09-14 16-40-31](https://user-images.githubusercontent.com/20466126/45557052-0a4af300-b83d-11e8-8058-e0ace0acfff3.png)

**Comment by murali-reddy** [comment]
Looks like you have nodes with configurations left over from previous deployments?

If you do deployment from scratch again, please ensure there is no `kube-bridge` interface, and CNI conf file.

May be you can try to delete the `kube-bridge` interface now and restart (kill the pod) kube-router pods?

**Comment by atibdialpad** [comment]
Hey, does the kube-router play a role in allocating ip addresses to pod ? I tried running kube-router with 'run_router = false' and the pod didn't get any IP. Is it possible to allocate pod ip without 'run_router = true' ?

**Comment by aauren** [comment]
No, kube-router doesn't play any role in allocating IP addresses to the pod, other than, by default, it looks up the pod-cidr for the node that was allocated but kube-controller-manager and configures the CNI plugin (which does provision the pod's IP address) with that CIDR.

Closing this as stale. Left over bridges can cause issues as Murali mentioned: https://github.com/cloudnativelabs/kube-router/issues/496
