### ISSUE TITLE
Pod-to-pod cross node connectivity flapping

### ISSUE THREAD

**Issue by ep4eg** [cloudnativelabs/kube-router#540]
I'm trying kube-router, but instantly got stuck with pod-to-pod cross node connectivity that apparently works, but not as I expect.

I have a very basic installation of k8s which is kubeadm+kube-router, 2 nodes (A and B) each node has pod-subnet, let's say 10.10.0.0/24 and 10.11.0.0/24, In the beginning, everything is fine, but time to time when I up some pods, I'm losing a connectivity from the node B to any pod on the other one (the bridge obtains the packages but nobody replies), but once I change the configuration of kube-bridge on the node A (something like 'brctl stp kube-bridge on', doesn't matter), everything instantly becomes fine, at the same time there is no issues with pod-to-pod communication inside a pod, pod2(10.11.0.222, which is on the node B) is accessible for pod1(10.10.0.222, which is on the node A).

**env**
CentOS 7.5.1804
Kernel 3.10.0-862.el7.x86_64

kubectl version --short
    Client Version: v1.11.2
    Server Version: v1.11.3

kubeadm version: &version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:04:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

kube-router version v0.2.0

Any ideas?

**Comment by murali-reddy** [comment]
Usually, once `kube-bridge` is setup there is nothing changing its configuration dynamically. When you loose connectivity from node A to node B what do you observe? does the packets from node A reach to node B and sent over `kube-bridge` interface?

Are the routes on node A and node B populated correctly to route the inter node pod traffic?

**Comment by ep4eg** [comment]
> does the packets from node A reach to node B and sent over kube-bridge interface?

Yes, they do, seems like after the packets achieve kube-bridge on the node B they cant be forwarded further to veth interface.

> Are the routes on node A and node B populated correctly to route the inter node pod traffic?

Everything ok with routes, as I said **pod-to-pod** connectivity works well, I'm struggling with **node-to-pod** connectivity. Put simply, when I ping a container inside a container everything is ok when I ping a container from a node, it's flapping.

**Comment by murali-reddy** [comment]
Are both nodes on same subnet (L2)?. Kube-router uses ipip tunnles for connectivity across the nodes in different subnets.

Also please see if disabling rp_filter has any difference. Also enable logging martian packets and see if there any martian packets.

**Comment by ep4eg** [comment]
So, I just disabled rp_filter and it works so far, that may be a security issue tho. Anyway, thank you!

**Comment by murali-reddy** [comment]
Usually it means routing is not correct. Do you have nodes with multiple interfaces? While disabling rp_filter fixes the problem, its good to keep it enabled and get to the root cause.

**Comment by ep4eg** [comment]
In my case cause was macvlan interface on a node, I just reworked configuration, so everything is ok now. Closing the issue.
