### ISSUE TITLE
FR: support/document minimalist containerd support (-kubernetes)

### ISSUE THREAD

**Issue by ptone** [cloudnativelabs/kube-router#546]
I was looking to see if I could use containerd to run only a pod on a minimal system and this requires CNI

When I tried to used kube-router for this, I was unable to figure out how to convince kube-router to provide CNI interface without assumptions that a full kubernetes control plane was in the mix

Ideally kube-router could act as a CNI containerd plugin:

https://github.com/containerd/go-cni

The proof point would be to run the nginx hello-world pod with crictl CLI tool using containerd (+CRI plugin and Kube-Router CNI plugin)

My naive quick hack attempt: 

```
  12  sudo mkdir -p /var/run/secrets/kubernetes.io/serviceaccount/
   13  sudo touch /var/run/secrets/kubernetes.io/serviceaccount/token
   14  sudo KUBERNETES_SERVICE_HOST=127.0.0.1 KUBERNETES_SERVICE_PORT=8080 ./kube-router --run-firewall --run-router

E0929 13:43:05.433595    8868 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Endpoints: Get https://127.0.0.1:8080/api/v1/endpoints?resourceVersion=0: dial tcp 127.0.0.1:8080: connect: connection refused
Failed to run kube-router: Failed to synchronize cache: 1m0s timeout
```

I was seeing if dummy vars could be used, obviously they are truly required.

**Comment by murali-reddy** [comment]
Kube-router by itself does not implement CNI. Its just uses underneath bridge, host-local standard CNI plugins to provide a Kubernetes networking solution.

https://github.com/containernetworking/plugins/tree/master/plugins
