### ISSUE TITLE
kube-router should tolerate node.kubernetes.io/not-ready

### ISSUE THREAD

**Issue by farcaller** [cloudnativelabs/kube-router#547]
When spinning up a kubeadm cluster the master is tainted with node.kubernetes.io/not-ready:

`KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config`

because kube-router cni isn't available yet. That prevents kube-router from installing a cni config in the first place; so it should tolerate the presence of `node.kubernetes.io/not-ready:NoSchedule`.

**Comment by murali-reddy** [comment]
thanks @farcaller for reporting this issue

Should we just do

```yaml
      tolerations:
      - operator: Exists
        effect: NoSchedule
```
with manifests in the folder https://github.com/cloudnativelabs/kube-router/tree/master/daemonset

this is what calico, flannel, weave doing as well.

**Comment by farcaller** [comment]
That's a rather bold toleration but I think it makes sense for a CNI component which is crucial for the node operation.

**Comment by methodx** [comment]
> That's a rather bold toleration but I think it makes sense for a CNI component which is crucial for the node operation.

But it seems legit for kube-router DaemonSet.
