### ISSUE TITLE
kube-router doesn't work with containerd out of the box

### ISSUE THREAD

**Issue by farcaller** [cloudnativelabs/kube-router#548]
containerd is oblivious to the injected cni config so it needs to be restarted after kuberouter creates the config. filing here because calico seems to work fine for whatever reason.

**Comment by menardorama** [comment]
Having similar problem with containerd and kube-router on kubernetes 1.11.
My case is that I can’t resolve kubernetes.default.... it’s Quite annoying.

A node reboot generaly solve the issue but that’s basically impossible to do in a prod env

**Comment by aauren** [comment]
Duplicate of #286
