### ISSUE TITLE
Default deny network policy and DSR services do not match

### ISSUE THREAD

**Issue by waldiTM** [cloudnativelabs/kube-router#570]
DSR services use IP-IP tunnels to get packets to the target pod. If I also define a network policy with a deny rule to restrict access to that pod, the rule does not match on the tunneled target packet, but in the IP-IP packet and is dropped without a specific rule.

To make that reliable working, kube-router would need to inject IP-IP accept rules from all nodes to the pods.

**Comment by murali-reddy** [comment]
@waldiTM thats interesting. thanks for reporting.

**Comment by aauren** [comment]
Closing this as I recently tried to reproduce this issue and could not. So with IP-IP encapsulation, the source and destination would be the real IPs of the nodes. These IPs are specifically allowed in the KUBE-ROUTER-SERVICES chain.

It's possible that this was a bug that was fixed somewhere along the road, but I can't find it present in any of the 1.0 releases. If anyone can still reproduce this issue please feel free to re-open with more details for a current kube-router release.
