### ISSUE TITLE
DRS mode needs to disable connection tracking

### ISSUE THREAD

**Issue by waldiTM** [cloudnativelabs/kube-router#571]
Connections via a DRS enabled service and destined for a pod on another node will never see return packets. This means that all connection tracking entries for connections to this service will stuck in `SYN_SENT` and timeout after some time.

**Comment by murali-reddy** [comment]
> This means that all connection tracking entries for connections to this service will stuck in SYN_SENT and timeout after some time.

@waldiTM thanks for the reporting. Do you mean the connection towards IPVS? Is it help by IPVS?

**Comment by aauren** [comment]
Closing as stale.
