### ISSUE TITLE
Add TCP graceful termination

### ISSUE THREAD

**Issue by MarkDeckert** [cloudnativelabs/kube-router#572]
Feature request:

When a pod is deleted, make an attempt to wait for TCP sessions to drain before killing the pod. Perhaps  by watching active connection count in ipvs and adding an additional wait period.  I would assume at some point you would want to just kill any long-running or stuck sessions regardless.

As a reference, see related functionality in kube-proxy: https://github.com/kubernetes/kubernetes/pull/66012

Also it might be a nice feature for there to be an option to disable or change the behavior slightly on a service by service basis via annotation.  If for example an app is configured in a way where it's intentional that clients never drop a session, the user might want to just always immediately force drop, or conversely, extend the wait period, on pod delete.

**Comment by roffe** [comment]
The default period is 5 minutes and can be set using `--ipvs-graceful-period` cli-opt 

The timeout can be overriden per service by setting the annotation `kube-router.io/service.gracefulterminationperiod` to a duration string

example:
    kube-router.io/service.gracefulterminationperiod: 30s

If the duration string is invalid the default period set by `--ipvs-graceful-period` will be used

I'm trying to get Active & Inactiveconn into the equation but i need to upgrade the vendored netlink & ipvs package for that to happend

**Comment by aauren** [comment]
Closed via #706. Thanks again @roffe!
