### ISSUE TITLE
Kube-router, GoBGP and Kernel Routing Table, Service VIP Persists

### ISSUE THREAD

**Issue by pichanaquiMantaTer** [cloudnativelabs/kube-router#574]
A service VIP is advertised from several k8s worker nodes to a route-reflector (GoBGP, external to cluster) with distinct next-hops all in subnets sometimes different from a selected worker node WN_0 not originating the VIP. In case one of the advertising worker nodes does belong to the same subnet as WN_0, as long as the BGP best next-hop is not in the subnet of WN_0, the VIP with next-hop does not get installed into the kernel routing table (KRT) of WN_0. However, if the BGP best route does have next-hop belonging to the same subnet as WN_0, the VIP with next-hop is installed into the KRT(WN_0). When the worker node no longer advertises the BGP best route for the VIP, the VIP with this next-hop should be withdrawn from the KRT. It is, on the other hand, withdrawn from the associated kube-router GoBGP table.

The VIP persists in the KRT(WN_0), which appears to be a bug in kube-router interaction with the KRT.

This also occurs when WN_0 originates the same VIP. In this case, since WN_0 has a pod advertising the VIP, a traceroute -I from the host of WN_0 to the VIP resolves to the VIP on the pod, despite the KRT only reporting the (/32 route) VIP to a next-hop on a different host on the same subnet.
Finally, does kube-router bypass the KRT altogether?

Reference: 
kube1 ~ # kube-router -V
Running kube-router version , built on 2018-09-12T20:15:54+0000, go1.10.3

All worker nodes only iBGP peer with an external route-reflector.

Thanks.

**Comment by aauren** [comment]
Closed via #629
