### ISSUE TITLE
Netmask is always /24 can't define it

### ISSUE THREAD

**Issue by menardorama** [cloudnativelabs/kube-router#581]
Hi,

I am using kube-router since 6 months and it's working great (well except Centos 7 Ipv6 bug but that's not the issue today).

I am planning to deploy a bare-metal kubernetes cluster where I plan to permit more than 110 pods per node; as my servers are quite big (256Go of RAM,Dual Xeon Gold, Full SSD drives) I am planning to permit 300 pods per node (10 node cluster).
The thing is kube-router assign a /24 network to my nodes.

Is there a way to define subnet lengh in kube-router ?

For example in calico I found this https://github.com/projectcalico/libcalico-go/issues/761 but nothing on kube-router....

Thanks a lot

**Comment by roffe** [comment]
kube-router is not responsible for assigning the cidr to your nodes, it's done by [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/). We just apply whats been decided.

The flag in question is

```
--node-cidr-mask-size int32     Default: 24
```
