### ISSUE TITLE
Default route from eBGP peer, pulls kernel default upon withdraw/shutdown

### ISSUE THREAD

**Issue by sanjmonkey** [cloudnativelabs/kube-router#584]
If an eBGP neighbor, say an upstream ToR, sends routes to kube-router which already exist in the kernel routing table, such as 0.0.0.0/0, and then the ToR either shuts down the session or withdraws 0/0, the node has its default route removed from kernel routing table, and is unreachable.

## Expected Behaviour
Kernel routing table to keep its configured default route, if it had one configured, when peering with external neighbors and the same route is received from them.

## Current Behaviour
Before eBGP session is established:
```
sandy.breeze@kube-node-uk02:~$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         80.80.80.1      0.0.0.0         UG        0 0          0 ens160
10.10.2.0       0.0.0.0         255.255.255.0   U         0 0          0 kube-bridge
80.80.80.0      0.0.0.0         255.255.255.248 U         0 0          0 ens160
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0

sandy.breeze@kube-node-uk02:~$ ip route list default
default via 80.80.80.1 dev ens160 proto static
```

Whilst eBGP session established and receiving 0.0.0.0/0 from neighbor:
```
sandy.breeze@kube-node-uk02:~$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         80.80.80.1      0.0.0.0         UG        0 0          0 ens160
10.10.2.0       0.0.0.0         255.255.255.0   U         0 0          0 kube-bridge
80.80.80.0      0.0.0.0         255.255.255.248 U         0 0          0 ens160
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0

sandy.breeze@kube-node-uk02:~$ ip route list default
default via 80.80.80.1 dev ens160 proto 17
````

After eBGP session is shutdown:
```
sandy.breeze@kube-node-uk02:~$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
10.10.2.0       0.0.0.0         255.255.255.0   U         0 0          0 kube-bridge
80.80.80.0      0.0.0.0         255.255.255.248 U         0 0          0 ens160
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0

sandy.breeze@kube-node-uk02:~$ ip route list default
sandy.breeze@kube-node-uk02:~$
(no output)
```

## Possible Solution
I'd expect in almost all cases, not pulling the default from the kernel routing table if it already had a default (ie through config/dhcp) would be enough.  I'd imagine there being a few ways it could be done.  Perhaps asking NL if a route exists and tagged with anything indicating its source (eg `RTPROT_STATIC` or similar) then don't install the one from BGP?

## Environment
- Kubernetes v1.12.3
- Kube-router version v0.2.3, built on 2018-11-22T20:20:27+0000, go1.10.5
- Nodes OS: Ubuntu 18.04.1 LTS
- libnl-3-200/bionic,now 3.2.29-0ubuntu3 amd64 [installed,automatic]
- libnl-genl-3-200/bionic,now 3.2.29-0ubuntu3 amd64 [installed,automatic]
- libnfnetlink0/bionic,now 1.0.1-3 amd64 [installed]
- iproute2-ss180129
- iptables v1.6.1

The problem is further compounded by the inability to set Import policies in goBGP at runtime, would you like enhancement request for that?

**Comment by murali-reddy** [comment]
Thanks for reporting this issue @sanjmonkey , please go ahead and raise enhancement request

**Comment by aauren** [comment]
Closing this in favor of #586 as that one describes both the problem and the solution.
