### ISSUE TITLE
kube-router consumes a lot of CPU with multiple network policies that target the same pods

### ISSUE THREAD

**Issue by mikn** [cloudnativelabs/kube-router#585]
We are running with 10s of network policies per namespace, that most of them allow pods from a service namespace to connect to the pods themselves in that namespace on specific ports. We're however noticing that now that we're having in the region of 50 network policies, a lot of CPU is being spent on just setting and updating ipsets. (North of 0.5 cores per node)

[callgraphs.tar.gz](https://github.com/cloudnativelabs/kube-router/files/2623347/callgraphs.tar.gz)
I've attached two SVG call graphs, one for heap and one for CPU that shows this behaviour.

It is also important to note that we have a lot of create/delete pod events because we run both CI with container stages as well as high-frequency cronjobs.

**Comment by murali-reddy** [comment]
> It is also important to note that we have a lot of create/delete pod events because we run both CI with container stages as well as high-frequency cronjobs.

@mikn kube-router is not currently well optimized for high rate of pod events. What it currently doing is to perform full sync of ipables based on all the network polices on each pod add/delete/update events.This should be optimised to delta sync of network policies that only affect the pods. 

I am marking the bug as enhancement to be addressed in one of the coming releases.

**Comment by MarkDeckert** [comment]
Is there any chance of this coming soon? We highly utilize network policy and I've noticed significant and prolonged CPU usage during pod updates.

**Comment by aauren** [comment]
Fixed via #1010
