### ISSUE TITLE
iptables >= 1.8 compatibility issue

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#592]
https://github.com/kubernetes/kubernetes/issues/71305

**Comment by uablrek** [comment]
I have tested basic function of `kube-router` (except network policies) with iptables v1.8.2 without problems.

I run `kube-proxy` outside any pod/container, in "main" namespace so to speak, so the host's version of iptables is used. If `kube-router` executes in a pod then the version of `iptables` (and libs) must match the version of the host. I don't think that is an easy problem to solve in a generic way.

**Comment by murali-reddy** [comment]
Right there is no easy way out. Even the latest of alpine images that kube-router uses still has iptables version ` v1.6.1` packages, so for now replacing the host binary with older version is workaround.

**Comment by murali-reddy** [comment]
`alpine:3.10` now has both `legacy` and `nft` version of iptables binaries bundled

**Comment by aauren** [comment]
This should no longer be an issue because we now incorporate https://github.com/cloudnativelabs/kube-router/blob/master/build/image-assets/iptables-wrapper-installer.sh into our container images
