### ISSUE TITLE
Network communication hangs

### ISSUE THREAD

**Issue by AlexB163** [cloudnativelabs/kube-router#600]
We have a service with external ip. Clients connect to our services throw it.
Traffic throw endpoint periodically hangs in about 40 - 60 seconds. On server we see that all network freezes.
Logs on server/kube-router is clear.

We tried to debug this issue - but without success
Can you help us figure out that the problem causes this behavior?

**Comment by AlexB163** [comment]
ipvsadm show about 4000 connections

**Comment by AlexB163** [comment]
kube_router_service_packets_in metric not showing any packets to service, but ipvsadm do

**Comment by AlexB163** [comment]
I found that conntrack closes connections while ipvs uses it

**Comment by lomkju** [comment]
@AlexB163 can you please tell us your OS?

**Comment by aauren** [comment]
Closing as stale.
