### ISSUE TITLE
gobgp complains about NextHop Attribute containing IPV6 address

### ISSUE THREAD

**Issue by Arvinderpal** [cloudnativelabs/kube-router#605]
For IPv6 route advertisements, MP-BGP extensions should be used. Recent PR https://github.com/cloudnativelabs/kube-router/pull/578 does this; however it also inserts the IPV6 address in the NEXTHOP field. This causes gobgp to produce the following error:

I1212 05:06:46.172157   22013 network_routes_controller.go:332] Processing bgp route advertisement from peer
WARN[0019] the received Update message was treated as withdraw  Key="fd00::9" State=BGP_FSM_ESTABLISHED Topic=Peer error="invalid nexthop address"

A recent PR in gobgp (https://github.com/osrg/gobgp/issues/1893) does not produce he above error/warning for IPv6 addresses in NEXTHOP field; however, according to rfc4760, NEXTHOP is only for IPV4 addresses. https://tools.ietf.org/html/rfc4760 

Suggested fix: remove the IPV6 address insertion into NEXTHOP.

**Comment by Arvinderpal** [comment]
@uablrek I will issue a small PR for this fix.

**Comment by gedOHub** [comment]
For IPv4 NextHopAttribute from API works. What methor I should use for setting nexthop for Ipv6?

**Comment by aauren** [comment]
Closed via #606. Thanks again @Arvinderpal !
