### ISSUE TITLE
HostPort not working on a single node kubeadm cluster

### ISSUE THREAD

**Issue by cjbottaro** [cloudnativelabs/kube-router#611]
I can't seem to get this to work on my single node Kubernetes cluster on my home computer, which is odd because it works just fine on 4 kops managed production clusters in AWS.

Here's what I did...
```
kubectl patch configmaps kube-router-cfg -n kube-system -p "$(cat kube-router-configmap-patch.yaml)"

kubectl patch daemonset kube-router -n kube-system -p "$(cat kube-router-daemonset-patch.yaml)"
```

Then I rebooted the machine.

Contents of the patch files are here:
https://gist.github.com/cjbottaro/517470a452deafc55dc222aa3b3b816d

Then I have a deployment with container spec like:
```
ports:
  - containerPort: 80
    hostPort: 80
```

Not sure where to go next with debugging this. I'm running Ubuntu 18.04 on the host and firewall is turned off:
```
$ sudo ufw status
Status: inactive
```

Thanks for the help.

**Comment by mk01** [comment]
if cni config contains more plugin configurations, it should have extension .conflist . otherwise kubelet complains. or you can simply add the ```  {
          "type":"portmap",
          "capabilities":{
            "snat":true,
            "portMappings":true
          }
        }``` into second file. 
(at least this is the behaviour on k8s 11.5)

also check if you have the proper binaries in /opt/cni/bin (normally installed by package kubernetes-cni)

if all this is correct, then table nat is extended with two chains like this (pod template is having containerPort 8443 / hostPort 9443 in this example)
```
Chain CNI-DN-ebebf586b4399758b1da4 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    6   496 DNAT       tcp      *      *       ::/0                 ::/0                 tcp dpt:9443 to:[fde4:101::2]:8443

Chain CNI-HOSTPORT-DNAT (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    7   576 CNI-DN-ebebf586b4399758b1da4  all      *      *       ::/0                 ::/0                 /* dnat name: "k8s-pod-network" id: "9436b1ea721e361edc03304a2c2a0d184531df10cc32b66596977d172e3a947b" */
```

... and used are in PREROUTING / OUTPUT of nat. (check with ip[6]tables -t nat -L -n -v)

(btw - it is unrelated to kube-router)

**Comment by cjbottaro** [comment]
Thanks for helping me debug this, it's way out of my wheelhouse.

I don't think my iptables have the right settings:
```
$ sudo iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 16 packets, 1399 bytes)
 pkts bytes target     prot opt in     out     source               destination
67314 4021K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 16 packets, 1399 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 49 packets, 2983 bytes)
 pkts bytes target     prot opt in     out     source               destination
 355K   21M DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 49 packets, 2983 bytes)
 pkts bytes target     prot opt in     out     source               destination
 932K   56M KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0
   66  4489 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set kube-router-pod-subnets src ! match-set kube-router-pod-subnets dst ! match-set kube-router-node-ips dst
    0     0 MASQUERADE  all  --  *      *      !100.64.0.0/24       !100.64.0.0/24        vdir ORIGINAL vmethod MASQ /*  */

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0

Chain KUBE-MARK-DROP (0 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x8000

Chain KUBE-MARK-MASQ (0 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x4000

Chain KUBE-POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000
```

But it does look like kube-router is using the correct conflist:

```
$ kubectl exec kube-router-87rb4 -n kube-system -- cat /etc/cni/net.d/10-kuberouter.conflist
{"cniVersion":"0.3.0","name":"kube-router-net","plugins":[{"bridge":"kube-bridge","ipam":{"subnet":"100.64.0.0/24","type":"host-local"},"isDefaultGateway":true,"name":"kubernetes","type":"bridge"},{"capabilities":{"portMappings":true,"snat":true},"type":"portmap"}]}

$ kubectl exec kube-router-87rb4 -n kube-system -- env | grep KUBE_ROUTER_CNI_CONF_FILE
KUBE_ROUTER_CNI_CONF_FILE=/etc/cni/net.d/10-kuberouter.conflist
```

Any ideas on what to try next? Thanks a ton for the help!

**Comment by cjbottaro** [comment]
> also check if you have the proper binaries in /opt/cni/bin

```
$ kubectl exec kube-router-87rb4 -n kube-system -- ls /opt/cni/bin
ls: /opt/cni/bin: No such file or directory
```
Uh oh. I'm using the following Docker image: `cloudnativelabs/kube-router:v0.2.3`.

**Comment by cjbottaro** [comment]
Oh, but it's all here on the host:
```$ ls /opt/cni/bin/
bridge      dhcp        flannel     host-local  ipvlan      loopback    macvlan     portmap     ptp         sample      tuning      vlan```

**Comment by mk01** [comment]
@cjbottaro 

yes, it is host the one having the binaries. ...
the configuration looks ok to me now, at least I retested again the same - configmap:
```
apiVersion: v1
data:
  cni-conf.json: {"cniVersion":"0.3.0","name":"kube-router-net","plugins":[
    {
  "name":"kubernetes",
  "type":"bridge",
  "bridge":"kube-bridge",
   "isDefaultGateway":true,
  "hairpinMode":true,
  "ipam": {
    "type":"host-local"
   }
 },
 {
    "capabilities": {
      "portMappings": true,
      "snat": true
    },
    "type": "portmap"
 }]
}
```

updated the initContainer & env variable as your setting... (and just to be sure restarted kubelet on the node(s)).
then created deployment of ubuntu image like this:
```
    spec:
      containers:
      - args:
        - bash
        image: ubuntu
        imagePullPolicy: Always
        name: testubuntu
        ports:
        - containerPort: 19999
          hostPort: 20001
          protocol: TCP
```

and as expected, this appeared on the target host (non relevant stuff is removed from the output):
```
root@kube-master:~# ip6tables -t nat -S
-N CNI-DN-e52a8a60a8612bd378856
-N CNI-HOSTPORT-DNAT
-A PREROUTING -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A OUTPUT -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A CNI-DN-e52a8a60a8612bd378856 -p tcp -m tcp --dport 20001 -j DNAT --to-destination [fde4:100::2]:19999
-A CNI-HOSTPORT-DNAT -m comment --comment "dnat name: \"kube-router-net\" id: \"207815a3e958e514b4ba74891fb6674c3c160f69ad68be38bb57990c141beb51\"" -j CNI-DN-e52a8a60a8612bd378856
```

anyhow, as said earlier, this is not functionality of kube-router, but of CNI networking. those changes are done by !docker! (not kube-router nor kubelet). the appropriate configuration (hostPort/containerPort to check) is bond to the POD's core container - "pause", not the deployment itself. check the node/docker itself, you should see something similar to this:

```
root@kube-master:~# docker ps |grep ubuntu
c978b9425f31        ubuntu@sha256:6d0e0c26489e33f5a6f0020edface2727db9489744ecc9b4f50c7fa671f23c49                                "bash"                   18 minutes ago      Up 18 minutes                           k8s_testubuntu_testubuntu-79f69c495-4rtmz_kube-system_3aa796de-07e8-11e9-94d6-024269e21c84_0
207815a3e958        k8s.gcr.io/pause:3.1                                                                                          "/pause"                 18 minutes ago      Up 18 minutes                           k8s_POD_testubuntu-79f69c495-4rtmz_kube-system_3aa796de-07e8-11e9-94d6-024269e21c84_0
root@kube-master:~#
```

```
root@kube-master:~# docker inspect 207815a3e958
[
    {
        "Id": "207815a3e958e514b4ba74891fb6674c3c160f69ad68be38bb57990c141beb51",
        "Created": "2018-12-25T01:56:01.351331446Z",
        "Path": "/pause",
...
            "NetworkMode": "none",
            "PortBindings": {
                "19999/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "20001"
                    }
                ]
            },
```
as you see I'm inspecting the "PAUSE" container, not the "main" ubuntu one.
at last, things to consider:
- I had various issues with docker versions above 17.03 - for instance ipv6 address allocations and other network related - could be you are seeing one of them.
- also, with some 'previous' versions of k8s the hostPort option wasn't passed to docker at all if CNI was used - some relevant discussion here https://github.com/coreos/flannel-cni/pull/5 and https://github.com/kubernetes/kubernetes/issues/23920

btw - this tests have been performed with docker-ce version 17.03 - the one from ubuntu repos, not docker repos - although version number same, the docker builds are not working properly
```
root@kube-master:~# apt-cache policy docker.io 
docker.io:
  Installed: 17.03.2-0ubuntu2~16.04.1
  Candidate: 18.06.1-0ubuntu1~16.04.2
  Version table:
     18.06.1-0ubuntu1~16.04.2 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
 *** 17.03.2-0ubuntu2~16.04.1 100
        100 /var/lib/dpkg/status
```

unfortunately that version is no longer available and that new 18.06 has again broken ipv6, so I can't test it (if hostPort works there). but you could try it with k8s 11.5 - at least to really confirm that the configuration is OK in general.
OR even better, replicate exactly the versions (k8s/docker/base image) of you kops production cluster - where you said it is working.

my experience here is negative one - I tested on kops clusters I have access to - running docker 17.09, k8s 1.10.11 and hostPort is not working there.

**Comment by murali-reddy** [comment]
if there are multiple CNI configuration files, then kubelet will pick one that is first in lexicographical order so `10-kuberouter.conf` will take precedence.

Since kube-router has multiple functionality that can be pick-and-choose there is no _single_ manifest, depending on which manifest you have choosen it may not be ensuring that conf file with `.conf` is  removed. One in the repo https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/kubeadm-kuberouter-all-features-hostport.yaml just simply installs `10-kuberouter.conflist`

**Comment by murali-reddy** [comment]
Original patch that was shared, just installed `.conflist` as well. so that explains. Hope this issue can be closed now @cjbottaro
