### ISSUE TITLE
Hostport pods take over traffic from services

### ISSUE THREAD

**Issue by rmb938** [cloudnativelabs/kube-router#612]
Kube-Router Version: v0.2.3

Steps:

1. Create a daemon set with a hostport. This port must match an existing service that is already created.
1. Wait for pods to start
1. Try and communicate with the service

Example:

The kubernetes service in the default namespace with a port of 443. Spin up a daemonset with pods that have a host port of 443. All traffic being sent to the kubernetes service is now being sent to the daemonset pods instead of the service pods.

As soon as the host port pods are deleted things go back to normal.

cni-config.json

```
    {
       "cniVersion":"0.3.0",
       "name":"mynet",
       "plugins":[
          {
             "name":"kubernetes",
             "type":"bridge",
             "bridge":"kube-bridge",
             "isDefaultGateway":true,
             "ipam":{
                "type":"host-local"
             }
          },
          {
             "type":"portmap",
             "capabilities":{
                "snat":true,
                "portMappings":true
             }
          }
       ]
    }
```

**Comment by roffe** [comment]
If this is a master node then yes, you cannot use port 443 as the api-server in most setups listens on the host interface and you would nuke it by setting up a nodeport service

**Comment by roffe** [comment]
on the workers it would kind of work but sinde nodeport applies to all the nodes in the cluster you bork your api by doing so

**Comment by roffe** [comment]
you can create a Daemonset with hostport and use a nodeselector / pod affinity / anti-affinity to just have it run on a set of non-master nodes that won't have 443 occupied

**Comment by rmb938** [comment]
It does seem that the portmap plugin https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap has some new options that may solve this.

Specifically these:

```
conditionsV4, conditionsV6 - array of strings. A list of arbitrary iptables matches to add to the per-container rule. This may be useful if you wish to exclude specific IPs from port-mapping
```

So if the service cidr is excluded that should solve the issue.

**Comment by rmb938** [comment]
So if I update my hosts to use the newest CNI plugins then I edit `/etc/cni/net.d/10-kuberouter.conflist` to have this in the portmap configuration
```
"conditionsV4": ["!", "-d", "100.67.0.0/16"]
```

where 100.67.0.0/16 is my svc cidr. It seems to work as expected.

However I need to edit `/etc/cni/net.d/10-kuberouter.conflist`` after kube-router adds the subnet as it seems that if I do it before (i.e via the config map) that option gets removed.
