### ISSUE TITLE
NetworkPolicy for host networked pods

### ISSUE THREAD

**Issue by bazuchan** [cloudnativelabs/kube-router#616]
I want to implement NetworkPolicy enforcement for host networked pods.

Currently if iptables policy for INPUT chain is ACCEPT and there is no final DROP/REJECT host networked pods will be accessible from all cluster (*except for pods running on same node) whatever NetworkPolicy is. If iptables policy for INPUT chain is DROP or there is final DROP/REJECT and there are no permitting rule in host firewall they will be inaccessible from cluster whatever NetworkPolicy is. Using host firewall you can allow access from all cluster, but not for example from certain namespaces or pods.

I see several choices:
1. Append same jump rules as in FORWARD chain to INPUT chain if pod ip is the same as node ip. This will work well only if there is no final DROP/REJECT rule and host firewall is setup to allow all needed host traffic. It will break everything if host firewall is empty. So it can only be enabled with command-line switch.
2. Make one more chain containg same rules as KUBE-POD-FW-* but without final REJECT and insert it into INPUT chain. It will not break anything and will enforce NetworkPolicy only if iptables policy for INPUT chain is DROP or there is final DROP/REJECT.
3. Add FORWARD jump rules for ips of all nodes on each node. And allow it in INPUT chain for all cluster. This way it will enforce NetworkPolicy only from inside of the cluster.

For my current use case any variant will do, but I want to implement it the way it gets accepted as PR.

**Comment by SerialVelocity** [comment]
I would love this feature as well. I think it might be fine to rely on the host network rules to be correct (so you don't clobber other services which are running on the host) and maybe to only apply rules which have ports specified?

@murali-reddy You seem to be an active maintainer. Do you have any thoughts about this? Would you accept a PR which adds this feature?

**Comment by murali-reddy** [comment]
@SerialVelocity PR #620 is expected to fix this. Will check @bazuchan would like to revice this PR

**Comment by bazuchan** [comment]
> @SerialVelocity PR #620 is expected to fix this. Will check @bazuchan would like to revice this PR

I'm waiting for #745 to get merged before updating this PR.

**Comment by aauren** [comment]
After experiencing an issue and looking into this issue deeper in #1067 we have decided that kube-router will not apply NetworkPolicy to HostNetwork'd pods. See [comment](https://github.com/cloudnativelabs/kube-router/issues/1067#issuecomment-828824649) on #1067 for more information.

@bazuchan I definitely appreciate your willingness to keep up development on this issue and its related PR #620
