### ISSUE TITLE
armhf support?

### ISSUE THREAD

**Issue by cjbottaro** [cloudnativelabs/kube-router#622]
Trying to get this to run on Rasbian Stretch which is `armhf`. I saw this commit https://github.com/cloudnativelabs/kube-router/commit/c7ce39836788d66b634b3c7c4f4c935468394bad, but that only looks to do `arm` and `arm64`?

Thanks for the help!

**Comment by cjbottaro** [comment]
Here's what I found out...

There is support for `arm` and `arm64` but cloudnativelabs doesn't host those images on Docker Hub. This guy does though: https://hub.docker.com/r/xjjo/kube-router/tags

I have a non-homogenous Kubernetes cluster; some nodes are `arm` and some are `amd64`. So taking inspiration from the flannel installation manifests, I had to make multiple kube-router DaemonSet manifests: `kube-router-arm` and `kube-router-amd64` using nodeSelector to put each one nodes of the the right architecture.

It would be really nice if cloudnativelabs hosted images of each supported arch on Docker Hub and altered the install manifests to include them. I can take care of that latter part if there is interest.

**Comment by cjbottaro** [comment]
Here ya go: https://gist.github.com/cjbottaro/5dfaef75a212a798c73b865c168ef19f

Couple of things to note:
* There are multiple DaemonSet manifests in that file
* hostPort is enabled

**Comment by hakan458** [comment]
@cjbottaro Can you provide a little more detail? What controls which one gets run? I see you have a line like 
```
      nodeSelector:
        beta.kubernetes.io/arch: arm
```
But not sure how it gets routed to one or the other? Is there one daemonset file which then points to the arm/amd64 one?
