### ISSUE TITLE
End-to-End (e2e) testing framework for kube-router

### ISSUE THREAD

**Issue by Arvinderpal** [cloudnativelabs/kube-router#624]
I'm actively working on adding IPv6 functionality to kube-router. This requires substantial changes and thus the likelyhood of something breaking is high. In order to minimize any such impact, I believe it's essential for us to have a (fairly) comprehensive e2e test suite. 

I believe any e2e solution must (i) support running tests against an existing vagrant cluster, (ii) support creation of vagrant clusters with different modes of operation (e.g. ipv4, ipv6, dual-stack clusters) and (iii) support addition of new environments beyond vagrant (e.g. DigitalOcean).

I'm aware of the following PR that brings e2e testing with Digital Ocean: https://github.com/cloudnativelabs/kube-router/pull/382 Unfortunately, it is not compatible with vagrant, which I feel is a more typical dev environment. 

I'm currently working on an e2e framework that leverages the excellent work done by the Cilium folks (https://github.com/cilium/cilium/tree/master/test). The initial goal will be to address requirement (i) above; that is, allow tests to be run against a manually configured vagrant cluster. 

I wanted to share this with you guys early so as to solicit suggestions. As soon as I have the e2e framework in some working order, I will do a PR. 

@murali-reddy @uablrek @andrewsykim

**Comment by andrewsykim** [comment]
👍 sounds good. I see value in having both. For what it's worth, the actual go test code in https://github.com/cloudnativelabs/kube-router/pull/382 should work with any cluster, just need to change a few parameters. Happy to wait to see what you come up with and discuss what would work best, not having to create a cluster on a cloud provider would be preferred if the test coverage ends up being the same.

**Comment by aauren** [comment]
Closed via https://github.com/cloudnativelabs/kube-router-e2e however, we should probably find a way to incorporate this into our CI tests.

Putting this on your radar @murali-reddy and to get your thoughts on how it would be best to incorporate e2e tests into our merge flows. 

There is also this e2e generic network policy testing suite that it might be worth seeing if we could incorporate. It would ensure that we stay consistent with the same network policy spec that other projects are using: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/network_policy.go
