### ISSUE TITLE
Feature Proposal: Enable Pure L3 ECMP Routing for Local Services

### ISSUE THREAD

**Issue by aauren** [cloudnativelabs/kube-router#633]
# Background
My organization desires to use kube-router in conjunction with the service annotation `kube-router.io/service.local: "true"` to use kube-router as a pure L3 ECMP service presentation layer for our Kubernetes services. There seems to be only a small change needed to facilitate this from what I can see of the project so far. However, I wanted to describe the problem here to see if I can gain consensus on a solution before I work on and submit a PR.

# Problem
kube-router inserts service routes into the host's routing table when the best next hop, that it receives through BGP, is within the host's subnet. This makes the service route at L2 instead of L3 bypassing ECMP and the load balancing that is provided there.

Since `kube-router.io/service.local: "true"` is enabled, this means that services will not have IPVS entries on hosts that don't run a pod attached to this service meaning that IPVS doesn't come into play for the vast majority of our nodes.

So, if multiple pods that back a given service are running within a single subnet, all of the other hosts within that same subnet will route all of their traffic to a single one of those pods, causing the service to hotspot and stop scaling within a given subnet.

# Proposed Solution
I would like to submit a PR that will expose a CLI option which, when enabled, will disable the injection of the best next hop into the host's routing table. Specifically, it would bypass the logic represented here: https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/network_routes_controller.go#L414-L504

This option would not work when `--enable-overlay=true` as the route needs to be injected so that overlay tunnel can be used for service traffic. So if `--enable-overlay=true` were enabled, my option would be automatically disabled at startup with a warning in the logs.

**Comment by murali-reddy** [comment]
I feel that nodes should never have received advertisements for service VIP's. Traffic to service VIP's should be sent gateway and should be ECMP ed from there. To me enforcing BGP import polices of service VIP at the nodes seem to be right. But not sure if is desirable for any reason each nodes to receive routes for the service VIP's. 

Lets see if other users has any opinion.

**Comment by aauren** [comment]
@murali-reddy Thanks for your comment here! For what it's worth, we are in agreement that nodes should never receive advertisement for the service VIPs and that instead traffic should be sent to the gateway and be ECMP'd from there.

Do you have an idea on what the next steps would be for this ticket? You mentioned enforcing BGP import policies of service VIPs. If you're able to flesh that out a bit more, and maybe give me some pointers for it around the code, I would be willing to take a stab at implementing that.

Let me know!

**Comment by murali-reddy** [comment]
@aauren please see

 https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md

and

https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/export_policies.go

and now we need on similar line import policies. there is `clusteripprefixset` already all you need to do is a create import policy that restrict accepting `clusteripprefixset` from `ANY` one

Please try to play with GoBGP configuration, then it would be easier to code it in the Kube-router + GoBGP client.

**Comment by aauren** [comment]
Closed via #721
