### ISSUE TITLE
Hairpin nat does not work

### ISSUE THREAD

**Issue by zerkms** [cloudnativelabs/kube-router#637]
There is a single pod `10.244.2.23` and a corresponding service `10.42.13.240`. The only port exposed is `80`.

Hairpin mode enabled globally via `--hairpin-mode=true` (and also tried the annotation).

The corresponding iptables rule was added by kube-router:

```
Chain KUBE-ROUTER-HAIRPIN (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
       0        0 SNAT       all  --  *      *       10.244.2.23          10.244.2.23          vaddr 10.42.13.240 vport 80 to:10.42.13.240
```

Yet, from inside the container it's impossible to connect via cluster ip:

```
# curl 10.244.2.23/index.php
37

# curl 10.42.13.240/index.php
curl: (7) Failed to connect to 10.42.13.240 port 80: Connection timed out
```

There is also no problem connecting it from outside the pod (eg: from any other pod or a cluster node)

What are the other requirements for the hairpin mode to work?

**Comment by murali-reddy** [comment]
Please see https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#hairpin-mode-example

Did you add `"hairpinMode":true` to the conf file ?

**Comment by zerkms** [comment]
I see. Nope, I did not notice that originally.

I'll check it and close this report tomorrow, thanks a bunch.

**Comment by zerkms** [comment]
I added `"hairpinMode":true` to the configmap, deleted all `kube-router` pods (so k8s recreated them).

Yet I still cannot connect to the service IP of itself from inside the pod.

What else do I do to debug it? Or what else should I have done apart of changing a configmap + deleting pods

**Comment by murali-reddy** [comment]
@zerkms I just tried hairpin mode. It works fine for me. Did you do both the steps mentioned in the [docs](https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#hairpin-mode)?

- adding `"hairpinMode":true` to your CNI conf file
- annotating service with "kube-router.io/service.hairpin="

**Comment by zerkms** [comment]
I did not annotate a service - I used `--hairpin-mode=true` which makes it on for all services.

I will reinstall the cluster from scratch in a virtual machine

**Comment by murali-reddy** [comment]
Ok there seems to be some issue with `--hairpin-mode=true`, please try annotation

**Comment by mk01** [comment]
@zerkms 

check whether hairpin mode is being configured for bridge ports (veth devices)
```
grep . /sys/devices/virtual/net/*/brport/hairpin_mode
```

**Comment by zerkms** [comment]
Yes, I confirm that after adding `"hairpinMode":true` to the CNI config + annotating a service hairpin mode works.

Thanks, and sorry.

**Comment by zerkms** [comment]
Another thing is that it looks like in my tiny vagrant repro-environment both annotation and `--hairpin-mode=true` work.

So it must be something else wrong with my bare-metal configuration.

**Comment by shayrybak** [comment]
I ran into a similar issue.
Finally was able to establish the issue is not with the flag at least for me.

The default sync period for the routing is 5 minutes. which caused me to think it wasn't applying

After setting it to 1 second, everything seems to run smoothly.

set these flags to change the sync periods
        `--iptables-sync-period=1s`
        `--ipvs-sync-period=1s`
        `--routes-sync-period=1s`
