### ISSUE TITLE
Ability to advertise routes between two kubernetes clusters

### ISSUE THREAD

**Issue by nuriel77** [cloudnativelabs/kube-router#641]
Is it possible to advertise routes between two kubernetes clusters to achieve networking between the two clusters?
If so, what is the way to connect the two? (didn't find something specific in documentation)

**Comment by Thoro** [comment]
I would go the route via a common router, both clusters connect via external peer to that router and the router advertises the others clusters routes.

i.e.: --peer-router-ips=

**Comment by nuriel77** [comment]
Thanks.
