### ISSUE TITLE
Can't ping external IP address with DSR enabled

### ISSUE THREAD

**Issue by jcpuzic** [cloudnativelabs/kube-router#644]
I have a simple exposed TCP/UDP service for DNS with an external IP.  It all works fine, I can resolve via the external ip, but I cannot ping the external IP address.  Is this expected behavior if I don't have that external IP manually added to the node's interface?  If I don't use DSR, then it pings just fine.

**Comment by murali-reddy** [comment]
DSR requires configuring IPVS in different way compared to non DSR cases. 

kube-router does not configure VIP on dummy interfaces essentially to achieve [VIP less director model](http://www.austintek.com/LVS/LVS-HOWTO/HOWTO/LVS-HOWTO.routing_to_VIP-less_director.html).

So ping will not work.

**Comment by jcpuzic** [comment]
Thanks for the reply, I chose to go the route of adding the VIP to the loop back interface to avoid IP conflict so that I can fail a node and not loose ping to the VIP.

**Comment by murali-reddy** [comment]
ok. Closing the bug.
