### ISSUE TITLE
IPIP tunnel interface not created

### ISSUE THREAD

**Issue by dontreboot** [cloudnativelabs/kube-router#647]
I am running kube router v0.2.3. I was able to get ip tunnel to work in a different cluster before; however, for the new cluster kube router had problems creating the tunnel interface inside the service container:
```
szhou@Shawns-MacBook-Pro:~$ kubectl get endpoints -n ingress-controller |grep 10.254.2.148
haproxy-ingress-prod-1    10.254.2.148:80,10.254.2.148:1936,10.254.2.148:443   3h
szhou@Shawns-MacBook-Pro:~$ kubectl get pods -n ingress-controller |grep haproxy-ingress-prod-1
haproxy-ingress-prod-1-5c7554bf6d-4klms   1/1       Running   0          3h
szhou@Shawns-MacBook-Pro:~$ kubectl exec -it haproxy-ingress-prod-1-5c7554bf6d-4klms -n ingress-controller -- ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if33: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 0a:58:0a:fe:02:94 brd ff:ff:ff:ff:ff:ff
    inet 10.254.2.148/24 scope global eth0
       valid_lft forever preferred_lft forever
szhou@Shawns-MacBook-Pro:~$
```

Looks like kube router had problem communicating with docker daemon.
```E0124 19:58:08.648399       1 network_services_controller.go:786] Failed to prepare endpoint 10.254.2.148 to do direct server return due to Failed to get docker container spec due to Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0124 19:58:08.664497       1 network_services_controller.go:932] Current network namespace before netns.Set: NS(13: 3, 4026531969)
E0124 19:58:08.664691       1 network_services_controller.go:786] Failed to prepare endpoint 10.254.2.148 to do direct server return due to Failed to get docker container spec due to Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0124 19:58:08.666806       1 network_services_controller.go:794] Cleaning up if any, old service IPs on dummy interface
```

I could see docker daemon is running on the worker node that particular kube router is running:
```root@K8SWORKER02:~# systemctl status docker
 docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-01-24 01:59:33 UTC; 21h ago
     Docs: https://docs.docker.com
 Main PID: 3558 (dockerd)
    Tasks: 492
   Memory: 278.5M
      CPU: 53min 17.466s
   CGroup: /system.slice/docker.service
```
Has anyone seen this with kube router?

**Comment by murali-reddy** [comment]
> however, for the new cluster kube router had problems creating the tunnel interface inside the service container:

@dontreboot are you using services with DSR (direct-server return) enabled? Please note that you need to provide access to the docker from the kube-router manifest.

these are the requirements from the user-guide.

*You will need to enable hostIPC: true and hostPID: true in kube-router daemonset manifest. Also host path /var/run/docker.sock must be made a volumemount to kube-router.*

**Comment by dontreboot** [comment]
@murali-reddy  Thanks for your quick response! I was able to resolve the issue.

**Comment by murali-reddy** [comment]
@dontreboot curious. What was the issue?

**Comment by dontreboot** [comment]
I think the wrong manifest (one of those manifest files that doesn't have DSR features) file was used.

**Comment by anitgandhi** [comment]
@murali-reddy quick question - what is `hostIPC: true` needed for? I understand why `hostPID: true` is needed since kube-router needs to enter the process network namespace, but I wasn't following why IPC is needed as well?

**Comment by murali-reddy** [comment]
@anitgandhi from the docs https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#direct-server-return

`You will need to enable hostIPC: true and hostPID: true in kube-router daemonset manifest. Also host path /var/run/docker.sock must be made a volumemount to kube-router.`

docker client uses socket for IPC to docker daemon
