### ISSUE TITLE
Services with 0 endpoints are created and deleted at each sync

### ISSUE THREAD

**Issue by renchap** [cloudnativelabs/kube-router#652]
If a service has 0 target pods, each sync creates an IPVS service, and then deletes it (and its IP):

```
$ kubectl logs -f kube-router-vmg92 --namespace kube-system|grep 172.18.75.139
I0131 14:22:25.416456       1 network_services_controller.go:1855] Successfully added service: TCP:172.18.75.139:8080 (Flags: )
I0131 14:22:25.417174       1 network_services_controller.go:1855] Successfully added service: TCP:172.18.75.139:7070 (Flags: )
I0131 14:22:25.620621       1 network_services_controller.go:1053] Found an IP 172.18.75.139 which is no longer needed so cleaning up
I0131 14:22:25.649744       1 network_services_controller.go:1088] Found a IPVS service TCP:172.18.75.139:8080 (Flags: [hashed entry]) which is no longer needed so cleaning up
I0131 14:22:25.649826       1 network_services_controller.go:1088] Found a IPVS service TCP:172.18.75.139:7070 (Flags: [hashed entry]) which is no longer needed so cleaning up
I0131 14:22:26.478995       1 network_services_controller.go:1855] Successfully added service: TCP:172.18.75.139:8080 (Flags: )
I0131 14:22:26.484770       1 network_services_controller.go:1855] Successfully added service: TCP:172.18.75.139:7070 (Flags: )
I0131 14:22:26.649749       1 network_services_controller.go:1053] Found an IP 172.18.75.139 which is no longer needed so cleaning up
I0131 14:22:26.668463       1 network_services_controller.go:1088] Found a IPVS service TCP:172.18.75.139:8080 (Flags: [hashed entry]) which is no longer needed so cleaning up
I0131 14:22:26.668695       1 network_services_controller.go:1088] Found a IPVS service TCP:172.18.75.139:7070 (Flags: [hashed entry]) which is no longer needed so cleaning up
```

We have many services with no targets (replica set to 0 for example), so each time there is a pod targeted by a service starting or stopping, hundred of IPVS services are created and immediately deleted.

When you lose some nodes (or drain them), or some pods are stuck in a restart loop, this creates a *lot* of IPVS activity on our nodes, causing production issues (200+ IPVS updates per second).

Here is one endpoint:
```
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2018-12-05T00:57:43Z"
  labels:
    app: xxx
    metrics: jmx
  name: xxx
  namespace: xxx
  resourceVersion: "26742"
  selfLink: /api/v1/namespaces/xxx/endpoints/xxx
  uid: c5bba106-f828-11e8-8bc3-3245140840c2
```

And the associated service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: "2018-12-05T00:57:43Z"
  labels:
    app: xxx
    metrics: jmx
  name: dw-plugins
  namespace: xxx
  resourceVersion: "26741"
spec:
  clusterIP: 172.18.75.139
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jmx-metrics
    port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: xxx
  sessionAffinity: None
  type: ClusterIP

```

**Comment by murali-reddy** [comment]
Thanks for reporting. This is known issue, fix should have gone as part of https://github.com/cloudnativelabs/kube-router/pull/599 which was withdrawn. @roffe Would you mind fixing this issue you have found earlier and fixed it? If you dont have cycles I can take care.

**Comment by renchap** [comment]
I checked #599 and I dont see how it is related. The problem here is that IPVS services are created even if they dont have any endpoints. 

According to https://github.com/cloudnativelabs/kube-router/blob/18769938629dc857692acfd7d11c20dcde81eba6/pkg/controllers/proxy/network_services_controller.go#L844-L847 
this should not happen. I am not very familiar with go but I am trying to add some logging on a custom version to understand why this check is not `true`.

**Comment by murali-reddy** [comment]
#599 at broader level was different problem, but this issue was getting addressed as well.

You are in right direction. 

Please see the conversation here https://kubernetes.slack.com/archives/C8DCQGTSB/p1544779320090200

**Comment by renchap** [comment]
So after adding a debug entry for `svc.local`, it looks like its `false` for all of our services.
I havent been able to find out what the `kube-router.io/service.local` annotation does, but it does not seem a normal behaviour that a service is added and then deleted during the same `sync` call.

One solution would be to not create it, but currently it is always created if not local, but deleted in the following lines because it has no endpoints, without checking if this is a local service.

As there are 2 conditions for the service to be created (being local OR having endpoints), could another solution be to not purge a service that has 0 endpoints but is not local, to match the creation condition? Here : https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/proxy/network_services_controller.go#L1064 & https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/proxy/network_services_controller.go#L1112

**Comment by renchap** [comment]
I did more investigation on this, and the IPVS services creation is not the only problem. Each time a service is called, `ip route` and `ipset` are called. I did a quick strace on a non-heavily loaded cluster:

```
$ time strace -q -f -p 61915 -eexecve -o kube-router-without-fw.trace
^C
real	1m28.205s
user	0m4.449s
sys	0m31.869s

$ grep -Po 'execve\("\K[a-z/]+' kube-router-without-fw.trace  | sort | uniq -c
   6563 /sbin/ip
   9430 /usr/sbin/ipset
```

So 6563 calls to `ip` and 943` calls to `ipset` in 90 seconds, without any real activity (pod start/stop) during this time.

**Comment by menardorama** [comment]
Hi,
I'm the client impacted by this issue.

Did a small test on a single node cluster and orphan services are not created using PR #653 

Please let me know if it's reasonable for you

Thanks

**Comment by murali-reddy** [comment]
this issue is addressed as part of https://github.com/cloudnativelabs/kube-router/commit/54eedcd0490dd28191d53971d9442f57d45da25d

and no longer reproducible in recent releases.  Please reopen if you still encounter any issues
