### ISSUE TITLE
Kube-router as a pure kube-proxy replacement nodeport does not work with calico

### ISSUE THREAD

**Issue by mrrandrade** [cloudnativelabs/kube-router#655]
Hello there.

Because of a major [kube-proxy slowdown](https://github.com/kubernetes/kubernetes/issues/73382) on my system where it was taking more than 10 minutes to update a ipvs service with the new ip, we needed an emergency replacement and we deployed kube router as a kube-proxy replacement because it was **much faster** at updates (although not optimal, but I'd settle to try to figure out why its taking 30 seconds instead of 900 seconds).

We got it working without much problem.Unfortunately, we can't seem to get nodeport to work.

The gotchas:

* kubernetes: 1.12.5
* CNI of choice:**calico** with **networkpolicy** enabled 

Unfortunately it's not possible to fully replace Calico with kube-router's other funcionalities. 

```
/opt/bin/kube-router --kubeconfig /etc/estaleiro/kube-router/node-kubeconfig.yaml --run-service-proxy=true --run-firewall=false --run-router=false --metrics-port 9169 --health-port 20244 -v1
```

Is there a way for them to interoperate in order to make nodeport work again?

**Comment by murali-reddy** [comment]
I can not think of reasons why it would not work. Sorry i need to try to find the problem. Meanwhile do you see any particular case this happening? Like pod's accessing node port? external client accessing node port? etc. Or node port just does not work in any of the cases

**Comment by MarkDeckert** [comment]
Could this be related?  @mrrandrade you might want to look at how calico and kube-router are interacting with the cni plugin conf files in /etc/cni/net.d/

https://github.com/cloudnativelabs/kube-router/issues/684

**Comment by aauren** [comment]
Closing as stale.
