### ISSUE TITLE
Kube Router picks up node.Spec.PodCIDR even though `kube-router.io/pod-cidr=` is specified

### ISSUE THREAD

**Issue by pramodhkp** [cloudnativelabs/kube-router#663]
https://github.com/cloudnativelabs/kube-router/blob/52127e6ccd591a39a43e6af9ff07a79f0a76112f/pkg/controllers/routing/network_routes_controller.go#L560

I'm using Openshift 3.9 and it doesn't add `PodCIDR` to the node spec. Kube-router does provide a way to configure pod CIDR through annotations, but it fails while syncing ipsets. 

Kube-router seems to be still picking up from `node.Spec.PodCIDR` even though annotation on the node is set. This results in an error in kube-router saying:

E0208 05:48:09.476533 1 network_routes_controller.go:262] Error synchronizing ipsets: Failed to sync Pod Subnets ipset: ipset v6.34: Syntax error: cannot parse : resolving to IPv4 address failed

**Comment by bhcleek** [comment]
This was resolved in #720

**Comment by aauren** [comment]
Closing via #720. Thanks @bhcleek!
