### ISSUE TITLE
BGP timer adjustment and RFC7911 add-path support?

### ISSUE THREAD

**Issue by colinfarley** [cloudnativelabs/kube-router#671]
I'm having trouble locating documentation on adjusting BGP hold/keep alive timers and enabling BGP additional paths.

I'm looking to adjust timers from the default to get quicker failure detection.

I'm looking for add-path support in a deployment where a node is configured as a route reflector to avoid a full ibgp session mesh. To advertise multiple next-hops to an external BGP peer over a single BGP session (for ECMP), the add-path BGP extension capability is required. gobgp has support for RFC7911 add-path (https://github.com/osrg/gobgp/blob/master/docs/sources/add-paths.md).

Thanks.

**Comment by aauren** [comment]
kube-router handles the add-path functionality of GoBGP automatically based upon Kubernetes service definitions. Closing as stale.
