### ISSUE TITLE
Question: ClusterIP/ExternalIP only without pod-networking?

### ISSUE THREAD

**Issue by zetsub0u** [cloudnativelabs/kube-router#672]
Hi,

I already have a working pod networking mechanism and i'm running BGP on every node for a full mesh. I was looking at a solution for publishing ClusterIP/ExternalIP as anycast routes in the RIB, is it possible to enable this without the full pod networking? The documentation seem to indicate no.

Would a  PR to support this be welcome?

Thanks.

**Comment by murali-reddy** [comment]
Please try https://cilium.readthedocs.io/en/v1.2/kubernetes/install/kube-router/#deploy-kube-router

```
- --run-router=true
- --run-firewall=false
- --run-service-proxy=false
- --enable-cni=false
- --enable-pod-egress=false
```

this combination should suit to what you are asking. But i suspect you will have conflict for port 179 on the node IP better kube-router and exisiting bgp.

**Comment by zetsub0u** [comment]
Hi, thanks for your comment, suppose i run
