### ISSUE TITLE
Kube-router fail to update ipset and restart

### ISSUE THREAD

**Issue by menardorama** [cloudnativelabs/kube-router#674]
We are having a long running issue on our baremetal cluster.
We are running kube-router as service proxy and we get regular network issues.

Every fex hours, we see this error message in the logs :
`failed to sync ipset: ipset v6.34: Kernel error received: Resource busy`

This error mean for us that kube-router is going to restart and we are going to have a network drop.

This is very annoying, all of our applications are then crashing.

We are running 
- Kubernetes 1.13..2
- Ubuntu 18.04
- Kube-router latest version

kube-router options :
`        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - --metrics-port=8000
        - --bgp-graceful-restart
        - --kubeconfig=/var/lib/kube-router/kubeconfig
`

Is somebody have an idea ?

Thanks a lot

**Comment by murali-reddy** [comment]
> This error mean for us that kube-router is going to restart and we are going to have a network drop.

@menardorama  Why would that happen? Are you using kube-router just for proxy? In which case kube-router is just programming IPVS, Its just control plane. Data path should have no impact

**Comment by menardorama** [comment]
running with 
- router
- firewall
- service proxy

kube-proxy is not running on the nodes

**Comment by murali-reddy** [comment]
ok, reason you are seeing that routes are withdrawn when kube-router pods dies is perhaps you may not enabled bgp-graceful-restart. If you dont are about BGP (like running on AWS) then you can enable it straight away so that data-path is not affected when control-place crashes or restarts.

Also see https://github.com/cloudnativelabs/kube-router/issues/675 to make it enabled by default

**Comment by AdrianBalcan** [comment]
I'm facing the same issue running a cluster with 40+ nodes on Kops AWS while using or not bgp-graceful-restart flag on kube-router.

**Comment by aauren** [comment]
Closing as stale. If you are still experiencing an issue related to this, please test using a recent version of kube-router 1.0.0-rc* and re-open with additional specifics from your run.
