### ISSUE TITLE
Allow Default Policy for KUBE-ROUTER-SERVICES to be Configurable

### ISSUE THREAD

**Issue by cjewgit** [cloudnativelabs/kube-router#678]
Hello,

since issue #602 was fixed in 0.2.4, `KUBE-ROUTER-SERVICES` introduces a default accept for services.

This unfortunately opens all services to the world. Is there any chance to make this change optional? 

Thanks
Chris

**Comment by murali-reddy** [comment]
Sure. For next release we will make this optional.

**Comment by cjewgit** [comment]
I can't see this in the new 0.3.0 release-notes. Was this implemented by any chance?

Thanks
Chris

**Comment by aauren** [comment]
This should have been fixed in #891 when we started applying network policy to the INPUT chain. Please re-open if this is still an issue with the 1.0 release.
