### ISSUE TITLE
firewalld blocks connections across subnets

### ISSUE THREAD

**Issue by amdonov** [cloudnativelabs/kube-router#681]
Related to #602 and #610

I'm running v0.2.5 in AWS with Kubernetes v1.13.3 on RHEL 7.6. We're running a cluster across three availability zones with one subnet per AZ. I'm able to connect to pods running within the same subnet, but I cannot communicate with pods running in different subnets. It all works great when I stop firewalld.

Also, I'm not running kube-proxy. We're using kube-router for services too.

I'm happy to provide log information, iptables dumps, etc.

Thanks!

**Comment by mk01** [comment]
@amdonov 

is the SG (SG in AWS attached to nodes) allowing Protocol 4 between the nodes?

**Comment by amdonov** [comment]
Yes. I wanted to rule that out, so I opened all ports and protocols for 10.0.0.0/8. The subnets for the nodes are 10.0.11.0/26, 10.0.11.64/26, and 10.0.11.128/26, . My pod network cidr is 10.208.0.0/16, and my service cidr is 10.192.0.0/12.

I feel reasonably confident that it's firewalld causing the problem given that stopping it solves the problem.

**Comment by aauren** [comment]
Closing this as stale. If you're still experiencing issues with the latest versions of kube-router and firewalld and are interested in troubleshooting this some more, please re-open.
