### ISSUE TITLE
kube-router iptables rule for ICMP breaks PMTU

### ISSUE THREAD

**Issue by thardie** [cloudnativelabs/kube-router#685]
The following rule the kube-router adds by default:

`ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            /* allow icmp echo requests to service IPs */ icmptype 8`

breaks ICMP unreachable - must fragment:

```02:09:46.233125 IP 10.104.10.66.4506 > 10.100.27.10.37742: Flags [.], seq 108:1556, ack 1161, win 244, options [nop,nop,TS val 90047081 ecr 302705102], length 1448
02:09:46.238984 IP 10.104.27.1 > 10.104.10.66: ICMP 10.100.27.10 unreachable - need to frag (mtu 1476), length 36
02:09:46.769167 IP 10.104.10.66.4506 > 10.100.27.10.37742: Flags [.], seq 108:1556, ack 1161, win 244, options [nop,nop,TS val 90047215 ecr 302705102], length 1448
02:09:46.769416 IP 10.104.27.1 > 10.104.10.66: ICMP 10.100.27.10 unreachable - need to frag (mtu 1476), length 36
```

Proved this by adding the following rule before in chain KUBE-ROUTER-SERVICES, it works again:

`ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0`

Should change the above rule to allow unreachable as well as echo.

**Comment by asteven** [comment]
I guess the simplest thing would be to not handle icmp at all. You could no longer ping service IPs, but question is if that made sense in the first place.

**Comment by thardie** [comment]
Can we just add another rule to allow icmp unreachables through?

**Comment by asteven** [comment]
Looking at e.g. http://shouldiblockicmp.com/ - should we allow all of those that we think may be useful? Who decides which ones are useful?

I come to believe that ICMP firewalling should not happen at the service IP level. IMHO this not something a CNI provider can address. Instead the policy should be defined at the host level as part of deployment.

@uablrek, @bazuchan, @murali-reddy  Would be great if you could share your opinion.

**Comment by Cytrian** [comment]
I just searched for hours, tcpdumped every connection in our datacenter to finally find this issue and resolve my problem. There's a GRE tunnel between office and datacenter, so MTU discovery is really necessary. So please allow ICMP packets.

**Comment by asteven** [comment]
@Cytrian if you need MTU discovery working in your environment then why don't you configure it on your host? Is something that kube-router does stopping you from doing so?

**Comment by thardie** [comment]
I suggest you read this article on the subject: https://blog.cloudflare.com/path-mtu-discovery-in-practice/

**Comment by asteven** [comment]
I think the following would be cleanest solution:

We replace the current rule that directs traffic into the KUBE-ROUTER-SERVICES chain:

```
-A INPUT -m comment --comment "handle traffic to IPVS service IPs in custom chain" -m set --match-set kube-router-service-ips dst -j KUBE-ROUTER-SERVICES
```

with

```
-A INPUT -m comment --comment "handle traffic to IPVS service IPs in custom chain" ! -p icmp -m set --match-set kube-router-service-ips dst -j KUBE-ROUTER-SERVICES
```

That is, we do not handle ICMP at all. We neither allow it, nor block it.
Up to you what you do with it.

@thardie can you please try if your setup works after running the following commands?

```
iptables -D INPUT -m comment --comment "handle traffic to IPVS service IPs in custom chain" -m set --match-set kube-router-service-ips dst -j KUBE-ROUTER-SERVICES

iptables -A INPUT -m comment --comment "handle traffic to IPVS service IPs in custom chain" ! -p icmp -m set --match-set kube-router-service-ips dst -j KUBE-ROUTER-SERVICES
```

**Comment by thardie** [comment]
I'll try this in the next day or so.

**Comment by bazuchan** [comment]
Any news here? Just hit same problem.

@murali-reddy is there reason why DSR services use fwmark ipvs entries? Looks like pmtu is broken for DSR services even if allowed in FW.

**Comment by asteven** [comment]
@bazuchan well this ticket is basically in: waiting for user feedback state. Personally I would have long closed it, but I cant. So if you care and want to test the proposed solution, go ahead and please give feedback.

If it works, create a PR. Or ping me and I will do it.

**Comment by bryanalves** [comment]
I ran into a similar issue (connecting to services via an ipsec tunnel), and missed this firewall rule when diagnosing.

asteven's suggestion above fixes this for me, so I would be in favor of allowing more icmp rules through so that PMTU works again.

**Comment by bazuchan** [comment]
I made PR with a bit different rules.

But it is still doesn't work for DSR (tunneled) services, probably because of fmarked ipvs services.

**Comment by aauren** [comment]
Adding to the 1.2 release as I think that this should be an easy win for that release.

**Comment by thardie** [comment]
Sorry I can't try this any more. The company I was working for that had this scenario is to more.

**Comment by aauren** [comment]
No worries, it's our bad for taking so long to come around to it. I agree with the overall gist of the issue and there's even a PR that's been submitted to address non-DSR functionality. We'll take it from here.
