### ISSUE TITLE
ipset kube-router-ipvs-services stops being updated

### ISSUE THREAD

**Issue by thardie** [cloudnativelabs/kube-router#686]
After some event (which is unknown), the main ipset (kube-router-ipvs-services) stops being updated, meaning deleted services are left in the set and new services are not added. The following is in the logs on the affected workers:

`E0307 01:38:56.058220   33061 network_services_controller.go:1135] Error syncing ipvs svc iptable rules: failed to sync ipset: ipset v6.34: Syntax error: cannot parse <nil>: resolving to IPv4 address failed`

**Comment by thardie** [comment]
I think the error might be a red-herring, but I still have the issue. I've tried deleting and re-creating my service. The service IP gets added to the ipset kube-router-service-ips, but the specific ports do not get added or removed to the set kube-router-ipvs-services.

```
# kubectl describe svc -n salt
Name:                     salt-master-service
Namespace:                salt
Labels:                   <none>
Selector:                 app=salt-master
Type:                     LoadBalancer
IP:                       10.253.51.155
LoadBalancer Ingress:     10.104.10.66
Port:                     publisher  4505/TCP
TargetPort:               4505/TCP
NodePort:                 publisher  31139/TCP
Endpoints:                10.254.2.228:4505
Port:                     request-server  4506/TCP
TargetPort:               4506/TCP
NodePort:                 request-server  31084/TCP
Endpoints:                10.254.2.228:4506
Port:                     api-server  8000/TCP
TargetPort:               8000/TCP
NodePort:                 api-server  30509/TCP
Endpoints:                10.254.2.228:8000
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30670
Events:                   <none>
```

```
# ipset list kube-router-service-ips|grep 10.104.10.66

10.104.10.66 timeout 0
```

```
# ipset list kube-router-ipvs-services|grep 10.104.10.66

```

**Comment by asteven** [comment]
Do you happen to be using named ports?

**Comment by thardie** [comment]
Here's a dump of the service definition. The ports have names in the service - Is that what you mean?

```
# kubectl get svc -n salt -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-03-07T01:28:33Z"
    name: salt-master-service
    namespace: salt
    resourceVersion: "10085193"
    selfLink: /api/v1/namespaces/salt/services/salt-master-service
    uid: 52393fad-4078-11e9-beca-7cd30acde1d4
  spec:
    clusterIP: 10.253.51.155
    externalTrafficPolicy: Local
    healthCheckNodePort: 30670
    ports:
    - name: publisher
      nodePort: 31139
      port: 4505
      protocol: TCP
      targetPort: 4505
    - name: request-server
      nodePort: 31084
      port: 4506
      protocol: TCP
      targetPort: 4506
    - name: api-server
      nodePort: 30509
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: salt-master
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 10.104.10.66
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by asteven** [comment]
I think is was mixing something related to network policies.

**Comment by asteven** [comment]
> 
> `E0307 01:38:56.058220 33061 network_services_controller.go:1135] Error syncing ipvs svc iptable rules: failed to sync ipset: ipset v6.34: Syntax error: cannot parse <nil>: resolving to IPv4 address failed`

Looking at the code, the logged error is probably the cause of the issue you are having.

```
# pkg/controllers/proxy/network_services_controller.go
...
    serviceIPsIPSet := nsc.ipsetMap[serviceIPsIPSetName]
    err = serviceIPsIPSet.Refresh(serviceIPsSets, utils.OptionTimeout, "0")
    if err != nil {
        return fmt.Errorf("failed to sync ipset: %s", err.Error())
    }

    ipvsServicesIPSet := nsc.ipsetMap[ipvsServicesIPSetName]
    err = ipvsServicesIPSet.Refresh(ipvsServicesSets, utils.OptionTimeout, "0")
    if err != nil {
        return fmt.Errorf("failed to sync ipset: %s", err.Error())
    }
...
```

If the error comes from the call to 'serviceIPsIPSet.Refresh', the later code which should sync the ips and ports (ipvsServicesIPSet.Refresh) will never run. Question is where does the error come from and how can I reproduce it.

Either way, the code needs some (debug) logging. e.g. the value of serviceIPsSets before trying to refresh the kube-router-service-ips ipset.

Patch request would be very welcome.

**Comment by thardie** [comment]
I'd have to get a debug environment set up to corner which case it is and the reason for the nil. Not sure when/if I'll get time for that, but may have to.

**Comment by aauren** [comment]
Closing as stale, but if you still have this issue with a current version of kube-router and are interested in debugging this further, please re-open.
