### ISSUE TITLE
Invalid kube-bridge IP address (old PodCIDR) after worker reboot

### ISSUE THREAD

**Issue by def0def0** [cloudnativelabs/kube-router#689]
We are running kube-router as daemonset on Kubernetes 1.11.1. When restarting one of the worker nodes the worker is assigned a new PodCIDR subnet but kube-bridge interface still has an IP from the old one.

I could solve the issue by deleting the IP AND restarting both docker and kubelet. Restarting kube-router pod, deleting kube-router pod or restarting kubelet only was not sufficient.

kube-router is set up according to the Host Port guide https://www.kube-router.io/docs/user-guide/#hostport-support and referenced yaml https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/kubeadm-kuberouter-all-features-hostport.yaml

Looks similar to previous issue https://github.com/cloudnativelabs/kube-router/issues/496 however this node was not deleted just restarted. Happened with two different nodes this week already.

**Comment by RaveNoX** [comment]
Add `forceAddress: true` to your configuration (by `kubectl -n kube-system edit cm kube-router-cfg` command).
For example if you have default configuration like:
```json
{
    "name":"mynet",
    "type":"bridge",
    "bridge":"kube-bridge",
    "isDefaultGateway":true,
    "ipam": {
        "type":"host-local"
     }
}
```
it must be changed to:
```json
{
    "name":"mynet",
    "type":"bridge",
    "bridge":"kube-bridge",
    "isDefaultGateway":true,
    "forceAddress": true,
    "ipam": {
        "type":"host-local"
     }
}
```

By the way, kube-router not manges bridge by itself, it delegates bridge mangement to the standard cni bridge plugin.
Configuration options of the standard bridge plugin you can see [here](https://github.com/containernetworking/plugins/tree/master/plugins/main/bridge)

**Comment by def0def0** [comment]
Thanks a lot for clearing this up, I had no clue this config is passed to bridge plugin, kube-router documentation doesn't mention this. 
After setting the forceAddress option in CM and restarting the worker I still saw addresses from old podCIDR range. I could see new podCIDR in /etc/cni/net.d/10-kuberouter.conflist however the forceAddress option was not present. I had to delete the config file and then kube-router pod so it's initialized again and the file is created fresh. After that I had to restart docker to restart the running pods and then finally they got new IP address. Is this behavior expected?

**Comment by RaveNoX** [comment]
Sorry, I forgot that the config is generated only if it does not exist yet (you can change this behaviour by changing daemonset: https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/kubeadm-kuberouter-all-features-hostport.yaml#L98 ).

Not sure that changing Pod CIDR is major issue than must to be fixed by kube-router.
Changing Pod CIDR should be not so frequent action in k8s clusters and should be performed carefully because it may hit running PODs.

Anyway, the final decision on this issue remains on the kube-router team.

**Comment by def0def0** [comment]
Ah, you are right, I forgot that line in the daemonset definition.

PodCIDR change is not something happening in common, but we are probably facing some issue - when rebooting the worker the node disappears from the cluster and after reboot it gets back as new node, that's why it gets new podCIDR I guess. On the other hand I don't think the podCIDR is something the node is guaranteed to get get till the end of the days.

I suppose this issue can be closed, as it looks it's not related to kube-router but to the CNI bridge plugin.

Thank you for your help @RaveNoX
