### ISSUE TITLE
--masquerade-all=false doesn't ensure it is disabled

### ISSUE THREAD

**Issue by lucasmundim** [cloudnativelabs/kube-router#691]
When a node is previously started with --masquerade-all flag enabled and then you disable it.

## Expected Behavior
iptables rule to masquerade all outbound IPVS traffic should be cleaned up.

## Current Behavior
iptables rule to masquerade all outbound IPVS traffic is left intact and probably cause unwanted behavior.

**Comment by aauren** [comment]
Fixed via #665. Thanks again @lucasmundim!
