### ISSUE TITLE
Using kube-router offline

### ISSUE THREAD

**Issue by tyilk** [cloudnativelabs/kube-router#693]
Can kube-router be used offline? I'm building on bare metal using kubeadm in a network without internet access.

I've loaded the busybox and kube-router images into the local Docker but "kubectl describe" on my kube-router pod shows "Failed to pull image "busybox": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/ ..."

I've removed both "imagePullPolicy: Always" lines from kubeadm-kuberouter-all-features.yaml without success.

**Comment by murali-reddy** [comment]
Please make sure busybox image is available as well

https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/kubeadm-kuberouter-all-features.yaml#L77

Other than that kube-router by itself does not need to be online. Once image is available on the node, kube-router process running on the pod does not require any internet access

**Comment by tyilk** [comment]
Thanks for the reply, I got it working by retagging both images in a local registry and tweaking kube-router's .yaml to pull those.

**Comment by murali-reddy** [comment]
thanks for the update
