### ISSUE TITLE
Kube-router does not support subnet 169.254.0.0/16

### ISSUE THREAD

**Issue by qiaoenxin** [cloudnativelabs/kube-router#694]
When I set subnet 169.254.0.0/16， the pods can communicate with each other. But the Service can not communicate with pods.

I create cluster with kubeadm.
kubeadm init --config kubeconfig.yaml

The kubeconfig.yaml like this.

apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.4
networking:
  podSubnet: "169.254.128.0/17"
  serviceSubnet: "169.254.64.0/18"

**Comment by asteven** [comment]
169.254.0.0/16 is reserved for link local addresses by RFC 5735.
Possibly you are seeing some side effect of (ab)using this network for a different purpose?

**Comment by qiaoenxin** [comment]
> 169.254.0.0/16 is reserved for link local addresses by RFC 5735.
> Possibly you are seeing some side effect of (ab)using this network for a different purpose?

   I use this subnet to avoid being confilcting with existing network.

**Comment by aauren** [comment]
Closing as stale, but I would, in general, agree with asteven. There are many things that count on the 169 address being used as defined in the RFC and you are likely to encounter multiple problems in devising networks like this.
