### ISSUE TITLE
Support for external BGP peer info to be passed to kube-router

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#7]
Add support for configuring a BGP peer information. Kube-router on each node will peer with provide external peer. Once peered, external peer will know how to route traffic to the pods with in the cluster.

This will enable use-case where external access to the pods are required.

Also cluster IP for the servces can be advertised, so external access to the services through the cluster IP can be achived.

**Comment by rmb938** [comment]
Having the option to only advertise the server cluster IP network when using another cni for pod networking would be useful.

Currently my kube clusters are using calico cni for BGP peering and I would like to use kube-router just to manage the service network.

**Comment by murali-reddy** [comment]
@rmb938 i wil think about it. With CNI plugins like Flannel, Weave this can be done because they dont do any routing. But if you have to use kube-router for service proxy and calico for pod-networking then things will be tricky. As calico CNI will be running its BGP on the node.

**Comment by murali-reddy** [comment]
This issue is fixed with commit 	#40f86e78

But this will only work when kube-router is running iBGP.  I will open a different bug to investigate for cases kube-router is just ruuning IPVS service proxy but be able to advertise cluster IP through CNI plug-in providing pod networking.
