### ISSUE TITLE
sync iptables is taking more than 3 min

### ISSUE THREAD

**Issue by sohel2020** [cloudnativelabs/kube-router#702]
I recently update my cluster OS. Previously I was using iptables version `iptables v1.4.21`. After my OS upgrade, I got `iptables v1.6.2`.

In v1.4.21 kube-router tooks 30s to be sync but in v1.6.2 it is taking more than 3 min. Because of Iptables contention, my kube-proxy is unable to grab iptables lock file and continuously crashing. 

In same cluster I'hv added Both IPtables versions instance for troubleshooting:
**iptables v1.6.2 output:**  sync iptables took 3m43.650719334s
**iptables v1.4.21 output:** sync iptables took 35.792316738s

**kuber-router version:** Running /opt/bin/kube-router version v0.2.0-7-g05907d8d-dirty, built on 2018-10-03T12:32:47+0600, go1.10.3

**Note:** I'm only using kube-router as a network policy controller.

**OS** 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2023.4.0
VERSION_ID=2023.4.0
BUILD_ID=2019-02-26-0032
PRETTY_NAME="Container Linux by CoreOS 2023.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Comment by sohel2020** [comment]
I double checked and I can confirm that it is something related with iptables version v1.6.2 and kube-router.

**Comment by aauren** [comment]
Closing as stale. On newer versions of kube-router and iptables I cannot reproduce this issue. If you're still able to reproduce it with newer versions of both, please re-open. Additionally, we are already tracking iptables performance issues with kube-router more generally other places, namely: #585
