### ISSUE TITLE
--set option deprecated, please use --match-set

### ISSUE THREAD

**Issue by sohel2020** [cloudnativelabs/kube-router#704]
I'm getting following error
`  Error syncing network policy for the update to pod: jcx-inst-fsgzx7fbcwlsjvadco0ylo/init-190405114807 Error: Aborting sync. Failed to sync network policy chains: Failed to run iptables command: running [/sbin/iptables -t filter -A KUBE-NWPLCY-BVOJZRDBHS52P4QD -m comment --comment "rule to ACCEPT traffic from source pods to specified ipBlocks selected by policy name: jcx-vpn-policy namespace jcx-inst-gobtvqusm1mqvurnxeabeh" -m set --match-set KUBE-SRC-QJODVQYJKUCMMIDY src -m set --set KUBE-DST-UZHCBIYQNUZ5SQSI dst -j ACCEPT --wait]: exit status 4: --set option deprecated, please use --match-set
    --set option deprecated, please use --match-set
    iptables: Resource temporarily unavailable.`

**kube-router version:** v0.2.5

Following commnad I'm using to run kube-router:
`/usr/bin/docker run --rm --privileged --net=host --name kube-router \
    -v /var/lib/kubelet:/var/lib/kubelet \
    -v /etc/kubernetes/ssl:/etc/kubernetes/ssl \
    -v /lib/modules:/lib/modules \
    docker.io/cloudnativelabs/kube-router:v0.2.5 \
    --run-router=false --run-firewall=true --run-service-proxy=false \
    --kubeconfig=/var/lib/kubelet/kubeconfig --metrics-port=8080 --metrics-path="/metrics" --v=2`

**Comment by soumeng09** [comment]
@sohel2020 what was the resolution for this?

**Comment by aauren** [comment]
@soumeng09 I believe that this likely only affects some people and not others based upon the iptables modules that they enable. However, all the same, #874 should remove the last bits of `--set` ipset logic.
