### ISSUE TITLE
Add option to SNAT Egress traffic to LoadbalancerIP

### ISSUE THREAD

**Issue by tbe** [cloudnativelabs/kube-router#705]
For some services, it is required to use the external IP of the service (mail clusters for example).

This could be done with an annotation, for example `kube-router/symetric-nat: true`

**Comment by aauren** [comment]
Have you reviewed #668 to see if this would mitigate your issue?

**Comment by tbe** [comment]
Yes, but that does only replace MASQUERADE with SNAT and the current HostIP. It does not allow "custom" SNAT rules.

**Comment by noillir** [comment]
same issue: https://github.com/cloudnativelabs/kube-router/issues/434

**Comment by aauren** [comment]
Closing in favor of #434
