### ISSUE TITLE
Add ability to use node labels to set node level config

### ISSUE THREAD

**Issue by mightwork** [cloudnativelabs/kube-router#710]
Kops currently does not support adding node annotation from the InstanceGroup spec [Issue](https://github.com/kubernetes/kops/issues/6026) 

If kube-router were to identify node level configs from node labels along with node annotations, we can use kops to set default node labels for each auto-scaling group. kube-router will then have all the required node configs at the time of pod creation. This will also help automate operations like setting up route reflector server/client as the node will now have required labels at the time of creation, avoiding the current flow of applying annotations manually on each node and restarting kube-router, something which is not feasible in the case of auto-scaling.

**Comment by asteven** [comment]
To me it sounds like you are saying: kops doesn't support this feature, please work around it in kube-router.
Wouldn't this be better solved with a FR or (better yet PR) to kops?

**Comment by aauren** [comment]
Closing as stale.
