### ISSUE TITLE
User "nodeclient" cannot list networkpolicies.networking.k8s.io at the cluster scope

### ISSUE THREAD

**Issue by jjrdev** [cloudnativelabs/kube-router#711]
after applying the azure aks demonset yaml here kubectl apply -f https://raw.githubusercontent.com/marrobi/kube-router/marrobi/aks-yaml/daemonset/kube-router-firewall-daemonset-aks.yaml to an Azure AKS Cluster with RBAC

initially the pods start but then when a simple network policy is applied start failing..

github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "nodeclient" cannot list networkpolicies.networking.k8s.io at the cluster scope

**Comment by Daryltp** [comment]
Did you find a solution to this problem? I am experiencing the same.

**Comment by MarcosMMartinez** [comment]
[kube-router-deploy.yml.txt](https://github.com/cloudnativelabs/kube-router/files/3253908/kube-router-deploy.yml.txt)

@murali-reddy @bzub @roffe @andrewsykim 

See the attached deployment yaml being used. Despite assigning the appropriate service account with appropriate perms, the kube-router logs show that User "nodeclient" is the service account with permission issue? 

It seems that this is the system:node service account. Why would this service account be leveraged under these circumstances? 
= We tried modifying the perms of this service account and we're able to resolve this issue, i.e. the kube-router pods do not eventually go into CrashLoopBackOff.

But that begs the question: why do we have to make these modifications to get kube-router to work?

**Comment by andrewsykim** [comment]
Looks like something is misconfigured on your cluster if the correct service account config on your DaemonSet is not being propagated to the pod. 

> But that begs the question: why do we have to make these modifications to get kube-router to work?

You don't have to configure RBAC if you don't want, but in most clusters it's important to configure it so kube-router can only access resources it cares about

**Comment by andrewsykim** [comment]
@jjrdev for the spec you posted (https://raw.githubusercontent.com/marrobi/kube-router/marrobi/aks-yaml/daemonset/kube-router-firewall-daemonset-aks.yaml), the error makes sense because it doesn't look like you assigned a service account to the DaemonSet at all

**Comment by MarcosMMartinez** [comment]
@andrewsykim 

Everything seems to check out on my end - still not sure what could be the cause of the issue. There seems to be so hard-coded, inherent tendency to use the system:node service account?

marcos@Azure:~$ kubectl describe **pod/kube-router-bfmc8** -n kube-system
~
**Controlled By:      DaemonSet/kube-router**
~
    Mounts:
      /etc/kubernetes/certs/ from kubecerts (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-router/kubeconfig from kubeconfig (ro)
      **/var/run/secrets/kubernetes.io/serviceaccount from kube-router-token-crktm (ro)**

marcos@Azure:~$ kubectl get serviceaccounts -n kube-system kube-router -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-06-04T17:55:52Z"
  name: kube-router
  namespace: kube-system
  resourceVersion: "7809711"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/kube-router
  uid: fe60bcaa-86f1-11e9-9d3a-ae8ed3ad49bb
secrets:
**- name: kube-router-token-crktm**


marcos@Azure:~$ kubectl get clusterrole kube-router -o yaml
apiVersion: rbac.authorization.k8s.io/v1
**kind: ClusterRole**
metadata:
  creationTimestamp: "2019-06-04T17:55:52Z"
  **name: kube-router**
  resourceVersion: "7809712"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/kube-router
  uid: fe799fe3-86f1-11e9-9d3a-ae8ed3ad49bb
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - nodes
  - endpoints
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - extensions
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch


marcos@Azure:~$ kubectl get clusterrolebinding kube-router -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: **ClusterRoleBinding**
metadata:
  creationTimestamp: "2019-06-04T17:55:52Z"
  name: kube-router
  resourceVersion: "7809713"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kube-router
  uid: fe89920e-86f1-11e9-9d3a-ae8ed3ad49bb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  **kind: ClusterRole
  name: kube-router**
subjects:
**- kind: ServiceAccount
  name: kube-router**
  namespace: kube-system

**Comment by andrewsykim** [comment]
What about the contents in `/var/lib/kube-router/kubeconfig`?

**Comment by MarcosMMartinez** [comment]
This is what we have:

marcos@Azure:~$ kubectl exec kube-router-bfmc8 -n kube-system -- cat /var/lib/kube-router/kubeconfig
apiVersion: v1
kind: Config
clusters:
- name: localcluster
  cluster:
    certificate-authority: /etc/kubernetes/certs/ca.crt
    server: https://aks-126-nginx-rbac-eus-dns-ca60928f.hcp.eastus.azmk8s.io:443
users:
- name: client
  user:
    client-certificate: /etc/kubernetes/certs/client.crt
    client-key: /etc/kubernetes/certs/client.key
contexts:
- context:
    cluster: localcluster
    user: client
  name: localclustercontext
current-context: localclustercontext

**Comment by andrewsykim** [comment]
What's the user specified from that kubeconfig? Will be the CN of the client certificate.

**Comment by MarcosMMartinez** [comment]
@andrewsykim You lost me there - can you elaborate?

**Comment by hatboyzero** [comment]
So, the CN - or Common Name - of the certificate referenced in the kubeconfig is "nodeclient".  I've verified this myself.  What this is telling me is that calls made by kube-router to fetch NetworkPolicy resources and such are using the identity specified in the kubeconfig client certificate and not the service account associated with the pod.

**Comment by hatboyzero** [comment]
A brief update - I resolved this issue on my end by creating a new kubeconfig file in a ConfigMap and using that instead of the node hosted kubeconfig (which was what was being used in the example above).  My kubeconfig is constructed as follows (I am provisioning this via terraform - hence the variable for server).

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-router-cfg
  namespace: kube-system
  labels:
    tier: node
    k8s-app: kube-router
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: cluster
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: ${azurerm_kubernetes_cluster.main.kube_config.0.host}
    users:
    - name: kube-router
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: cluster
        user: kube-router
      name: kube-router-context
    current-context: kube-router-context
```

And then I am mounting said ConfigMap as a volume in the appropriate location for kube-router to find it.
