### ISSUE TITLE
kube-router pods crash when api server restarts/goes down

### ISSUE THREAD

**Issue by MarkDeckert** [cloudnativelabs/kube-router#712]
# Kube-router version
0.2.5

# kubernetes version
1.13.5 bare metal

# Features
All features enabled

# Problem
If API server is down/unavailable, kube-router pods often crash. This causes any incoming cluster traffic that depends on the proxy to fail.

# Error message:

> client-go/informers/factory.go:73: Unexpected watch close - watch lasted less than a second and no items received                                                                                                                       [5/1248]
W0402 16:53:17.623971       1 reflector.go:334] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.NetworkPolicy ended with: very short watch: github.com/cloudnativelabs/kube-router/vendor/k
8s.io/client-go/informers/factory.go:73: Unexpected watch close - watch lasted less than a second and no items received
W0402 16:53:17.624008       1 reflector.go:334] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.Pod ended with: very short watch: github.com/cloudnativelabs/kube-router/vendor/k8s.io/clie
nt-go/informers/factory.go:73: Unexpected watch close - watch lasted less than a second and no items received
W0402 16:53:17.624033       1 reflector.go:334] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.Endpoints ended with: very short watch: github.com/cloudnativelabs/kube-router/vendor/k8s.i
o/client-go/informers/factory.go:73: Unexpected watch close - watch lasted less than a second and no items received
W0402 16:53:17.624060       1 reflector.go:334] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.Namespace ended with: very short watch: github.com/cloudnativelabs/kube-router/vendor/k8s.i
o/client-go/informers/factory.go:73: Unexpected watch close - watch lasted less than a second and no items received
W0402 16:53:17.624083       1 reflector.go:334] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.Node ended with: very short watch: github.com/cloudnativelabs/kube-router/vendor/k8s.io/cli
ent-go/informers/factory.go:73: Unexpected watch close - watch lasted less than a second and no items received
E0402 16:55:23.551582       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=105, ErrCode=NO_ERROR, debug=""
E0402 16:55:23.551979       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=105, ErrCode=NO_ERROR, debug=""
E0402 16:55:23.552158       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=105, ErrCode=NO_ERROR, debug=""
E0402 16:55:23.552289       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=105, ErrCode=NO_ERROR, debug=""
E0402 16:55:23.552560       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=105, ErrCode=NO_ERROR, debug=""
E0402 16:55:23.555834       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=105, ErrCode=NO_ERROR, debug=""
W0402 16:55:24.152872       1 reflector.go:334] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.NetworkPolicy ended with: too old resource version: 32941719 (35943704)
W0402 16:55:24.152989       1 reflector.go:334] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.Service ended with: too old resource version: 35943039 (35943701)
E0402 16:55:33.558249       1 reflector.go:315] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to watch *v1.Namespace: Get https://10.13.158.148:6443/api/v1/namespaces?resourceVersion=34897293
&timeoutSeconds=315&watch=true: net/http: TLS handshake timeout
E0402 16:55:33.558289       1 reflector.go:315] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to watch *v1.Pod: Get https://10.13.158.148:6443/api/v1/pods?resourceVersion=35944174&timeoutSeco
nds=590&watch=true: net/http: TLS handshake timeout
E0402 16:55:33.558316       1 reflector.go:315] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to watch *v1.Endpoints: Get https://10.13.158.148:6443/api/v1/endpoints?resourceVersion=35944177&
timeoutSeconds=414&watch=true: net/http: TLS handshake timeout
time="2019-04-02T16:55:34Z" level=info msg="peer graceful restart" Key=10.13.158.106 State=BGP_FSM_ESTABLISHED Topic=Peer
time="2019-04-02T16:55:34Z" level=info msg="Peer Down" Key=10.13.158.106 Reason=graceful-restart State=BGP_FSM_ESTABLISHED Topic=Peer
time="2019-04-02T16:55:34Z" level=info msg="peer graceful restart" Key=10.13.158.79 State=BGP_FSM_ESTABLISHED Topic=Peer
time="2019-04-02T16:55:34Z" level=info msg="Peer Down" Key=10.13.158.79 Reason=graceful-restart State=BGP_FSM_ESTABLISHED Topic=Peer
E0402 16:55:39.177577       1 runtime.go:66] Observed a panic: &runtime.TypeAssertionError{interfaceString:"interface {}", concreteString:"cache.DeletedFinalStateUnknown", assertedString:"*v1.Pod", missingMethod:""} (interface conversion: i
nterface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/asm_amd64.s:573
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/panic.go:502
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/iface.go:252
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:172
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1557
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:209
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:544
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/asm_amd64.s:2361
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod [recovered]
        panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod
goroutine 119 [running]:
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x16ab340, 0xc4206cf440)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).OnPodUpdate(0xc4202a8000, 0x173ac40, 0xc422cf8240)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:172 +0x334
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).newPodEventHandler.func3(0x173ac40, 0xc422cf8240)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1557 +0x3e
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(0xc42043aa20, 0xc42043aa60, 0xc42043ab30, 0x173ac40, 0xc422cf8240)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:209 +0x49
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc420b97400)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:544 +0x205
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).(github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.run)-fm()
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383 +0x2a
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc420635100, 0xc42043b200)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

**Comment by MarkDeckert** [comment]
I'm not understanding the complexity sufficiently to understand why a "cache.DeletedFinalStateUnknown" is being passed instead of a pod object, but I've submitted a PR to hopefully handle the panic and prevent a crash:  https://github.com/cloudnativelabs/kube-router/pull/714

**Comment by renaudhager** [comment]
Hi,

I also noticed that Kuberouter is not happy (failing its liveness probe) when API server is not responding. Have you had the opportunity to test your fix?

**Comment by MarkDeckert** [comment]
@renaudhager unfortunately I haven't been able to successfully build the latest version of kube-router with or without this change.  Not sure how people are managing to do that.

The PR i submitted may or may not completely fix the crashing since there are other interface casts for different objects in there without proper error checking.  The fix I added would only catch the one for pods, since I wanted to keep this minimal.  And since I can't build the latest version I'm unable to test and check out the other casts.

Also in my case it's not the liveness check failing since its a runtime error.  The pod immediately restarts.

There are also other reasons why your kube-router might be failing the liveness probe when the API server doesn't respond.  There are heartbeat checks for various things that will cause it to fail if something is down.  Especially I noticed if you turn on metrics.  The metrics heartbeat is a flat 30 seconds to fail.

**Comment by renaudhager** [comment]
@MarkDeckert Thanks for your reply.
I found this https://github.com/cloudnativelabs/kube-router/issues/651#issuecomment-458416622 and it solves my issue.

**Comment by atibdialpad** [comment]
Any updates on this ? 
Can the kube-router be made to run even if the api-server is unreachable and not crash w/o having to make the checks at all places (PR by @MarkDeckert ).
Today if I look at Kublet for example, it keeps on running inspite of api-server stopping/starting..

**Comment by murali-reddy** [comment]
@atibdialpad https://github.com/cloudnativelabs/kube-router/issues/810 should have fixed this. 

https://github.com/cloudnativelabs/kube-router/releases/tag/v1.0.0-rc1 has this fix please try out

**Comment by atibdialpad** [comment]
Thanks @murali-reddy 
I see the code changes in bgp_policies.go and NRC but no changes in NPC. I hope NPC is also taken care of

**Comment by atibdialpad** [comment]
@murali-reddy @renaudhager 
I see the code changes in bgp_policies.go and NRC but no changes in NPC. I hope NPC is also taken care of ? 
Basically my question is does this fix take care of all places/all controllers or only NRC ?

**Comment by murali-reddy** [comment]
> Basically my question is does this fix take care of all places/all controllers or only NRC ?

@atibdialpad did you try out v1.0.0-rc1  with the fix?

**Comment by atibdialpad** [comment]
@murali-reddy 
I have some custom changes in kr code, so I am sort of stuck with version 0.3.1
https://github.com/cloudnativelabs/kube-router/compare/master...atibdialpad:bgp_policy_fix

I will need to build the 0.3.1. image with this patch and test. Shall do that and come back.
I have basic 2 doubts on the fix proposed here :
1. I fell this might not fix all places where we depend on the api sever. Shall test my case at least and report back
2. api-server is supposed to be the brain of the system and the slave nodes shd get all info from it. In this fix, we are storing some info in the context of the controllers (eg. nrc.PodCidr).. its a fair assumption that pod_cidr won't change but still, It looks slightly off the design.

**Comment by murali-reddy** [comment]
> its a fair assumption that pod_cidr won't change but still, It looks slightly off the design.

No it wont change. Kube-controller-manger does the IPAM and allocates subnet to each node. Unless a node is deleted assignement will remain. Fix simply removed the code which was reading the pod CIDR from the node object read from the API server to cached value.

NPC does not require pod CIDR so it never reads it. Looing at the code all the instances (which read pod CIDR directly from API server) are removed now.

**Comment by atibdialpad** [comment]
Hey @murali-reddy 
I see the crash in NPC even with this patch
Here is the stack trace. 
I0304 12:10:57.123210   10578 network_policy_controller.go:235] sync iptables took 9.47414ms
E0304 12:10:57.123363   10578 runtime.go:66] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x178a420), concrete:(*runtime._type)(0x188e560), asserted:(*runtime._type)(0x1a21140), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/iface.go:248
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:175
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1634
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:209
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:544
/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod

goroutine 254 [running]:
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x17fd480, 0xc0004578c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).OnPodUpdate(0xc0007580c0, 0x188e560, 0xc0008b3e80)
	/root/GOPATH/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:175 +0x3a3
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).newPodEventHandler.func3(0x188e560, 0xc0008b3e80)
	/root/GOPATH/src/github.com/cloudnativelabs/kube-router/pkg/controllers/netpol/network_policy_controller.go:1634 +0x3e
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/controller.go:209
github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0008a10e0)
	/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/tools/cache/shared_informer.go:544 +0x25e
github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000529020, 0xc00086ecb0)
	/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/root/GOPATH/src/github.com/cloudnativelabs/kube-router/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
I0304 12:11:45.879766   18767 kube-router.go:216] Running /usr/local/kube-router/kube-router version , built on , go1.12.6

**Comment by aauren** [comment]
Hmm... From the documentation for `DeletedFinalStateUnknown` it says:

```
DeletedFinalStateUnknown is placed into a DeltaFIFO in the case where an object was deleted but the watch deletion event was missed. In this case we don't know the final "resting" state of the object, so there's a chance the included `Obj` is stale.
```

If I had to guess, I would guess, that this happens after you allowed kube-router to connect back up with the kube-apiserver after having lost it's connection?

In this case, kube-router would have missed the watch deletion event, so it would not know the final state of the pod, all it knows is that it no longer exists.

@murali-reddy my guess is that we need to handle this by not blindly casting to the final API type of any function calls that stem from `DeleteFunc`. Instead we should check the type first.

In this case, for all of our updaters in NPC we only really care to be notified so that we can call npc.Sync and get relevant attributes for updating metadata. Since the metadata we're using in the logs is really only Name and Namespace, we could actually likely consolidate most of these methods and instead attempt to cast to v1.Object which is an abstraction of Pods, Namespace, and NetworkPolicy and contains methods for `GetName()` and `GetNamespace()` then we could handle checking for the `DeleteFinalStateUnknown` in a single spot.

**Comment by atibdialpad** [comment]
@aauren yeah, the crash is seen only when kube-router was disconnected from the api-server and there is an update (pod deletion in my case). If I don't delete a pod there is no crash.

**Comment by atibdialpad** [comment]
@murali-reddy  @renaudhager @aauren @MarkDeckert 
For the time being, I want the routes advertised by kube router to be preserved (for some time) in the BGP Peer even when kube router crashes. Will 'bgp-graceful-restart' capability help me do it ?

**Comment by murali-reddy** [comment]
Sorry for the delay

@atibdialpad thanks for testing it out. 

> If I had to guess, I would guess, that this happens after you allowed kube-router to connect back up with the kube-apiserver after having lost it's connection?
> In this case, kube-router would have missed the watch deletion event, so it would not know the final state of the pod, all it knows is that it no longer exists.

@aauren This is exactly my guess too. However, even if there is network partion or not I think current way of delete handlers is wrong or atleast *not* in the best practice of current contollers. Taking cue from many in-tree controllers in Kubernetes `DeletedFinalStateUnknown` must be explicitly handled. For e.g in kube-proxy this is how service delete is handled https://github.com/kubernetes/kubernetes/blob/v1.17.3/pkg/proxy/config/config.go#L357

So i think all instances of delete handlers should be modified in similar fashion to kubernetes in-tree controller.

> in general is there a design doc, that talks about how kuberouter gets updates from the watchers and syncs it current state.

@atibdialpad its just standard semantices of kubernetes controllers, you may want to look at https://github.com/kubernetes/sample-controller/blob/master/controller.go

> Is there some sort of queue where api servers enqueues all the updates for kr to dequeue when it reconnects to it ? How are we ensuring that no updates will be missed ?

Kubernetes watch API updates are not necessarily guaranteed to be delivered. hence you have resync on informers or explicit periodic resync 

>For the time being, I want the routes advertised by kube router to be preserved (for some time) in the BGP Peer even when kube router crashes. Will 'bgp-graceful-restart' capability help me do it ?

It should.

While kube-router should be fixed to be more graceful when API server is down, I would imagine in any production envirormnet API server must be highly available,  its source of truth for all the controllers running on top of Kubernetes, it can only lead to situation like this bug.

**Comment by aauren** [comment]
@MarkDeckert @atibdialpad Can you test out a kube-router deployment from master? I believe that with #864 #856 and #813 that this bug should now be fixed.

**Comment by nishadmusthafa** [comment]
Hi @aauren  , I work with @atibdialpad . We tested the build based off of the latest master and we didn't see the crash. Tested with deletes to Pods, namespaces and networkpolicies. 

I think we are good to close this.

**Comment by murali-reddy** [comment]
thanks @nishadmusthafa @atibdialpad 

Closing the issue.
