### ISSUE TITLE
Rebase image to distroless or debian-base

### ISSUE THREAD

**Issue by danbeaulieu** [cloudnativelabs/kube-router#713]
Per https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md

The Kubernetes project is making an effort to standardize all images to a [distroless image](https://github.com/GoogleContainerTools/distroless) for performance and security reasons. In special cases they also use a debian-base image.

Should kube-router, as part of the k8s ecosystem, adopt a similar plan? This would mean moving off of the alpine base and switching to the "official" [debian-base k8s.gcr.io/debian-base](https://github.com/kubernetes/kubernetes/tree/master/build/debian-base). I don't think the distroless base image would work for kube-router as it depends on a few system libraries.

**Comment by asteven** [comment]
Going from alpine to debian seems to be a step backwards from a security point of view.

**Comment by aauren** [comment]
I agree with @asteven. Alpine is working fine for us for now, gaining conformity here doesn't seem to have a huge advantage. Open to being wrong, feel free to re-open with more arguments.
