### ISSUE TITLE
Unit test "make test" failed of v0.2.5 on x86_64 linux

### ISSUE THREAD

**Issue by samding01** [cloudnativelabs/kube-router#717]
Get `kube-route` v0.2.5 and install [go](https://dl.google.com/go/go1.12.3.linux-amd64.tar.gz). (v1.12.3)
Build container is fine but  unit test :`make test` gets failed as:
```
# github.com/cloudnativelabs/kube-router/pkg/controllers/proxy
pkg/controllers/proxy/network_services_controller.go:1607:6: Info call has possible formatting directive %s
FAIL    github.com/cloudnativelabs/kube-router/pkg/controllers/proxy [build failed]
^CMakefile:58: recipe for target 'test' failed
make: *** [test] Error 2
```
If comment on `pkg/controllers/proxy/network_services_controller.go:1607`, then it gets
```
*** Test killed with quit: ran too long (10m0s).
FAIL    github.com/cloudnativelabs/kube-router/pkg/controllers/routing  600.786s
?       github.com/cloudnativelabs/kube-router/pkg/healthcheck  [no test files]
?       github.com/cloudnativelabs/kube-router/pkg/metrics      [no test files]
?       github.com/cloudnativelabs/kube-router/pkg/options      [no test files]
ok      github.com/cloudnativelabs/kube-router/pkg/utils        (cached)
Makefile:58: recipe for target 'test' failed
make: *** [test] Error 1
```
Here is the detailed log file: 
[make_test.log](https://github.com/cloudnativelabs/kube-router/files/3108752/make_test.log)

**Comment by aauren** [comment]
kube-router doesn't work with go v1.11 and above. See: https://github.com/cloudnativelabs/kube-router/pull/706/files#r274596251

In the meantime, I have go v1.12 installed on my system and `BUILD_IN_DOCKER=true make` will allow you to make kube-router FWIW
