### ISSUE TITLE
Use kubernetes watch API for fetching node list

### ISSUE THREAD

**Issue by mpashka** [cloudnativelabs/kube-router#727]
In big kubernetes clusters kubernetes API can be bottleneck. Each time API receives request it goes to etcd, fetches data from it and provides response. And this operation requires significant amount of CPU resources.
In our kubernetes cluster installation we observed significant API server performance degradation when API server requests reached 4k/minute.
In order to reduce API server load kubernetes watch API can be used instead of fetching node list. kube-router already uses watch API. But there are several places in code where get node list is used directly. Instead of using node list it's possible to have node list structure and update it using node watch api notifications.

**Comment by aauren** [comment]
I believe that this may have been addressed between #813 and #856. If I got this wrong, please feel free to re-open.
