### ISSUE TITLE
advertise-cluster-ip=true, but not to iBGP peers ?

### ISSUE THREAD

**Issue by sanjmonkey** [cloudnativelabs/kube-router#730]
Hey,

I was wondering what the reasoning was behind only advertising cluster-ip to eBGP peers when advertise-cluster-ip=true is toggled?

I have a use case where I need pods on say node-01 to communicate with a cluster IP living on node-02 only.  The cluster IP does'nt live on node-01 because externalTrafficPolicy:local is configured, as I want to enforce a networkpolicy to restrict traffic to the externalIP, by source IP.

It would be really easy to solve if all my iBGP mesh of kube-routers knew about the origins of the cluster-ip's too - but maybe there is something else going on here?

Cheers
Sandy

**Comment by aauren** [comment]
As an internal cluster communication mechanism cluster IP is meant to be used from node -> node. As such it should be getting translated via IPVS before it ever leaves the node and then egress across the network using the pod network's routing either via BGP and the advertised pod subnets or via IPIP tunneling.

There was a problem with how cluster IPs interacted with local services that interrupted this flow, but it was fixed recently here: https://github.com/cloudnativelabs/kube-router/pull/836

Does that answer your question?

**Comment by aauren** [comment]
Closing as stale.
