### ISSUE TITLE
Request to be invited to Kube-Router Slack Channel

### ISSUE THREAD

**Issue by sbrohi-att** [cloudnativelabs/kube-router#746]
Hello, 

I would like to be invited to the Kube-Router Slack channel here: 

https://kubernetes.slack.com/messages/C8DCQGTSB/

Please send the invite to the following email address: brohishazad@gmail.com

Thank you.

**Comment by murali-reddy** [comment]
@sbrohi-att #kube-router is just one of the channels in https://kubernetes.slack.com. Are you having trouble signing up for Kubernetes slack?

**Comment by sbrohi-att** [comment]
@murali-reddy Yes, I am having trouble signing-up. Please send me an invite to the Kubernetes Slack channel so that I can join.

**Comment by murali-reddy** [comment]
https://github.com/kubernetes/community/issues/3247
