### ISSUE TITLE
add routes in the rib created by kube-router 

### ISSUE THREAD

**Issue by atibdialpad** [cloudnativelabs/kube-router#748]
Is it possible to add entries in the gobgp rib created by kube-router ? I have a use case where I want to create a subinterface, say eth0:1 and puts its IP into the rib.

**Comment by atibdialpad** [comment]
any ideas/comment ?

**Comment by murali-reddy** [comment]
> I have a use case where I want to create a subinterface, say eth0:1 and puts its IP into the rib.

@atibdialpad can you elaborate a bit please? What do you mean by putting IP in to the RIB

**Comment by atibdialpad** [comment]
Hey Murali, 
I have a use case where I need to DNAT/SNAT all traffic coming_in/going_out from a POD. This is because, the application that this POD talks to whitelists only a particular IP. So, I have this sort of a deployment:
external_app ---> DNAT ingress traffic from whitelisted_ip to pod_ip ----> POD
POD ---> SNAT egress pod traffic to whitelisted_ip ---> external IP
This makes the external application assume that it is talking to the whitelisted IPs and not the POD ip.
To advertise this whitelisted IP, I need to install this IP into the RIB.
With KubeRouter running a bgp instance, I am not able to add this.
so, right now I am running a gobgp process and installing the route via :
gobgp global rib add -a ipv4 <whitelisted_ip> nexthop <node_ip>

It would have been much easier had there been a way to install this router in the RIB created by the kube-router itself.

**Comment by atibdialpad** [comment]
To add : The reason why I am not using k8s services with external IP is because egress traffic gets SNAT 'ed to NODE_IP which being a non whitelisted IP is dropped by the external application.

**Comment by atibdialpad** [comment]
any ideas/comment ?

**Comment by atibdialpad** [comment]
Hey @murali-reddy , 
I did some code browsing and found that kuberouter uses old version of gobgp 1.33 (https://github.com/cloudnativelabs/kube-router/blob/54eedcd0490dd28191d53971d9442f57d45da25d/Gopkg.toml) 
but latest version of grpc 
(https://github.com/cloudnativelabs/kube-router/search?q=bgpapi&unscoped_q=bgpapi). 

Because of gobgp protobuf api change post 1.33, if I use gobgp cli to manipulate rib of kube-router, it fails saying :
"rpc error: code = Internal desc = grpc: error unmarshalling request: proto: bad wiretype for field gobgpapi.Path.Age: got wiretype 2, want 0" 

What are your thoughts about it ?

**Comment by atibdialpad** [comment]
Hey @murali-reddy 
I could communicate to kube-router's 0_3_1 gobgpd using GRPC v1.33
I am able to add a route to the global rib using my python GRPC client code (stub.AddPath), however this route does not get advertised to the peer-router. 
I checked the code to see how 'external-ip' is advertised by kube-router and found that it also does a 'AddPath' api call only. Am I missing something ?

**Comment by murali-reddy** [comment]
@atibdialpad Yes, kube-router is still using older of gobgp. Unfortunately upgrading to latest version is big effort (due to api breaking changes)

>I checked the code to see how 'external-ip' is advertised by kube-router and found that it also does a 'AddPath' api call only. Am I missing something ?

there are BGP export policies that gets created by kube-router as well. may be that is preventing the routes that you added from being advertised, may be try to delete the policies and see if it has any effect?

**Comment by atibdialpad** [comment]
Hey @murali-reddy 
Yup, creating bgp export policy worked. I followed this kube router file "kube-router/pkg/controllers/routing/bgp_policies.go" and replicated the steps to add a bgp policy using grpc python client. My external-ip got advertised and I was able to ping it.
Though, after some time, I see my policy gets deleted from the node. Is there some process in kube-router/kubernetes in general that monitors policies created by kube-router and deletes any externally added proxies ?

**Comment by murali-reddy** [comment]
@atibdialpad there is periodic sync that tries to update the desired config. Perhaps that is resetting what you have added. Are you updating the export policies created by the kube-router?

**Comment by atibdialpad** [comment]
@murali-reddy 
I am creating a new export policy. Please find the o/p below :
>> ~/GOBGP/GOBGP_1.33# ./gobgp global policy
Import policy:
    Default: accept
Export policy:
    Default: reject
    Name kube_router:
        StatementName kube_router_stmt0:
          Conditions:
            PrefixSet: any podcidrprefixset
            NeighborSet: any iBGPpeerset
          Actions:
             accept
        StatementName kube_router_stmt1:
          Conditions:
            PrefixSet: any clusteripprefixset
            NeighborSet: any externalpeerset
          Actions:
             accept
        StatementName kube_router_stmt2:
          Conditions:
            PrefixSet: any podcidrprefixset
            NeighborSet: any externalpeerset
          Actions:
             accept
    **Name atib_policy_export:
        StatementName atib_statement:
          Conditions:
            PrefixSet: any atib_prefix_defined_set
            NeighborSet: any externalpeerset
          Actions:
             accept**

**Comment by murali-reddy** [comment]
@atibdialpad 

> Though, after some time, I see my policy gets deleted from the node.

so your observation is after a while `atib_policy_export ` gets deleted?

**Comment by atibdialpad** [comment]
@murali-reddy 
Yeah exactly.

**Comment by murali-reddy** [comment]
Ok. I dont see kube-router flushing export policies. Is it possible that kube-router pod is restarting and hence loosing the config changes you made?

**Comment by atibdialpad** [comment]
Hi @murali-reddy  
I am not running kuberouter as a pod/daemon.  
It is running as a bare process in a linux machine. You were referring to a periodic sync, can you point out where that code sits ?

**Comment by murali-reddy** [comment]
@atibdialpad  this is the periodic sync loop

https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/network_routes_controller.go#L249


and this is part of the sync-loop where policies are updated

https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/network_routes_controller.go#L289

**Comment by atibdialpad** [comment]
Updating issue with slack conversation:
murali.reddy [11:16 AM]
@atib I am not sure why would that happen, As per the logic in kube-router it just manipulating few named policies. Can you try to set `--routes-sync-period`  value to couple of hours so that periodic sync does not update the export policies. When things are static (no services getting added/deleted etc) just add your routes to the RIB and see if they persist now. If  added routes remains then there is some bug in either kube-router logic or GoBGP. But we need way to be sure its issue with kube-router.

atib [11:34 AM]
@murali.reddy that is a very good suggestion. I will change the timer and check. Thanks, was not aware that KR has that timer functionality

**Comment by atibdialpad** [comment]
Hey @murali-reddy 
To make sure that the issue is KubeRouter and not gobgp specific, I ran a gobgp damon and used my scripts to create 2 bgp export policies (Policy 1 and Policy 2) one after another. Policy 1 remained in the system even after Policy 2 was added and both routes were properly advertised to the bgp peer.
I also tried increasing to --routes-sync-period 2hrs but that didn't help. From the code I saw there is one more place apart from this periodic sync that recreates the policies, it is :
kube-router/pkg/cmd/kube-router.go

if kr.Config.RunRouter {
		nrc, err := routing.NewNetworkRoutingController(kr.Client, kr.Config, nodeInformer, svcInformer, epInformer)
		if err != nil {
			return errors.New("Failed to create network routing controller: " + err.Error())
		}

		nodeInformer.AddEventHandler(nrc.NodeEventHandler)
		svcInformer.AddEventHandler(nrc.ServiceEventHandler)
		epInformer.AddEventHandler(nrc.EndpointsEventHandler)

		wg.Add(1)
		go nrc.Run(healthChan, stopCh, &wg)
	}
Do you think any one of the above handlers gets called when I add a global export policy ?

Still, why it deletes my policy is a mystery ? I am stuck on this :-(

**Comment by atibdialpad** [comment]
Hey @murali-reddy 
It is actually one of the event handlers that is being triggered and is calling "AddPolicies" and not the periodic sync 
This is the code flow I found out using debug logs:: 

 ecmp_vip.go:166] atib : newEndpointsEventHandler calling OnEndpointsUpdate
 ecmp_vip.go:199] atib : Inside OnEndpointsUpdate
 ecmp_vip.go:225] atib : OnEndpointsUpdate calling tryHandleServiceUpdate
 ecmp_vip.go:115] atib : tryHandleServiceUpdate
 ecmp_vip.go:100] atib : calling AddPolicies handleServiceUpdate. Trigger svc is ‘kubernetes'
 bgp_policies.go:19] atib : inside AddPolicies
 bgp_policies.go:130] atib : inside addExportPolicies
 bgp_policies.go:266] atib : inside addImportPolicies

For a quick verification, I commented out the "AddPolicy" call and my policy was not deleted and remained in the system for ever.

The actual problem I feel is why this AddPolicy call removes bgp policies that is added by me. Is there is gobgp/kube-router config file from where it picks all polices that should be there ?

**Comment by atibdialpad** [comment]
Hey @murali-reddy 
I think I got the RCA. The problem is in the addExportPolicies code which calls "ReplacePolicyAssignment"
This is most probably flushing bgp policies created by me.
I commented this out things are working fine. 

Also, lates gobpp code has removed all "Replace" RPC calls. 
What do you think ?

**Comment by atibdialpad** [comment]
Hey @murali-reddy , 

I have tested out this piece of code and stuffs were working for me. Can you please look at it. If it looks good, I will raise a PR:

FILE : pkg/controllers/routing/bgp_policies.go
FUNCTIONS : addExportPolicies() 
Line : 247
if !policyAssignmentExists {
                err = nrc.bgpServer.AddPolicyAssignment("",
                        table.POLICY_DIRECTION_EXPORT,
                        []*config.PolicyDefinition{&definition},
                        table.ROUTE_TYPE_REJECT)
                if err != nil {
                        return errors.New("Failed to add policy assignment: " + err.Error())
                }
        } else {
                // configure default BGP export policy to reject
                /*
                err = nrc.bgpServer.ReplacePolicyAssignment("",
                        table.POLICY_DIRECTION_EXPORT,
                        []*config.PolicyDefinition{&definition},
                        table.ROUTE_TYPE_REJECT)
                */
                err = nrc.bgpServer.SetDefaultPolicy("", table.POLICY_DIRECTION_EXPORT, table.ROUTE_TYPE_REJECT)
                if err != nil {
                        // return error and error message
        }

Similar change in addImportPolicies() as well.

Why is this needed :  KubeRouter was calling a "ReplacePolicyAssignment" on the global table. This will remove all bgp policies that were added by other clients/user. For example, in my use-case I have some IPs (outside of k8s services/external_ip etc) which I need to advertise to my peer router. So I am creating a BGP policy to allow these. The above call removes all policies added by me.

**Comment by atibdialpad** [comment]
Hey @murali-reddy, can you please have a look at it share your thoughts ?

**Comment by atibdialpad** [comment]
Hey @murali-reddy any update on this ? Did you have a chance to take a look at it ? We are running a custom version of kube-router with this change for some time now.

**Comment by atibdialpad** [comment]
Hey @murali-reddy any update on this ?

**Comment by atibdialpad** [comment]
https://github.com/cloudnativelabs/kube-router/pull/872

**Comment by aauren** [comment]
Closing from lack of response on PR.
