### ISSUE TITLE
override-nexthop and not creating tunnel interfaces

### ISSUE THREAD

**Issue by sanjmonkey** [cloudnativelabs/kube-router#749]
**Running kube-router version v0.3.1, built on 2019-05-12T09:22:07+0000, go1.10.8**

Hi,

Recently I decided to multi-home a kube-router.  2 x /31 networks, one public providing
public services and one private, providing services inside an L3VPN.  Imagine something
like this:

```
+---------------+     +----------------+
|  AS65530 TOR  |     |  AS65530 TOR   |
|               |     |                |
+----------+----+     +---+------------+
           |              |
           |              |
           |              |
       172.16.1.0/31     1.1.1.0/31
           |              |
           |              |
           |              |
         +-+--------------+--+
         |   k8s node        |
         |                   |
         |     +---------+   |
         |     |         |   |
         |     kube-router   |
         |     | AS64512 |   |
         |     +---------+   |
         +-------------------+
```

I accepted the granularity of export-maps was not there, but I'm happy to control those
at the ToR to decide if they're services for the L3VPN side, or for the public side.

However, what I noticed was that the NH was overwritten to always be the public, even
on the private session.  And so I enabled --override-nexthop, which appeared to fix it
for this case.

However, I then noticed that my full iBGP mesh between AS64512 kube-router nodes was no
longer building tunnel interfaces and not injecting routes into the nodes routing table to
enable reachability to the other pods CIDR.  I am running: 
--enable-overlay=true
--enable-ibgp=true 
--enable-cni=true

I see in https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/network_routes_controller.go#L444

we do not create the tunnels if nrc.overrideNextHop is enabled.

So, I was wondering;
- am I using override-nexthop for the correct use case?
- whats the use case for not creating the overlay if override-nexthop is enabled?
- if not override-nexthop, could we not set NH to be localAddress instead of self?

Comments / suggestions appreciated!

**Comment by murali-reddy** [comment]
@sanjmonkey thanks for reporting the issue

> we do not create the tunnels if nrc.overrideNextHop is enabled.

yes that's true. Will get back to you with rationale why its done that way (need to recall)

Generally these combinations and resulting typologies have grown organically.  Needs to simplify and make it easier to get a mental map of the falgs and effect on the resulting topology.

**Comment by aauren** [comment]
Closing as stale.
