### ISSUE TITLE
NodePort Service not visible beyond node itself

### ISSUE THREAD

**Issue by cerebrate** [cloudnativelabs/kube-router#757]
This is my first kubernetes/kube-router cluster, so I should like to apologize in advance for any inadequate information. System is Debian Buster, clean install, with Kubernetes 1.15 installed via kubeadm, following the instructions [https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/](here) and [https://github.com/cloudnativelabs/kube-router/blob/master/docs/kubeadm.md](here), using kube-router for all its roles; currently just a single node.

For my first test, I installed the http-svc example from [https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/http-svc.yaml](here) as a simple test and attempted to expose it via a NodePort, i.e., editing the service to this:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"http-svc"},"name":"http-svc","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"http-svc"}}}
  creationTimestamp: "2019-07-13T15:03:24Z"
  labels:
    app: http-svc
  name: http-svc
  namespace: default
  resourceVersion: "1876"
  selfLink: /api/v1/namespaces/default/services/http-svc
  uid: 567f3f13-c7e8-40ab-bfc1-144cb2c2e2d4
spec:
  clusterIP: 10.106.29.92
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30178
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-svc
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

But the service external IP continues to show up as _<none>_, rather than _<nodes>_:

```
$ kubectl get service -o wide
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE    SELECTOR                                                                          
http-svc     NodePort    10.106.29.92   <none>        80:30178/TCP   98m    app=http-svc                                                                      
kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP        105m   <none>       
```

On digging into it a little further on the node itself with _ipvsadm_ , what I see is this:

```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.16.3.14:30178 rr
  -> 192.168.0.8:8080             Masq    1      0          0         
TCP  10.96.0.1:443 rr
  -> 172.16.3.14:6443             Masq    1      2          0         
TCP  10.96.0.10:53 rr
  -> 192.168.0.6:53               Masq    1      0          0         
  -> 192.168.0.7:53               Masq    1      0          0         
TCP  10.96.0.10:9153 rr
  -> 192.168.0.6:9153             Masq    1      0          0         
  -> 192.168.0.7:9153             Masq    1      0          0         
TCP  10.106.29.92:80 rr
  -> 192.168.0.8:8080             Masq    1      0          0         
UDP  10.96.0.10:53 rr
  -> 192.168.0.6:53               Masq    1      0          0         
  -> 192.168.0.7:53               Masq    1      0          0         
```

Which seems to show the NodePort mapping correctly in the first entry, but while I can connect to it from the node itself on via 172.16.3.14 (the node's LAN IP), I cannot connect to it on http://172.16.3.14:30178 from anywhere else on the network. The connection instead simply times out:

```
$ curl 172.16.3.14:30178
curl: (7) Failed to connect to 172.16.3.14 port 30178: Connection timed out
[1]    20239 exit 7     curl 172.16.3.14:30178 
```

I've tried several installations at this point, using several different machines and VMs, and the issue seems to be consistent, so either I'm mucking something up without knowing it, or there's a bug somewhere. Any suggestions on how I might go about further diagnosing it?

**Comment by aauren** [comment]
If I had to guess I would say that something else is going on that is unrelated to kube-router since you can connect to it from the node itself.

Is it possible that you have a firewall setting that is blocking the traffic? Can you post the output from `netstat -tnlp` and `iptables -nvL`?

Also can you confirm that there are no other firewalls on the network between your client and your kubernetes cluster? It would be a better debugging test if both your client and your k8s cluster we're on the same L2 network and not going through any gateways. Can you confirm if this is the case?

Are you able to start a daemon of nginx (not in k8s) on a high port range and reach it from your client?

**Comment by cerebrate** [comment]
That was my first guess, too, but after trying several installs on different machines, etc., all from clean images, I ended up at quite the loss as to what else it might be.

There shouldn't be any firewall settings blocking trafffic. I know for certain there aren't any anywhere else on the network except at the border router, and since the client and cluster are on the same L2, same switch even, that shouldn't be an issue. As for the cluster node, it's a fresh install of Debian buster with docker, kubernetes, and kube-router added, so there shouldn't be any settings there either that aren't related to one of them.

ss -tnlp and iptables -nvL results are attached:

[ss-tnlp.txt](https://github.com/cloudnativelabs/kube-router/files/3390068/ss-tnlp.txt)
[iptables-nvL.txt](https://github.com/cloudnativelabs/kube-router/files/3390069/iptables-nvL.txt)

Running nginx (or another server) on a high port range works fine and is reachable from a client.

**Comment by aauren** [comment]
I'm on my phone right now so I can't review all the iptables statements, but it jumped out on me that you have a default drop policy on your forward table. I would try changing that first.

Also it looks like Docker has a lot of rules k8s usually works best when you turn off Dockers control of the firewall.

**Comment by cjbottaro** [comment]
I'm seeing something similar, but for ClusterIP services.

I can curl the pod ip just fine from any node, but going through the service times out unless I'm on a pod that is on the same node as the pod running the service.

Here's my `iptables -nvL` output:
https://gist.github.com/cjbottaro/f295483f644bfcfd890211c09d058b44

**Comment by cerebrate** [comment]
@aauren Aha! Not sure why docker was creating all those rules, but after disabling docker's interaction with iptables, clearing all the chains, and restarting the docker daemon, it started working. Thanks muchly for the help, and glad it wasn't a bug after all!

**Comment by cerebrate** [comment]
(Sorry, @cjbottaro, didn't see your comment before I closed it. I'll leave it up to you whether to reopen here or not.)

**Comment by cjbottaro** [comment]
I just terminated my nodes and let them come back up and things work now.
