### ISSUE TITLE
ClusterIP/ExternalIP stops being announced after 5 minutes

### ISSUE THREAD

**Issue by bazuchan** [cloudnativelabs/kube-router#765]
I upgraded to latest master and ClusterIP/ExternalIP stops being announced after 5 minutes (pod cidr announce still works). Version compiled on end of may from master works fine.

**Comment by murali-reddy** [comment]
@bazuchan thanks for reporting. 

There is a regression in the master (https://github.com/cloudnativelabs/kube-router/pull/721#issuecomment-507751303) which is not fixed yet.

**Comment by aauren** [comment]
This issue appears to be fixed by @tamihiro's change on #771

**Comment by andrewsykim** [comment]
Looks like this was fixed, please reopen if you're still seeing this issue
