### ISSUE TITLE
Is kube-router v0.3.2 can be use in production now??  thanks

### ISSUE THREAD

**Issue by zhxjdwh** [cloudnativelabs/kube-router#768]

**Comment by zhxjdwh** [comment]
I had wait for a year ...

**Comment by murali-reddy** [comment]
please use 0.3.1. 0.3.2 has a regression yet to be fixed.

**Comment by iamakulov** [comment]
For the reference, this is likely the regression that’s being mentioned: https://github.com/cloudnativelabs/kube-router/issues/765
