### ISSUE TITLE
ipvs not usable in node, kube-router delete user services.

### ISSUE THREAD

**Issue by lumasepa** [cloudnativelabs/kube-router#770]
When I setup a service in ipvs using ipvsadm in a node all works fine. But once kube-router is deployed my ipvs service is deleted, if I recreate the service it gets deleted again.

Is this the normal behavior of kube-router? If it is, somewhere in the doc should be advised this.
Is there any way to tell kube-router to not delete an ipvs service?
Is there any way to tell kube-router to create a "static ipvs" managed by a third party?

**Comment by lumasepa** [comment]
What I'm trying to do with the ipvs service is avoid to have a load balancer for masters apiservers in a masters HA scenario.

To do that I'm doing client side load balancing using ipvs, so in each node I setup a ipvs service that points to each master apiserver and a small daemon health checks the apiservers and adds or deletes masters nodes from the service. 

The advantage of this approach is that you don't need a load balancer with its own HA to have HA in the masters but the downside is that the masters are going to receive health checks from each node instead of a single health check the one of the load balancer. 

Could this functionality be part of kube-router? If so, I can implement it with some guidance.

**Comment by aauren** [comment]
This should be fixed via #830. Feel free to re-open if you still see issues.
