### ISSUE TITLE
Export of Multipath Routes to the Kernel

### ISSUE THREAD

**Issue by bensallen** [cloudnativelabs/kube-router#774]
Requesting support be added for multi-path routes in Kube-router. 

For a cluster that has nodes dual-homed into two parallel leafs, each interface on a separate subnet, it is not currently possible for kube-router to export both learned routes to the Linux kernel.

With a external route reflector on each leaf and the option `--override-nexthop` enabled, the RIB on the nodes appear to be correctly learning both routes to other nodes, eg:

```
~ # gobgp global rib -a ipv4
   Network              Next Hop             AS_PATH              Age        Attrs
*> 10.42.0.0/24         192.168.101.12                            00:02:30   [{Origin: i} {LocalPref: 100} {Originator: 192.168.101.12} {ClusterList: [0.0.0.42]}]
*  10.42.0.0/24         192.168.102.12                            00:02:30   [{Origin: i} {LocalPref: 100} {Originator: 192.168.101.12} {ClusterList: [0.0.0.42]}]
*> 10.42.1.0/24         192.168.101.13                            00:02:36   [{Origin: i} {LocalPref: 100} {Originator: 192.168.101.13} {ClusterList: [0.0.0.42]}]
*  10.42.1.0/24         192.168.102.13                            00:02:33   [{Origin: i} {LocalPref: 100} {Originator: 192.168.101.13} {ClusterList: [0.0.0.42]}]
*> 10.42.2.0/24         192.168.101.11                            00:02:40   [{Origin: i}]
```

However kernel's routing table of the nodes in this cluster only have the first route listed. The equivalent setting in BIRD, for example, to support exporting both routes as multipath, is `merge paths yes;` under `protocol kernel`.

It appears kube-router is not inserting multi-path routes here: https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/network_routes_controller.go#L493. It appears it either is just getting the best path, or inserting one route on-top of the other (not validated which).

It looks like `watchBgpUpdates` or `injectRoute` will need to be updated to merge paths to the same destination together and make a netlink.Route with MultiPath populated.

**Comment by uablrek** [comment]
Duplicate https://github.com/cloudnativelabs/kube-router/issues/410

**Comment by bensallen** [comment]
Closing in favor of #410.
