### ISSUE TITLE
Ability to limit motd output

### ISSUE THREAD

**Issue by rmb938** [cloudnativelabs/kube-router#776]
While the motd when execing into the kube-router pod is nice, in large clusters it scrolls the debugging commands off of the screen due to having a large number of bgp peers and ipvs services.

The ability to disable showing bgp and ipvs info via a environment variable or something would be awesome.

**Comment by wu0407** [comment]
Custom dockerfile and rebuild docker image

**Comment by aauren** [comment]
Closing as stale. If you're still interested, feel free to re-open with a suggested implementation plan to resolve this including what the option that would be added and how it would be honored within the container and we'll review it.
