### ISSUE TITLE
need to skip binding dev to ipip tunnel when node's advertising address is on loopback interface

### ISSUE THREAD

**Issue by tamihiro** [cloudnativelabs/kube-router#780]
Still working on the same scenario as [778](https://github.com/cloudnativelabs/kube-router/issues/778#issue-489674106), I've got gobgp to be able to establish peers with my patch #777. However nodes are still unreachable to each other through the ipip tunnel interface. I have recognized network_routes_controller.go creates ipip tunnel with device name set to `nrc.nodeInterface`, which prevents the tunnel from working when tunnel source address is on loopback interface. 

Below is an example of non-working tunnel.
```
8: tun-192168014@lo: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 65496 qdisc noqueue state UNKNOWN group default qlen 1000
```
I have submtted another PR #779. With this patch ipip tunnel is created without being bound to loopback interface, like below.
```
8: tun-192168014@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1460 qdisc noqueue state UNKNOWN group default qlen 1000
```

I'd appreciate your review on this one in addition to my previous PRs.

**Comment by aauren** [comment]
Fixed via #779
