### ISSUE TITLE
arm64 release

### ISSUE THREAD

**Issue by nerzhul** [cloudnativelabs/kube-router#783]
Hello,
currently you are providing arm64 builds, they works as intended, but there is also ARM64 support in the code. Can you provide release build ?

Thanks

**Comment by aauren** [comment]
@murali-reddy Is this something that you want to support?

**Comment by aauren** [comment]
I believe this is closed via #894. Can you confirm @mrueg?

**Comment by mrueg** [comment]
Container images are available here: https://hub.docker.com/layers/cloudnativelabs/kube-router/arm64-v1.0.0-rc2/images/sha256-d6fa25e3f076c4b75c7bb284924def9de03e9220d4193a842ddbec6923316fab?context=explore

Binaries will be released on the next rc / proper 1.0
