### ISSUE TITLE
Allow to use IPv4 string as RR cluster id

### ISSUE THREAD

**Issue by jdrahos** [cloudnativelabs/kube-router#785]
Hey guys, thank you for this great project. 
I have made some changes in my fork and would like to propagate upstream as much as possible to avoid merging issues when we need to build new version of the image.
Gobgp allows you to use both integer and IPv4 strings for configuring RR cluster ids. Kube-router will fail to start gobgp server in network routes controller if someone will need to peer with a RR server using IPv4 string as cluster id as it allows to configure only integers.

**Comment by jdrahos** [comment]
PR #786 is simple implementation of this feature

**Comment by andrewsykim** [comment]
Thanks for the PR @jdrahos will try to review it soon

**Comment by aauren** [comment]
Closed via #786
