### ISSUE TITLE
Weight configuration for ipvs backends

### ISSUE THREAD

**Issue by jdrahos** [cloudnativelabs/kube-router#789]
We have several generations of hardware in our on-prem bare metal clusters. This results in clusters with high variation of nodes when it comes to performance. 
Currently when using kube router as service proxy it is not possible to set the weights for the backends in ipvs or even choose weighted scheduling method for the vip. 
We want to be able to annotate the node with weight which would be used when configuring backends running on the node in ipvs.

**Comment by andrewsykim** [comment]
> or even choose weighted scheduling method for the vip.

You can actually set the scheduler with the annotation `kube-router.io/service.scheduler`. 

> We want to be able to annotate the node with weight which would be used when configuring backends running on the node in ipvs.

Let me think about this one, because kube-router does client-side load balancing I think it's tricky to implement.

**Comment by jdrahos** [comment]
Thank you @andrewsykim for looking at this. 
The problem is that if you set one of they weighted scheduler strategies using the annotation you have mentioned it will default to round robin. The code which is responsible for processing the annotation doesn't support weighted scheduling methods ->
https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/proxy/network_services_controller.go#L1412

Using the weights specified on nodes for endpoints running on these nodes when setting up the ipvs vip for a service works as expected for us in production. If you can think of a better solution, that works for us too.

**Comment by aauren** [comment]
Related to #1038. Closing this one to consolidate the number of places we talk about this feature.
