### ISSUE TITLE
external-ip not advertised

### ISSUE THREAD

**Issue by jlauro** [cloudnativelabs/kube-router#791]
Tested with kubernetes 1.16.0, and kube-router version v0.3.2 and also tested with kubernetes 1.15.4 deployed with kubeadm on Centos 7.

cidr and pods advertise without issue.

Trying to expose a test service with  kubectl expose deployment/bootcamp --type="LoadBalancer" --port 8080 --external-ip=10.0.87.3.  The /32 CLUSTER-IP  from kubectl get services is advertised outside the cluster, but the external IP is not. It is setup in the IPVS, so the external IP works with a static route from the upstream router.  kube-route is configured with --advertise-external-ip=true --advertise-load-balancer-ip=true (among others).  Any known version or other parameters that must be configured for kube-router to advertise external ip outside the cluster?

I can either try to diagnose current installation.  If there is any specific versions and known deployment methods along with specific configurations that will work, I can redeploy to match and try to narrow down what is causing the issue.

**Comment by andrewsykim** [comment]
Can't seem to see why external IP won't work here unless your network devices weren't setup to do that. Can you share some logs from kube-router?

**Comment by jlauro** [comment]
I have a test cluster I can redeploy quickly from some scripts.  Let me know what versions of kubernetes/etc I should deploy, and I'll do a fresh deployment, and where/how are the logs you want.

**Comment by andrewsykim** [comment]
@jlauro v0.3.2 is known to have some critical bugs, can you try with v0.4.0-rc1 please? Kubernetes version shouldn't matter

**Comment by aauren** [comment]
Closing as stale
