### ISSUE TITLE
k8s daemonset rollingupdate sometimes triggers 'administrative shutdown' on all kube-router pods

### ISSUE THREAD

**Issue by mars64** [cloudnativelabs/kube-router#792]
Kops-based Kubernetes 1.11.10 cluster on AWS, kube-router 0.3.2, using: 

```
      - args:
        - --hairpin-mode
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --metrics-port=12013
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
        - -v 0
```

DaemonSet configured with `.spec.updateStrategy.rollingUpdate.maxUnavailable: 1`. 

While implementing `bgp-graceful-restart` the pod network became unavailable. All pods logged: 

```
time="2019-10-02T21:41:27Z" level=info msg="Peer Down" Key=<some ip> Reason="notification-received code 6(cease) subcode 2(administrative shutdown)" State=BGP_FSM_ESTABLISHED Topic=Peer
```

The podnet recovered itself when the daemonset was done rolling.

**Comment by wu0407** [comment]
the message generated by kube-router pod deleted

**Comment by jraby** [comment]
This is expected if graceful restart is not enabled.

Once it is, subsequent restart of kube-router should not cause routes to be removed from peers (until the default graceful restart time of 90s expire)

**Comment by jraby** [comment]
From what I understand, if graceful restart is not enabled, kube-router (gobgp) will send the administrative shutdown as part of its exit sequence.
BGP peers are expected to remove routes received from the peer that is going down when they receive such a message.

When `--bgp-graceful-restart` is enabled, the BGP Graceful Restart capability is advertised to peers and the 'administrative shutdown' message is not sent by kube-router when it is going down.
The reference for all this is the RFC: https://tools.ietf.org/html/rfc4724#page-3

As for the kube-router pod restarts, I have not seen this behavior. Are there any events in the pods when it happens (probe failure, exit code, etc...)?
It would probably be best to close this issue and to open a new issue to track this problem down.

**Comment by mars64** [comment]
Cheers! I looked deeper into the issue queue and I believe there is already effort to resolve what I'm seeing. I think we're hitting https://github.com/cloudnativelabs/kube-router/pull/753 which is already merged. I look forward to the next release.

Closing.
