### ISSUE TITLE
hope this project more activity 

### ISSUE THREAD

**Issue by wu0407** [cloudnativelabs/kube-router#793]
This project solved the problem of running kubernetes under the old network facilities. unlike cailico which has many iptables rules and can not disable. This project is very light and easy maintenance.
but the status of this project:
1. More issue not sloved
2. Code is infrequent update

**Comment by andrewsykim** [comment]
@murali-reddy is taking some time off, I'm hoping to help out whenever I have time. Please re-open if activity slows down again :)
