### ISSUE TITLE
Request for opinion on adding more CLI flags

### ISSUE THREAD

**Issue by jraby** [cloudnativelabs/kube-router#794]
We are about to deploy a custom version of kube-router on our clusters where we needed a bit more control over the default behavior.

We added a few options, namely:
 - `--peer-router-passwords-file`: to read peer password from a file (which can be sourced from a k8s secret)
 - `--bgp-graceful-restart-time`: to set the BGP graceful-restart-time to something different than gobgp's default value of 90s (in our case, we're using kube-router for podCIDRs on a baremetal cluster with nodes that will not change often, so having a long graceful restart time makes sense so routes do not go away even if kube-router is down)

And we are thinking of adding a few more:
  - `bridge-interface`: to set the name of the bridge to create / manipulate. We need this for a smooth online migration from flannel (cni0) to  kube-router. Right now we simply hardcoded it, but I'm thinking of either adding a CLI flag for it, or reading it from the CNI json config.

 - ~~`--node-asn` + `--route-reflector-{client,server}`: these are currently only settable from node annotations, but we would rather have them set via the CLI since we deploy route-reflector servers in a different deployment than the route-reflector clients (and we mostly do not use node annotations, it would keep our node deployment simple)~~ edit: this wouldn't work, annotations are required to select which nodes to peer with. 

Would these be accepted if we submitted (separate) PRs for them?
(asking before hammering  them into good shape :)  )

**Comment by wu0407** [comment]
--bgp-graceful-restart-time in this commit https://github.com/cloudnativelabs/kube-router/commit/803bd9025699ef15ddd87c8189d804107198dda5

**Comment by jraby** [comment]
graceful deferral time is different from graceful restart time. (see https://tools.ietf.org/html/rfc4724#page-3)

**Comment by andrewsykim** [comment]
I'm not opposed to `bridge-interface` but I'm going to noodle on it a little bit first. 

Do you need it only for migration purposes?

**Comment by jraby** [comment]
I needed it for migration purposes, and i still need it after.

Ill try to send something soon.

**Comment by aauren** [comment]
This has been closed through #953 and #986
