### ISSUE TITLE
Add Condition to remove ACCEPT all from KUBE-ROUTER-SERVICES

### ISSUE THREAD

**Issue by DandyDeveloper** [cloudnativelabs/kube-router#797]
This is a duplicate of #682. Following a change made in #602.

It would be good to get a flag to remove the ipvs Firewall chain "accept all". 

I will be adding this, I just wanted a clear feature/issue to reference.

**Comment by murali-reddy** [comment]
@DandyDeveloper this can be closed now?

**Comment by DandyDeveloper** [comment]
@murali-reddy Yes! How often do releases go out?

Do you have a CI in place that checks master (we can build from master until the next RC is ready).
