### ISSUE TITLE
add health/liveliness check for kube-router

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#80]
We need to add health/liveliness check for the kube-router pods in cases where the kube-router daemon exits (for e.g #78) for problems that occur running daemon over a period of time. Adding such checks would atleast trigger kubernetes to redeploy the pod. While it may hide errors till we notice atleast service will be available.

**Comment by SEJeff** [comment]
What do you envision a liveness probe for kube-router actually checking? I'd assuming something about the bpg status, but what makes sense?

For webapps, I'll generally do the db equiv of `SELECT 1`

**Comment by murali-reddy** [comment]
@SEJeff at the minimum periodic control loops are able to sync configurations (to ipvs, iptables etc) to the desired state. failing which liveliness check should fail.

**Comment by roffe** [comment]
Working on this [here](https://github.com/roffe/kube-router/tree/healthcheck) right now.
