### ISSUE TITLE
Update release notes for v0.3.2 in GitHub

### ISSUE THREAD

**Issue by iostat** [cloudnativelabs/kube-router#804]
Hello, 

I was recently doing some maintenance and upgrades on my cluster, and found that `kube-router` v0.3.2 was available. Not seeing any notes about known bugs or regressions with that version on its release, I decided to upgrade my `kube-router` install. Everything appeared to be working swimmingly well, until I started restarting nodes and found that half the time I couldn't hit any of my services by service VIP, nor make DNS requests (via the kube-dns VIP), etc. After two hours of intense head scratching and seeing no immediately obviously related issues in the issue tracker, I eventually found issue #768 with @murali-reddy 's note about a bug in v0.3.2, and upon further investigation, realized that #756 was indeed the cause of my issues. I downgraded to v0.3.1 and everything went back to normal.

Nonetheless, I imagine going forward plenty more people will experience similar frustrations as me when regressions like that crop up again, and even though we're all aware that `kube-router` is still quite experimental in some aspects, perhaps we can save other users some time in the future by introducing some kind of policy of updating release notes for known affected versions when major regressions like the one in v0.3.2 are discovered?

Many thanks,
-Ilya

**Comment by andrewsykim** [comment]
@iostat sorry for the trouble here, we're releasing v0.4.0 soon. There's a release candidate availble here https://github.com/cloudnativelabs/kube-router/releases/tag/v0.4.0-rc1, please try it out. I'll update the release notes with a warning.

**Comment by andrewsykim** [comment]
Updated release notes, thanks @iostat 

/close
