### ISSUE TITLE
Martian packets on tun interfaces

### ISSUE THREAD

**Issue by bljordan** [cloudnativelabs/kube-router#812]
After enabling martian packet logging on all interfaces, we're seeing these in our logs:
`Nov 14 02:48:18 ip-10-0-0-182.ec2.internal kernel: IPv4: martian source 100.96.236.156 from 10.0.0.41, on dev tun-102522758`

From the logs, it looks to be a single pod IP at a time and many different node IPs.

We saw this PR from 2017 and wondering if this is to be expected of if traffic is actually being dropped? https://github.com/cloudnativelabs/kube-router/pull/143

We're running kube-router v0.4.0-rc1 with args:
```
        - --bgp-graceful-restart
        - --hairpin-mode
        - --kubeconfig=/var/lib/kube-router/kubeconfig
        - --metrics-port=12013
        - --run-router=true
        - --run-firewall=true
        - --run-service-proxy=true
```

Thanks!

**Comment by aauren** [comment]
Possibly related to https://github.com/cloudnativelabs/kube-router/issues/511

**Comment by aauren** [comment]
Closing as stale.
