### ISSUE TITLE
docs url issue

### ISSUE THREAD

**Issue by nightan42643** [cloudnativelabs/kube-router#814]
https://www.kube-router.io/docs/user-guide/bgp.md 404
https://www.kube-router.io/user-guide/ 404

**Comment by arianvp** [comment]
Introduction also produces a 404 https://www.kube-router.io/introduction/

**Comment by aauren** [comment]
FYI @murali-reddy

**Comment by aauren** [comment]
@murali-reddy is this something that can be fixed easily? We've gotten multiple reports in slack and now two issues opened for this.

**Comment by murali-reddy** [comment]
@aauren I created kube-router.io website and kube-router.io/docs with mkdocs with very little knowledge and skill. Sources are here at https://github.com/cloudnativelabs/kube-router.io. Honestly docs need revamp. If i remeber correctly something needs to be changed in https://github.com/cloudnativelabs/kube-router.io/blob/master/mkdocs.yml#L18 to fix. Should be a simple fix.

**Comment by blue-troy** [comment]
https://www.kube-router.io/introduction/ stil 404 not found

**Comment by aauren** [comment]
This should be fixed by https://github.com/cloudnativelabs/kube-router.io/pull/33

**Comment by aauren** [comment]
This is finally fixed! Documentation on kube-router.io is now up to date.
