### ISSUE TITLE
kubeadm upgrade breaks network configuration

### ISSUE THREAD

**Issue by dredwilliams** [cloudnativelabs/kube-router#833]
I switched from using flannel to kube-router on a working 1.17.0 cluster -- followed directions and everything worked as expected.

I upgraded the cluster using standard kubeadm process, and all of a sudden cluster networking stopped.  I noticed during the upgrade that kubeadm (I think) re-started the kube-proxy daemonset on all nodes -- I assume this is the root of the problem, but couldn't verify that assumption.  The installation instructions delete the kube-proxy daemonset, but apparently it is still in the base configuration -- so kubeadm restarts it during the upgrade.

I deleted kube-proxy again per the installation instructions, but that didn't fix the routing.  I re-installed (delete then apply) the kube-router manifest, but that didn't fix it either.  Restarting all the kubelets didn't seem to have any impact.  It wasn't until I rebooted all nodes in the cluster that the cluster networking was functional again.

Configuration:
- 10 node Centos 7 cluster
- k8s version 1.17.0 -> 1.17.1
- kube-router master branch 
-- using only service-proxy and router features

I am very pleased with the capabilities and performance of kube-router ... this glitch during upgrade is the only issue I've experienced -- thanks!

Ed Williams

**Comment by murali-reddy** [comment]
@dredwilliams thanks for opening the issue

instructions in kube-router docs are pretty old before kubeadm supported configuration to not to install kube-proxy by default. I think documentation need to updated with instructions to leverage kubeadm config to skip installing kube-proxy by default

**Comment by dredwilliams** [comment]
Ok -- how do I get kubeadm to not install kube-proxy?  I tried looking in the kubeadm docs but couldn't identify a likely candidate ...

**Comment by MrFreezeex** [comment]
> Ok -- how do I get kubeadm to not install kube-proxy? I tried looking in the kubeadm docs but couldn't identify a likely candidate ...

You can skip the "kube-proxy" addon phase during kubeadm init. To do that you just have to add "--skip-phases=addon/kube-proxy" to your kubeadm init command.

**Comment by Tatsu-Kishi** [comment]
Hey, am setting up a new k8s cluster right now and tried skipping kube-proxy during init, however now kube-router doesn't come up because it's missing the configmap kube-system/kube-proxy

**Comment by murali-reddy** [comment]
@Tatsu-Kishi you are right. We do have problem. kube-router was resuing the kubeconfig generated for kube-proxy, If we skip the kube-proxy through configuration then kube-router need to find alternative way to get kubeconfig.

**Comment by aauren** [comment]
Closing in favor of #859  as there is more description on that one. But definitely a thing worth doing.
