### ISSUE TITLE
Segmentation violation with arm build

### ISSUE THREAD

**Issue by rkojedzinszky** [cloudnativelabs/kube-router#839]
I have deployed the official multiarch image to my k8s, and on my arm boxes kube-router panics:
```
I0125 08:21:27.505261       1 kube-router.go:216] Running /usr/local/bin/kube-router version v0.4.0-rc2, built on 2020-01-22T14:44:32+0000, go1.10.8
Failed to run kube-router: Failed to create network policy controller: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x385860]

goroutine 100 [running]:
github.com/cloudnativelabs/kube-router/pkg/healthcheck.(*HealthController).HandleHeartbeat(0x12232000, 0x0)
	/go/src/github.com/cloudnativelabs/kube-router/pkg/healthcheck/health_controller.go:74 +0x34
github.com/cloudnativelabs/kube-router/pkg/healthcheck.(*HealthController).RunCheck(0x12232000, 0x1220b180, 0x12229bc0, 0x122a2ce0, 0x0, 0x0)
	/go/src/github.com/cloudnativelabs/kube-router/pkg/healthcheck/health_controller.go:181 +0x1b4
created by github.com/cloudnativelabs/kube-router/pkg/cmd.(*KubeRouter).Run
	/go/src/github.com/cloudnativelabs/kube-router/pkg/cmd/kube-router.go:112 +0x52c
```

Howewer, I am building my own kube-router multiarch images with go1.13.4 based on official master branch, and those images start well.

**Comment by bogsen** [comment]
Encountered a similar issue on my arm64 boxes (except for the panic - output just stopped at "Failed to create network policy controller" for me). The issue seems to be that the official arm images are built with non-arm base images, so even though the Go binary is cross-compiled and works fine, the tools it requires that are installed in the image won't be able to run.

**Comment by murali-reddy** [comment]
@rkojedzinszky @bogsen can you please point out required base image to be used for arm64?

Is it `https://hub.docker.com/r/arm64v8/alpine/`?

**Comment by rkojedzinszky** [comment]
@murali-reddy I am building kube-router on real arm and arm64 hardwares using multiarch image golang:alpine and then using the in-tree Dockerfile to create the final image.

**Comment by rkojedzinszky** [comment]
@murali-reddy The latest v0.4.0 images still have these issues. As @bogsen wrote, the image contains binaries for wrong archs:
```bash
$ docker run -it --rm --platform linux/arm64 --entrypoint sh cloudnativelabs/kube-router:v0.4.0 
Unable to find image 'cloudnativelabs/kube-router:v0.4.0' locally
v0.4.0: Pulling from cloudnativelabs/kube-router
9123ac7c32f7: Pull complete 
a013fcd37187: Pull complete 
f05b35ee35f1: Pull complete 
d5f2f9556b5b: Pull complete 
9a8c754d2d95: Pull complete 
719231d59839: Pull complete 
d36face758d9: Pull complete 
Digest: sha256:bea26ac7c8bc1b88b7d7e1183b90aa900338be07ff22cb01c73ff0929d071043
Status: Downloaded newer image for cloudnativelabs/kube-router:v0.4.0
~ # apk --no-cache add file
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libmagic (5.36-r1)
(2/2) Installing file (5.36-r1)
Executing busybox-1.29.3-r10.trigger
OK: 28 MiB in 43 packages
~ # file /bin/bash
/bin/bash: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
~ # file /usr/local/bin/kube-router 
/usr/local/bin/kube-router: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=aHZX5RNB87hFT520c88e/mbJpGCjqdEV9fHoN0zMH/TPjhoSYwcAPXQqQHW-SM/d8POInyEGGfAF8Yhznvd, with debug_info, not stripped
```

Until it is fixed, I use rkojedzinszky/kube-router, which is built only for amd64, arm and arm64.

Regards,

**Comment by HaveFun83** [comment]
Same issue here with rpi-4
@rkojedzinszky  thanks for your builds

**Comment by murali-reddy** [comment]
@rkojedzinszky I tried to fix CI to push multi arch images. Unfortunatley I could not get enough time to fix it. But I would like to fix this ASAP. If any one wished to submit a PR happy to work with them to incorporate in CI.

Also please see https://github.com/cloudnativelabs/kube-router/issues/503

**Comment by evanrich** [comment]
I just came across this while trying to deploy a multiarch environment.  Added 2 raspberry pis (arm64) to my existing AMD64 master.  When K8s tries to scale the kube-router onto each of the Pi's, it fails with @bogsen message "Failed to create network policy controller"

I'll try changing the image kube-router uses to the one posted by @rkojedzinszky that supports arm64 and amd64

**Comment by mrueg** [comment]
Please give https://github.com/cloudnativelabs/kube-router/pull/885 a try.
