### ISSUE TITLE
Failed PR image push should not cause CI to fail

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#84]
This is for cases where a PR is submitted from an external repo branch. Docker push will not work since Travis secret variables are not exposed to external repos. Example: #83

**Comment by bzub** [comment]
We may be able to use Docker Hub automated builds to lift this limitation on PR builds.

https://docs.docker.com/docker-hub/builds/

**Comment by aauren** [comment]
Closing as stale.
