### ISSUE TITLE
LVS doesn't follow nodeport service update accordingly

### ISSUE THREAD

**Issue by ethinx** [cloudnativelabs/kube-router#841]
Hi kube-router,

We tried v0.4.0 kube-router recently, and found issue with nodeport service.

At the beginning, we create a nodeport service and point to target port 80

```
apiVersion: v1
kind: Service
metadata:
  name: mp
  namespace: test
spec:
  clusterIP: 172.30.105.6
  externalTrafficPolicy: Cluster
  ports:
  - name: nontls
    nodePort: 30356
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

after service being created, we change target port to others and take a look on the node, the RS port doesn't follow updates.

```
### we try to change target port several times (to 81, 443, 8080) and the orphan ports are not being removed.
TCP  192.168.3.1:30356 rr
  -> 172.16.3.4:80                Masq    1      0          0
  -> 172.16.3.4:81                Masq    1      0          0
  -> 172.16.3.4:443               Masq    1      0          0
  -> 172.16.3.4:8080              Masq    1      0          0
  -> 172.16.4.17:80               Masq    1      0          0
  -> 172.16.4.17:81               Masq    1      0          0
  -> 172.16.4.17:443              Masq    1      0          0
```

any advised?

cluster version: 1.15.7
kube-router: v0.4.0

**Comment by murali-reddy** [comment]
> we try to change target port several times (to 81, 443, 8080) and the orphan ports are not being removed.

@ethinx thanks for reporting the bug. Looks like regression. I can confirm the behaviour. Will try to get a bug fix release v0.4.1

**Comment by ethinx** [comment]
thanks @murali-reddy 

Or would you suggest a version without this problem? I could move forwards and test other cases.

**Comment by murali-reddy** [comment]
Looks like regression has been around for quite a while. I dont want to suggest very old version, please wait for a day or more will make a release with fix
