### ISSUE TITLE
Discussion: gobgp update to v2.X.X - preparation for go update/go modules switch

### ISSUE THREAD

**Issue by ghouscht** [cloudnativelabs/kube-router#845]
Hi,
As you may already know the gobgp version (v1.33) currently used by kube-router does not properly work with go versions >1.10 (latest 1.10 version released on 2019/01/23). For further details see my comments in https://github.com/cloudnativelabs/kube-router/pull/838.

So I think it's time to start working on updating gobgp 😉.

Currently I see two different approaches to get this done.

**update go version prior to update gobgp**
1. Create a fork of the old version of gobgp then fix the issue which is described in #838.
2. Change kube-router to use the fork of gobgp.
3. Update kube-router to a recent go version and switch to go modules
4. Start updating of gobgp and rewrite the kube-router code to work with gobgp v2.

Pros:
- security issues (net/http had some "serious" issues for example) from older go versions are fixed fast
- people can work on kube-router with a more state of the art tooling
- other libraries/tools continue to work (no more support for go 1.10)
- #834 would be fixed and also similar possible upcoming problems

Cons:
- quite a lot of work which is done just for a very limited timeframe (forking and patching gobgp, changing kube-router to use the fork)

**update gobgp and then go version**
1. Update kube-router to use gobgp v2
2. Update go version and switch to go modules

Pros:
- less work and probably the simpler more straightforward approach

Cons:
- takes more time, as a lot of kube-router code needs to be changed before go version can be updated
- users need to work with outdated tooling
- security issues (fixed in newer go versions) stay open until all the work is done

I'm happy to help with this, just curious to hear which approach is preffered.
Thank you for feedback,
Thomas

**Comment by mrueg** [comment]
As far as I know, only the tests hang and you can compile a functioning kube-router with a later version of golang (at least we do it but possibly we might use a subset of the functionality that doesn't cause kube-router to hang). It would be great if someone could dedicate some time to upgrade gobgp, at least to see what breaks and what APIs have changed.

**Comment by ghouscht** [comment]
Sure, that's correct. The only thing which does not work is a graceful stop of the BGP server inside kube-router. However this is not really a problem in k8s environments as there is a `terminationGracePeriodSeconds` in the deployment and after the grace period is over k8s simply kills the pods.
Not a clean "solution" but still works 😄

**Comment by murali-reddy** [comment]
Updating GoBGP would be quite a lot of work. I plan to work on it next coming months. But first i would like to get 1.0 out (https://github.com/cloudnativelabs/kube-router/projects/6) so that we can bring this sort of disruptive changes.

**Comment by ghouscht** [comment]
Sounds good! I'll leave the issue and PR open, just ping me as soon as you're ready, I'm happy to help out here.

**Comment by aauren** [comment]
Linking #948

**Comment by aauren** [comment]
This has been closed via #948 and was merged into master via #982
