### ISSUE TITLE
document requirements for OpenStack

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#854]
VM's provisioned on OpenStack have anti-spoofing measures which will drop packets if the source address is not matching to the assigned VM's ip. This prevents pod-to-pod traffic across the nodes getting routed when kube-router is used in direct routing mode.

Following are options to overcome this limitation:

- configure OpenStack to allo pod-to-pod traffic. Steps are documented for kubespray https://github.com/kubernetes-sigs/kubespray/blob/master/docs/openstack.md

- alternatively users can choose to use full-overlay (IP-in-IP even for nodes in same subnet)
```
       - --enable-overlay=True
        - --overlay-type=full
```

**Comment by aauren** [comment]
Closing this as stale.
