### ISSUE TITLE
IP IP tunnel between Kube-router and external device

### ISSUE THREAD

**Issue by kunalpuriii** [cloudnativelabs/kube-router#860]
We are using following setup
kubernetes version: v1.17.4
NGINX as ingress controller which is advertising cluster as a service to F5
F5 CIS for integration between NGINX ingress controller and F5
F5 external load balancers
Kube router as CNI

NGINX as ingress controller advertised POD network outside of kubernetes cluster to F5, as F5 is not on same network with kubernetes it has to install the routes and intermediate devices does need to have routing to kubernetes POD network as well.

To avoid configuring routing on the devices between F5 and Kubernetes cluster, Does kube router support IP IP tunnel between the kube-router to the north bound device in this case F5 which is out of kubernetes cluster.

If  yes please guide me to the documentation or if no are we planning to introduce enhancement on connecting kube-router with the devices outside cluster on IP IP tunnels

@murali-reddy @dlamotte 

Thanks for your help

**Comment by murali-reddy** [comment]
No. Kube-router uses IP-in-IP tunnel only for pod-to-pod networking traffic which east-west.

**Comment by aauren** [comment]
Closing as asked and answered
