### ISSUE TITLE
 is there any way to set different subnets on the same host using Cilium?

### ISSUE THREAD

**Issue by ShixiongQi** [cloudnativelabs/kube-router#868]
Hey folks, 

Is there any way to set different subnets on the same host using Kube-router? Do I need to do any changes on the configuration file? Or set up multiple daemonsets on the same host? Thanks

To be more specific, I want to setup two different subnets (for example 10.244.1.0/24 and 10.244.2.0/24). So I can deploy kubernetes pods into these two subnets. When the pods in different subnets want to communicate with each other, I want to know how will they go through the host network stack. In my impression, if I create two subnets on the same host. There will be two bridges in the host network stack, each of them belongs to one subnet. And when the pods in the different subnets want to communicate with each other, the packets will go through these two linux bridges. Though I think no one will do this in production….

**Comment by aauren** [comment]
@murali-reddy correct me if I'm wrong here, but as far as I know, I don't believe that kube-router supports what you're trying to do. When kube-router starts it expects a single cluster CIDR specified either via: `--cluster-cidr` or via the CIDR set on the node by the kube-controller-manager if available. It connects a single kube-bridge interface to this subnet.
