### ISSUE TITLE
Feature request: Add a way to specify CIDRs to exclude from iptables MASQUERADE target

### ISSUE THREAD

**Issue by FabienZouaoui** [cloudnativelabs/kube-router#871]
I'm using a vpn between two kubernetes clusters.

Unfortunately kube-router sets up an iptables rules that MASQUERADE traffic when trying to access remote targets.

Please have a look at  #870 if you consider this request in the scope of kube-router.

**Comment by aauren** [comment]
My gut says that to keep kube-router simple I would expect the traffic to MASQUERADEed any time that it was crossing the cluster boundaries (i.e. anytime the traffic was not going to another pod in the cluster, even if it was going to pod in a different kubernetes cluster). This allows kube-router to take full advantage of using BGP on the network to make further routing decisions.

@murali-reddy do you have an interest is supporting the use-case here?

**Comment by FabienZouaoui** [comment]
I get your point.
Anyway, I can set "enable-pod-egress" to false and manage my egress rules on my own.
I'm closing this issue.
