### ISSUE TITLE
[Feature] Check for dependency binaries on startup

### ISSUE THREAD

**Issue by DandyDeveloper** [cloudnativelabs/kube-router#878]
Looks like we're not checking for the binaries from dependencies and CNI plugins (bridge / host-local).

We should check for these on service startup to make sure we can actually create the interfaces and bridges needed by kube-router to function. Otherwise, the pod on a node will just error out with a limited error.

**Comment by aauren** [comment]
I think that this would be difficult to integrate into kube-router as kube-router itself is CNI agnostic. It essentially just on the CNI to be functioning by the time it comes into play. It doesn't necessarily care which CNI plugins are configured and it also doesn't have awareness of where the CNI plugins are located, as this is a parameter that is passed to the kubelet (via `--cni-bin-dir`).

If I remember correctly from when I setup my first k8s cluster (somewhere around 1.9) there was no part of the stack that emitted good error messages for this, which I agree should be corrected if that's still the case. However, I think the best place for these messages is the kubelet as it is the most CNI aware component.
