### ISSUE TITLE
Publish multi-arch images during push on master

### ISSUE THREAD

**Issue by rmb938** [cloudnativelabs/kube-router#887]
Currently only amd64 images are built and published for pushes to master. 

Publishing the other architectures and the manifest image will allow us to test master commits on multiple architectures without having to built the image manually.

**Comment by mrueg** [comment]
See also: https://github.com/cloudnativelabs/kube-router/issues/503

**Comment by aauren** [comment]
Closing in favor of #503. @rmb938 let us know if you don't think #503 covers your use-case.

**Comment by rmb938** [comment]
@aauren #503 specifically mentions github releases only. I'm talking about pushes to master. 

This image specifically `https://hub.docker.com/r/cloudnativelabs/kube-router-git`

Also technically #503 was finally fixed with #885. 

More specifically all I want to do is change https://github.com/cloudnativelabs/kube-router/blob/master/build/travis-deploy.sh#L46 to include multi-arch.

**Comment by aauren** [comment]
Re-opening based on clarification.
