### ISSUE TITLE
IPVS timeout is not updated without service recreation after sessionAffinityConfig.clientIP.timeoutSeconds update

### ISSUE THREAD

**Issue by rearden-steel** [cloudnativelabs/kube-router#910]
Kube-router does not update this field in IPVS when service is updated.
If you delete/create the service it is configured correctly.

**Comment by aauren** [comment]
Thanks for reporting @rearden-steel 

I was able to reproduce and submitted a fix that I tested against my own cluster.

**Comment by rearden-steel** [comment]
@aauren thanks!
