### ISSUE TITLE
Reconsider use of liveness probe in daemonset

### ISSUE THREAD

**Issue by zerkms** [cloudnativelabs/kube-router#912]
Related: https://github.com/cloudnativelabs/kube-router/issues/651

At the moment DaemonSet comes with the following liveness probe declaration

      livenessProbe:
        httpGet:
          path: /healthz
          port: 20244
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 3
        successThreshold: 1
        failureThreshold: 3

Now - if API becomes unavailable for several minutes the following happens:

```
E0526 22:23:45.846305       1 health_controller.go:118] Network Routing Controller heartbeat missed
E0526 22:23:47.311018       1 health_controller.go:118] Network Routing Controller heartbeat missed
I0526 22:23:51.980398       1 kube-router.go:178] Shutting down the controllers
I0526 22:23:51.980454       1 health_controller.go:161] Shutting down health controller
I0526 22:23:51.982558       1 network_services_controller.go:358] Shutting down network services controller
I0526 22:23:51.982575       1 health_controller.go:178] Shutting down HealthController RunCheck
E0526 22:23:51.984242       1 health_controller.go:150] Health controller error: http: Server closed
I0526 22:23:51.984865       1 network_policy_controller.go:166] Shutting down network policies controller
```

If I don't miss anything: `/healthz` starts returning non-200s and kubelet restarts the pod.

Right before restarting - kube-router cleans up the ipvs table.

Then it's being started again, cannot connect to API, hence does not set any routes now.

After several minutes of the API unavailability the complete cluster turns into potato. (unless I'm missing something).

**Comment by murali-reddy** [comment]
> After several minutes of the API unavailability the complete cluster turns into potato.

What version of kube-route you are using? [v1.0.0-rc2](https://github.com/cloudnativelabs/kube-router/releases/tag/v1.0.0-rc2) release has several fixes that lets kube-router run with out API

> Right before restarting - kube-router cleans up the ipvs table.

That can not be true. It only cleansup stale service objects. Does this repro all the time?

**Comment by zerkms** [comment]
Tbh I run a rather obsolete v0.3.2 and haven't upgraded to newer v0.4.0 and v1.0.0-rcX because of their problems with memory.

For 0.3.2 it reproduces every time, I think I will have to upgrade to the latest 1.0.0-rc and re-open it if necessary.

Thanks, and my apologies.
