### ISSUE TITLE
allow setting BGP holdtime

### ISSUE THREAD

**Issue by cloudnativer** [cloudnativelabs/kube-router#922]
Our production environment Kube router went down for a short time and then recovered automatically. During this period, the pod on the server works normally, but the BGP route of the switch on the kube-router is lost.
In this case, we hope that during the short outage of kube-router, the upper switch can still retain BGP neighbors and routes. The solution is to set "bgp-graceful-restart=true" and set the holdtime to a larger value.

**Comment by cloudnativer** [comment]
The BGP holdtime set by our network switch device is 300s, while kube-router cannot adjust the holdtime.

**Comment by cloudnativer** [comment]
We can see that the holdtime in the kube-router source code is 90s, but there is no place to modify it.

**Comment by cloudnativer** [comment]
BGP will automatically negotiate and take the minimum holdtime of both parties.

**Comment by cloudnativer** [comment]
Is there any way to customize and adjust the BGP holdtime of kube-router?
In this way, the online network equipment and kube-router can negotiate a more suitable holdtime value for their own production environment.

**Comment by cloudnativer** [comment]
We have modified the source code of kube-router and added the "bgp-holdtime" function parameter of setting holdtime, which is used to adjust the holdtime of BGP negotiation with the connected network devices.Please see https://github.com/cloudnativelabs/kube-router/pull/921.
In this way, we can customize the hold time of negotiation between kube-router and switch device.

**Comment by cloudnativer** [comment]
> We have modified the source code of kube-router and added the "bgp-holdtime" function parameter of setting holdtime, which is used to adjust the holdtime of BGP negotiation with the connected network devices.
> Please see #921.

-------------------------------------------------------------------------------------

In this way, we can customize the hold time of negotiation between kube-router and switch device.

**Comment by aauren** [comment]
I believe that you would also need to adjust the restart time setting as well. There is currently a PR open for this functionality here: https://github.com/cloudnativelabs/kube-router/pull/799

**Comment by cloudnativer** [comment]
> I believe that you would also need to adjust the restart time setting as well. There is currently a PR open for this functionality here: #799

Yes, holdtime and restart time work together for better results.

**Comment by aauren** [comment]
Closed via #921
