### ISSUE TITLE
Allow route reflector and route server configuration for external BGP peer

### ISSUE THREAD

**Issue by alexises** [cloudnativelabs/kube-router#924]
On bare metal deployment of kube router, you could have an etherogenous network configuration.

In instance, the current external-peer feature could only do : 

- eBGP session
- one session per kube-proxy that announce his own pod subnet.

To simplify the deployment on bare metal configuration, like the route reflector provided inside the cluster itself (green link on the below schemas), It should be possible to configure eBGP session as route server and iBGP session with route reflector on some kind of edge kube-router node (red link on below schema).

In additions, the promoted edge node should be able to send the whole list of prefix without altering the next-hop (so the data-plane flow directly to the affected node instead of using the edge node)

Please find a relevant schemas below.

![network](https://user-images.githubusercontent.com/2833598/84010145-8885ec00-a974-11ea-9498-ca903a97fa1c.png)

As I have seen on the code, only a bit of code on controller should be added to do this.

**Comment by aauren** [comment]
@murali-reddy Any thoughts on this?

**Comment by aauren** [comment]
Closing as stale
