### ISSUE TITLE
Can't find configuration for a new passive connection from:192.168.34.129

### ISSUE THREAD

**Issue by dmanbu** [cloudnativelabs/kube-router#925]
Please forgive me for my poor English

docker version: 18.09.9
k8s version: 1.16.4
kube-router version: 0.4.0

k8s node:
192.168.34.228 k8s-master-01
192.168.34.227 k8s-master-03
192.168.34.226 k8s-master-03

BGP ROUTER IP: 10.10.10.26

kube-router args:
	- "--run-router=true"
	- "--run-firewall=true"
	- "--run-service-proxy=true"
	- "--hairpin-mode=true"
	- "--nodeport-bindon-all-ip"
	- "--cluster-cidr=172.30.0.0/16"
	- "--kubeconfig=/var/lib/kube-router/kubeconfig"
	- "--advertise-cluster-ip=true"
	- "--advertise-external-ip=true"
	- "--advertise-loadbalancer-ip=true"
	- "--cluster-asn=64512"
	- "--nodes-full-mesh=false"
	- "--enable-pod-egress=false"
	- "--enable-overlay=false"
	- "--enable-ibgp=true"

kube-router Configuration:

kubectl annotate node k8s-master-01 "kube-router.io/rr.server=42"
kubectl annotate node k8s-master-01 "kube-router.io/node.asn=64512"
kubectl annotate node k8s-master-01 "kube-router.io/peer.asns=64512"
kubectl annotate node k8s-master-01 "kube-router.io/peer.ips=10.10.10.26"

kubectl annotate node k8s-master-02 "kube-router.io/rr.client=42"
kubectl annotate node k8s-master-02 "kube-router.io/node.asn=64512"

kubectl annotate node k8s-master-03 "kube-router.io/rr.client=42"
kubectl annotate node k8s-master-03 "kube-router.io/node.asn=64512"

My k8s environment is BGP mode, three nodes, both master and node

Now use 192.168.34.228 as a Route-Reflector and switch pairing, and connect the other two nodes to Route-Reflector
Now that the Pod network and the physical network are connected, there is no problem with the connection
But the kube-router of 192.168.34.227 192.168.34.226 these two nodes has been reporting the following warning

![20200611145721](https://user-images.githubusercontent.com/10231091/84354682-e3794680-abf3-11ea-800d-bc1cf4763e8e.png)

192.168.34.129 This IP is the gateway, I have no configuration related to this address
I don’t know if this is a configuration error or a bug, please help me, thanks

**Comment by murali-reddy** [comment]
> 192.168.34.129 This IP is the gateway, I have no configuration related to this address
I don’t know if this is a configuration error or a bug, please help me, thanks

@dmanbu Do you have any BGP configuration on 192.168.34.129 to peer with 192.168.34.227 192.168.34.226?

`Can't find configuration for a new passive connection from:192.168.34.129` indicates 192.168.34.129 is trying to establish BGP session with that node.

**Comment by dmanbu** [comment]
> > 192.168.34.129这个IP是网关，我没有与此地址相关的配置，
> > 我不知道这是配置错误还是错误，请帮助我，谢谢
> 
> @dmanbu您在192.168.34.129上是否有任何BGP配置与192.168.34.227 192.168.34.226对等？
> 
> `Can't find configuration for a new passive connection from:192.168.34.129` 表示192.168.34.129正在尝试与该节点建立BGP会话。

192.168.34.227 192.168.34.226 does not have any peer configuration with 192.168.34.129

**Comment by murali-reddy** [comment]
> 192.168.34.227 192.168.34.226 does not have any peer configuration with 192.168.34.129

Thats the point i am trying to make. `192.168.34.227 192.168.34.226` does not have peering with `192.168.34.129`, but `192.168.34.129` is trying to peer with `192.168.34.227 192.168.34.226`.

**Comment by dmanbu** [comment]
> > 192.168.34.227 192.168.34.226 does not have any peer configuration with 192.168.34.129
> 
> Thats the point i am trying to make. `192.168.34.227 192.168.34.226` does not have peering with `192.168.34.129`, but `192.168.34.129` is trying to peer with `192.168.34.227 192.168.34.226`.

I'm sorry, I configured BGP peering of 192.168.34.227 192.168.34.226 on the router, I forgot to delete
Thank you for your help

**Comment by dmanbu** [comment]
I don’t understand, why there are so many msg="No matching path for withdraw found, may be path was not installed into table" ?

**Comment by murali-reddy** [comment]
What are the IP 10.254.x.x/32 that are getting withdrawn? Have you checked your BGP configurations correctly?

**Comment by dmanbu** [comment]
> What are the IP 10.254.x.x/32 that are getting withdrawn? Have you checked your BGP configurations correctly?

SERVICE CIDR is 10.254.0.0/16
This problem only appears on 192.168.34.227 192.168.34.226
I can access pod ip and service ip on the host's network
I checked the available parameters of kube-router, only the cluster-cidr related to the pod, and no service-related configuration

**Comment by murali-reddy** [comment]
Sorry I am not sure what is the problem you are facing. Since the original issues turned out to be a configuration issue, can you please close this issue and open seperate issue with issue you are facing and symptoms?

**Comment by dmanbu** [comment]
> Sorry I am not sure what is the problem you are facing. Since the original issues turned out to be a configuration issue, can you please close this issue and open seperate issue with issue you are facing and symptoms?

Ok, thank you very much for your help !!
