### ISSUE TITLE
DSR with port remapping

### ISSUE THREAD

**Issue by galli-leo** [cloudnativelabs/kube-router#936]
According to the documentation (and also my testing), DSR is currently not supported with services that do port remapping.

Is this a limitation of the underlying systems or just not currently implemented in kube-router?

If it's the latter, I would gladly help with adding support.

**Comment by murali-reddy** [comment]
To achive DSR kube-router relies on IPVS/LVS tunneling mode. Unlike NAT mode, IPVS/LVS tunneling mode does not modify packet and just encapsulates and forwards the traffic to real server in this case pod's behind the service. In general it is expected that real server listen on same port as port remapping is not done. It may be possible to add iptables PREROUTING to remap port with  in the pod. You may try and see.

**Comment by aauren** [comment]
Closing as stale
