### ISSUE TITLE
gobgp shipped in kube-router image has possible issues again

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#94]
@thoro reported below on gitter

```
gobgp global rib
rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: bad wiretype for field gobgpapi.Path.SourceAsn: got wiretype 2, want 0
```

Need to check, https://github.com/osrg/gobgp/releases/tag/v1.22 released today, if it fixes the issues.

**Comment by bzub** [comment]
I've got a change ready that compiles gobgp client from the vendored source in the kube-router repo.  That should at least make sure client/library are in sync.

**Comment by bzub** [comment]
Seems to be fixed now.
`kubectl -n kube-system exec kube-router-0rg16 -- gobgp global rib`
```
   Network              Next Hop             AS_PATH              Age        Attrs
*> 10.2.0.0/24          147.75.77.117                             00:00:13   [{Origin: i}]
```
