### ISSUE TITLE
IPVS rules not cleaned up when using the --cleanup-config flag

### ISSUE THREAD

**Issue by bpasson** [cloudnativelabs/kube-router#968]
I noticed the IPVS rules are never clean when you run the --cleanup-config flag.  The code has a place, but its not implemented. See the listing below.

https://github.com/cloudnativelabs/kube-router/blob/4307bdd19cdcf76b6635abc80bd84f3562acbb20/pkg/controllers/proxy/network_services_controller.go#L2061-L2067

**Comment by aauren** [comment]
Closed via #1132
