### ISSUE TITLE
Prefix and peer sets used to defing BGP export polcies keep growing with redundent IP

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-router#97]
Kube-routers network routes controller use three sets to define BGP export policies

-podcidrprefixset
-clusteripprefixset
-externalpeerset

Periodically does advertising of routes, etc. It also update the export policies based on the current state. Update in the periodic sync is not idempotent. Each time periodic sync, redundent ip gets added to the set

```
gobgp policy neighbor
NAME             ADDRESS
externalpeerset  10.21.15.253
                 10.21.15.254
                 10.21.15.253
                 10.21.15.254
                 10.21.15.253
                 10.21.15.254
                 10.21.15.253
                 10.21.15.254
                 10.21.15.253
                 10.21.15.254
                 10.21.15.253
                 10.21.15.254
                 10.21.15.253
```

Kube-router needs to check if ip exists before attempting to add to the set.

@thoro nice catch. thanks for reporting.

**Comment by bzub** [comment]
`kube-router-git:bzub-redundant-definedsets` container image is an attempt to address this. Will merge after a bit more testing.

**Comment by murali-reddy** [comment]
Change looks good. Thanks @bzub
