### ISSUE TITLE
Document `--service-cluster-ip-range`

### ISSUE THREAD

**Issue by SerialVelocity** [cloudnativelabs/kube-router#987]
My cluster started up and network policies were not working when talking to a service IP

I found this rule in my iptables:
```
-A KUBE-ROUTER-INPUT -d 10.96.0.0/12 -m comment --comment "allow traffic to cluster IP" -j RETURN
```

That IP is not used anywhere in my cluster and looks like it is an undocumented flag default here:
https://github.com/cloudnativelabs/kube-router/blob/v1.0.1/pkg/options/options.go#L79

Can you document the `--service-cluster-ip-range` flag here:
https://www.kube-router.io/docs/user-guide/

P.S. An even better solution would be to retrieve this range automatically from kubernetes

**Comment by aauren** [comment]
Unfortunately the docs at kube-router.io have gotten stale. There is an issue out there to update them, but the maintainer hasn't had time recently to take care of it: https://github.com/cloudnativelabs/kube-router/issues/814

In the meantime, I would recommend always using the docs as viewed through GitHub itself. That option has been added to the official docs here: https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#command-line-options and it was also specifically called out in the release notes for 1.0: https://github.com/cloudnativelabs/kube-router/releases/tag/v1.0.0

The GitHub user-guide document should be always be up to date with the current options as unit tests actually require that document to be identical to the output produced from `kube-router --help`.

As far as I'm aware there is no place where Kubernetes exposes the service IP range through it's API for us to consume, but if you're able to find one please let us know as I think that would be preferred as well.

**Comment by SerialVelocity** [comment]
I guess a hack like https://stackoverflow.com/a/61685899 isn't really an option?

**Comment by aauren** [comment]
I don't think it is wise on relying on command output for a core component like this. The work around as linked makes use of the UI of the kubectl command and can change verbiage or functionality at any time. I've commented on an upstream issue for exposing this functionality and will hope that the sig-network team considers re-opening the issue and implementing the functionality: https://github.com/kubernetes/kubernetes/issues/25533#issuecomment-698451277
